### ISSUE TITLE
Low bandwidth error - reproduceable

### ISSUE THREAD

**Issue by MaxeMAUT** [derekhe/msfs2020-map-enhancement#101]
**Describe the bug**
After loading a flight I either get the "low bandwidth..." message immidiatly after the loading screen, or after some Seconds. If I then reactivate the data download inside FS2020 I can see that the tool starts to download data again, but it gets slower and slower and while FS2020 still tries to load the data it aborts after 30s up to 4 or 5 minutes and displays the low bandwidth message again.

When looking at the task manager I can see the download speeds going up to 40 to 50 MB/S (I have 250MB down/ 50 MB Up) but then the speed drops down to 1Mb/s really quickyl and then the download stops fully which then results in FS2020 switchting to offline mode. Pls help.

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: MS Store
 - MSFS2020 Version: SU8 fully up to date (13.04.2022)

**Log** 
Please provide the logs:
- Find out "Trouble
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476866/renderer.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476867/main.log)
 Shooting" tab and attach the log files

- Attach log
[localgoogle-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476861/localgoogle-access.log)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476862/virtualearth-access.log)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476864/error.log)
s from
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8476865/image_server.log)
: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

**Comment by MaxeMAUT** [comment]
Any infos here already? Or any idea what is wrong?

**Comment by remonremmers** [comment]
I have the same problem

**Comment by derekhe** [comment]
@MaxeMAUT I see from the log you opened the high lod feature and it has some error happening when accessing the cache. Please try clear the cache once you have this problem.

**Comment by MaxeMAUT** [comment]
@derekhe sadly this this not help. The error still persists even after clearing the cache also when using the FS2020 cache (ofc cleared aswell).

What I can obsere is that the downloadspeed in task manager first is around 8-15MB/s and then quickly drops down to below 1MB/s or even fully stops. Could this be an issue with python/nginx having problems with connecting/having a stable connection? It also happens with a deactivated Firewall.

**Comment by derekhe** [comment]
Please try latest 5.0.1 version

**Comment by MaxeMAUT** [comment]
@derekhe I salute you. I know works a lot better. Sometimes I get a low bandwidth message when i first load into the flight or while flying but after that message all is fine and it loads. Maybe you can "stabilize" the downloard rates a bit more, then those messages might stop aswell. :) Thank you for the updates!

**Comment by derekhe** [comment]
Fixed in latest version.
