### ISSUE TITLE
game doed not load any flight with google maps.

### ISSUE THREAD

**Issue by Kajinek11** [derekhe/msfs2020-map-enhancement#102]
**Describe the bug**
I have a trouble. In the game menu (map) have got google maps, but if click to "FLY" - the game stuck and "not responde" I can not fly anywhere. After restart game in NORMAL MODE without google maps, game work normaly. 😞 I have cache OFF. 

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [steam]
 - MSFS2020 Version [last one]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8480970/error.log)

**Comment by h0wardch3ng** [comment]
https://twitter.com/MSFS_Support

Maybe.

**Comment by Kajinek11** [comment]
I do not understand what I should search at MSFS Twitter forum? You  mean ask?
