### ISSUE TITLE
Any plan for pre-cache feature?

### ISSUE THREAD

**Issue by kn007** [derekhe/msfs2020-map-enhancement#103]
Good module for me. Thanks for your work.

Will you plan add a button to cache whole world map with zoom level 0-8(user choose?)
Thank you.

There are some bugs(maybe):
1. When close the program, the nginx without exit. Re-Open the program will show 443 already used.
2. In program, I reload (or force-reload) the page. Nginx status is missing, "Inject" button will be greyed out.
3. It looks like the "mt.google.com" and "khm.google.com", their caches are not compatible.
4. Wrong value in 3rd parameter of `setInterval` in "RuntimeInfo.vue"

Some advices:
1. Maybe add a debug mode for nginx logs. I disable access log and change error log level to emerg. It does not need logs when working fine. 
2. For Nginx conf, `worker_process auto;` should be fine.

**Comment by derekhe** [comment]
Yes, I'm working on the offline download and will release it soon.

**Comment by kn007** [comment]
Where's the button to cache maps?

**Comment by derekhe** [comment]
Still working on it
