### ISSUE TITLE
Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

### ISSUE THREAD

**Issue by r00fer** [derekhe/msfs2020-map-enhancement#105]
Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

**Comment by r00fer** [comment]
Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

**Comment by h0wardch3ng** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/104#issuecomment-1099866706

**Comment by wibowoazh** [comment]
how?
