### ISSUE TITLE
After installing update 1.25.7, Google maps stopped loading. Is this problem just me?

### ISSUE THREAD

**Issue by lorakolesnik** [derekhe/msfs2020-map-enhancement#106]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

**Comment by derekhe** [comment]
I tested and it works well. Please note that the SU9 beta is not completely released and may have issues.
