### ISSUE TITLE
Confused about "back to bing Map

### ISSUE THREAD

**Issue by Otrman99** [derekhe/msfs2020-map-enhancement#107]
I think I like using google maps and have installed the latest version.  What I would like to do is to launch Map Replacement and occasionally try to go back to Bing to see the difference between Bing and Google by clicking on "back to Bing".  When I do this I don't see any difference.  Am I doing something wrong?

Thanks in advance,
Otrman AKA Henry

**Comment by derekhe** [comment]
Back to Bing means to exit the mod actually. You need to restart the MSFS2020 to see the difference. And also the "Rolling cache" should turn off inside the game.

**Comment by Otrman99** [comment]
I sort of figured that.  Sometimes it is difficult wo see whether Bing or Google is better under some circumstances.  It would really be usefull to be flying along using google and flip back to bing to see the difference.  Rolling Cache?  ? Do I need to run it off in order to use Google maps?  Would it be possible for you to do that when a user chooses google?

**Comment by martinsstuff** [comment]
> I sort of figured that. Sometimes it is difficult wo see whether Bing or Google is better under some circumstances. It would really be usefull to be flying along using google and flip back to bing to see the difference. Rolling Cache? ? Do I need to run it off in order to use Google maps? Would it be possible for you to do that when a user chooses google?

Not the dev but I believe I understand how the mod works:

### Flipping back and forth on the fly:
There are two problems with this:

A) DNS Cache: The mod works by changing the returned IP address for the Bing server through the hostsfile, MSFS would have to re-lookup the hostname to start talking to the locally hosted server when already using Bing (or vice versa). How frequently is does that can be found out by logging DNS queries (not sure how TTL plays into this when it's constantly pulling data from Bing).

B) MSFS caching scenery: Even without rolling cache, MSFS will have to cache some data, probably in RAM. Clearing this might just be a matter of teleporting far enough away (possible without having to sit through loading screens, and could be scripted).

### Rolling Cache:

The rolling cache should not prevent the mod from working, but it might cause issues if, even for a moment, the sim pulls data from the wrong source, in which case you'd have to wait for the cached data to expire or, the easiest option, just disable the rolling cache.

Also, from my personal experience, the rolling cache makes my performance worse and introduces micro stuttering despite using an SSD.

### How this could be implemented in the mod:

1. Flipping imagery sources:
 By providing a transparent mode which bypasses the mod's cache (if enabled) and sends data unmodified to the original Bing servers. Additionally it would be possible through the MSFS API to automatically teleport the aircraft far away and back to force the scenery to reload, if rolling cache is disabled.

2. Disabling rolling cache:
 Probably not on the fly but the mod could modify the relevant config file to turn the rolling cache off before starting the sim.

Realistically speaking, I feel like the mod providing a "transparent mode" is the feature most viable for inclusion, automatically teleporting to clear the cache would add a lot of bloat to the application to talk to the MSFS API.

Disabling the rolling cache automatically could work with the option that starts the sim automatically, but it would once again add bloat to the program.

---

There might be better ways to do this but that's just what I came up with on the spot.
