### ISSUE TITLE
Different Tiles Bings Map Latest

### ISSUE THREAD

**Issue by AppleUK123** [derekhe/msfs2020-map-enhancement#109]
Hi, just wanted to check whether this is the same on your PC?

This is with the Bings Map latest. As you can see the tiles are in squares, as if they are loading a slightly different map.
Here is location: High LOD enabled, Cache Deleted then turned back on.

Thank you for a great mod! I usually use Google and don't experience this
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101504298/163888973-7e4a5b11-87af-4a0f-ad34-851f4431d49a.png">

**Comment by martinsstuff** [comment]
Try to disable the cache entirely (mod and sim), does it appear in game as well or just the map? I actually had the impression the map always remained on Bing while I definitely noticed changes in game when using Google.

**Comment by h0wardch3ng** [comment]
Enter the in-game setting
Please trun on all online service and turn off rolling cache

**Comment by AppleUK123** [comment]
Thank you will try and report back. When I'm flying low its fine. But when I climb higher I start to see this square pattern.

**Comment by h0wardch3ng** [comment]
Try delete rolling cache again.

**Comment by AppleUK123** [comment]
Thank you for your suggestions.
I've tried disabling then re-enabling online services as well as disabling cache.
It seems like it is a map issue - due to LOD maybe? 
When I'm zoomed far out it fine and when I'm zoomed far in its fine. But when around 20000-30000ft I get those mismatched tiles. Not everywhere in the world. I wonder if there is any way to resolve this please?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101504298/163989104-8ed276ce-796d-4350-8ddd-a6b448b1dcb7.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101504298/163989302-0744c59b-64cc-4466-8a4d-daabcf98184e.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/101504298/163989335-dffbd2f5-4e51-407a-bece-3f220d52d6e0.png">

**Comment by AppleUK123** [comment]
If someone uses Bing latest please can you confirm if you also see this around Peterborough

**Comment by h0wardch3ng** [comment]
Why not use google maps or mapbox?

**Comment by derekhe** [comment]
It is because of lod of satellite images. Please try different map service.
