### ISSUE TITLE
Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

### ISSUE THREAD

**Issue by wibowoazh** [derekhe/msfs2020-map-enhancement#110]
Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

HOWWWW?
i try reinstall on local file but still not work

**Comment by h0wardch3ng** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/104#issuecomment-1099866706

**Comment by derekhe** [comment]
@h0wardch3ng thanks for your support to answer these questions :)
I will close this as this problem is addressed in other comments.
I'm working on a new version and will have a better guide for error and treatment.
