### ISSUE TITLE
Access Denied running as Administrator

### ISSUE THREAD

**Issue by doubacc** [derekhe/msfs2020-map-enhancement#111]
Is there any known cause or solution for this? 

I'm running Powershell 5.1 as Admin (same happens with cmd and with Visual Studio Developer Console)

![image](https://user-images.githubusercontent.com/104014995/164198694-3edb4e43-7f99-4a52-99fd-69938717701a.png)

**Comment by h0wardch3ng** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/104#issuecomment-1099866706
