### ISSUE TITLE
only load one image and "Runtime Info" did not refresh 

### ISSUE THREAD

**Issue by b0ynextd00r** [derekhe/msfs2020-map-enhancement#112]
He哥您好，

感谢share这个强大的mod，我现在卡在无法load和刷新地图，请您帮看看。
![image](https://user-images.githubusercontent.com/58327476/164309229-cbffc3f7-710c-4010-8f01-7ac50317897e.png)
目前谷歌地图访问没问题，也试过不用代理用ArcGIS，还是一样这个界面不刷新，游戏里也没有变化。

目前还尝试过删除Roaming里的文件夹并重装，重启，并且游戏设置里也打开了bing map和删除了rolling cache。

刚启动程序还没inject map时查看console，就报以下错误，感觉应该和游戏设置没什么关系
![image](https://user-images.githubusercontent.com/58327476/164310283-960d9ad1-4552-4c82-b71a-3b52549fde25.png)

**Comment by derekhe** [comment]
首先确保把杀毒软件之类的先关闭一下
然后在游戏启动前运行这个
另外你的游戏是steam版本的么？或许你关闭一下steam再试试？
我之前遇到过有人报过steam版本会有一些问题，但我没有steam版本的所以很难确认什么问题。

**Comment by b0ynextd00r** [comment]
> 首先确保把杀毒软件之类的先关闭一下 然后在游戏启动前运行这个 另外你的游戏是steam版本的么？或许你关闭一下steam再试试？ 我之前遇到过有人报过steam版本会有一些问题，但我没有steam版本的所以很难确认什么问题。

确实是防火墙的问题，加入白名单就可以了，感谢！
