### ISSUE TITLE
Hosts file is hard coded to C drive

### ISSUE THREAD

**Issue by JohnMcAvinue** [derekhe/msfs2020-map-enhancement#113]
**Describe the bug**
I have two versions of Windows 10 running on my machine, dual boot. My work is run on C drive and for Flightsim I run on F drive. I would imagine this kind of set up is not that unusual.

After injecting in the UI, the "Nginx Server Access Check" never goes green. When I checked the logs, I see loads of references to custom hosts that are on my C drive.

The path to the hosts file is hard coded to C drive here:

https://github.com/derekhe/msfs2020-map-enhancement/blob/master/src/services/hosts.ts#L9

If it's hard to work out the path that the application is running on, then maybe a config setting could workaround this issue?

**Comment by derekhe** [comment]
I will provide an option to set the hosts files.

**Comment by derekhe** [comment]
It is fixed in latest 5.0.0 beta version and please try.
