### ISSUE TITLE
bonjour il y a beaucoup de déconnection et perte de bande passante. aider moi merci

### ISSUE THREAD

**Issue by nay95** [derekhe/msfs2020-map-enhancement#115]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

**Comment by derekhe** [comment]
Please turn OFF high-old
Please use the cache option in the mod
