### ISSUE TITLE
When I turn on the mod, absolutely all the trees will disappear.

### ISSUE THREAD

**Issue by JimmyGrizzly** [derekhe/msfs2020-map-enhancement#116]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
When I turn on the mod, absolutely all the trees will disappear.
![Microsoft Flight Simulator Screenshot 2022 04 22 - 11 40 47 46](https://user-images.githubusercontent.com/104186830/164612927-aabdef47-1e0d-4a63-817c-039c13793d72.png)
![Microsoft Flight Simulator Screenshot 2022 04 22 - 11 47 06 74](https://user-images.githubusercontent.com/104186830/164612939-8193b0a0-a898-49ed-9ad7-256aa225ee89.png)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8537374/error.log)

**Comment by derekhe** [comment]
Hi, I see the problem may be because the first layer of the map was not loaded OR the satellite image can't be recognized by AI to generate trees. Please switch to other maps (Bing, arcgis, mapbox) and try.
