### ISSUE TITLE
Security warning when trying to run the software

### ISSUE THREAD

**Issue by SeanPeterson69** [derekhe/msfs2020-map-enhancement#117]
**Describe the bug**
Security warning when trying to run the software

**Screenshots**
![-2022-apr-23-006](https://user-images.githubusercontent.com/26149766/164915256-cb0dcfc9-cf5e-4dfa-9595-508565bfb3c0.jpg)

![-2022-apr-23-007](https://user-images.githubusercontent.com/26149766/164915253-fe404d40-b739-47a8-96ee-bc88e0353fe2.jpg)

**Desktop (please complete the following information):**
 - MSFS2020 version: Microsoft Store version
 - MSFS2020 Version [e.g. 22]

Is this normal when trying to run this software?

**Comment by Mazeee1** [comment]
Yes, that's normal. Under the first time usage banner it says that you have to accept it.

**Comment by h0wardch3ng** [comment]
Approve any warning if you want use this softwore

**Comment by derekhe** [comment]
Close this as I mentioned in the "First time usage"
