### ISSUE TITLE
From SU9, the map loading and streaming is very slow。

### ISSUE THREAD

**Issue by jydsj** [derekhe/msfs2020-map-enhancement#119]
**Describe the bug**
很好的地图软件之前一直正常使用，非常感谢！但这次SU9后，进入世界地图明显感觉地形纹理加载很慢，点“FLY”后蓝条卡在80~90%处一直进不去，有时等15分钟后能进到驾驶舱（SU9前只需1分钟左右），飞机升空后看地面纹理非常模糊。关闭地图软件后游戏就恢复正常。Community文件夹 空
logs压缩包已提供。谢谢。

**Screenshots**
![2345截图20220428115822](https://user-images.githubusercontent.com/75497415/165949598-80b7a1a4-e892-483d-9c06-2576ba747be3.jpg)
![2345截图20220429204339](https://user-images.githubusercontent.com/75497415/165950028-ff3c4c39-cd0a-4292-bca7-6ce241e2360a.jpg)
![2345截图20220428225547(1)](https://user-images.githubusercontent.com/75497415/165950052-d5d09e2e-f2af-4317-9dbe-1e6bb2fe3c0f.jpg)

**Desktop (please complete the following information):**
 - MSFS2020 version: 微软商店版

**Log** 
Please provide the logs:
logs压缩包：[logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8596254/logs.zip)

**Additional context**

**Comment by jydsj** [comment]
首先谢谢回复！
google/bing/arcgis/mapbox 全部试过都一样。arcgis不用代理也同样问题。SU9前地图软件一直正常用。现在关闭地图软件后，进游戏点“FLY”进游戏也是正常，网络应该没有问题。
这个是SU9前正常使用时我在bilibili发的视频 https://www.bilibili.com/video/BV16L411K7rU?spm_id_from=333.999.0.0

**Comment by jydsj** [comment]
下面附上几张图，地图软件启动OK，代理测试OK，游戏进地图页面后，点“FLY”蓝条卡住。

![2345截图20220428115822](https://user-images.githubusercontent.com/75497415/165948615-53fcda5c-8fe6-4959-8b3d-92c4aaf70ef3.jpg)
![2345截图20220429204339](https://user-images.githubusercontent.com/75497415/165948635-96b48cb7-760e-4afc-9296-8edfb1c4656e.jpg)
![2345截图20220428225547(1)](https://user-images.githubusercontent.com/75497415/165948676-14bdc94a-c4ad-477e-af0e-cf68db0e6b07.jpg)

**Comment by h0wardch3ng** [comment]
Do you keep community folder empty?

**Comment by jydsj** [comment]
是的，community为空。我每次游戏升级都清空community，升级好后重启电脑，保持community为空测试游戏。
发现这个问题后我又还重装了一次map-enhancement，但还是没有改变。

**Comment by h0wardch3ng** [comment]
Try to close all firewall?

**Comment by jydsj** [comment]
是的，防火墙一直是关闭的，非U也一直是英语美国。昨晚又全部删除并重新安装了整个游戏，但还是没有解决问题。

**Comment by derekhe** [comment]
@jydsj 我现在也是在用SU9，从beta版本就使用了，该mod使用正常。昨天我也玩过，也是正常的能够加载。加载速度比较慢的问题，我用Bing (Latest)不加代理，确实会比较慢，原因是网络速度比较慢，大概是1.5M/s左右。
请确保先打开cache，然后把HighLOD关闭试试。

**Comment by jydsj** [comment]
@derekhe 谢谢您的回复。
Google/Bing（Latest）加代理，ArcGIS不加代理，都试过，都一样问题。cache一直是打开的，我现在再去试试HighLOD关闭会怎么样。SU9之前一直很好，现在没有这个地图软件都不想玩游戏了。

**Comment by derekhe** [comment]
打开HighLOD以后因为加载量是平时的4倍，所以很慢。

**Comment by jydsj** [comment]
@derekhe 试了关闭高LOD，还是卡住进不去，点"FLY"到现在10几分钟了还是没进去。稍后我录几个启动游戏的视频放到bilibilis上，麻烦您给分析一下。先谢谢了，我实在太喜欢您这个地图软件了。

**Comment by derekhe** [comment]
把Trouble Shooting里面涉及到的日志全部打包发到这里来供分析，要不然我也不知道为什么。

**Comment by jydsj** [comment]
@derekhe 好的，谢谢。
logs压缩包：
[logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8596250/logs.zip)

未开地图软件时游戏加载视频  [https://www.bilibili.com/video/BV1aZ4y1y7cB/](url)
打开地图软件后的游戏加载视频  [https://www.bilibili.com/video/BV1q5411R7CJ/](url)

**Comment by derekhe** [comment]
我看了日志和视频，日志中也是正常在加载的，视频中我也看到最后也加载了6000多张图片，此时差不多应该可以加载了。具体我也搞不清楚为什么游戏就卡了……

**Comment by jydsj** [comment]
@derekhe 就是，我也觉得非常奇怪，游戏都删除重装过了都不行。SU9之前一直好好的。还是谢谢您的付出，真的是一款非常好的软件，用不起来我很遗憾。。。

**Comment by h0wardch3ng** [comment]
> @derekhe 就是，我也觉得非常奇怪，游戏都删除重装过了都不行。SU9之前一直好好的。还是谢谢您的付出，真的是一款非常好的软件，用不起来我很遗憾。。。

https://www.flightsimulator.com/april-21st-2022-development-update-2/

I think there is something wrong with the game.
Now waiting for the asobo dev team to solve.

**Comment by jydsj** [comment]
@h0wardch3ng 非常感谢您！谢谢您的信息。我也在怀疑SU9后，游戏加载地图纹理有问题，也有可能是加载方式有某些改变。当我用回游戏自带Bing地图时，好久没有出现过的地图纹理网格状加载突变又回来了，未加载到部分的地皮纹理非常模糊。（LOD=200)
遗憾的是我的英语水平有限（我是老年人），实在无能力用英语去官网表达清楚问题。
再次感谢！

**Comment by derekhe** [comment]
这个问题我还在调查中，英语的问题不是太大，我也是国人，咋们用中文交流即可。另外我的QQ：3828 8889+1(请做一下加法免得被人滥用），需要的话可以加。

**Comment by jydsj** [comment]
@derekhe 非常感谢您，已申请加您QQ。

**Comment by maximilian1064** [comment]
@derekhe 你好，我也是这个问题。我用的是这个工具很早的版本，不过SU9前一直都没问题。我看log服务器在一个request上无限循环（下图），希望能给你解决问题提供点线索。
![Capture](https://user-images.githubusercontent.com/16747243/166124464-159a52dc-36e8-44e0-839c-4e7bd1f31721.PNG)

**Comment by maximilian1064** [comment]
原始域名https://kh.ssl.ak.tiles.virtualearth.net/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr工作，但是转换过后的google域名https://23.211.5.150/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr是invalid url，可能是这个原因。

**Comment by maximilian1064** [comment]
> 原始域名https://kh.ssl.ak.tiles.virtualearth.net/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr 工作，但是转换过后的google域名https://23.211.5.150/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr 是invalid url，可能是这个原因。

刚试了下工具4.2.3版本，又没有这个问题了。。。

**Comment by h0wardch3ng** [comment]
@maximilian1064 
Changing the SOP of the startup software
1. Open the game
2. Turn off the networking function in the game
3.Open this software
4. Turn on the network function in the game

**Comment by jydsj** [comment]
经过反复测试，现在情况如下：
1.打开google地图软件，Community为空，点'FLY’后卡蓝条，进不去游戏。
2.关闭google地图软件，Community为空，游戏正常。
3.关闭google地图软件，Community中只放进一个由google转换的地景插件，其它插件都不放入，卡蓝条（进主菜单前的蓝条）进不去主菜单页面。
4.关闭google地图软件，Community放入全部插件（除上述2中的那个地景），游戏正常。

**Comment by h0wardch3ng** [comment]
@jydsj mapbox一切正常

**Comment by maximilian1064** [comment]
> > 原始域名https://kh.ssl.ak.tiles.virtualearth.net/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr 工作，但是转换过后的google域名https://23.211.5.150/tiles/cm01321201?g=9126&n=z&cmt=hrcmdtmr 是invalid url，可能是这个原因。
> 
> 刚试了下工具4.2.3版本，又没有这个问题了。。。

@h0wardch3ng Thanks for the guide. As said here it actually works with the latest version. The version I used is just too old...

**Comment by derekhe** [comment]
For the latest update and loading issue, my reply is:

- Long loading time is often caused by slow network access to the map provider, please check the network loading speed and wait.
- SU9 has a longer loading time because it loads new data from ms server.
- In SU9 I found that sometimes it is loading for a long time even the progress bar goes to 100% but still loading.
- CTD issue may not be caused by this mod, most of the time it is a bug of MSFS2020, please have a look at: https://forums.flightsimulator.com/c/bugs-and-issues/ctds/260

Recommendation:

- Disable high-lod if you have a long loading time.
- Disable in-mod cache
- Enable in-game rolling cache (so that it can cache more data in-mod cache can't handle)
