### ISSUE TITLE
Nginx Server Access Check lädt und lädt

### ISSUE THREAD

**Issue by fliegeroli** [derekhe/msfs2020-map-enhancement#121]
**Describe the bug**
Nginx Server Access Check lädt und lädt

**Screenshots**
![image](https://user-images.githubusercontent.com/104644267/165990692-bb6f4cc8-cdd7-4344-89fb-f420c220c4b5.png)
**Desktop (please complete the following information):**
 - MSFS2020 version: 1.25.7.0 [e.g. msstore]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8592496/error.log)

**Additional context**

**Comment by fliegeroli** [comment]
Wäre schön, wenn mir geholfen werden könnte.

**Comment by derekhe** [comment]
Please provide me other logs mentioned in "Trouble Shooting"

**Comment by fliegeroli** [comment]
[https://flightsim.to/file/19345/msfs-2020-google-map-replacement/280306](url) Danke. Mein Problem hat sich erledigt
