### ISSUE TITLE
According to Google Replacement Tool, Bing Maps are buggy

### ISSUE THREAD

**Issue by didl24** [derekhe/msfs2020-map-enhancement#122]
Hello people,                                                                                                                                                                                          Because many are so enthusiastic about the GoogleMaps implementation, I downloaded and tried out the Google Replacement Tool v4.2.3. When I loaded the Google Maps, it didn't convince me because the colors were too monotonous. Back to the Bing Maps, I had to realize that the satellite images are now a mixture of Google and Bing. Even if I choose "Bing Maps" for the replacement tool, about 25% of Google Maps still show through Terrible to look at. Cleared rolling cache, no change. Logging in and out of XBox, MSStore, no change. Emptying the community folder, no success. Content xml reset, no success. Deleting the host files: 127.0.0.1kh.ssl.ak.tiles.virtualearth.net 127.0.0.1 khstorelive.azureedge.net No success. The Google images are always in the same places and don't seem to let Bing overwrite them anymore. No change after multiple reboots The overall impression conveys 75% Bing and 25% Google Is there just a fresh install?                                                                                                                                            Greetings Didl

**Comment by h0wardch3ng** [comment]
Go to game settings, delete all rolling cache In `Data`

**Comment by didl24** [comment]
Rolling cache in game is every off for me, but i still cleared it with no success

**Comment by h0wardch3ng** [comment]
I think this is a game bug

**Comment by derekhe** [comment]
Disable the cache inside the mod

**Comment by didl24** [comment]
i have disabled the cache, but no success
![Microsoft Flight Simulator Screenshot 2022 04 24 - 10 17 15 78](https://user-images.githubusercontent.com/104712256/166151022-f87f15b3-ebe8-4cd0-8308-95a5d57ad580.png)

**Comment by derekhe** [comment]
Please check if the rolling cache inside the game is enabled, if yes, please delete and close it.
