### ISSUE TITLE
Nginx Server checking forever

### ISSUE THREAD

**Issue by 0rz777** [derekhe/msfs2020-map-enhancement#130]
**Describe the bug**

Nginx Server is checking forever when I  press "Start Flying" in 5.01/5.00, no matter which image server I chose, Nginx Server will not pass at all.

**Screenshots**
![2022-05-07 23_48_25-Vite App](https://user-images.githubusercontent.com/9088957/167261856-4dca3130-af85-46e4-a0a3-31df886f5c04.png)

**Desktop (please complete the following information):**
 - MSFS2020 version: msstore
 - MSFS2020 Version: SU9

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach all the log files
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8645510/error.log)
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8645509/image_server.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8645522/main.log)

**Additional context**
Appreciated for any help!

**Comment by wd78502245** [comment]
I think I have the same problem, is there a solution? How to find "Trouble Shooting"?

**Comment by derekhe** [comment]
Please try 5.0.3 and use the “Report Issue” page to collect logs for me.

**Comment by 0rz777** [comment]
> Please try 5.0.3 and use the “Report Issue” page to collect logs for me.

Hi derekhe, thanks for the reply, 5.05 is still showing: Image Server: good, Nginx Server: checking when I press "Start Flying", I have not even opened my MSFS yet,

Please see attached log:
[20220517160321.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8706377/20220517160321.zip)

**Comment by derekhe** [comment]
Nice, I had to write something in my mod to let user do these things to fix the hosts file.

**Comment by derekhe** [comment]
I added this information into the https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ page
