### ISSUE TITLE
Half black taskbar icon

### ISSUE THREAD

**Issue by Enska215** [derekhe/msfs2020-map-enhancement#132]
**Describe the bug**

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.25.9.0

- Mod version
5.0.3
**Log**
[20220514113035.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8692646/20220514113035.zip)

**Screenshots**
[Screenshot 2022-05-14 113029](https://user-images.githubusercontent.com/81373541/168420038-2d22579d-21a1-4199-a9ab-821cc84e5fb8.png)

**Additional context**
Taskbar icon is half black

**Comment by derekhe** [comment]
Aha, I know this problem and will fix it in future.

**Comment by Enska215** [comment]
Thanks!

**Comment by derekhe** [comment]
Fixed in 5.0.5
