### ISSUE TITLE
Issue with displaying aerial images

### ISSUE THREAD

**Issue by slrmd** [derekhe/msfs2020-map-enhancement#135]
**Describe the bug**

**MSFS version:**
 - Steam
 - 1.25.9.0

**Mod version:**
- 5.0.6

**Log**
[20220519215842.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8733095/20220519215842.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/98208085/169381186-7d15acc0-7132-4393-9c18-8c3a166cd8d1.png)

**Additional context**
First of all, I want to thank **derekhe** for his tool!
After the last sim update there was a problem with the mod. On the world map mod works good. But in the simulator aerial images loading does not work. Default aerial images from Bing work good in both cases.

**Comment by h0wardch3ng** [comment]
Please check you internet connection.
