### ISSUE TITLE
Image Server failed

### ISSUE THREAD

**Issue by Sanderli25** [derekhe/msfs2020-map-enhancement#136]
**I have installed the Map Enhancement before, and got the same issue as I ran into now then. I complete the installation as described, and gets the message"image server failed" in the bottom left.**

**MSFS version:**
 - msstore
 - MSFS2020 Version Italy and Malta world update.

**Mod version:**
- Mod version 5.0.6

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 
[20220521000420.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8744755/20220521000420.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/89723211/169618415-f1c04704-39b1-479b-b480-14aa1dcd55fa.png)

**Additional context**

**Comment by h0wardch3ng** [comment]
Please check 443 port or firewall.

**Comment by CES564** [comment]
![image](https://user-images.githubusercontent.com/107012790/172276011-82c1b69d-9644-4b73-af4f-db449f0ec153.png)
[20220607092321.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8849279/20220607092321.zip)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

**Comment by derekhe** [comment]
Please try latest version.
