### ISSUE TITLE
WONT START

### ISSUE THREAD

**Issue by tonygard** [derekhe/msfs2020-map-enhancement#137]
**Describe the bug**

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by tonygard** [comment]
I GET THIS ERROR whent i hit start "Check the Store for more info about Microsoft Flight Simulator."

**Comment by derekhe** [comment]
Please check if you select the correct mod version. You can start your msfs2020 manually.
