### ISSUE TITLE
no images downloaded

### ISSUE THREAD

**Issue by TheStressMachine** [derekhe/msfs2020-map-enhancement#138]
**Describe the bug**
Nginx and Image server show "good", sample image is downloaded, but no subsequent images are downloaded once MSFS is launched.
**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Log**
[20220521172524.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8748369/20220521172524.zip)

**Screenshots**

**Additional context**

**Comment by h0wardch3ng** [comment]
Please check hosts file.

**Comment by TheStressMachine** [comment]
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

**Comment by dataslug1** [comment]
I had the same problem - I had MSFS installed on a Standard user account (Windows 10) and no subsequent images were downloaded, even when running app "as admin".

HOWEVER it did work when I changed my whole account type to Administrator account.  Then it was able to install certificate and it worked fine.  I tried changing back to standard later but it did not work.  Would be great if could fix it so my whole account doesnt need to be admin.  Many thanks!

**Comment by derekhe** [comment]
@dataslug1 good to know and it is a known issue. I can't fix it because it is needed to change the hosts file.

**Comment by TheStressMachine** [comment]
@derekhe why was this closed.  The comment from dataslug has nothing to do with my issue.  My account is an admin.

**Comment by derekhe** [comment]
Hmm, yes. @TheStressMachine do you have any clue about your issue? I find out that it is ngninx not started properly, but I don't know why.

**Comment by TheStressMachine** [comment]
The server was up and running, I even interacted with it manually to test the hosts redirect, and it was all fine.   I turned off photographic imagery then turned it on again and all the sudden it worked.  Weird.  Thanks!
