### ISSUE TITLE
Mod is replacing airport textures with google maps textures

### ISSUE THREAD

**Issue by crazyforiphone** [derekhe/msfs2020-map-enhancement#139]
**Describe the bug**

**MSFS version:**
 - msstore or steam steam
 - MSFS2020 Version [e.g. 22] 1.22.9.0

**Mod version:**
- Mod version 5.0.6

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 
[20220522195908.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8750502/20220522195908.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/10215076/169722038-72a9aa47-7feb-4474-99bf-5b30467fa038.png)
![Uploading image.png…]()

**Additional context**
happening at multiple airports, not just one airport.

**Comment by crazyforiphone** [comment]
I deleted the cache in game and in the map enhancement program and am still seeing this issue 
![image](https://user-images.githubusercontent.com/10215076/169849508-e679c7ae-81cc-4779-a973-28d2f8f3766c.png)
[20220523110520.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8755733/20220523110520.zip)

**Comment by derekhe** [comment]
I think it is the airport's issue and they don't have an image for this area to cover the satellite images.
