### ISSUE TITLE
Adjust satellite image

### ISSUE THREAD

**Issue by derekhe** [derekhe/msfs2020-map-enhancement#146]
Including satellite image's:
* Brightness
* Hue
* Color
* Contrast

**Comment by dataslug1** [comment]
Could it be possible to adjust colour of specific tiles only?  I often find regions of neon green terrain colouring.  Thank you

**Comment by derekhe** [comment]
Yes, the 3d areas has this problem. Even the tiles the mod loads is 2d but it still has this border. I can't fix it at the moment.
