### ISSUE TITLE
Mixed map

### ISSUE THREAD

**Issue by derekhe** [derekhe/msfs2020-map-enhancement#148]
User can draw polygon and choose which satellite image to use so we can have mixed map from different provider

**Comment by dataslug1** [comment]
That would be amazing, as some regions are better with google and some with bing.

I currently swap back and forth between the two, including moving my original MS Rolling Cache back.  I was going to suggest it might be good feature to include this feature in the app itself:
-When click start flying, rename or move MSFS bing rolling cache file, and disable rolling cache in config
-When click stop flying, rename or move MSFS bing rolling cache file back into correct place, and enable rolling cache in config.

**Comment by josefpy** [comment]
If you can apply the MSFS Map Enhancement the option of change satellite image with polygons it will amazing! I will pay for Pro Versión

**Comment by derekhe** [comment]
@josefpy now it is in 7.3.0, please have a try.
