### ISSUE TITLE
don't connect to the servers

### ISSUE THREAD

**Issue by Romeoobravo** [derekhe/msfs2020-map-enhancement#161]
**Describe the bug**

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
no valid information, will close
