### ISSUE TITLE
Just updated and now does not work

### ISSUE THREAD

**Issue by mikeh2010** [derekhe/msfs2020-map-enhancement#162]
**Describe the bug**
Shows image server as red failed
**MSFS version:**
 - steam
 - Latest

**Mod version:**
- 5.07

**Log**
[20220604132544.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8837692/20220604132544.zip)

- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**
Do I need python installed now?

**Comment by mikeh2010** [comment]
just rolled back to 4,2,3 and it works

**Comment by derekhe** [comment]
Please try uninstall 5.0.7 and install it again.

**Comment by mikeh2010** [comment]
Reinstalled and its the same problem...
None of the 5.x.x have worked for me.

**Comment by mikeh2010** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/198#issuecomment-1179268013
