### ISSUE TITLE
[Feature] Support Ortho4XP provider files

### ISSUE THREAD

**Issue by stackTom** [derekhe/msfs2020-map-enhancement#167]
#### Motivation

Add more providers from which to obtain imagery.

#### Detailed design

Add support for parsing Ortho4XP .lay files

#### Alternatives

Less servers from which to download scenery.

#### More detail (optional)

Is there any interest for this? I am considering doing a pull request for this, so that we are able to use .lay Ortho4XP provider files and thus have access to a larger amount of servers to use.

**Comment by derekhe** [comment]
I have no idea about Ortho4XP, could you give me more information about this?

**Comment by stackTom** [comment]
Ortho4XP has a .lay file format with a collection of a bunch of files describing servers from which to download satellite imageries. I wrote a basic parser in C# so that FSEarthTiles supports .lay files. I imagine writing a parser for msfs2020-map-enhancement should be even easier, since the code handling this is written in python, correct? (Ortho4XP is also written in python).

Here is an example .lay file: https://github.com/stackTom/Ortho4XP_FSX_P3D/blob/master/Providers/United_States/USGS.lay

**Comment by derekhe** [comment]
I see it is a url template to provide satellite imagery providers and the format is quite easy to parse. I'm going to have a look.
Btw, I'm going to make a pro version which support new features and this file format give me some tips :)

**Comment by stackTom** [comment]
Yes, would be great if you add it. Might need a custom solution if you plan to sell this feature. But definitely having more providers would be great.

**Comment by derekhe** [comment]
@stackTom although it is different implementation, the custom map may help: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Custom-map-editor
