### ISSUE TITLE
Nginx failed to start

### ISSUE THREAD

**Issue by Cjneilson12** [derekhe/msfs2020-map-enhancement#168]
**When starting the image server comes up good but nginx failed. I have also created a new host file**

**MSFS version:**
 - msstore or steam: steam
 - MSFS2020 Version: 1.25.9.0

**Mod version:**
- Mod version: 5.0.7

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**
[20220613204302.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8893961/20220613204302.zip)

**Comment by h0wardch3ng** [comment]
Check hosts file.
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#damaged-hosts-file-by-other-program

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
