### ISSUE TITLE
Problem after starting computer

### ISSUE THREAD

**Issue by noels7** [derekhe/msfs2020-map-enhancement#171]
Program operates ok . Turn off computer and on restart your program will not run.

Win 11
msstore 
 MSFS2020 Version 1.26.5.0

**Mod version:**
7 and 
[20220622092255.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8953425/20220622092255.zip)
8

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/82074379/174915780-488fc9e4-d680-4b25-9ff1-d051dd784236.jpg)
[20220622092255.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8953432/20220622092255.zip)

**Additional context**

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

**Comment by noels7** [comment]
Many thanks for your assistance. Appreciated
