### ISSUE TITLE
Circle of good ortho below, bad/no ortho outside of it

### ISSUE THREAD

**Issue by piedmonitor** [derekhe/msfs2020-map-enhancement#174]
**Describe the bug**
I have a circle of "good" ortho below me, but outside of that circle there is very weird terrain/no ortho. I am using mt.google.com with a 20 GB cache within your app and a 16 GB rolling cache in 2020 which I have cleared oujt. 

**MSFS version:**
 - Steam
 - MSFS2020 Version [e.g. 22] 1.26.5.0

**Mod version:**
- Mod version 5.0.7

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**
Zipped video attached 

**Additional context**
[20220625234415.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8985939/20220625234415.zip)
[2022-06-25 23-42-24.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8985940/2022-06-25.23-42-24.zip)

**Comment by derekhe** [comment]
Please set the terrian details to above 300.
