### ISSUE TITLE
Host FIle Not Foound

### ISSUE THREAD

**Issue by Busta62** [derekhe/msfs2020-map-enhancement#175]
Receiving error message that host file is not found

**MSFS2020 version:**
 -steam
 - MSFS2020 Version 1.26.5.0

**Mod version:**
5.0.9

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**
[20220626174307.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8987574/20220626174307.zip)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

**Comment by Busta62** [comment]
Good Evening – A new development on my problem. Thinking my host file was not right, I copied a host file from another computer to a thumb drive and installed it into my MSFS2020 computer. The replacement worked and now the map enhancement program works perfectly. Thank you.

Sent from Mail for Windows

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
