### ISSUE TITLE
Problem with port 443

### ISSUE THREAD

**Issue by wradz55** [derekhe/msfs2020-map-enhancement#178]
**Describe the bug**
I can't kill the processes using port 443. First, there is a lot o them and the second, when I kill one of them after a while it starts again and occupies port 443.
**MSFS version:**
 - msstore
 - MSFS2020 Version 
   1.26.5.0
**Mod version:**
- 5.09

**Additional context**
[20220628175905.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9002727/20220628175905.zip)

**Comment by derekhe** [comment]
I can't help you fix the 443 port issue, please try to find out which program and uninstall it.
