### ISSUE TITLE
Image Server Failed

### ISSUE THREAD

**Issue by Mauleflyer** [derekhe/msfs2020-map-enhancement#179]
I have used with mod for many months, now every time I start it I get "Image Server Failed".  I am not having internet issues. 

**MSFS version:**
 - msstore 
 - MSFS2020 Version [e.g. 22]

5.0.9

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

[20220628155138.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9004392/20220628155138.zip)

**Screenshots**

**Additional context**

**Comment by Bodenseeler742** [comment]
same here

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
