### ISSUE TITLE
Feature Request: Show Ping

### ISSUE THREAD

**Issue by Orbitally** [derekhe/msfs2020-map-enhancement#18]
If possible it would be great to be able to see the response time of the Google servers such as the popup that appeared when testing the proxy in the non-electron version since that was a great way to see which server would be better used. If it could make a comeback in this version as well that would be amazing!

**Comment by danolc1** [comment]
look Great

**Comment by derekhe** [comment]
Its on the way, will work on it later.

**Comment by derekhe** [comment]
I will close this now and will open in future when implement
