### ISSUE TITLE
Connection to Image Server

### ISSUE THREAD

**Issue by hotelpf23** [derekhe/msfs2020-map-enhancement#180]
First of all thanks a lot for this great addon. Now I got a little problem since version 5.0.9: when starting the enhancer the image servers fails at first. After I stop the mod and starting again it works fine. I did not had this with the previous versions. Is there any help for that. Thankyou.

Best regards Jörg Trefzer, Switzerland

**Comment by derekhe** [comment]
Please give me logs for investigation

**Comment by hotelpf23** [comment]
Since this morning everything works very fine. I installed version 5.0.8 and reinstalled version 5.0.9 over 5.0.8.
So no actions to be taken anymore. Congrats for this addon and thankyou. Regards

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
