### ISSUE TITLE
Clear Cache

### ISSUE THREAD

**Issue by TootY1993** [derekhe/msfs2020-map-enhancement#183]
When using the 'Clear Cache' option it provides the following error 'Clear cache error, please retry or restart mod'

**MSFS version**
 - Microsoft Store
 - MSFS2020 Version - Honestly not sure, but it's the most up-to-date as of 30/06/2022

**Mod version:**
- Mod version 5.0.9

**Log**
Attached

**Screenshots**
Attached
<img width="619" alt="image" src="https://user-images.githubusercontent.com/108494291/176779506-ce628872-6770-41ac-957d-8031ae29510e.png">

**Additional context**
[20220630220803.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9023414/20220630220803.zip)

**Comment by TootY1993** [comment]
Hello,

Could I ask if you've managed to look into this?

Thank you,

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
