### ISSUE TITLE
Nginx Server stucked in "checking" mode

### ISSUE THREAD

**Issue by Zofren** [derekhe/msfs2020-map-enhancement#189]
**Describe the bug**

In the previous version, both indicators were green and I could see tiles loading and cache load. 

It is now stucked as figured in the joined picture.

**MSFS version:**
 - steam
 - MSFS2020 Version [e.g. 22] : 

**Mod version:**
- Mod version : same with 5.0.9 and 5.1.0

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file : Collect issue doing nothing

**Screenshots**
![2022-07-02_11h15_19](https://user-images.githubusercontent.com/1533636/176994398-692ba364-e97d-4afb-8dc5-ca5668c6a870.png)

**Additional context**
- MOD starting MSFS
- Cache set to 50Go
-

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
