### ISSUE TITLE
Unable to create certificate

### ISSUE THREAD

**Issue by khaapamaki** [derekhe/msfs2020-map-enhancement#19]
I get following error when creating a certificate. I believe the second one is because java.io cannot access path with letter 'ä' in my name. I currently have similar issue with javac.exe in my own project. Some code bases are still in 2022 unable to handle paths with UTF8/16 characters. Version 0.1.0 and before worked fine for me. The issue is on 3.0.0.

Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net The local CA is already installed in the system trust store! 👍 Note: Firefox support is not available on your platform. ℹ️ ERROR: failed to execute "keytool -importcert": exit status 1 keytool error: java.io.FileNotFoundException: C:\Users\Kati Haapamäki\AppData\Local\mkcert\rootCA.pem (The system cannot find the path specified)

EDIT: Not sure about previous version number, but pre-installer version...

**Comment by derekhe** [comment]
hmm, non-ascii characters will cause problems. This tool is not created by me but I can have a look if anything can do from my side.

**Comment by derekhe** [comment]
Possible way to fix this:
add an system environment variable CAROOT and set it to C:\

**Comment by khaapamaki** [comment]
Thanks, I'll try that. I was a bit wrong though. Certificate files are created, but they cannot be read. I still believe it's because that Java component cannot access my AppData due that non-ASCII character. I have a second account that I use for testing. It has no non-ASCII characters in the AppData path and you application runs without issues with it. It would probably help if I manage to create certs to some accessible folder.

There are some apps that fail in this scenario. As proof my User folder has three different folders, of which two of them are bogus and created by some 3rd party apps, not by Windows. 
![image](https://user-images.githubusercontent.com/12098712/148682427-2033cd53-d904-4334-9d5e-a6da18f165ed.png)

**Comment by derekhe** [comment]
Yes, non ascii always have this issue. Is the fix good?

**Comment by derekhe** [comment]
I will close this as no reponse for a long time.

**Comment by khaapamaki** [comment]
Sorry for the delay. 3.0.6 did not solve the issue for me.
