### ISSUE TITLE
[Feature] Possibility to disable "de-brightness" image processing feature

### ISSUE THREAD

**Issue by Tragedie-v-JZD** [derekhe/msfs2020-map-enhancement#190]
#### Motivation

Althought that brightness of (especially) "bing maps (latest)" is not so much real in MSFS environment, i like that "colorfull" world.  In previous versions i was able to "disable" de-brightness in appropriate .py file. In latest version i noticed that source code is obfuscated, so i am not able to do that by self.

#### Detailed design

Checkbox in application UI which will allow configuration (at least disable / enable of de-brightness) of the image processing.

Thank you

**Comment by derekhe** [comment]
The image adjustment will come later in pro version.

**Comment by derekhe** [comment]
The pro version now contains image processing, could you have a try?
