### ISSUE TITLE
Invalid License Error

### ISSUE THREAD

**Issue by 7ilmaz** [derekhe/msfs2020-map-enhancement#194]
**Invalid License Error**

**MSFS version:**
 - msstore
 - MSFS2020 1.26.5

**Mod version:**
- Mod version 5.1.0

**Log**
- zip file can't be attached. 
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9043459/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9043460/renderer.log)

**Screenshots**
![Screenshot 2022-07-05 082624](https://user-images.githubusercontent.com/108661324/177255692-153f8b3b-658c-48f7-8983-04c28bd49b80.png)

**Additional context**
can't connect to image server, and I get an invalid license error.

**Comment by Bodenseeler742** [comment]
here the same :(

**Comment by derekhe** [comment]
Thanks for reporting, I'm trying to fix this issue.

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
