### ISSUE TITLE
Version 5.1.0

### ISSUE THREAD

**Issue by musicmaker7** [derekhe/msfs2020-map-enhancement#196]
**Describe the bug**  I cannot use the app.  I had to reinstall 5.0.9  If I load it to fly, I lose control of the app and cannot close or end the mod.  i have to uninstall it.

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.25

**Mod version:**
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
Please try latest version.
