### ISSUE TITLE
PUA:Win32/Pearfoos.B!ml detected in your code with new version

### ISSUE THREAD

**Issue by xGhostWolfx** [derekhe/msfs2020-map-enhancement#197]
While this can be a false positive, and low impact any flag is alarm for concern and was never there before or detected by other virus/malware programs previously.

The location of this potential malware: MSFS2020 Map Enhancement\resources\extra\server\dist\pytransform.pyd

this is also linked to spyware and back doors to install other malware.  I really hope this isn't the case but please address

**Comment by zaelu** [comment]
I can also confirm this warning from windows defender with version 5.10 and it doesn't appear right away after install/upgrade but rather after few days.

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
