### ISSUE TITLE
Image Server Failed

### ISSUE THREAD

**Issue by Walshie1987** [derekhe/msfs2020-map-enhancement#198]
Hi, 

FIrstly great plugin, honestly the nest I've use for any sim! (FS / X-plane)

I consistantly get the image server failed message now when I start, using 5.0.9 with any map server selected. It's been like this for a day or two now.

Error logs attached.

Thanks in advance,
Chris
[20220708193508.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9074409/20220708193508.zip)

**Comment by Walshie1987** [comment]
These seems to be an issue with cache, once disabled it loads instantly.

Hope this helps,
Chris

**Comment by derekhe** [comment]
5.x version is not supported now, will close this.
Please try 6.1.0
