### ISSUE TITLE
Circling Texture Around Cities

### ISSUE THREAD

**Issue by TootY1993** [derekhe/msfs2020-map-enhancement#199]
Screenshots attached. For some reason, I get circling which looks to be the default textuiring around larger cities. The rest of the areas seem to be covered by the Google Maps mod. I have no cache within MSFS or the Application..

Is this normal?

**MSFS version:**
 - Microsoft Store
 - MSFS2020 Version 1.25

**Mod version:**
- Mod version 5.1.0

**Screenshots**
Attached
![Microsoft Flight Simulator Screenshot 2022 07 09 - 16 16 49 62](https://user-images.githubusercontent.com/108494291/178112226-1bbfc83a-fe49-4eda-85e5-f884d6976dac.jpg)
![Microsoft Flight Simulator Screenshot 2022 07 09 - 16 24 27 81](https://user-images.githubusercontent.com/108494291/178112245-1124821d-15f4-405f-a884-025f49b0bfa4.jpg)

**Comment by PilotNerd95** [comment]
I am having this same problem. Occurs for Bing Latest maps as well. Curious if this is due to base code preserving Bing original maps around cities? I am no code expert, so I don't know for sure.

**Comment by TootY1993** [comment]
Any chance we could get an update from the content creator?

Thank you
