### ISSUE TITLE
Acces denied creating certificate

### ISSUE THREAD

**Issue by MendioxCS** [derekhe/msfs2020-map-enhancement#20]
ISSUE: I've installed everything as said, but when I click on "Inject Google Maps" an error appears: "Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access denied."... How may I solve this? Any suggestion? Thanks a lot for this mod...

**Comment by derekhe** [comment]
I think it caused by your antivirus, please check your antivirus settings or try uninstall it (restart computer after you do), then have a try.

**Comment by MendioxCS** [comment]
Good day, I'm using windows defender antivirus, I've disabled it and still same problem. I'm using now the new 3.0.5 version but issue is still there. Is there any way to create the certificate myself? Thanks a lot.

**Comment by derekhe** [comment]
Please have a look here: https://github.com/FiloSottile/mkcert/issues/231

**Comment by MendioxCS** [comment]
Hi, I've tried it and works really nice for me. It was a quite difficult process but works great! Thanks a lot for the solution. Best regards...
