### ISSUE TITLE
Nginx Server alaways in checking model

### ISSUE THREAD

**Issue by Yang-Noah** [derekhe/msfs2020-map-enhancement#200]
**Describe the bug**
Nginx Server alaways in checking model no matter which way i try to connect.
**MSFS version:**
latest until 2022/7/10
 - msstore or steam
 - mmstore
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version
5.10
**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**
![a7b65a43f569fbd74f76f583947d8c3](https://user-images.githubusercontent.com/91602159/178135772-c5506265-07b1-4236-9265-a9a4fb85884b.png)

**Additional context**

**Comment by derekhe** [comment]
5.x version is not supported now.
