### ISSUE TITLE
CTD , here is the log 

### ISSUE THREAD

**Issue by mikecbr** [derekhe/msfs2020-map-enhancement#201]
**Describe the bug**

**MSFS version:**
 - msstore 
 - MSFS2020 latest stable

**Mod version:**
- 509

**Log**

[20220710160934.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9079219/20220710160934.zip)

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
