### ISSUE TITLE
I'm just going to have this total Loaded image of 1, and I'm not going to load any other layers

### ISSUE THREAD

**Issue by GloriaQianxi** [derekhe/msfs2020-map-enhancement#202]
I'm just going to have this total Loaded image of 1, and I'm not going to load any other layers

([](![QQ图片20220719144711](https://user-images.githubusercontent.com/82936094/179684185-b7ce2628-3632-49ee-9b1f-94a24a877ada.png)))

**Comment by derekhe** [comment]
Please try 6.1.0.
Please provide more information.

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#image-loading-issue
