### ISSUE TITLE
Can't find host file咋办？点击start就直接跳出来这个网页，然后下面红色显示Can't find host file。网上修复host方法全用过了，软件也卸载重下很多遍。还是一样点击start就弹出这个网页，下面显示Can't find host file

### ISSUE THREAD

**Issue by wobuzd11** [derekhe/msfs2020-map-enhancement#203]
**Describe the bug**

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
这个99%和杀毒软件有关系

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
