### ISSUE TITLE
CTD with custom scenery

### ISSUE THREAD

**Issue by MrPeterJin** [derekhe/msfs2020-map-enhancement#204]
**Describe the bug**
Hi, when I start your awesome mod with ZGGG made by samscene3D, it cannot render properly (screenshot is provided below) and crashed to desktop, else where is normal.

**MSFS version:**
 - steam
 - MSFS2020 Version 1.27.11.0

**Mod version:**
- Mod version  5.10

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 
... seems collect logs button is not responding? I've clicked it and it didn't show any zip file.

**Screenshots**

![image](https://user-images.githubusercontent.com/51412849/180342116-9d76aa6a-f670-42e0-9287-18cb681d89d0.png)

**Additional context**

**Comment by derekhe** [comment]
Are you use SU10 Beta?

**Comment by MrPeterJin** [comment]
> Are you use SU10 Beta?

Yes... Seems like it is the SU10 Beta's own problem with custom scenery?

**Comment by MrPeterJin** [comment]
Okay it turns out to be the SU10 Beta Problem... Get an update and it went back to normal.

**Comment by MrPeterJin** [comment]
Hi, I am using the updated SU10 now, but the problem still persists:

![image](https://user-images.githubusercontent.com/51412849/193393024-3a2b172e-d307-431e-9086-551c95dde98c.png)
![image](https://user-images.githubusercontent.com/51412849/193393035-d415032d-0672-4428-a1f5-16ac489f0016.png)
 
And here is the log file:
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9689560/log.zip)

**Comment by derekhe** [comment]
Try update to latest version, v5 is not supported any more.

**Comment by deiks** [comment]
I got few CTDs with the latest version. Not sure if it's related to map enhancement at all. Will try to play without it and test it. Everything was fine with the version before last one.

**Comment by deiks** [comment]
At least not getting CTD with older version (for now) -- back to 6.1.6.0

But getting these:

![2](https://user-images.githubusercontent.com/4221827/195575682-29353da4-5869-461c-9d22-189f7848a43f.png)
![3](https://user-images.githubusercontent.com/4221827/195575718-fd00c740-eea7-47f0-adc4-479961df7359.png)
![1](https://user-images.githubusercontent.com/4221827/195575634-caf68bf6-4a75-4e84-825c-24972f8c72ad.png)
![4](https://user-images.githubusercontent.com/4221827/195575517-c6726dac-b690-4c15-8b08-eebb6f947dba.png)
![5](https://user-images.githubusercontent.com/4221827/195575587-609f3c62-9881-4c3d-af9d-c9811395c30f.png)

**Comment by MrPeterJin** [comment]
Hi, try to clear your MSFS cache and MSFS enhancement cache. After that, restart the game. I fixed it by applying these.

**Comment by deiks** [comment]
> Hi, try to clear your MSFS cache and MSFS enhancement cache. After that, restart the game. I fixed it by applying these.

Will try to do that. Don't get that every time, so I assume it's something mixed within rollcache and map enhancement.

Do you have issue with loading tiles in distance? And how does that work? Is it related to connection or? Like when I'm flying, I can see that it loads tile by tile in front of me (almost not important -- in 2 seconds I overfly it so nonsense to load it if I can't enjoy in it). My connection is fast and stable, so don't see that should be issue. I would like to have faster load in front of me.
