### ISSUE TITLE
msfs2020

### ISSUE THREAD

**Issue by kingofclubs77** [derekhe/msfs2020-map-enhancement#205]
**Describe the bug**
will not launch game, I have steam and store and neither launches. My pc is reset and it worked on the previous ssd.
**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
5.1.0 has a token inside and seems it is expired. Please use 5.0.9 instead.
I'm writing a complete new version.

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
