### ISSUE TITLE
[Feature] Start Map Enhancement via Console

### ISSUE THREAD

**Issue by pthoelken** [derekhe/msfs2020-map-enhancement#207]
#### Motivation

So for my case I start the simulator and a bunch of .exe addons by a batch file. Usually all addons are batch files / console applications. When I configures the Map Enhancement the first time IMHO I don't need the GUI anymore. 

#### Detailed design

Start the application as console application like these: 

`start "" "C:\Program Files\MSFS2020 Map Enhancement\MSFS2020 Map Enhancement.exe" --console --force-startup
`
And only a console windows comes up with force starting map enhancement.

**Comment by derekhe** [comment]
Sorry I don't have this plan at the moment :)

**Comment by pthoelken** [comment]
IMHO we don't need this anymore bc you can configure the map enhancement tool that the flight simulator starts automatically with the map server when you start the map enhancement. 

I was not informed about this fact before. 

So, for me ... closed?

**Comment by pthoelken** [comment]
But may another question, what do you think is the best map provider? Currently I'm using "mapbox".

**Comment by derekhe** [comment]
It depends on different area.
For me living in China, the best is Google Maps
