### ISSUE TITLE
[Feature] Deploy the web server on Linux server/docker

### ISSUE THREAD

**Issue by dominick-han** [derekhe/msfs2020-map-enhancement#208]
#### Motivation
As my understanding, we are using flask/nginx to MITM (pretend to be azureedge.net/edgekey.net), and serving google/whatever map images via web server. Technically this could be anywhere, not just on localhost, as long as we (manually) edit the host file to point at the IP/server that serves this on port 443

#### Detailed design
Be able to install/launch this program in linux, via CLI (so we can make it a persistent service), and this can be shared between multiple computers playing MSFS. Also increases cache hit if multiple games are flying in the same area?

Also, some people might prefer to deploy it in kubernetes/docker? 

#### Alternatives
N/A

#### More detail (optional)
- Have to figure out how to provide the CA/cert to each of the computers running the game
- Is there any rate limit from google maps/other providers?
- Larger cache maybe?
- I'm a developer as well and can help/take on the projest, let me know!

Thanks,
Dominick

**Comment by derekhe** [comment]
I don't have any plan to serve it on a server.

* Have to figure out how to provide the CA/cert to each of the computers running the game
Yes, you can create a licence using mkcert.exe. You can find it out in the source code and you will see the parameters.

* Is there any rate limit from google maps/other providers?
I don't know.

* Larger cache maybe?
I'm working on a complete new version using C#, will fix the cache issue.
