### ISSUE TITLE
MOD keeps crashing

### ISSUE THREAD

**Issue by NGOKrisHawkins** [derekhe/msfs2020-map-enhancement#209]
**Describe the bug**

**MSFS version:** 9
 - msstore or steam  mstore
 - MSFS2020 Version [e.g. 22]

**Mod version:**  5.1.0
- Mod version

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**
the app keeps freezing while open and its not generating the title during a flight

**Comment by jkkfsfsq1** [comment]
i have the same problom

**Comment by derekhe** [comment]
5.1.0 has a token inside and seems it is expired. Please use 5.0.9 instead. 
I'm writing a complete new version.

**Comment by NGOKrisHawkins** [comment]
How do I use the token, where do I find it ?

**Comment by derekhe** [comment]
hmm, I'm wrong. Just checked the license token is still vaild. Please try 5.0.9.
I'm working on complete new version, maybe can fix these issues.

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
