### ISSUE TITLE
程序无法运行

### ISSUE THREAD

**Issue by gykg0718** [derekhe/msfs2020-map-enhancement#213]
尊敬的贺先生，首先要向你表示感谢，这个软件真的太棒了!

两个多月前我在网上花了20多块钱买的这个软件，卖家远程协助费了好大的劲才调试出来，期间把windows 11降到windows 10 Pro，又改了地区和语言等。使用的时候感觉非常满意，尽管说谷歌地图用不了，但是对我而言bing的最新地图以及Mapbox已经非常满意了。后来我又升级到5.10，但起来不太顺畅。最近一个星期突然就不能使用了，各种配置也看着都没问题，但是就是运行不起来（所有的地图模式都不能用），不知道什么原因。
前一时期我注意到MAPBOX下载超过200000张照片，是这个因素导致的？可为什么其他胡地图模式也失效了呢？
附上相关信息。
[20220801185753.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9233356/20220801185753.zip)

希望您为大陆玩家提供一个权威的、完整的配置和使用说明。也请开放微信或支付宝支付功能，以便我们表达感谢。
我的联系方式：wangxk@sina.com，
谢谢！

**Comment by derekhe** [comment]
可能是之前的Token过期了，请用5.0.9版本。后续版本正在开发中。

**Comment by derekhe** [comment]
hmm, I'm wrong. Just checked the license token is still vaild. Please try 5.0.9.
I'm working on complete new version, maybe can fix these issues.

**Comment by derekhe** [comment]
说实在的，某海鲜市场卖软件的也太多了，被坑的玩家也不在少数。而且我得到的回报其实非常非常的少，感觉到非常的无力。
所以也就没有动力在大陆推广和做事情了。

**Comment by derekhe** [comment]
Please try use latest version, will close this now.
