### ISSUE TITLE
Default BING maps can't correct work after using mod with google map

### ISSUE THREAD

**Issue by lesykbiceps** [derekhe/msfs2020-map-enhancement#214]
**Describe the bug**
First off all I should say that google map working good but when I try to return default BING map my sim cant normally work.
I get a message that my bandwidth is too low for data and my connection lost so I go to offline. Reinstalling a simulator on a different disk didn't help and it is not problem with internet connections(checked with google maps and different games). Your mod delete two last line in hosts file after switching off so this file is good and clear after   disabling your mod. Also I deleted hosts file but it didn't help so I don't know what to do to have normal BING map
**MSFS version:**
 -  last steam version
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version
5.0.9
**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 
[20220802152754.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9242284/20220802152754.zip
**Screenshots**
![image](https://user-images.githubusercontent.com/71440148/182377130-a7ecef4b-4595-48c3-8729-732e4dcb6a17.png)
First image when I take off and all is good
![image](https://user-images.githubusercontent.com/71440148/182377220-301961da-b203-4cd1-aec6-177266727e2c.png)
Second image after some time after take off(maybe 2-3 minutes) speed of internet go down and I get a message in mfs and go automatically offline.
**Additional context**
When I loading with standart BING in some airport I have normal phototerrain around my airport but when I take off and fly 2 minutes from airport phototerrain suddenly stopped loading and I have a message that I switched to offline .
But sometimes I have this problem even on ramp
![image](https://user-images.githubusercontent.com/71440148/182378712-c6072c9c-2b07-4609-95c7-cbf0e42cd3d7.png)

 I have such  behavior with my  internet connection only when I use standard BING maps

**Comment by RafaTornich** [comment]
Hi there, I'm having the exact same problem
MOD v. 5.1.0
MSFS2020 v. 1.27.13.0

**Comment by derekhe** [comment]
Please wait the new version 6. The old version's performance is improved in this version.
