### ISSUE TITLE
Crashing when clicking settings icon

### ISSUE THREAD

**Issue by rickvandijck** [derekhe/msfs2020-map-enhancement#216]
Clicking the settings icon crashes the app

**MSFS version:**
 - MS Store
 - SU 10 1.27.14.0

**Mod version:**
- 6.0.0 Alpha

**Log**
I can't, since I don't have access to the settings tab

**Comment by derekhe** [comment]
Thanks for reporting, I will have a look.

**Comment by marcelocanela** [comment]
I click to open the program as explained in the readme and nothing happens. what should I do ?

**Comment by derekhe** [comment]
@marcelocanela  what's your windows version? could you give me a screenshot using "winver" command?

**Comment by marcelocanela** [comment]
> @marcelocanela qual a sua versão do windows? você poderia me dar uma captura de tela usando o comando "winver"?

Windows 10 Pro v.21H2

**Comment by derekhe** [comment]
ok, I'm looking at this problem. It can be reproduced in windows 10

**Comment by derekhe** [comment]
How about 6.0.5? I fixed it.
