### ISSUE TITLE
Error: Could not find hosts file

### ISSUE THREAD

**Issue by PaulFMcG** [derekhe/msfs2020-map-enhancement#219]
**Describe the bug**
The Google Maps were not loading and i saw mention of deleting the hosts file. I moved it to the desktop so it was all "original" and i then created a new hosts file. Now the system says it cant find it...i even tried to put back the old "original" hosts file and it still cant find it...even though i see it there.

**MSFS version:**
 - msstore or steam: MS Store
 - MSFS2020 Version [e.g. 22]:26.5

**Mod version:**
- Mod version: 6.0 Alpha

**Log**
- Please use the "Collect Logs" button in "Report Issue" page and attach the zip file 

**Screenshots**
![image](https://user-images.githubusercontent.com/111211008/184520924-d89e2824-e61a-4f55-a78c-e748dbabbbb7.png)

![image](https://user-images.githubusercontent.com/111211008/184520939-dd2cfedc-8c19-43f3-b943-45b7eb379c06.png)

![image](https://user-images.githubusercontent.com/111211008/184520948-c4410684-637e-478d-9b8a-d70a5f0e9294.png)

**Additional context**

**Comment by derekhe** [comment]
I think the hosts file you created ends with ".txt" which shows "Text Document" as Type.
Please let windows show the file extension and remove the ".txt"

**Comment by PaulFMcG** [comment]
WOW...Thank You...
I saw it was saving as a .txt and didn't realize that was the issue. 
Found a YouTube video on how to allow windows to show the extensions for know file types and was then able to see it was a .txt file. 
I deleted the .txt and it now works. 
Thank You!
