### ISSUE TITLE
Unable to exit the MSFS2020 Map Enchancement Window

### ISSUE THREAD

**Issue by junfan85** [derekhe/msfs2020-map-enhancement#221]
**Describe the bug
Whenever i close the "MSFS2020 Map Enhancement" window, it will not close. I need to run Task Manager and "End Task*

**MSFS version:**
 - msstore

**Mod version:**
- 6.06

**Log**
- Please use the "Collect Logs" button in "
[nlog-2022-08-21.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9389398/nlog-2022-08-21.log)
[nlog-internal.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9389399/nlog-internal.log)
Report Issue" page and attach the zip file 

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
I'm investiagting this problem. I can reproduce on my computer.

**Comment by derekhe** [comment]
It is fixed in 6.1.0, please try.
