### ISSUE TITLE
Connection problems using version 6.0.6

### ISSUE THREAD

**Issue by Gerardus1** [derekhe/msfs2020-map-enhancement#222]
Connection issues in MSFS 10 BETA after installing Map Enhancements 6..0.6. 
After uninstalling 6.0.6. I get still the message in MSFS _**@Your Bandwidth is to low, for data streaming, you have been switched to offline mode

please advice

Msfs 2020 Beta 10, 1.27.16.0 msstore mod 6.0.6

**Comment by mtjoeng** [comment]
check your host file, was my problem

**Comment by Gerardus1** [comment]
Thanks for you comment, but what is an host file, pls explain

**Comment by mtjoeng** [comment]
c:\Windows\System32\drivers\etc\hosts 
Map Enhancements adds 2 lines:
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
which are deleted when Map Enhancements stops. But sometimes this gets stuck, and the host file has these lines when you start MSFS without Map Enhancements. That's when I have/had Connection errors.

**Comment by Gerardus1** [comment]
Thank you very much for your help mtjoeng! Problem is SOLVED!
