### ISSUE TITLE
[Feature] Possibility To Add Apple Maps As Source

### ISSUE THREAD

**Issue by TooSpooky** [derekhe/msfs2020-map-enhancement#228]
Hello,

I'd like to ask about the ability for Apple Maps to be added as a source to pull tiles from. I'm unsure about their API capability.

They seem to have better quality in certain areas in comparison to Bing and Google, if not at least more up to date data. Especially in areas such as China.

Comparisons:
Apple Maps: https://i.imgur.com/Di39Ixz.jpeg

Google Maps: https://i.imgur.com/Vwm7SIH.jpeg

Here's another good example in New York via Duckduckgo who also uses Apple Maps: https://duckduckgo.com/?va=j&t=hb&q=New+York+JFK+airport&ia=web&iaxm=maps&iax=images&strict_bbox=0&bbox=31.85651075839243%2C118.71588432796466%2C31.699783858612015%2C118.92273628719317

Thanks for your time and take care!

**Comment by josefpy** [comment]
Its true! Apple maps has a really good color and quality image. If it will posibility to add in the aplication definetively I will pay for Pro versión

**Comment by derekhe** [comment]
After you enable the pro version, you can use the "Custom map feature". 
I didn't validate apple map is working or not. Please provide the url and I can test it.

**Comment by derekhe** [comment]
@TooSpooky @josefpy https://github.com/derekhe/msfs2020-map-enhancement/wiki/How-to-use-Apple-maps
