### ISSUE TITLE
谷歌地图

### ISSUE THREAD

**Issue by LanJack** [derekhe/msfs2020-map-enhancement#23]
一切运行正常，但是在游戏内就是无法显示google地图 软件也只能显示
![image](https://user-images.githubusercontent.com/46474649/148654456-5bbb355a-5214-4913-ac9d-a90663203512.png)

**Comment by derekhe** [comment]
在Trouble Shooting页面里面，找到Log folder，然后把目录里面的文件传到这里。

**Comment by LanJack** [comment]
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7835337/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7835338/renderer.log)


> 在疑难解答里面，找到日志文件夹，然后把目录里面的文件传到这里。

**Comment by LanJack** [comment]
> 在疑难解答里面，找到日志文件夹，然后把目录里面的文件传到这里。

以前用python版本的时候成功了很久，但是最近开始就无法正常使用了，无论是python还是软件。

**Comment by derekhe** [comment]
这个有可能是你的谷歌访问有一些问题？请检查一下，可以试试ArcGIS能不能访问（这个不用翻墙）
另外可以看一下你的hosts文件是不是有什么杀毒软件给锁定了，或者是一些软件持续的在更新hosts文件

**Comment by LanJack** [comment]
> 这个有可能是你的谷歌访问有一些问题？请检查一下，可以试试的ArcGIS能不能访问（这个不用翻墙） 另外可以看一下你的主机文件是不是有什么杀毒软件给锁定了，或者是一些软件持续的在更新hosts文件

我检查了我的谷歌访问，并没有任何问题同时我也尝试过了ArcGIS这个模式同样不行，我把杀毒软件全关掉了也还是无法正常运行，并没有软件在持续的更新hosts文件。

**Comment by shulinbao** [comment]
我最近抓包的时候发现，卫星地图的路径从
`https://kh.ssl.ak.tiles.virtualearth.net/tiles/akh{quadkey}.jpeg?n=z&g={gen}\`
变成了
`https://kh.ssl.ak.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?n=z&g={gen}\`
这会导致本工具失效，解决办法是
`\resources\extra\nginx\conf\nginx.conf`
将 location ~* /tiles/akh.*? { 改为 location ~* /tiles/a.*? {
`\resources\extra\server\sever.js`
将 router.get("/tiles/akh:quadKey.jpeg", async (ctx, next) => { 改为 router.get("/tiles/a:quadKey.jpeg", async (ctx, next) => {

希望能解决到你的问题

**Comment by shulinbao** [comment]
python版本也是类似的，server.py里面对应的部分即可

**Comment by LanJack** [comment]
> 我最近抓包的时候发现，卫星地图的路径从 `https://kh.ssl.ak.tiles.virtualearth.net/tiles/akh{quadkey}.jpeg?n=z&g={gen}\` 变成了 `https://kh.ssl.ak.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?n=z&g={gen}\` 这会导致本工具失效，解决办法是 `\resources\extra\nginx\conf\nginx.conf` 将 location ~* /tiles/akh._? { 改为 location ~* /tiles/a._? { `\resources\extra\server\sever.js` 将 router.get("/tiles/akh:quadKey.jpeg", async (ctx, next) => { 改为 router.get("/tiles/a:quadKey.jpeg", async (ctx, next) => {
> 
> 希望能解决到你的问题

感谢回复，问题已解决

**Comment by derekhe** [comment]
Fixed in version 3.0.8, please have a try

**Comment by zhang-zeyu** [comment]
@LanJack 老哥你是怎么解决的 我和你同样的问题
