### ISSUE TITLE
High LOD vertical inconsistency

### ISSUE THREAD

**Issue by mikluhomaklay** [derekhe/msfs2020-map-enhancement#230]
Hello derekhe. Im Zhdun from flightsim.to.

I believe i have discovered the cause of the problem with tiles being replaced ahead and behind the active camera in a very noticable and annoying nature in certain areas, when High LOD is enabled. I was able to reproduce it.

The problem is not the app, but the tiles from map provider on different detail level. 
So when High LOD is enabled the app is requesting images from a higher lod layer from the provider and combines them into higher resolution tile. However such a shift to a higher lod layer in some areas results in the problem that the tiles from the map provider may be from a different year and season. Therefore the high resolution textures around active camera may have a significal shift in color/tone. And this is causing inconsistency with lower LOD tiles in the distance. All map providers have this issue in certain areas. I have reproduced with Bing and with Google and there were also reports that it also happens with mapbox. 

It can also be observed on the world map in msfs. So in a region where images on different lod layers are not same images, but from different year/season, you will see a sudden color change on the map when zooming in to max. And when zooming out just one step, it switches the color again. In such a region you always get this problem. 

In other regions, where no color change at maximum zoom level appears, means that same images are used by map provider for all lod levels, they just have different resolutions. Then this problem does not come up, as the images from lower lod layer are matching the images from next lod layer.  

Suggested solution: 
This can probably be fixed when the app ensures that all tiles, the high and low resolution ones are coming from same LOD layer from the provider. However this would also result in higher bandwidth required in high LOD mode, as it would mean requesting higher lod layer also for the lower resolution tiles.

**Comment by derekhe** [comment]
Yes, exactly, thanks your feedback.  Yesterday I also updated FAQ page here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#image-quality-issue

One solution is to merge the lower level from higher lod offline.
Another solution is lock the lod in some area to prevent this happen (but requires lots of human efforts)
