### ISSUE TITLE
Mod doesn't load Images

### ISSUE THREAD

**Issue by Cocazou** [derekhe/msfs2020-map-enhancement#239]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore 
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version 6.1.0.0

**Device ID**
- Device ID
11GZ3JB9E6AYKSPHMCQE2VB0K6VQ9TV577SRZTW6E86FX9R9EAAG

**Log**
- Please attach the log zip file 
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9478666/log.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/35146192/188170023-cde7bd7e-055f-48c0-ae20-89943c198fc4.png)
![image](https://user-images.githubusercontent.com/35146192/188170585-ac70450a-a919-4ae7-bea8-f4acaca6b30b.png)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Out of the box. Only added checked the box with High LOD.

Looked over the FAQ without finding a solution

Regards

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#image-loading-issue

**Comment by Cocazou** [comment]
Hi,

Yes it is ON.

And Issue is still there after Update

**Comment by derekhe** [comment]
Did you open your game after the mod starts? And turn on the bing online maps

**Comment by Cocazou** [comment]
These are my steps

Opening the game -> Starting the game ->  Open/Start the mod

**Comment by derekhe** [comment]
You are in wrong order:

* Open/start the mod and make sure very check is passed
* Play with the game.
