### ISSUE TITLE
Request: Add command line switch to start app with injection running

### ISSUE THREAD

**Issue by jeffdamp-wave** [derekhe/msfs2020-map-enhancement#24]
Version: v3.0.5
Add a command like "MSFS2020 Map Enhancement.exe"-run to start the app with "Inject Google Map" checked.  This way you can add this to a batch file when launch MSFS2020.

Also get rid of the Pause when the program exits.  When launch from the command line you should not block from returning to the prompt.  The old code in the run.bat had a pause at the end.

**Comment by derekhe** [comment]
I will close this now and will open in future when implement
