### ISSUE TITLE
Don't start installation

### ISSUE THREAD

**Issue by palladro** [derekhe/msfs2020-map-enhancement#240]
Iìve the 5.0.9 version install and want to instal the new 6.1.3 but when i try there is an error reporting that i haven't the permission to open the file. I try to downoload several time and extract in different directory but the problem still remain. Obviously i've put the file in the exclusion list of the antivirus (like i do with previous relase) but i can't install.

msstore
 - MSFS2020 Version 1.26.5.0

- Mod version 6.1.3

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I had this problem 1 or 2 times but can't reproduce. Please try restart?
