### ISSUE TITLE
无法用命令行启动程序

### ISSUE THREAD

**Issue by demonguy** [derekhe/msfs2020-map-enhancement#241]
模拟飞行一般要一次性开很多工具, 比如

- google map replacement
- 录像工具
- 模拟joystick工具
- 代理
- little navmap
- 航图

所以我自己写了个批处理. 但是似乎googlemap replacement会随着父进程的关闭而关闭
`C:\Windows\System32\cmd.exe /C start "" "H:\GoogleMapEnhancement\MSFS2020 Map Enhancement.exe"`
比如我这样启动是启动不了的, 不知道有木有解决办法

**Comment by derekhe** [comment]
hmm，这个应该是你没有用管理员启动的问题？

**Comment by demonguy** [comment]
不是, 我确定是更新了6.10.0之后的问题.
5.x的时候还没有这个问题. 你是没有这个问题吗?

**Comment by derekhe** [comment]
![image](https://user-images.githubusercontent.com/1734077/189525941-ef9543e7-68ae-42b7-b288-02ea47ed12ff.png)

我这里正常可以启动

**Comment by demonguy** [comment]
我这样是不行的

- `C:\Windows\System32\cmd.exe /C start "" "H:\GoogleMapEnhancement\MSFS2020 Map Enhancement.exe"`
- `H:\GoogleMapEnhancement\MSFS2020 Map Enhancement.exe"`
这样操作的现象是程序没打开, 还遗留了一个cmd窗口

这样是可以的, 但是也会遗留窗口
`"C:\Users\Public\Desktop\MSFS2020 Map Enhancement.lnk"`

你使用powershell能做到执行脚本之后命令行自动退出吗?

**Comment by derekhe** [comment]
我试了下从命令行弄个bat文件确实会留下一个cmd窗口。你自行看看有没有其他的解决方案，本身设计这个程序的时候是没有考虑命令行执行的。

**Comment by demonguy** [comment]
好吧.
我对windows不太熟悉, 感觉像是你的代码在某个地方bingding了console. 估计是为了打印log? 我不太确定.
以前也会留下窗口, 但是只要用start就没问题, 升级6.1.0之后就悲剧了, 我自己再看看吧~,谢了
