### ISSUE TITLE
Paid for Licence of Pro version did not receive email

### ISSUE THREAD

**Issue by baxterbj** [derekhe/msfs2020-map-enhancement#242]
I have paid the $30 dollars USD and have not received a Pro Licence.
I did not understand Device id so may have, Given my device Name.
I have now found device id, but how do i submit this as I have not received a licence for my payment?

Regards Brian
BJ from Oz

**Comment by derekhe** [comment]
Copy the device id here and refill the form: https://docs.google.com/forms/d/e/1FAIpQLSchhHIUjSoQx3HgA6nJcULwTziE7ppTaDvx9IETlPkpK81WTw/viewform
![image](https://user-images.githubusercontent.com/1734077/189517807-b7e9f1f3-f62d-4863-9781-97d76cc1c575.png)

**Comment by baxterbj** [comment]
Sent from Mail for Windows
