### ISSUE TITLE
Unable to use Pro version as per emails of Licence and Device Id

### ISSUE THREAD

**Issue by baxterbj** [derekhe/msfs2020-map-enhancement#244]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by baxterbj** [comment]
MSSTORE version
615 version of Map Enhancement
Device Id 8019648C-D51A-4FBB-843A-783DEB221410
Device Id showing in Map Enhancement: F6FBXSEEY14N0RHXY7SFN7DBHWK99WRAAQWW2QAB4Y3Z056QNAJG
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9543809/log.zip)
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9543810/log.zip)
You sent me special id as I could not press on copy device Id. Before you sent me this I deleted and reinstalled a fresh copy thinking my copy was corrupted. So, the Licences do not work
![bj screeny](https://user-images.githubusercontent.com/113281267/189555642-8a2c7059-0eef-482d-84b5-15cc64d542e1.png)

**Comment by derekhe** [comment]
I sent you a new license. Please check.
