### ISSUE TITLE
Find out satellite image URL prb

### ISSUE THREAD

**Issue by albihihi** [derekhe/msfs2020-map-enhancement#246]
**Describe the bug**
Open developer mode in Chrome by pressing F12
when i open this link  and swich  from map to sat  i get this  

**MSFS version:**
![IMG_6810](https://user-images.githubusercontent.com/113530043/190178466-c82037f5-2d9a-46e9-ad28-1978132b6792.jpg)

 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Should use the "Network" tab
I updated the doc, please try again.
https://github.com/derekhe/msfs2020-map-enhancement/wiki/How-to-use-Apple-maps

**Comment by albihihi** [comment]
![IMG_6812](https://user-images.githubusercontent.com/113530043/190204441-f2720a57-b9e8-4ebb-b4dd-bbe893f77d9a.jpg)
Iuse the **Network tab**

**Comment by albihihi** [comment]
The instructions by pictures( how to use apple maps) not enough need video tutorial, i hope you do
thank you

**Comment by derekhe** [comment]
Now the 6.1.7 has builtin apple map, please retry :)
