### ISSUE TITLE
cant log with Apple Map 

### ISSUE THREAD

**Issue by albihihi** [derekhe/msfs2020-map-enhancement#247]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by albihihi** [comment]
![IMG_6820 (1)](https://user-images.githubusercontent.com/113530043/190674321-9122cd72-c050-428d-8afa-cb1b2c8728c0.jpg)
![IMG_6819](https://user-images.githubusercontent.com/113530043/190675197-b080b66d-24bd-4bdb-a3e3-2fbe5d9b6068.jpg)

**Comment by derekhe** [comment]
Please attach the log zip file

**Comment by albihihi** [comment]
What is the log zip file you mean?

**Comment by derekhe** [comment]
Please go here: 
![image](https://user-images.githubusercontent.com/1734077/191024834-61dde86b-b80f-400d-82f0-6323e8200676.png)

**Comment by albihihi** [comment]
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9604949/log.zip)

**Comment by derekhe** [comment]
I see the problem is the access token maybe invalid after a long time.
In current solution, maybe you had to capture a new token to before "start flying"

**Comment by albihihi** [comment]
For the Apple map need new token? from where i get token?

**Comment by albihihi** [comment]
I have license enabled and can not log with Apple Map!

**Comment by albihihi** [comment]
Thank you for the ubdate  6.1,7 , Apple map working fine

**Comment by derekhe** [comment]
Good
