### ISSUE TITLE
host file. 

### ISSUE THREAD

**Issue by jmp44** [derekhe/msfs2020-map-enhancement#249]
I used rshosts_20 by mistake and  restore my file host and now i can't open msfs20-map-enhancement. I have an error : hosts is denied . 
I Can t do a new ( I try) . can you help me . WINDOWS 11 msfs2020  (store)

![Capture d’écran 2022-09-17 192154](https://user-images.githubusercontent.com/113789388/190869135-97299558-fd62-4fc0-86a8-428e86fc0780.png)

Système  64 bits, processor x64
Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz

**Comment by derekhe** [comment]
You can use your notepad with administrator and create a new hosts file there. This is a common issue, please google :)

**Comment by jmp44** [comment]
> You can use your notepad with administrator and create a new hosts file there. This is a common issue, please google :)



> You can use your notepad with administrator and create a new hosts file there. This is a common issue, please google :)



> You can use your notepad with administrator and create a new hosts file there. This is a common issue, please google :)

I found host file , was hidden by microsoft . this this i have : 

# Fichier Hosts créé par RstHosts

127.0.0.1       localhost
::1             localhost

but map_enhancement don t work ( it works very well  before my mistake) have to write some thing more in this file ?
ty for your answer

**Comment by jmp44** [comment]
I found host file , was hidden by microsoft . this this i have :

Fichier Hosts créé par RstHosts

127.0.0.1 localhost
::1 localhost

but map_enhancement don t work ( it works very well before my mistake) have to write some thing more in this file ?
ty for your answer

 

Envoyé: dimanche 18 septembre 2022 à 04:29

I found host file , was hidden by microsoft . this this i have :

Fichier Hosts créé par RstHosts

127.0.0.1 localhost
::1 localhost

but map_enhancement don t work ( it works very well before my mistake) have to write some thing more in this file ?
ty for your answer
De: "hesicong" ***@***.***>
À: "derekhe/msfs2020-map-enhancement" ***@***.***>
Cc: "jmp44" ***@***.***>, "Author" ***@***.***>
Objet: Re: [derekhe/msfs2020-map-enhancement] host file. (Issue #249)


 

You can use your notepad with administrator and create a new hosts file there. This is a common issue, please google :)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

**Comment by jmp44** [comment]
I try ALL nothing HOSTs clean now but not modified by appli???
