### ISSUE TITLE
Request: Make more  batch file friendly

### ISSUE THREAD

**Issue by jeffdamp-wave** [derekhe/msfs2020-map-enhancement#25]
version: 3.0.5
1. Remove the spaces in the name.
2. Launching the App from a cmd or batch file causes the cmd window get redirected as a console out for the app.  This seems very odd because just clicking on the app doesn't do this.  Spewing prints to the console can impact performance.  Please allow for launching the app without it taking over the cmd window.  This sort of spew should only be for debugging purposes and should not be displayed by default.

**Comment by derekhe** [comment]
Hi, since majority of users lunch the app directly without using cmd window, so I will set this request as low priority and will look at it in future.
This app is electron based, if you can find out why solution, please give me a pull request.

**Comment by derekhe** [comment]
I will close this now and will open in future when implement
