### ISSUE TITLE
cannot get hosts file to accept

### ISSUE THREAD

**Issue by biggles58** [derekhe/msfs2020-map-enhancement#250]
**Describe the bug** When starting the map enhancement I keep getting the error - Patch hosts file failed - Access to the path C:\Windows\system32\drivers\etc\hosts is denied. I have tried making a new hosts file but still having no luck. I have tried all the other suggestions.

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**4KP167KG73RQ9J1KYBBZA1BQQWQX5GJS75BRQQ14REJQ306D9QCG
- Device ID 

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9597294/log.zip)

**Additional context**

**Comment by jmp44** [comment]
same as I said before for me with vers 5or 6 same and nothing after a  restors systeme. I try also all FAQ possibility

**Comment by derekhe** [comment]
I list out common issues for hosts: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue
Please try to find out. It can't cover all scenario, you can try to allow the software to modify the hosts file
