### ISSUE TITLE
crash with su10

### ISSUE THREAD

**Issue by whynot102** [derekhe/msfs2020-map-enhancement#254]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
causing crash with su10, even after uninstall, and reinstall of msfs2020

**Comment by derekhe** [comment]
Please disable this mod and retry. It won't be the problem I fly with SU10 10h+ without problem.

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/251
