### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by demonicdave** [derekhe/msfs2020-map-enhancement#258]
I have been trying unsuccessfully to get this mod to run, I do not run any aftermarket Virus software, I have added exceptions, i have ran as administrator, but  I still can't get it to work.

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam  store
![Screenshot (47)](https://user-images.githubusercontent.com/71354630/193172158-e17fa9ef-8932-4894-bc23-eedfa181ad32.png)

 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version  6.1.7.0

**Device ID**
- Device ID WPQF5VKN342PYPV7TFDA2T74A22BRZGZZ98YPJRDC0T5H0E879KG

**Log**
- Please attach the log zip file 
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9680024/log.zip)

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by demonicdave** [comment]
> https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

I have tried all of that before i posted, not really sure what the issue is, I have disabled all of my virus software and my firewall, I am really at a loss here, I have used previous versions without issue

**Comment by derekhe** [comment]
I can't solve the hosts access issue, it mostly caused by antivirus or some host protected application.

**Comment by demonicdave** [comment]
> I can't solve the hosts access issue, it mostly caused by antivirus or some host protected application.

I believe I have solved the issue, maybe you can save this for future reference, I had an older mod of the map enhancement on my system also, since I couldn't get this one working, I uninstalled that and it seems to be working now
