### ISSUE TITLE
Image Server Failed

### ISSUE THREAD

**Issue by Mr-Ango** [derekhe/msfs2020-map-enhancement#269]
I have used the MOD happily for at least a year. Now on startup, I get "Image server: checking" and after a few seconds "Image server: failed"   
(Nginx server goes to "good")

**MSFS version:**
 - Steam
 - MSFS2020 Version  1.27.21.0 

**Mod version:**
- 5.1.0

**Device ID**
- What does this mean? PC not xbox?

**Log**
- No zip file in the MSFS2020-map-enhancement folder. None shown up in a full PC search. (I did click the COLLECT LOGS button)

Please provide me screenshots for the mod and msfs2020 if possible
![failed](https://user-images.githubusercontent.com/105569288/194009177-22f1d57a-3f60-4785-b24e-e0e9c00acafd.jpg)
[I tried to paste a screenshot jpg here and that's what happened. Could it be related to my problem?]

**Additional context**
If I bypass the MOD and use the plain MSFS it all runs fine.
I did try starting the MOD with different settings - ArcSis, Google, new Bing - but always "Image server: failed"
Other Steam games run OK
Not sure, but I think the problem happened before sim update 10

Ian (marangog@gmail.com)

**Comment by derekhe** [comment]
V5 is not supported any more. Please upgrade to newest version.
