### ISSUE TITLE
Connect the Google Maps API through Cloudflare Worker, a reverse proxy way.

### ISSUE THREAD

**Issue by h0wardch3ng** [derekhe/msfs2020-map-enhancement#27]
I find a way to access Google Map satellite tile picture file, avoid use local proxy.

Use Cloudflare Works service as reverse proxy

# 0. Apply a [Cloudflare account](https://dash.cloudflare.com/sign-up)

# 1. Add new Workers script

## 1.1 Go to Workers page

![navi](https://user-images.githubusercontent.com/2175497/148780183-95939e61-4327-49f2-accc-6745708280e9.jpg)

## 1.2 Click 'Create a Service'

![neww](https://user-images.githubusercontent.com/2175497/148780322-1cd5253e-5e8c-480c-b321-2bd3f7173158.jpg)

## 1.3 Taking names and selecting options

![w1](https://user-images.githubusercontent.com/2175497/148779983-64676d81-148c-4780-b9de-e89c375c90ae.jpg)

# 2. Edit worker rules

![w3](https://user-images.githubusercontent.com/2175497/148780906-d3eab7e2-3d22-48d5-994d-0d8e7d4ed805.jpg)

```
addEventListener(
	"fetch",event => {
		let url=new URL(event.request.url);
		url.hostname="khm.google.com";
		let request=new Request(url,event.request);
		event. respondWith(
			fetch(request)
		)
	}
)
```

Copy and Paste, and click 'Save and Deploy'

# 3. Test connection

Google origin tiles URL:

https://khm.google.com/kh/v=908?x=1674&y=895&z=11

Workers tiles URL:

https://googlemap.level5.workers.dev/kh/v=908?x=1674&y=895&z=11

------

# 4. Use your domain (*OPTIONAL*)

![dns](https://user-images.githubusercontent.com/2175497/148782726-1b3150c0-51e4-484b-9db0-0824095a6aa3.jpg)
![dns2](https://user-images.githubusercontent.com/2175497/148782734-09194919-f365-4e65-a6c4-61c0b240ea56.jpg)
![dns3](https://user-images.githubusercontent.com/2175497/148782736-97a76131-d557-4baa-b85f-7b9d46bff898.jpg)

https://gmap.via.moe/kh/v=908?x=1674&y=895&z=11

--------

- https://github.com/derekhe/msfs2020-google-map/issues/13

**Comment by derekhe** [comment]
Good work and I will close it for other's reference.
