### ISSUE TITLE
SQLite Error 26: "file is not in database" 

### ISSUE THREAD

**Issue by Brada2150** [derekhe/msfs2020-map-enhancement#270]
**Describe the bug**

The bug happens every time you press the "Start" button in the app

Please describe the bug in detail to help me understand the scenario

After updating to the latest version 6.1.8.0. and trying to start the app, this happens. Previous version was working fine, the installer/update .exe was downloaded via the app from Flightsim.to

Nothing else changed, FS2020 was previously updated to the latest version with SU11.

**MSFS version:**
 - msstore 
 - MSFS2020 Version 1.27.21.0

**Mod version:**
- 6.1.8.0

**Device ID**
- BHPC3RFB884PPMPDCKA7FSTXS8BXCFYRMNS8SBR28QKHQCBYSDH0
- 
**Log**
- 
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9717821/log.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/113528301/194125828-3e404739-8dc7-45e3-86e9-b11842b5a8f9.png)

**Comment by derekhe** [comment]
Please upgrade to 6.1.9
