### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Rattso77** [derekhe/msfs2020-map-enhancement#272]
G'day - I purchased a licence $30 from you - got the email & tried to get it into the application but all I get is the following when I am prompted to open the licence file - 
Error
License is invalid or expired
error: Device  ID not match your machine

please help me sort this out

see ya

Jon Brunker

4SF09F23ZDZ5ACT5D1TARSP9ZJ4BZR1TJTJTPYVAH125KVFZD97G
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9732915/log.zip)

**Comment by derekhe** [comment]
I resent you the license with correct device id. Last time the device id is incorrect: 

Incorrect:
4SF09F23ZDZ5ACT5D1TARSP9ZJ4BZR1TJTJPYVAH125KVFD97G

Correct:
4SF09F23ZDZ5ACT5D1TARSP9ZJ4BZR1TJTJTPYVAH125KVFZD97G
