### ISSUE TITLE
I was using this mod, but when I stop to use it when i load the MSFS alone, the maps are no accurate and appears some stranges tiles. 

### ISSUE THREAD

**Issue by alquivir** [derekhe/msfs2020-map-enhancement#273]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.27.21

**Mod version:**
- Mod version 6.1.9.

**Device ID**
- Device ID
- W8EC4BQKNM9E74R6E7NF8FMKY7P0WV8PW73NMG817X3KBCFH1990

**Log**
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9749570/log.zip)

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible
LEPA
![Captura de pantalla 2022-10-11 002807](https://user-images.githubusercontent.com/115508927/194962098-3eaa4673-33d2-4069-a014-2bf58a155711.jpg)
![Captura de pantalla 2022-10-11 002745](https://user-images.githubusercontent.com/115508927/194962099-c416bf9f-fa85-44cf-bc20-36b22e79bbeb.jpg)
LERS

![Captura de pantalla 2022-10-11 003959](https://user-images.githubusercontent.com/115508927/194962750-8c142cd4-37f5-42e3-9dab-907b9ac5f503.jpg)

**Additional context**

I was using this mod, but when I stop to use it when i load the MSFS alone, the maps are no accurate and appears some starnges tiles.

**Comment by derekhe** [comment]
This is SU10 bug, please wait for msfs to fix it.
