### ISSUE TITLE
Map Enhancement update

### ISSUE THREAD

**Issue by PitNi** [derekhe/msfs2020-map-enhancement#277]
habe beim Map Enhancement  update einen falschen Installationpfad eingegeben..
Habe M.E. deinstalliert. Seitdem kann der Sim  nur noch Offline betrieben werden. Laden eines Fluges im Onlinemodus bricht nach dreiviertel Ladevorgang ab und der sim friert ein.

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ
