### ISSUE TITLE
麻烦请教一下代理速度过慢问题

### ISSUE THREAD

**Issue by Fern43nd0** [derekhe/msfs2020-map-enhancement#279]
**Describe the bug**
你好，请问一下代理速度过慢是怎么回事？
已经提前测试过节点速度，在youtube、fast.com和speedtest.net测试网速都能达到100M满速，但使用软件的socks5或者http代理功能并进入游戏后读取google map的速度基本在500Kb/s左右，最高也就1M/s，请问下这个情况应该如何改善？因为这个速度太慢，会影响游戏内正常显示。尝试过更换服务器，更换2号google map服务器直接就没速度了，我用的代理客户端是v2rayN，游戏是steam版最新，软件内设置我只开了High LOD，别的选项都是默认状态。游戏内rolling cache已经清除并关闭，软件的cache功能已开启并且缓存文件放在ssd里的。如果大佬看到，希望有时间能帮我解答下，感谢。

Please describe the bug in detail to help me understand the scenario

**MSFS version:Steam
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:6.2.1
- Mod version

**Comment by derekhe** [comment]
这个速度可能和代理服务器有一定的关系。我在软件上已经最大可能的优化了连接，造成这种问题可能是keep-alive连接被对代理服务器给关闭了等。对这个我是没有什么办法的，你可以试试别的代理。
