### ISSUE TITLE
Mod not started properly

### ISSUE THREAD

**Issue by saveriomangione** [derekhe/msfs2020-map-enhancement#285]
**Describe the bug**

Idownloaded the new version 6.2.2.0 but patch hosts file failed. I never experienced any issues with previous versions

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version 
 - 
**Mod version:**
- 6.2.2.0

**Device ID**
- B67V6F9V1VFBMJBC12VWEV05HME5R1FN52JAJQ1A4GYGMKMGW6NG

**Log**
- Please attach the log zip file 

**Screenshots**
![Immagine 2022-11-05 094854](https://user-images.githubusercontent.com/117510024/200111800-f2b08095-85d8-45c9-ac73-3724fe54b2d6.jpg)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

[nlog-2022-11-05.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9943415/nlog-2022-11-05.log)
[nlog-internal.log](https://github.com/derekhe/msfs2020-map-enhancement/files/9943416/nlog-internal.log)

**Comment by derekhe** [comment]
[WooCommerce](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue)
