### ISSUE TITLE
latest version wont install

### ISSUE THREAD

**Issue by Mr-Ango** [derekhe/msfs2020-map-enhancement#286]
Installation stopped immediately, with "Cannot write autofac.dll".  I moved the existing autofac.dll and retried to install. Autofac.dll was successfully written, but then
 "Error opening the file for writing.  D:\MSFS2020 Map Enhancement\Core.dll"
I am running the installation file as administrator with McAfee Real-time scanning off.
 On a retry, I ignored the core.dll error and found that each new file gave the same "error opening the file..."

* - steam
 - MSFS2020 Version 1.27.21.0

**Mod version:**
- Mod version 6.2.1.0.(Pro)

**Device ID**
- Device ID K28QWK28YGKGQXBCJEB1E6F89YEJZRGTJGQA7YQ9Y1W747WMB7S0

**Log**
-[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9944832/log.zip)

**Screenshots**

![map error](https://user-images.githubusercontent.com/105569288/200144500-7adfb7ce-cd3e-4a66-8a86-33649c426bd0.jpg)

**Comment by derekhe** [comment]
try restart



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 6, 2022 06:59 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [derekhe/msfs2020-map-enhancement] latest version wont install (Issue #286)




 
Installation stopped immediately, with "Cannot write autofac.dll".  I moved the existing autofac.dll and retried to install. Autofac.dll was successfully written, but then
 "Error opening the file for writing.  D:\MSFS2020 Map Enhancement\Core.dll"
 I am running the installation file as administrator with McAfee Real-time scanning off.
 On a retry, I ignored the core.dll error and found that each new file gave the same "error opening the file..."
  
  
steam 
 
  
MSFS2020 Version 1.27.21.0 
 
Mod version:
  
Mod version 6.2.1.0.(Pro) 
 
Device ID
  
Device ID K28QWK28YGKGQXBCJEB1E6F89YEJZRGTJGQA7YQ9Y1W747WMB7S0 
 
Log
 -log.zip
 
Screenshots

**Comment by Mr-Ango** [comment]
Yes, that fixed it. Thank you.
