### ISSUE TITLE
Got invoice for $150 from Mapbox for data usage!!!!

### ISSUE THREAD

**Issue by CajunRon** [derekhe/msfs2020-map-enhancement#287]
Just wanted to let you know that I got an invoice from Mapbox for $150 because I exceeded the "free" data usage.  Luckily they didn't have any way to automatically charge me.  I am NOT a high volume user of your product so I don't know what is going on.   Perhaps this should be looked into. Copy of email is attached

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

![Mapbox invoice](https://user-images.githubusercontent.com/93894047/200346174-f2b6b919-c2e1-4316-b915-e84f69cb7834.JPG)

**Comment by derekhe** [comment]
Please notice the free tiles. It is very easy to reach it if you turn on highlod and fly for several hours.
![image](https://user-images.githubusercontent.com/1734077/200349794-8dfec458-97e3-4f2f-a93e-6376619ea2fe.png)
