### ISSUE TITLE
Cant switch to google maps (or any maps)

### ISSUE THREAD

**Issue by grimsan55** [derekhe/msfs2020-map-enhancement#288]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Mod version:**
- 6.2.2

**Device ID**
- AATTQBVH9RMWJK33N1EVX7TQWXJ6MH0Y00N51EJ4SVN2515Z6HY0

**Log**
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9972129/log.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/8499989/200860660-914d4882-4a92-48f4-97e3-a9d2fa1d16ae.png)

First time i try to run this mod, more people have been complaining about the same issue on flightsim.to. Trying to use google as maps. Tried both #1 & #2
Program is running as admin, restarted the program multiple times

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#443-port-is-occupied

**Comment by grimsan55** [comment]
yeah sorry about that, missed that i still had an active website running in my IIS. Thx! :)
