### ISSUE TITLE
MSFS Map Enhancement

### ISSUE THREAD

**Issue by PitNi** [derekhe/msfs2020-map-enhancement#289]
nach Installation des letzten updates habe ich folgendes Problem:
Das Laden eines Fluges friert bei ca. 75% Fortschritt des Ladebalkens ein. Im Task Manager wird "keine Rückmeldung" angezeigt.
Der Sim muss dann über den Task Manager abgebrochen werden.
Im Offlinemodus funktioniert der Sim. Wenn ich im Offlinemodus starte und währen des Fluges online gehe, funktioniert es ca. 1 Minute und friert dann ein.
Ich habe Map Enhancement deinstalliert, in der Host-Datei die Einträge gelöscht und auch bei den Zertifikaten ein Zertifikat, das den Namen eines der beiden Host Datei Einträge hatte , gelöscht. Leider wurde das Problem damit  nicht gelöst.
Können Sie mir helfen? Gibt es im Microsoft Betriebssystem noch Map Enhancement Einträge, die gelöscht werden müssen?

**Comment by derekhe** [comment]
Please provide your mod version, and attach log files

**Comment by PitNi** [comment]
die History:
am 20.10.2022 habe ich den Sim ohne map enhancement gestartet, einen Flug gemacht und den Sim wieder geschlossen.
Dann habe ich Map Enhancement gestartet und ein update wurde angezeigt. Ich habe das update ausgeführt, aber leider unbemerkt über einen falschen Installationspfad. Ich hatte Map Enhancement auf disc F installiert, das update wurde aber auf disc C ausgeführt. Ich habe den Sim dann mit aktiviertem Map Enhancement gestartet. Leider fing da das Problem an, daß der Sim keine Internetverbindung mehr aufbaute. Kurz vor Beenden des Ladevorgangs eines Fluges friert der blaue Ladebalken ein.
MSFS kann nur noch offline ausgeführt werden.
Leider gibt es keine files die ich anfügen könnte. Die Versionsnummer des updates weiß ich nicht mehr, es war die Version mit der chinesischen Map.
