### ISSUE TITLE
Downloading the last version triggers Antivirus quarantine

### ISSUE THREAD

**Issue by JexD** [derekhe/msfs2020-map-enhancement#29]
Hey, trying to download the last version (and it is my first version) but it can't be done due to windows defender not happy with the .exe

**Comment by derekhe** [comment]
It is false positive, some users report, some don't. I have no idea about it.
If you upload the file into "https://www.virustotal.com/" you can check the result.
FlightSim.to also use this tool to check.
This is the report: https://www.virustotal.com/gui/file/40874106a42d78458877508fa995dad57e3ba6f901b622d632d9478243d997d7
