### ISSUE TITLE
Game crashing at start

### ISSUE THREAD

**Issue by ushijinx** [derekhe/msfs2020-map-enhancement#292]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - steam
 - MSFS2020 40th annivedrsary edition new update

**Mod version:**
- 6.2.3.0

**Device ID**
-2RG8JNNNXH29CKQHSTD457FRTF9ANBQ0S8TAC1D6NP39NSWRVWGG

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/9996698/log.zip)

![image](https://user-images.githubusercontent.com/89031462/201511782-4ae14b16-867c-451c-b3b0-365127be87f0.png)
![image](https://user-images.githubusercontent.com/89031462/201511884-3cc6eda0-b2a5-4a65-b5f6-c0ea81ba3f23.png)

**Comment by derekhe** [comment]
https://www.google.com/search?q=nvwgf2umx.dll&rlz=1C1ONGR_enUS1021US1021&oq=nvwg&aqs=chrome.2.69i57j46i175i199i512j0i512l4j0i395i512l3j0i512.3135j1j7&sourceid=chrome&ie=UTF-8

Please try out solutions.
