### ISSUE TITLE
Bug hosts

### ISSUE THREAD

**Issue by mathieu38149** [derekhe/msfs2020-map-enhancement#294]
**Describe the bug**
when i launch mod in admin and no protection he say acces are denied to hosts

**MSFS version:**
 - msstore 
 - MSFS2020 last

**Mod version:**
- last
**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

![image](https://user-images.githubusercontent.com/83405336/202894833-d6f85bf3-3240-4d40-a2fa-9153b36d19ac.png)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue
