### ISSUE TITLE
有没有办法帮助翻译

### ISSUE THREAD

**Issue by leon332157** [derekhe/msfs2020-map-enhancement#295]
有些翻译可以改进一下，希望可以帮助改进。

**Comment by derekhe** [comment]
可以哈，请帮忙提一下。由于新的版本是闭源了所以没有源代码可供参考。可以帮忙截个图说一下。

**Comment by leon332157** [comment]
看到好像7.0换回electron前端了，如果可以开源前端的话可能更简单些。
![image](https://user-images.githubusercontent.com/30728609/205474419-b06ff7ec-3d02-4726-ad9f-ee8dee77f03d.png)
这里有个小bug

![image](https://user-images.githubusercontent.com/30728609/205473981-213f5dab-9e8e-4a53-8046-4e4e4db08c00.png)
这里应该是`Please use for entertainment purposes only` 可以再加一句 `Note: This map server is PRO version only`

![image](https://user-images.githubusercontent.com/30728609/205473998-015e2d63-04d0-4eb2-9b97-760d7f3ab52e.png)

`can be used very quickly. Some users already received bills over $200 from mapbox, so please monitor your usage carefully."
![image](https://user-images.githubusercontent.com/30728609/205474386-af11b8de-811c-4d12-93a7-dbfde7cdcfe9.png)
这里虽然是中国地图，不知道需不需要翻译。

![image](https://user-images.githubusercontent.com/30728609/205474152-2192e7fc-0f69-4edf-b3ac-06a5b79ac199.png)
"The cache speeds up image loading by reusing previously downloaded image tiles. It is recommended to disable the "Rolling Cache" option in MSFS, otherwise you may notice issues if you switch map servers. 

The cache file here is different from the cache file used by MSFS, therefore "Use default location" is recommended. 

其他还有一些小细节不太重要，可以另外再截图。

**Comment by derekhe** [comment]
谢谢哈，借助于ChatGPT我已经把英语给重新整理了一次，应该会更好一些了。
