### ISSUE TITLE
Backend Server error with the latest versions

### ISSUE THREAD

**Issue by rtk1972** [derekhe/msfs2020-map-enhancement#298]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**
[nlog-2022-12-05.log](https://github.com/derekhe/msfs2020-map-enhancement/files/10154409/nlog-2022-12-05.log)
[nlog-internal.log](https://github.com/derekhe/msfs2020-map-enhancement/files/10154411/nlog-internal.log)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Hi I see the backend server started slow when creating cache. You can try refresh the page by CTRL+R several times and see if it works.  
Btw, do you have a slow disk on D:\?

**Comment by rtk1972** [comment]
ah multiple CTRL R did it. Do i have to do this every time ? i am on SSD and M2 SSD so no slow hard drives

**Comment by derekhe** [comment]
I will try to move the init cache stage into another to speed up the
startup time.

**Comment by rtk1972** [comment]
awesome, thanks for your super fast help !
