### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Authentic60** [derekhe/msfs2020-map-enhancement#299]
**Describe the bug**

A screen appear with this text : 

Apply hosts change failed

Can't patch hosts file, please try:

run as administrator right
try to turn off your antivirus and restart your computer.
check if any tools inside your antivirus is protecting your system.
try to add this mod into white list
Error detail: Access to the path 'C:\WINDOWS\system32\drivers\etc\hosts' is denied.

And i can't Start the map installation

**MSFS version:**
 - msstore

**Mod version:**
- 7.0.3

[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/10156913/log.zip)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue
