### ISSUE TITLE
Nginx Server Access Check failed

### ISSUE THREAD

**Issue by sashman2013** [derekhe/msfs2020-map-enhancement#30]
I am trying to boot up google maps for the first time and I am unable to. When flipping the switch, the Nginx server access check failes and I am unable to go any further. Is there something I can do to fix this? I am not getting any error messages and I'm not seeing any error messages, just the orange X next to the Access check.

**Comment by derekhe** [comment]
Can you give me the log files, the file directory is in "Trouble Shooting" tab, you can find it. 2 files.

**Comment by sashman2013** [comment]
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7873117/renderer.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7873118/main.log)

Im not very literate with computers so its probably something real simple. Thanks for the help

**Comment by sashman2013** [comment]
Hello, been a cpl days since I last heard from you. Were you able to figure out what was wrong? Thanks

**Comment by derekhe** [comment]
Sorry for late reply, from the log I can't tell why it fails. I will try to add more logs and please update later and give me the log.

**Comment by sashman2013** [comment]
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7884478/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7884479/renderer.log)

Here are the new logs from version 3.0.7

**Comment by derekhe** [comment]
Where did you install the mod into?

**Comment by sashman2013** [comment]
Again, not computer literate so I have no idea. Where/how can I check that?

**Comment by noels7** [comment]
Installed program in default location.
Nginx Server Access Check and Image Server Access Check never completes check.

[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7901435/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7901436/renderer.log)

**Comment by sashman2013** [comment]
It worked after I uninstalled and installed version 3.0.8. Im all set, thanks for the help!

**Comment by noels7** [comment]
Installed program (3.0.8) in default location Program works sometimes and on other occasions
Nginx Server Access Check and Image Server Access Check never complete check.

Error: Stop server failed, error: Error: EBUSY: resource busy or locked open.
C:\Windows\System32\drivers\etc\hosts

Any advice/assistance would be appreciated.

noels7

[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7908447/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7908448/renderer.log)

**Comment by derekhe** [comment]
Will close this as no response for a long time.
