### ISSUE TITLE
Updated to 7.04 (pro) - now can't connect to any server?

### ISSUE THREAD

**Issue by golfcart222** [derekhe/msfs2020-map-enhancement#301]
Error Message.....
Can't access remote image server
If you are using a proxy to connect to remote server, please make sure the proxy is working.

Was working until this new update.  What gives ?

**Comment by Avance78** [comment]
same error here just after 7.04.

**Comment by derekhe** [comment]
Sorry, my bad, there is my cache configuration is packed wrong in the exe file, so it seeks a nonexisting file.

Please reset the cache once as a workaround.

I will release a new version tomorrow to fix this problem.

**Comment by golfcart222** [comment]
> Sorry, my bad, there is my cache configuration is packed wrong in the exe file, so it seeks a nonexisting file.
> 
> Please reset the cache once as a workaround.
> 
> I will release a new version tomorrow to fix this problem.

That worked - thanks

**Comment by Avance78** [comment]
Thank you for your reactivity !
