### ISSUE TITLE
Backend Server start failed

### ISSUE THREAD

**Issue by Entropy-Xu** [derekhe/msfs2020-map-enhancement#302]
**Describe the bug**

Backend Server start failed

**MSFS version:**
 - msstore 
 - MSFS2020 latest version

**Mod version:**
- 7.0.5

**Device ID**
- 5CBEQCX6XVF0EWYJG9PMHHEBE44Y5W0D4GKNDSDG1VHKH7PVK57G

**Log**
- 
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/10199203/log.zip)

**Screenshots**

![1](https://user-images.githubusercontent.com/53283266/206829716-047d8d0a-42a2-4879-b14c-5f5c7c5ea5bc.png)

**Additional context**

**Comment by derekhe** [comment]
这个大概率是你有什么443端口占用导致没有启动起来。看日志就写了个app started，你可以试试卸载了重装。

**Comment by SkeletoNCY** [comment]
443端口如上图，没有占用。如果只是端口占用我就不会来发issue了。然后经测试6.x.x旧版运行正常，7.0.5出现这个问题
