### ISSUE TITLE
This program will not let me continue without buying a subscription uninstall causing problems

### ISSUE THREAD

**Issue by DutchPJD** [derekhe/msfs2020-map-enhancement#304]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Could you provide more details?

**Comment by DutchPJD** [comment]
Hi
 Yes I  was running map enhancement and this happened
I clicked on anything that was not later and that started the problem of
having to pay so I deleted the program then when I ran Flight sim 2020 on
my pc on the map all the detail was gone . so I reinstalled map enhancement
and found out that it will stay free as long as I click on later
everytime and the map now has all the details so I guess everything will be
ok except I have this annoying message that is always trying to suck  me in
picture attached

Phil


***@***.***>
Kelowna ***@***.***>

***@***.***>

Phil & Ingrid Douziech
#29 1874 Parkview Crescent
Phone:  778-478-1873

Mesa AZ Phone # (480) 822-7845
Kelowna BC V1X 7G6





Please always Use  E-Mail  ***@***.***


Skype use ***@***.***


Contact Me <http://www.squaredance.bc.ca/contact.htm>LinkedIn
<http://www.squaredance.bc.ca/contact.htm>  Chat [image: Google Talk/]
***@***.***
