### ISSUE TITLE
As you can see in the Screenshot, there are lots of colored squares in the scenery, without any error msg on screen, whatsoever Kind of annoying and Sim-Destroying

### ISSUE THREAD

**Issue by ghost** [derekhe/msfs2020-map-enhancement#305]
**Describe the bug**

As you can see in the Screenshot, there are lots of colored squares in the scenery, without any error msg on screen, whatsoever
Kind of annoying and Sim-Destroying

**MSFS version:**
 - MS Store
 - MSFS2020 Version [e.g. 1.29.30.0]

**Mod version:**
- 7.0.6 beta

**Device ID**
- 1KCT8X86CDMAHGHQZ3F3A6KZ8AXX9VYPSHXQFM32NEEW05R027J0

**Log**
- The option to provide a log file is, seemingly, unavailable
- 
**Screenshots**

Impossible to Upload, the max size for screenshot ist ridiculously low, please provide a separate way on how to submit that screenshot

**Additional context**

**Comment by derekhe** [comment]
Can you try resize the image?
