### ISSUE TITLE
MSFS freezes when I click Fly since uninstalling Map Enhancement

### ISSUE THREAD

**Issue by aremgee** [derekhe/msfs2020-map-enhancement#307]
**Describe the bug**
I wasn't able to get the app to work right, so I uninstalled it. I checked the "hosts" file, and the 2 lines that you noted in your FAQ are not there - it is just a set comment lines.

Now, almost every time I try to launch a flight, MSFS freezes when I click on Fly. This happens if I start on a runway or at a gate, or if I load a saved flight. However, I am able to load a Discovery flight.

I have gone so far as doing a complete reinstallation from Steam, with nothing in the Community folder, and it still happens. It happens with or without peripherals.

AT THIS POINT, I CANNOT USE THE FLIGHT SIMULATOR!

Please describe the bug in detail to help me understand the scenario

**MSFS version:** 1.29.30.0
 - msstore or steam - Steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version 7.0.5

**Device ID**
- Device ID

**Log** - I have already deleted your app
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

Please help me! I can't use MSFS anymore.

**Comment by derekhe** [comment]
If you don't have the two lines in your hosts file, then it isn't related to this mod. Please check what else is wrong.

**Comment by aremgee** [comment]
Thank you for the quick reply, and I appreciate your comment.

The problem began immediately after I used your program. Is there anything else from your program that gets modified on my PC beyond the hosts file that I could look for?

I'm very desperate right now.

Best regards,

Robert

Robert M. Golub, MD
Executive Deputy Editor, JAMA
Professor of Medicine and Preventive ***@***.***>

***@***.***>
Northwestern University Feinberg School of Medicine
________________________________
