### ISSUE TITLE
Mod not working since yesterday.

### ISSUE THREAD

**Issue by ideoda** [derekhe/msfs2020-map-enhancement#308]
It stopped working. The program starts but got no images from google. Do i have to buy a license to get it working again? It was working before, so its changed from free to licensed?

**Comment by derekhe** [comment]
The free google map is still the same as before. If you want enhanced images, please use google map pro.

**Comment by ideoda** [comment]
then please help me because the images are not coming down. It shows 1 and no more. 

![16719618166697421228390880082474](https://user-images.githubusercontent.com/47631463/209463490-ec53604c-d5c8-43f0-b169-a33f282fb216.jpg)

**Comment by andremesel** [comment]
The free google maps are not working , in my case is giving proxy error but i dont use any proxy.

Regards
