### ISSUE TITLE
Mapbox (Pro) does not connect

### ISSUE THREAD

**Issue by cortega0221** [derekhe/msfs2020-map-enhancement#309]
**Mapbox (Pro) does not connect I receive and mage server test failed pop-up, all other "PRO" servers connect and work without problems"**

I have the licensed version 7.06 beta (Pro) running on Windows 11 Pro. #

**MSFS Update 11 (latest)**
 - MSSTORE

**Device ID**
- B0ZKY4SCGZY5CZVMR2RYDW1Z0Q6DCT3B2B86RAXA4F4HDTH213Q0

**Log**
- Please attach the log zip file 

**Screenshots**

![Screenshot 2022-12-26 110310](https://user-images.githubusercontent.com/121456460/209577150-abdd2260-58d4-4b21-a652-452d095d3fec.png)
![Screenshot 2022-12-26 110352](https://user-images.githubusercontent.com/121456460/209577161-47b56557-4bc3-4cdd-ab8c-99fdcd938c4f.png)

**Comment by derekhe** [comment]
I found the buildin token is invalid now. Finding a way to fix it.

**Comment by cortega0221** [comment]
Thank you. To be clear; in my opinion this is just a minor bug, I think MSFS2020 Map Enhancer is a great product, and I’m more than happy with it. I’ve been using it for a very long time; I have no doubt you’ll fix it. In addition, this version is in beta, I’m just trying to help, not criticize.Respectfully,CarlosOn Dec 26, 2022, at 6:23 PM, hesicong ***@***.***> wrote:﻿
I found the buildin token is invalid now. Finding a way to fix it.
