### ISSUE TITLE
New map does not appear in MSFS

### ISSUE THREAD

**Issue by patirish2** [derekhe/msfs2020-map-enhancement#310]
[nlog-internal.log](https://github.com/derekhe/msfs2020-map-enhancement/files/10305572/nlog-internal.log)
A950A4M18QAA8S6TENKJJFG7R7FFK7GWH5TBRP5NK14AQ4N3E0D0

I have followed all the suggestions.  I disabled anti-virus and insured that the rolling cache is off. The new maps do not appear in MSFS.
Thanks
Pat Freel

**Comment by patirish2** [comment]
If I turn photogrammetry OFF, the alternate maps appear.

**Comment by derekhe** [comment]
Yes, the photogrammetry data will cover the satelite images.

**Comment by patirish2** [comment]
I suggest you add that to your instructions. No where do you say to turn off photogrammetry 


Sent from AT&T Yahoo Mail for iPhone


On Tuesday, December 27, 2022, 00:41, hesicong ***@***.***> wrote:




Yes, the photogrammetry data will cover the satelite images.

**Comment by patirish2** [comment]
Your screen shot of the video configuration panel shows photogrammetry turned on
Thanks for a great program
