### ISSUE TITLE
MS Server override is not working 

### ISSUE THREAD

**Issue by Langestange1988** [derekhe/msfs2020-map-enhancement#312]
Hello Team
trying to get the new Map Enhancement 7.0.7 working but failing with the follwing error

Image server test failed
MS server override is not working
Please try:
Disable any global proxies
Disable any game accelerator

The following things have been done so far

- Checked if a global proxy is set on the system 
- Tried to find a game accelerator - a more specific information would be highly apprechiated
- Disabled windows defender completely 
- Tried with 'Google Maps Server' (not pro), 'Bing Maps (latest)'

Host file will be edited during startup and cleared after closing the application (working as intended)

DeviceID: E4VZDJW0VPE8YV2BJB3ZD01DYZ3NNBDJJB468ZFKNFW3VQ5GG8WG

If you can please assist with this matter, it would be greatly appreciated.

Regards

**Comment by fish125658** [comment]
Same issuse 
DeviceID: E67TJGYGB6BT9EB98ZXSMQSNFRYA2NF77EW53B2DC37RZVMTM83G

**Comment by fish125658** [comment]
I am sure the problem is caused by the hosts file, my hosts file is no content, but Map Enhancement cannot modify my hosts, when I deleted the hosts and created new one, Map Enhancement is back to normal.

**Comment by derekhe** [comment]
Yes follow the FAQ, most issues are mentioned there.
