### ISSUE TITLE
License rendered invalid due to hardware change

### ISSUE THREAD

**Issue by AAronNA888** [derekhe/msfs2020-map-enhancement#313]
Hello, hope you have a nice day. I changed my PCs hardware resently an this rendered my license invalid. Can you help me with that?

My old device ID: 7AP72F3VEA96RMZM439F00ZW8GMHGB72WN12BR4H5FHSJ5K9NN80

My new device ID: Z52HYPY4SBHY6QS1JT58W0GTJ5ZJW4434HEQZR1H0ZKGR2F0YDFG

[license-Alexander Dolgin-7AP72F3VEA96RMZM439F00ZW8GMHGB72WN12BR4H5FHSJ5K9NN80.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/10360386/license-Alexander.Dolgin-7AP72F3VEA96RMZM439F00ZW8GMHGB72WN12BR4H5FHSJ5K9NN80.zip)

**Comment by derekhe** [comment]
Already give you a new license

**Comment by AAronNA888** [comment]
Thanks))) Happy New Year!
