### ISSUE TITLE
 changed my PCs hardware recently

### ISSUE THREAD

**Issue by mnpostema32** [derekhe/msfs2020-map-enhancement#316]
Hello, 

How are you? 

I changed my PCs hardware recently an this rendered my license invalid. Can you help me with that?

My old device ID: KG0TQPXFHGCYMQTG0GQ0NK9M6T8R926H6YA57K0GHJQNXJS74N4G

New ID: 1C563GQY5D77XH750G11G0D7R8ZST1MH8GSQ1J6YVXH1XGNZ3HP0

Can you please help me?

My email is:

mpostema322@hotmail.com

Greetings

Matthias from FSVisions.nl

**Comment by mnpostema32** [comment]
Hi, did you get my message?

Greetings

matthias

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/License#change-device-id

**Comment by mnpostema32** [comment]
Hi, 

i did already two times, no reply or new license at all :-(
