### ISSUE TITLE
有时候游戏闪退 

### ISSUE THREAD

**Issue by sunset1234321** [derekhe/msfs2020-map-enhancement#317]
有时候游戏闪退 
应该怎么查看log反馈给你
用的google map server(pro)

**Comment by derekhe** [comment]
目前所有的有关游戏闪退的问题都是游戏本身或者各类插件引起的，没有一起是由于这个插件引起的。你可以试试清理下游戏内缓存和mod中的缓存。如果不能解决请关闭第三方插件。
