### ISSUE TITLE
[Feature] Same cache for both Google Maps Servers (Pro)

### ISSUE THREAD

**Issue by buehner** [derekhe/msfs2020-map-enhancement#320]
#### Motivation

Just downloaded v7.0.8 (Pro) and realized that there are two Google Maps Server (Pro) now. As i already created 70 GB of cache in v7.0.7., i'd like to reuse this cache in future (as google seems to block requests when a certain threshold of requests is reached by an IP address).

Can you confirm that i have to select "Google Maps Server 2 (Pro)" to re-use my existing cache from v7.0.7? It seems that a separate cache is build for "Google Maps Server 1 (Pro)".

#### Detailed design

I assume that these two servers are mirrors!? And then it would make sense to use the same cache for those two servers? Is it possible to implement this?

**Comment by derekhe** [comment]
Good idea.
Yes they are mirrors

**Comment by derekhe** [comment]
Please try 7.0.9 which already implement this.
