### ISSUE TITLE
Google Maps Pro Server1/2 Still not working

### ISSUE THREAD

**Issue by Blackearth160** [derekhe/msfs2020-map-enhancement#321]
DeviceID: 9S10FQRZ7DQ40W0F1VT8SB5AEMVSY79RK7ER5P36RWVN9J5EK6JG

Still having the issue that it won't work living in belgium i don't think i need an proxy the apple maps does work. 

when i'm trying  the china server it says it works but i don't know if it really will work

**Comment by derekhe** [comment]
Please try visit: maps.google.com and turn on the satellite view.

**Comment by derekhe** [comment]
Please try 7.0.9 which add load balancer

**Comment by GrandPoobahB** [comment]
I'm seeing this this morning with both Google Maps 1 pro and Google Maps, but not Google Maps 2 pro. With 7.0.9. Did not have problems last night with 7.0.8 and Google Maps Pro. I expect my IP + API key combo is getting throttled?

**Comment by GrandPoobahB** [comment]
BTW when I attempt to turny on satellite view in maps.google.com I see flashing grids but no satellite images, which makes me really suspect my IP address has been throttled.

**Comment by BlodhemnUK** [comment]
I am same as above poster, no images with Google maps.com, just the flashing grids, and also get following error message when I select google maps in map enhancement - 

Can't access remote image server
If you are using a proxy to connect to remote server, please make sure the proxy is working.

**Comment by Blackearth160** [comment]
after the 7.09 still same tryed to put the maps.google.com on satalite restarted the map enhancement. same issue. when i'm starting the apple maps or the china server it will start the server.. but i don't know if the game will load in the images that way.. earlyer when this mod was free i did use the google maps servers but some images where little bit corrupted by purple pixels in the photo images.. 
![screenshot 1](https://user-images.githubusercontent.com/123269864/215339973-0c5e391b-a194-4a33-aef1-d839fd3c4cc6.PNG)
![screenshot 2](https://user-images.githubusercontent.com/123269864/215339981-400b60db-4cc7-43e5-84f6-65e6c84dc8d2.PNG)
![screenshot 3](https://user-images.githubusercontent.com/123269864/215339982-688f97d2-98e9-4f13-86c8-5696a9798b78.PNG)

**Comment by GrandPoobahB** [comment]
This morning I was able to connect to both "Google Maps Server 1" and "Google Maps Server" which strongly suggests that this is some sort of quota throttling being imposed by Google.
