### ISSUE TITLE
Update fails with message "MSFS2020 Map Enhancement Cannot be Closed"

### ISSUE THREAD

**Issue by maksim-radziuk** [derekhe/msfs2020-map-enhancement#322]
**Describe the bug**

Every time when trying to update the application to the new version I get the message MSFS2020 Map Enhancement Cannot be Closed (screenshot below). Running installer from different location does not help. Running installer right after PC restart does not help. The installer is run with admin rights. The only way to update is complete uninstall of the application

**MSFS version:**
 - msstore

**Mod version:**
- 7.0.7 Pro 

**Device ID**

- M2ZGCC90PME8XHNKSKHMEXW1882NSE9K8HS2VM4KFK00G1Y8MWH0

**Screenshots**

![Screenshot 2023-01-30 211039](https://user-images.githubusercontent.com/53411986/215559455-1e093387-453e-41bd-ac19-8cbb798c342a.png)
![Screenshot 2023-01-30 211242](https://user-images.githubusercontent.com/53411986/215560032-546e3f11-5c4d-4028-90d5-1580f9b8a104.png)

**Comment by derekhe** [comment]
I don't know why it happen and 1 or 2 cases reported this issue. I will close and will keep monitor on it.
