### ISSUE TITLE
Apply Hosts Change Failed

### ISSUE THREAD

**Issue by dazvid70** [derekhe/msfs2020-map-enhancement#323]
I am on 7.0.9 and this was working fine until this morning when i get the above error.

I have tried adding it to the firewall rule and deleting the host file and using a back up host file with no success.

Turned off anti virus as well.

Can you help?

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#host-related-issue

**Comment by dazvid70** [comment]
Thank you I’ll give this a go tonight

**Comment by dazvid70** [comment]
All sorted thank you
