### ISSUE TITLE
软件开了，进游戏不读取，游戏内地图光秃秃的

### ISSUE THREAD

**Issue by woshitangtaizong** [derekhe/msfs2020-map-enhancement#327]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Add any other context abo
![20230213_043231](https://user-images.githubusercontent.com/125150581/218335667-e1c87698-bb88-499e-9d00-c27fcc2c2719.jpg)
ut the problem here.

![20230213_043231](https://user-images.githubusercontent.com/125150581/218335656-cabc5acf-f8b0-48da-a3f4-5e3804d49607.jpg)

**Comment by derekhe** [comment]
请参考中文说明书内的方法排查
