### ISSUE TITLE
Tiles loading while flying

### ISSUE THREAD

**Issue by rk85097** [derekhe/msfs2020-map-enhancement#329]
**Describe the bug**

Since ever I upgraded to the paid version, no matter what settings I choose, I see the tiles load up as I fly, this basically kills the experience and is not playable. Keep in mind that I have 1GB internet speed and a high-end PC. Please advise.

**MSFS version:**
 - Steam version
 - Latest

**Mod version:**
- 7.0 (Tried beta and nonbeta)

**Device ID**
- N4X6C2WBBHHKEVK79FMDTPSZXX4WZQQP50MTPSWMHSGV0Q3BNZ00

**Log**
- Where this can be found?

**Screenshots**
[VIDEO](https://mega.nz/file/dNtHEYbL#vqeUz66XSKHqYnf7OCbifqoNQf7UBUE_vR9A8xIil90)

**Additional context**
I used the old version up to not long ago - it was working perfectly fine since I got it (more than 8 months now), only after upgrading and paying a yearly sub, I started to get this behavior, which makes a really bad experience.

**Comment by derekhe** [comment]
Which may are you using? And where are you flying?

You can try to enable the HighLOD feature in the mod and also use higher terrain level of detail (more than 300) in the game.

**Comment by rk85097** [comment]
- I have tried google pro 1 & 2.
- I have tried with HighLOD and without, same results

Can you please provide me with a link to the installer of the old versions?

**Comment by derekhe** [comment]
The google maps are upgrading so It may have some issue in some places. Could you tell me where you saw these tiles so that I can have a check.
