### ISSUE TITLE
Unable to update host file

### ISSUE THREAD

**Issue by chjohans** [derekhe/msfs2020-map-enhancement#33]
I'm new to this, and just installed v 3.0.6 from flightsim.to. When I tried to "Inject Google Map" I get an error message like in the attachment.

I know the reason, it's because my host file is set to read-only. It's a common thing to do to avoid the host file being "hijacked", and some security tools will both suggest and actually set the host file to read-only.

Since this tool has to be run as admin I suggest that you check the file attributes on the host file before trying to open it for writing, and if it's set to "read-only" then remove that flag, but please *set it back* to read-only as soon as you close the file for writing, to respect the owner's settings. This should be a "less than a minute" fix so I see no reason not to do this. :)

![snap002919](https://user-images.githubusercontent.com/24390228/149630779-701a2420-0074-4d59-bdf6-c4facdae5422.png)

**Comment by derekhe** [comment]
I can't do much for this because some antivirus prevent it. For a normal system without hosts locking, there is no issue. So for these kind of people, they need to add this software as whitelist. 
I will close this as I plan not touch user's hosts file if it is protected.
