### ISSUE TITLE
maps loading in the app but getting offline map in game

### ISSUE THREAD

**Issue by Beeo32** [derekhe/msfs2020-map-enhancement#333]
when i start the app it works fine but in msfs the map is just like offline mode and the map enhancement mod still takes data 
edit: it did work before but now idk why is it broken
here its downloading in the app normally ![Screenshot (534)](https://user-images.githubusercontent.com/85417119/221699214-88c16579-cd11-4a41-a602-703d951a7071.png)

and here is how it looks in game ![Screenshot (535)](https://user-images.githubusercontent.com/85417119/221701783-4c4f41fa-2543-4d5f-a6a8-d99b3f37a1f6.png)

**Comment by Beeo32** [comment]
also DeviceID: SM49BEWP9FK46FJPXA1SJK2WPR0N8STPVCYQ8Y83KFAT1V826H2G

**Comment by maszat** [comment]
I think it started with SU12 beta 2

**Comment by tmmtaha75** [comment]
Same here with the paid version of this software on SU12 Beta

**Comment by derekhe** [comment]
I fixed this issue, please download and install latest https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.0
