### ISSUE TITLE
Not working with msfs beta since update

### ISSUE THREAD

**Issue by mikluhomaklay** [derekhe/msfs2020-map-enhancement#334]
**Describe the bug**

The tool is not loading images anymore since latest update from 23. february when sim update 12 beta build is used (1.31.19.0). Still working with stable build (1.30.12.0) though. All image providers. 

**MSFS version:**
1.31.19.0
steam

**Mod version:**
7.0.11 beta

**Device ID**
17DQHVMQSN6WYX7V645WJBXTXVV7CCT6XERSB3WJXJBRW1T4M5V0

**Additional context**
It was working with the sim update 12 beta before the latest msfs update. 
This behavior is consistent. Switching to stable makes it work again. switching to beta no images are downloaded. In the app the image counter doesn't increase when scrolling and zooming over the map. 
All image providers are affected, so I assume they might have changed something with the request.

**Comment by jcuellars** [comment]
Same here.

**Comment by guitartom47** [comment]
Confirmed here as well.

**Comment by AviatorETSI** [comment]
same here

**Comment by derekhe** [comment]
I fixed this issue, please download and install latest https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.0

**Comment by mikluhomaklay** [comment]
Derekhe would you mind sharing technical details what exactly they have changed so that it stopped to app?

**Comment by derekhe** [comment]
Sorry I can't. I want keep this in low profile to prevent this mod being blocked again.
