### ISSUE TITLE
Cant load any server except apple maps

### ISSUE THREAD

**Issue by Topher420247** [derekhe/msfs2020-map-enhancement#335]
I joined the beta and then reverted back to current version. Map enhancement mod will only connect to the apple maps server and it doesnt actually load any images once in the game its like it loads the base of the world but not the map layers on top. ive uninstalled and deleted the appdata folder and reinstalled and it still does the same thing. any help is greatly appreciated i have loved using the apple map server so far in my gliding flights it really makes a huge difference

**Comment by derekhe** [comment]
Confirmed. The beta seems changed something, I'm look at why.

**Comment by Topher420247** [comment]
If you need anything from me just let me know I'm sure I can figure out how to get it for ya

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 28, 2023 at 5:20 AM, ***@***.***> wrote:   


Confirmed. The beta seems changed something, I'm look at why.

**Comment by derekhe** [comment]
I fixed this issue, please download and install latest https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.0
