### ISSUE TITLE
GOOGLE MAPS NOT LOADING

### ISSUE THREAD

**Issue by Saptasindhu07** [derekhe/msfs2020-map-enhancement#336]
![Screenshot_20230301_073759](https://user-images.githubusercontent.com/126634604/222026242-e6fc269b-04ed-4134-850f-2ec477603745.png)

GOOGLE MAPS NOT WORKING SCREENSHOT ABOVE

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore 
 - MSFS2020 Version [e.g. 22]
 Latest

**Mod version:**
- 7.0.12

**Device ID**
- ZM37F5W90MTBBHMB2B93Y1ZVXVD7MA2PEPF891C0TSGZ6YYC8YW0

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I fixed this issue, please download and install latest https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.0
