### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by shi4stone** [derekhe/msfs2020-map-enhancement#338]
Just finished a flight using Google map pro, then i quit the game and want to try another map, but constantly getting this error. no matter which server i try or restart the program.

Image server test failed

Can't access remote image server

If you are using a proxy to connect to remote server, please make sure the proxy is working.

**Comment by didierma34** [comment]
Hi

"shi4qtone", since 3 days i've the same message (Image test server failed). 

I've also the Pro and I can't connect to Google server 1 Pro, Google Server 2 Pro and Google server Map (not pro).

So I can't use this add on...
Is somme one has an idea ?

Thank's

**Comment by jcuellars** [comment]
Same here, issue started today.

**Comment by derekhe** [comment]
Mostly it is because google blocked you for huge amount of access.

**Comment by shi4stone** [comment]
But other map services that I never used be have the same issues. So it is not a usage problem.Sent from my iPhoneOn 11 Mar 2023, at 03:56, hesicong ***@***.***> wrote:﻿
Mostly it is because google blocked you for huge amount of access.

**Comment by MrRazgriz** [comment]
Same problem here, no matter the server. Maybe MS blocked the addon?

**Comment by FastCDr** [comment]
After updating to version 7.1.1, the same error got out. Nothing helps, even added a working proxy server.

**Comment by derekhe** [comment]
Could you try other maps?

**Comment by fkarste** [comment]
Image server test failed at Goggle Maps. NAy fix to the issue?

**Comment by JingleLeBoss** [comment]
Can't access remote image server
If you are using a proxy to connect to remote server, please make sure the proxy is working.
Bing Map (Latest) works fine but unable to lauch Google maps, tried version 7.1.2 - 7.1.1 and 7.1.0 same issue
I do not have any proxy.
Maybe a solution?
Thanks

**Comment by Nebular64** [comment]
Having the same issue.  Running v.7.1.3.  Used it yesterday for a flight and now today I'm not able to connect to any Google server.
The only server I can access is Bing.

**Comment by cptben137** [comment]
it hasn't worked for me for 2 days.
Already restarted the router, didn't help.

**Comment by MrRazgriz** [comment]
Hey felas.
You guys need a new hosts file (C:\Windows\System32\drivers\etc), or put on  these lines:

127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

It solved for me, I can fly with a decente satelite images again>

Sorry for Godzilla, I don't kmow english too much.

**Comment by JingleLeBoss** [comment]
I already have these 2 lines in my hosts, but can't access google map server, only Bing works fine
