### ISSUE TITLE
Add option for the default Bing Map

### ISSUE THREAD

**Issue by twasono** [derekhe/msfs2020-map-enhancement#342]
[Idea/Feature]

Hi,

Some people like to use your app for its cache feature, because the internal MSFS Rolling cache is broken and causing stutters.

Could you also add the MSFS Bing Map (default)?
Currently I use the Bing Map (Latest) option, which is good. But, sometimes the brightness and hue of the tiles between LODs are different and that doesn't happen with MSFS default Bing map.

With the default MSFS Bing map option, I can use your amazing app to be a proxy cache and to replace the MSFS rolling cache functionality.

Thank you.

**Comment by derekhe** [comment]
The default bing map has a color correction layer and it is removed when using this mod. If I cache the old bing map you will still see the brightness and hue tiles. 
I'm working on a pro version of bing maps which may improve this situation.

**Comment by AppleUK123** [comment]
> The default bing map has a color correction layer and it is removed when using this mod. If I cache the old bing map you will still see the brightness and hue tiles. I'm working on a pro version of bing maps which may improve this situation.

Hi Derekhe, I have the Pro licence and thoroughly enjoy the mod! Would it be possible to have some way of colour correcting the Google Photogrammetry city imagery, so the transition between normal ground textures and 3D city textures is less noticeable?
