### ISSUE TITLE
Setup-3.0.5.exe detected has a Trojan by Windows 11 

### ISSUE THREAD

**Issue by Soufiane974** [derekhe/msfs2020-map-enhancement#35]
Hi, 

Windows 11 detects your setup.exe (MSFS2020-Map-Enhancement-Setup-3.0.5.exe) has a trojan and block the installation. 

I can work around by allowing the setup in the windows 11 antivirus settings. This post is just to inform you because this might scare some people off.

Thanks,

**Comment by derekhe** [comment]
You can test latest version. I already mentioned that this is a false positive, my defender in windows 11 reports it is good. I will close this as this is an known issue and can't fix by me.
