### ISSUE TITLE
Access to hosts is denied.

### ISSUE THREAD

**Issue by mikluhomaklay** [derekhe/msfs2020-map-enhancement#351]
**Describe the bug**

After updating to 7.1.1 its now unable to patch hosts saying
Access to the path 'C:\Windows\system32\drivers\etc\hosts' is denied.
Suggests:
1. run as administrator right
I do
2. try to turn off your antivirus and restart your computer.
Don't have any AV software besides active windows defender.
Certainly I won't disable this!
3. check if any tools inside your antivirus is protecting your system.
No AV. Added the apps root folder to white list of Windows defender, though it didn't help. 
Also Defender doesn't complain about any suspicious things going on, so I don't think its him who is blocking the access to hosts. 

What it might also be: After last time using the app I have discovered some virus activity (not caused by the app) and cured the system successfully using the Dr.Webs "cureit" tool. It might have changed something with the access rights on that file I guess?

**MSFS version:**
 - steam
 - SU12

**Mod version:**
7.1.1

**Comment by derekhe** [comment]
Please check the FAQ: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ
