### ISSUE TITLE
Access to \etc\hosts' is denied. Still! FAQ doesn't help.

### ISSUE THREAD

**Issue by mikluhomaklay** [derekhe/msfs2020-map-enhancement#354]
**Describe the bug**

Hey derekhe. 
As I reported earlier the app is unable to access the hosts file. You have closed the issue with the link to FAQ.
However it doesn't help. I did even more then that. 
1. I have no any virus scanner besides windows defender, which is completely disabled!
2. I have added root folder of the app to exclusions in security options.
3. I am logged in as administrator
4. I have disabled windows User Account Control
5. I have claimed the ownership of the etc folder and hosts file
6. I have removed the hidden flag for both folder and file
7. I have provided full access rights to both folder and file for the administrators and regular users as well
8. I have rebooted the system.

I can write freely to that file with a file editor now.
but the application is still claiming it has no access to it. Starting it also in admin mode. 

See, I have completed 1 month evaluation, it was working and I liked using apple maps, now I was considering buying a year license, but of course not if I can't get it working. 

Do you have any idea? I don't have any more. 

PS:
additionally tried completely wiping and reinstalling the app to a different non system related folder
didn't help either.

**Comment by derekhe** [comment]
Please give me the device id shown inside the license page, I will have a look the logs&nbsp;





------------------ Original ------------------
From: mikluhomaklay ***@***.***&gt;
Date: Wed,Mar 29,2023 6:07 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Access to \etc\hosts' is denied.Still! FAQ doesn't help. (Issue #354)





 
Describe the bug
 
Hey derekhe.
 As I reported earlier the app is unable to access the hosts file. You have closed the issue with the link to FAQ.
 However it doesn't help. I did even more then that.
  
I have no any virus scanner besides windows defender, which is completely disabled!
 
I have added root folder of the app to exclusions in security options.
 
I am logged in as administrator
 
I have disabled windows User Account Control
 
I have claimed the ownership of the etc folder and hosts file
 
I have removed the hidden flag for both folder and file
 
I have provided full access rights to both folder and file for the administrators and regular users as well
 
I have rebooted the system.
  
I can write freely to that file with a file editor now.
 but the application is still claiming it has no access to it. Starting it also in admin mode.
 
See, I have completed 1 month evaluation, it was working and I liked using apple maps, now I was considering buying a year license, but of course not if I can't get it working.
 
Do you have any idea? I don't have any more.

**Comment by mikluhomaklay** [comment]
17DQHVMQSN6WYX7V645WJBXTXVV7CCT6XERSB3WJXJBRW1T4M5V0

However, I have resolved it!

I have just deleted the freeking hosts file (was empty anyway).
On starting the app a new hosts file was created automatically and now its working!

Maybe worth picking this up to FAQ?

**Comment by derekhe** [comment]
Sure good to know&nbsp;





------------------ Original ------------------
From: mikluhomaklay ***@***.***&gt;
Date: Wed,Mar 29,2023 7:06 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Access to \etc\hosts' isdenied. Still! FAQ doesn't help. (Issue #354)





 
17DQHVMQSN6WYX7V645WJBXTXVV7CCT6XERSB3WJXJBRW1T4M5V0
 
However, I have resolved it!
 
I have just deleted the freeking hosts file (was empty anyway).
 On starting the app a new hosts file was created automatically and now its working!
 
Maybe worth picking this up to FAQ?

**Comment by mikluhomaklay** [comment]
just bought annual license, but you sent me month license :-), could you check this? 

best regards.

**Comment by derekhe** [comment]
please request another one and select annual license don’t pay again





------------------ Original ------------------
From: mikluhomaklay ***@***.***&gt;
Date: Wed,Mar 29,2023 7:35 AM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Access to \etc\hosts' isdenied. Still! FAQ doesn't help. (Issue #354)





 
just bought annual license, but you sent me month license :-), could you check this?
 
best regards.

**Comment by derekhe** [comment]
Please use this link to create a new one for you:
https://license.aiflygo.com/app/license/renew-63e74582b66be413a3e09bed
