### ISSUE TITLE
COLORFUL PIXELS AND MIXED MAP HELP ME!!

### ISSUE THREAD

**Issue by Knorre11** [derekhe/msfs2020-map-enhancement#358]
Hello! after SU12 the map ehacement stopped working for me, the ground image of the mod is mixed with the original image of FS2020, and it has many colored pixels on the ground, after a few seconds the simulator crashed, I tried to reinstall my FS2020, format my computer, and it still doesn't work. I've tried all other versions, including the new 7.1.2 and I'm still having the same problem. I do not know what to do.

Some prints of my problem, all versions are like this, seconds after the simulator crash, in the following prints I was using version 7.1.0.

file:///C:/Users/rknor/Downloads/j.webp
file:///C:/Users/rknor/Downloads/map-ehacment-issue.webp
file:///C:/Users/rknor/Downloads/map.webp

**Comment by derekhe** [comment]
Please find out the possible answers here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ
