### ISSUE TITLE
From SU12, the map loading and streaming is very slow。

### ISSUE THREAD

**Issue by jydsj** [derekhe/msfs2020-map-enhancement#360]
**Describe the bug**
首先非常感谢！但这次SU12后，进入世界地图时地形纹理很难加载，点“FLY”后蓝条卡在80%处一直不动。
这个问题我在SU9和Map Enhancement版本v4.2.3时遇到过，后来随着Map Enhancement版本升级后就好了，直到这次游戏SU12后又出现相似问题。但这次不完全一样的是，有时卡住不动（20分钟），有时卡住后直接CTD，有又能加载进去。版本7.1.2比7.1.1稍好一些。
Community文件夹 空
非U为  美国（英语），
logs压缩包已提供。谢谢。

**MSFS version:**
 - MSFS2020 Version [e.g. 22] 微软商店版

**Mod version:**
7.1.1    7.1.2 

**Device ID**
- Device ID

**Log**
[logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/11140648/logs.zip)
  请注意TXT文件里4月4日的最后几次数据。

**Screenshots**
![2345截图20230404002201](https://user-images.githubusercontent.com/75497415/229577359-28a1676f-21b4-419d-afe0-f89c635d1587.jpg)
![2345截图20230404002626](https://user-images.githubusercontent.com/75497415/229577491-b522013c-a94a-44d5-9c4b-c2a88f6d4cac.jpg)

**Comment by derekhe** [comment]
mixed map 不能选择同一个超清的，你选成bing地图或者arcgis……否则啥都加载不了。另外官方qq群欢迎加入：756035791
