### ISSUE TITLE
Backend server failed to start

### ISSUE THREAD

**Issue by Trivium1709** [derekhe/msfs2020-map-enhancement#361]
**Describe the bug**

For weeks now I can't use the app because I keep getting the message that the backend server failed to start. I followed the instructions provided to no avail.

**MSFS version:**
 - steam
 - MSFS2020 Version 1.31.22.0

**Mod version:**
- 7.1.2

**Device ID**
- the app is not showing me a device ID at all, possibily related to the issue? Included this in the screenshots.

**Log**
- [logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/11158361/logs.zip)

**Screenshots**

[[Please provide me screenshots for the mod and msfs2020 if possible](https://imgur.com/a/YnWM2oG)]

**Additional context**
I reinstalled the app multiple times, checked the ports usage using netstat, disabled hyper V and added to the antivirus expections.

**Comment by derekhe** [comment]
Hi, it maybe related to 443 or 42098 port is occupied, please check here see if you can solve the problem: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#443-or-42098-port-is-occupied

**Comment by Trivium1709** [comment]
> Hi, it maybe related to 443 or 42098 port is occupied, please check here see if you can solve the problem: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#443-or-42098-port-is-occupied

As I mentioned, I checked for this with those instructions and no process is using those ports.

**Comment by Trivium1709** [comment]
![image](https://user-images.githubusercontent.com/129949025/230094254-8a4b6b08-e912-43ad-a067-c1ca144113b8.png)
here is the result of the command

**Comment by derekhe** [comment]
Thanks. It is something related to generate a valid device id. I'm going to find out why and it takes time. Thanks for your feedback.

**Comment by Trivium1709** [comment]
Thank you, I'll wait for an update on that.

**Comment by derekhe** [comment]
It seems your WMI service has some issue. There are several possible solutions you can have a try:
* https://stackoverflow.com/questions/53638627/system-runtime-interopservices-comexception-while-trying-to-create-a-system-rest
* The second answer in:  https://stackoverflow.com/questions/53638627/system-runtime-interopservices-comexception-while-trying-to-create-a-system-rest    
* https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10

**Comment by cbailoni** [comment]
Hey @derekhe I'm having the same issue since the upgrade to 7.1.1 and last build. I've tried all of the options you gave, including the last one that seems to be working to @Trivium1709 but it didn't worked for me. Any ideas when we will have a fix?

**Comment by derekhe** [comment]
@cbailoni please also do take a screenshot for me for investigate

**Comment by cbailoni** [comment]
![Screenshot 2023-04-05 092356](https://user-images.githubusercontent.com/15645170/230135380-3e606cfa-510b-4dd8-ab05-eba0b7665fb8.png)
Here it is

**Comment by Trivium1709** [comment]
I think he ment the commands he wanted me to use and post the results

**Comment by derekhe** [comment]
@cbailoni I mean this screenshot: https://github.com/derekhe/msfs2020-map-enhancement/issues/361#issuecomment-1497462540

**Comment by cbailoni** [comment]
@derekhe here it is, 
![Screenshot 2023-04-10 095523](https://user-images.githubusercontent.com/15645170/230915364-2eb87dcf-d1b8-48a1-a36f-93656fad95af.png)

**Comment by cbailoni** [comment]
@derekhe any idea of how can I fix that?

**Comment by derekhe** [comment]
Hi I see the backend started but do you have more output when run the command?
