### ISSUE TITLE
Error on opening app

### ISSUE THREAD

**Issue by mxc1972** [derekhe/msfs2020-map-enhancement#364]
Have this error (see attached file)

**MSFS version:
 - steam
 - 1.31.22.0

**Mod version:
- 7.1.3

**Device ID**
- 0MWBSGWRGN8RNHXGGGP7NA6RKF7WCKXHFP6W6W69Q7SDDND9WR80

**Log**
- Please attach the log zi
![Screenshot_21](https://user-images.githubusercontent.com/130281396/230764746-294dc57e-7245-4db6-99d9-7b4b7c085128.png)
p file 

**Screenshots**

**Comment by derekhe** [comment]
Sorry for the inconvience, this issue related to incorrect payment data (I'm sorry that maybe it just a false positive). Could you provide me your payment detail so I can reactive the license for you. 
Please email your payment detail to hesicong at gmail.com

**Comment by harutoshinakagawa** [comment]
3度目もPaypalでの支払いを試みましたが、結果の返信がありません。
Paypalも元通帳を確認しても引き落とされた実績はありません。
今後どうすれば解決するでしょうか。
