### ISSUE TITLE
program does not recognize the lisence i bouhgt

### ISSUE THREAD

**Issue by hen223** [derekhe/msfs2020-map-enhancement#365]
and i did a mistake and pay twice. please, i need help. thank you

**Comment by derekhe** [comment]
nws please ask for refunds i will pay it back&nbsp;





------------------ Original ------------------
From: hen223 ***@***.***&gt;
Date: Sun,Apr 9,2023 5:58 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] program does not recognize thelisence i bouhgt (Issue #365)





 
and i did a mistake and pay twice. please, i need help. thank you

**Comment by hen223** [comment]
thank you, but i want to ask why the program does not recognize the lisence? what could be the problem?

**Comment by derekhe** [comment]
Sorry for the inconvience, this issue related to incorrect payment data (I'm sorry that maybe it just a false positive). Could you provide me your payment detail so I can reactive the license for you.
Please email your payment detail to hesicong at gmail.com

**Comment by hen223** [comment]
It's ok. It working now. Thank you

בתאריך יום א׳, 9 באפר׳ 2023, 13:28, מאת hesicong ***@***.***
