### ISSUE TITLE
Error  Backend server start failed.

### ISSUE THREAD

**Issue by kennethwmartin301** [derekhe/msfs2020-map-enhancement#366]
I had recently had to re-install windows 11 from scratch and have loaded all my old programs up without trouble however Map Enhancement 7.1.3 gives me the error noted in the attached file. I have tried all the 4 considerations listed to no solution. The response is always the same. "Error   Backend server start failed.  etc...."  Map Enhancement was working nicely before. What can be done to correct this? 

<img width="344" alt="Screenshot 2023-04-09 085239" src="https://user-images.githubusercontent.com/59145771/230783044-7440104e-c532-4c1d-abe6-224e67062818.png">

**Comment by Kittster** [comment]
I have had this issue with ver:

**Comment by Kittster** [comment]
Hold it, I put the 7.1.0 version back again and it failed to start.  Then I turned off my VPN ) - (Private Internet Access or PIA) and it worked.  So, I uninstalled 7.1.0 and reinstalled ver 7.1.3, kept the VPN turned off and it worked.  I closed it (Stop) and turned on the VPN and it failed to start again.  I Stopped the 7.1.3 version, turned off the VPN and started 7.1.3 ver again, but it failed.  I could not get it to launch again.  Perhaps it will on my next reboot, but I'm not flying today, so will not chase it further on Easter Sunday.

**Comment by kennethwmartin301** [comment]
Derek,

 

OK…. Sounds like you are getting a handle on this. I thought I was going nutts. 

 

Happy Easter and thanks for checking this out. 

 

😊

**Comment by Kittster** [comment]
I wouldn't close it Derekthe.
This is the only program on my PC for which I have to disable my VPN in order to use the program.  That is not a good fix for this problem.  Others have found a way to work around it and I would hope you would do the same.  I did reboot my PC, turned off my VPN and it worked.  I stopped the program, turned On the VPN again and tried to start the program and once again it failed to load.  I would not call that a proper fix.
Thank you - Please reconsider a proper fix for this issue.

**Comment by kennethwmartin301** [comment]
Kittster,

 

Thanks for the work around. I will give that a try and let you know what happens. 

 

Kenneth Martin

510 717 2068

**Comment by kennethwmartin301** [comment]
Derek,

 

I turned OFF the VPN and re-started the computer from a cold start and the failure error remains. Here is a photo. I have also turned off the security on the machine and ran the application as administrator and yet the same response. Any thoughts?

 



 

From: ***@***.*** ***@***.***> 
Sent: Monday, April 10, 2023 9:16 AM
To: 'derekhe/msfs2020-map-enhancement' ***@***.***>; 'derekhe/msfs2020-map-enhancement' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [derekhe/msfs2020-map-enhancement] Error Backend server start failed. (Issue #366)

 

Kittster,

 

Thanks for the work around. I will give that a try and let you know what happens. 

 

Kenneth Martin

510 717 2068
