### ISSUE TITLE
Server not starting if booting from Network Location

### ISSUE THREAD

**Issue by MyFilippo94** [derekhe/msfs2020-map-enhancement#37]
I run Windows within a VM, and everything except for the OS is stored within drives accessible through Samba shares, in a local virtual network.

When booted from within the network location, it fails because it passes `\\XXX.XXX.XXX.XXX\<path>\resources\extra\nginx\conf` as a path, rather than the one with assigned letter `F:\<path>\resources\extra\nginx\conf`.

Booting it from `C:\<path>` works without issues.

[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7908921/main.log)

**Comment by derekhe** [comment]
Yes, do not use network path. Nginx won't support it.
