### ISSUE TITLE
License server is down can't purchase a license

### ISSUE THREAD

**Issue by YounesCheikh** [derekhe/msfs2020-map-enhancement#377]
Hello, 

**Describe the bug**

The license server is down and can't purchase a license, so I'm wondring if this same server will be used for a license validation once purchansed? 

**Screenshots**

<img width="1026" alt="Capture" src="https://user-images.githubusercontent.com/1327480/233496298-29ab688d-d859-48bd-b61c-4a788496d65a.PNG">

**Comment by YounesCheikh** [comment]
Ok Server is back, I payed through Paypal , but when sending the form I get the following error message: 

<img width="350" alt="2023-04-21 02_31_12-License et 4 pages de plus - Personnel – Microsoft​ Edge" src="https://user-images.githubusercontent.com/1327480/233513755-9036a8b8-2932-4fb8-a96d-979e7a4e3fe8.png">

**Comment by derekhe** [comment]
I fixed the server, please try again. Sorry for the inconvenience.

Younes CHEIKH ***@***.***>于2023年4月21日 周五08:32写道：

**Comment by YounesCheikh** [comment]
Fixed and well received my license. Thanks for your help and quick reaction :)
