### ISSUE TITLE
All of a sudden my entire map is glitched like this

### ISSUE THREAD

**Issue by Conky11** [derekhe/msfs2020-map-enhancement#379]
I believe its google maps and bing competing but I have cleared rolling cache in MSFS and turned it off but I cannot fix this issue. Can someone help?

https://imgur.com/a/7qL3IIV

**Comment by derekhe** [comment]
It may because you use dx12 which has bug.
Another reason would be the network issue, try to set the "Network settings" to "Normal" instead of "Enhanced"
