### ISSUE TITLE
Auto Start error

### ISSUE THREAD

**Issue by WarriorII** [derekhe/msfs2020-map-enhancement#38]
Whenever the auto start button is pressed, I get an error that Port 443 is being used by another app and this program will not run.

Mike

![Port 443](https://user-images.githubusercontent.com/88691149/150697055-540648a7-8b01-448b-933d-b98fee8bb2e5.jpg)

**Comment by derekhe** [comment]
I think it is because some software occupied 443 port, please check: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#443-port-is-occupied

**Comment by derekhe** [comment]
Did you fix it?

**Comment by WarriorII** [comment]
No, just don't use the auto start.  Start it manually.

**Comment by derekhe** [comment]
Will close this as no response for a long time.
