### ISSUE TITLE
MapBox Free Server is only "Image server test failed"

### ISSUE THREAD

**Issue by levelupsim** [derekhe/msfs2020-map-enhancement#380]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - steam
 - MSFS2020 Version 1.31.22.0

**Mod version:**
- 7.1.5

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
You need to setup the mapbox account.
