### ISSUE TITLE
Paiement BUY MY COFFE ce jour pour 1 mois mais pas reçu de licence. Mail : jjobringer83@gmail.com

### ISSUE THREAD

**Issue by JJO83** [derekhe/msfs2020-map-enhancement#381]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/License
