### ISSUE TITLE
You can close it but it's still not fixed

### ISSUE THREAD

**Issue by Topher420247** [derekhe/msfs2020-map-enhancement#384]
Can't connect to any servers still keep getting the proxy error. Can load Google maps in browser no problem i paid for a year license but haven't been able to use it for the past 2 months.

**Comment by Topher420247** [comment]
![Untitled](https://user-images.githubusercontent.com/114457567/235227470-386b40dc-37d6-487f-ab3c-2d92924a830d.jpg)
![msfsmapgoogle1](https://user-images.githubusercontent.com/114457567/235227502-9d6bed98-9543-4278-af0b-5fbb8178f179.png)

**Comment by Topher420247** [comment]
the only one that connects is apple maps and when i get in game that is what i see 
my device id is QZ7BRNX5MRGW1HHYRNHE5ZSM3GYGW2EKY3NESXD5FYPTR08PVHG0

**Comment by derekhe** [comment]
Please make sure your network is good. You can try open maps.google.com. Normally if you can't use bing (latest), then you have trouble.
You can remove the hosts file and create a new one to try.

**Comment by Topher420247** [comment]
I have starlink network is good I can load the game fine so long as I don't load map enhancement first. All the map websites work in browser on the same desktop I just can't get anything to load except Apple and it doesn't look like it really is loading.  I have created new host file as well. I really have tried all the solutions I've seen you post in other issues but nothing has worked. It always look like so amazing flying gliders in vr with the stunning terrain maps but you have spoiled me and stock just doesn't cut it now lol thank you for taking the time to try and fix it.

**Comment by derekhe** [comment]
Then I think it maybe your network issue, I can't do anything for it.

**Comment by Topher420247** [comment]
> Then I think it maybe your network issue, I can't do anything for it.

I understand that there is an issue but the only thing that doesn't work with my network is map enhancement mod everything else that I use doesn't have any issues. I'm just trying to figure out what I need to do to get this working again I can't be the only one there were a bunch of open tickets with the same issue

**Comment by derekhe** [comment]
Ok sure and thanks for that. Please let me know your result.

**Comment by Topher420247** [comment]
i dont know what you did but you fixed it. i tried on a whim to open it and it downloaded the newest version and connected perfectly im goin to go fly thank you for your continued support and hard work this mod really makes the difference for msfs

**Comment by derekhe** [comment]
I have done nothing....
