### ISSUE TITLE
Program don`t recognize Pro License

### ISSUE THREAD

**Issue by dibraze** [derekhe/msfs2020-map-enhancement#385]
After installing MSFS2020 Map Enhancer, entering new order license,
the program accept the license but won't change to pro mode.
Pls help 

Greets,  
Dave

**Comment by derekhe** [comment]
What's your device id?

**Comment by dibraze** [comment]
9H4WBT16QVT63HM6BGX88JZ0RYW0NG2RZBG59BREJSV7S3DGA3B0

**Comment by derekhe** [comment]
I see the license is installed good, please give me the screenshot

**Comment by dibraze** [comment]
![image](https://user-images.githubusercontent.com/131987114/234902118-3346ff6d-bdf9-4299-93aa-2eaec2bc2bcd.png)

**Comment by derekhe** [comment]
Please first try use Bing (Latest) to see if it works or not.

**Comment by dibraze** [comment]
Works! no problem at all
just in the left corner of the program it should say also (PRO) ... isn't it true?

**Comment by dibraze** [comment]
nevermind.... 
now it works after just doing bing! 
thanks for your fast support!

**Comment by derekhe** [comment]
it should have a PRO on the title (I think it is a bug introduced in 7.1.5 and it is hidden)
