### ISSUE TITLE
Map Enhancement Processes remain after STOP and close program

### ISSUE THREAD

**Issue by OldTiredSailor** [derekhe/msfs2020-map-enhancement#386]
**Describe the bug**
After a normal close of MSFS (quit to desktop) and a normal STOP of MSFS2020 Map Enhancement everything seems OK.  But - using Task Manager I find four (4) processes remaining and they all have the name MSFS2020 Map Enhancement.  They use no CPU but each have 154 MB memory allocated.  I have to use Kill Process to get rid of them.  If I don't Kill them - at Windows ShutDown time I cannot shut down. OR - If I try to restart Map Enhancement - nothing happens and the processes do not become active again

The PIDs for each remaining process are the same as the ones in use when MSFS is running. 

**MSFS version:**
 **- steam**
 - MSFS2020 Version [e.g. 22]
 - **1.32.7.0**

**Mod version:**
- Mod version 7.1.5

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please try latest version.
