### ISSUE TITLE
Maps to old

### ISSUE THREAD

**Issue by kuilbop** [derekhe/msfs2020-map-enhancement#387]
I' ve tried the month paid version, but to my horror. 
The maps used are at least 3yrs old in Netherlands. 
And Netherlands doesn' t differ that much from bing. 
Pro or the "normal" server.

For me that's an absolute NO-NO for further paid version
Sorry to be this blunt about it, but just really dissapointed

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please check if your rolling cache is enabled, turn it off otherwise old
bing data is used.

Pascal Kuilboer ***@***.***>于2023年5月1日 周一03:47写道：

**Comment by kuilbop** [comment]
Nope, but did you really think I'm that thick... Come on.
There are buidlings which were demolished 3 years ago (bing won' t even show those at all, so that' s NOT it) 
So that' s why om so dissapointed for paying for old stuff.
How would you feel if you bought a "new" car and later you find out that the bugger is over 3 years old.
Would you feel the same.

**Comment by derekhe** [comment]
Please give your device id and also give me some screenshots regarding your issue.


Also make sure to use latest version, clean the mod cache or disable it to see if anything different.





------------------ Original ------------------
From: Pascal Kuilboer ***@***.***&gt;
Date: Tue,May 2,2023 10:18 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Maps to old (Issue #387)





 
Nope, but did you really think I'm that thick... Come on.
 There are buidlings which were demolished 3 years ago (bing won' t even show those at all, so that' s NOT it)
 So that' s why om so dissapointed for paying for old stuff.
 How would you feel if you bought a "new" car and later you find out that the bugger is over 3 years old.
 Would you feel the same.

**Comment by gavroch** [comment]
Bonjour, j'ai le même problème, les cartes ne sont pas a jour et j'ai supprimé le caché de flight, il y a plein d'arbres,  flight réglé au minimum, sa viens peu t'être de moi   

voir en réel    (https://vimeo.com/manage/videos/819590217) 

Hello, I have the same problem, the maps are not up to date and I deleted the hidden flight, there are plenty of trees, flight set to the minimum, its come little to you from me   

See in real        (https://vimeo.com/manage/videos/819590217) 

![teste flight](https://user-images.githubusercontent.com/132381071/235725493-f58b0917-fe63-42ec-ba83-aff150f8eee8.jpg)

![teste google](https://user-images.githubusercontent.com/132381071/235725497-929c390f-f4e1-4c79-8395-dfd473b2c562.jpg)

**Comment by kuilbop** [comment]
> > Now all of a sudden Schiphol and surrounding areas are different. What did you do and i rather have that you'd be honest about it. Sorry but if you want paying customers to stay... like i was till 30th of april..... be honest
> 
> I have no idea. The software is completely there and I have no way to change any one on your machine.

Sorry, but can´t test the PRO maps anymore to see if there are any changes, and i´m not planning to order another sub. 
If you take Lisse (The netherlands) for exmaple... my hometown... ther are buildings there that were demolished 3 years ago, while google maps show the situation from a few months ago (thus reasonbly recent) 
The google server shows an even worse situation.
So for me as i said an absolute no-go to go PRO again.
I had very high hopes to get away from Bing maps with your mod, but very dissapointed for even the €5 monthly purchase.

device id cause your asked : FZ0H0NRGH2W9C060GX24FAV7XXRPQRQB11S8MMF71T425YWZXAB0

**Comment by kuilbop** [comment]
![maps](https://github.com/derekhe/msfs2020-map-enhancement/assets/3214000/0f1f0c37-2a52-4589-ae59-ea063a8a612b)
![agathakerk-niet af](https://github.com/derekhe/msfs2020-map-enhancement/assets/3214000/5417975b-37e9-496a-ab3a-3da97c44ae18)

**Comment by kuilbop** [comment]
I don' t know which maps you use, but it sure ain't Google and for sure not recent up to date ones. 
I used a month pro, but now I strongly believe it was a waste of money

**Comment by derekhe** [comment]
See: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#what-can-this-mod-do-and-what-cant

The mod can only replace the ground texture, nothing else.
