### ISSUE TITLE
Google Maps 

### ISSUE THREAD

**Issue by StevenSilvaB767** [derekhe/msfs2020-map-enhancement#388]
**Describe the bug**
since some versions I am having a strange problem with MSFS2020 Map Enhancement and https://www.google.com/maps. It turns out that when I'm on flights of more than 2 hours, the download from the Google Maps Server stops, and the landscape becomes unenjoyable. (www.google.com/maps can't be opened in the browser with problems, the most common is that it does not open the aerial or satellite image) it is as if it were banned or the IP was blocked the error in the browser is resolved after 2 or 4 days after the error and later the program works again.

so. What is the solution or how to stop this error once and for all?
Please describe the bug in detail to help me understand the scenary

Thanks for the help

**MSFS version:**
 steam
 - MSFS2020 Version 
 - 1.32.7.0

**Mod version:**
- 7.1.5

**Device ID**
- KSXWBYTV7ZH7MM10DR951Y33H43MB1JWSQQWPJ6ZZB70BD6S6C90

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I don’t have any way to get it work because google blocks you for high
traffic access maybe you can use other maps

StevenSilvaB767 ***@***.***>于2023年5月1日 周一21:43写道：

**Comment by twasono** [comment]
Make sure to enable cache. It helps to minimize the download traffic to google maps.

**Comment by diehummel** [comment]
Use an VPN or try to get a new IP from ISP.
I have the same issue that Google is blocking my IP.
Also then i cannot use Google Earth because of this block.

**Comment by StevenSilvaB767** [comment]
@twasono 
thanks for the reply. I do not use it in these cases since they are long-haul flights to destinations that are almost regular or rare for me. and the truth is I don't know if that option works for me

**Comment by diehummel** [comment]
@StevenSilvaB767 I use ProtonVPN (Free) and use the Netherlands VPN Server.
With them the Google Maps are working.

If i don't want to use the VPN, then i use Bing Maps (normaly with an NVIDIA Color correction, but current drivers causes crashes when color correction is used)

**Comment by StevenSilvaB767** [comment]
@diehummel neither VPN nor changing IPs works always ends in the same silly error

**Comment by StevenSilvaB767** [comment]
@diehummel update: using PROTON VPN solved the error tkank u so much!!
