### ISSUE TITLE
Keep getting put into offline mode when using this Mod (apple maps pro)

### ISSUE THREAD

**Issue by TommyButch** [derekhe/msfs2020-map-enhancement#389]
Keep getting put to offline mode when using these maps

i start the map enhancement like normal then sometime in the flight it can be anytime i get an error saying ive been put to ofline mode, my internet is good too also cant be that.

**MSFS version:**
 msstore version
 - MSFS2020 Version sim update 13
Mod version is 7.1.5

**Device ID**
- Device ID     3KM4NMHPKCBJSJ7NRXVENVEHSNQ5MAK7APCRN0W4EWC7SN22VJTG        

**Log**
- Please attach the log zip file    
i dont know how to get the log file
**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

[log20230504.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11400909/log20230504.txt)
[log20230502.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11400910/log20230502.txt)
[log20230503.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11400911/log20230503.txt)

**Comment by TommyButch** [comment]
I watched this video https://www.youtube.com/watch?v=ZqZsVND6KGU&ab_channel=BrettInTech      and think I found the issue, if you watch that video near the end its default is 20% and you can change it down to 0, apparently the 20% is windows using bandwidth when it doesn't need to. Mine was on 80% so I was only getting 20% off my Wi-Fi so I changed it down to 0% and haven't had the issue since, this is to help anyone getting the same issue as me try and watch that linked video above ^ :)

**Comment by TommyButch** [comment]
> Good to know :)

that wasn't the issue i don't think, i keep being switched to offline mode still.

**Comment by TommyButch** [comment]
![Microsoft Flight Simulator Screenshot 2023 05 05 - 19 20 54 74](https://user-images.githubusercontent.com/132608573/236537686-a91b66db-7003-43cb-a921-c59f66455076.png)
  this is what i get when switched to offline

**Comment by derekhe** [comment]
Can you try set the "Network setting" to "Normal" instead of "Enhanced" to have a try.

**Comment by TommyButch** [comment]
> Can you try set the "Network setting" to "Normal" instead of "Enhanced" to have a try.

i have tried that too, i was on 'enhanced' changed to 'normal' few days ago and still having the same problem unfortunately.

**Comment by twasono** [comment]
Unfortunately Google Map limits the downloaded tiles per IP address per certain duration of time.

The only thing we can do is to enable cache on this app to reduce the download when flying on the same area.

The other alternative is to select another map (Bing Map Latest), which I suppose has larger limit or no limit at all.

**Comment by TommyButch** [comment]
> Unfortunately Google Map limits the downloaded tiles per IP address per certain duration of time.
> 
> The only thing we can do is to enable cache on this app to reduce the download when flying on the same area.
> 
> The other alternative is to select another map (Bing Map Latest), which I suppose has larger limit or no limit at all.

ok thank you, so if i got better wifi would it stop doing this ?   i get around 5 MB/S

**Comment by diehummel** [comment]
> > Can you try set the "Network setting" to "Normal" instead of "Enhanced" to have a try.
> 
> i have tried that too, i was on 'enhanced' changed to 'normal' few days ago and still having the same problem unfortunately.

Do you have Google Earth Pro intalled on your PC?
If yes, retry Map Enhancement after uninstall it. Don't know why, but since i uninstalled it, the map tool workd again for me with google maps.

**Comment by TommyButch** [comment]
@derekhe what else should i do to try fix this issue ?

**Comment by TommyButch** [comment]
hey @derekhe  my  month is nearly over, given the issues please can I have another month to properly test the addon in a working state ?  thank you

**Comment by TommyButch** [comment]
Internet isnt the issue, new wifi installed getting 400 mb/s on my pc and it is doing it again....

**Comment by derekhe** [comment]
I'm testing and it is working fine.

**Comment by TommyButch** [comment]
ok i know its working fine for others but whats the problem with mine ?

**Comment by derekhe** [comment]
What’s your exact problem?





------------------ Original ------------------
From: TommyButch ***@***.***&gt;
Date: Wed,May 24,2023 7:52 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Keep getting put into offlinemode when using this Mod (apple maps pro) (Issue #389)





 
ok i know its working fine for others but whats the problem with mine ?

**Comment by derekhe** [comment]
The Microsoft server connections are var from different locations, and it doens't depends on your wifi's speed. You may try use different servers to see if some server may have the issue. The best to try is "Bing (latest)" which connets to MS servers, then "ArcGIS", then "Google"

**Comment by TommyButch** [comment]
Ok I will try google and see if I have the same problem, what your saying is I can’t use apple as it isn’t connnecting to the servers properly ? On 24 May 2023, at 2:22 pm, hesicong ***@***.***> wrote:﻿
The Microsoft server connections are var from different locations, and it doens't depends on your wifi's speed. You may try use different servers to see if some server may have the issue. The best to try is "Bing (latest)" which connets to MS servers, then "ArcGIS", then "Google"

**Comment by TommyButch** [comment]
ok ill try google maps now, also i had network on normal before and it was still doing it. Is there no way at all that it could be a fixable issue ?

**Comment by TommyButch** [comment]
sorry i meant ill try bing maps

**Comment by TommyButch** [comment]
still getting the issues  even with bing and google maps @derekhe

**Comment by TommyButch** [comment]
https://cdn.discordapp.com/attachments/1087815040658309200/1111290097921437796/image.png      could it be ports @derekhe be using different ports, ive noticed i only get the issue in the fenix ?    so far anyways on my flight in the PMDG 738 i haven't had the issue.

**Comment by TommyButch** [comment]
Can now confirm i have the issue with the PMDG 738 too, theres got to be something wrong with the map enhancement its going wrong with everything.

**Comment by TommyButch** [comment]
hey Derek i have a file called flight simulator in my appdata >local> flight simulator and it has mapscaches and overides could this be any reason im getting a issue ? maybe i need to delete this ? its frustrating as this is such a great add on and getting disconnected every flight is not ideal.

**Comment by TommyButch** [comment]
@derekhe looks like its just apple maps doing this, google maps is fine, so is there a way to change isp or dns for the apple to work,  my key runs out I've been trying to troubleshoot Windows reinstall, MSFS etc. Haven't been able to fully utilise the product can I have my month extended please.
