### ISSUE TITLE
No images are loaded

### ISSUE THREAD

**Issue by djedhor** [derekhe/msfs2020-map-enhancement#39]
When I start the program, everything looks fine, only the counter for the images does not increase and in the simulator the images do not change.
In the Dev Tool I receive this error message:
DevTools failed to load source map: Could not parse content for app://./ajv.js.map: Unexpected end of JSON input
Can you help me?

![grafik](https://user-images.githubusercontent.com/86651730/151542347-751e93f9-b461-4a9a-b080-d6a53324d2ed.png)

**Comment by djedhor** [comment]
And the Logfiles
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7959975/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7959976/renderer.log)

**Comment by djedhor** [comment]
The Bing Map in the MSFS was not enabled.

**Comment by derekhe** [comment]
Did you disabled the rolling cache?
Did you start the mod before starting msfs2020?
Which msfs2020's version? ms store or stream?

**Comment by zhang-zeyu** [comment]
@djedhor Hi I have save issue with you, can you please tell me how to solve this?
