### ISSUE TITLE
Google Maps Pro License

### ISSUE THREAD

**Issue by PotipharII** [derekhe/msfs2020-map-enhancement#393]
I wanted to renew my Google Maps Pro license. This was not possible via the renewal function. I get an error message about creating a new license.

Divece ID: NJ9H97AS4NC0WF2DAZ0N7MHZVGZQ6HDE9HK2YP0QENFHEH7PT4R0
Paypal Transaction Code: 2ST21207466699809

**Comment by derekhe** [comment]
Sorry I think you can request a new license for this new purchase: https://appsmith.aiflygo.com/app/msfs2020-map-enhancement-licence/new-license-645f90d7f9a0567cd9600e2e

**Comment by PotipharII** [comment]
As I wrote, I also get a message when applying for a new license. ;-)
![Screenshot 2023-05-14 155406](https://github.com/derekhe/msfs2020-map-enhancement/assets/133574181/586ffa21-5dbf-498c-9947-18e948f4632d)
And I don't know what I could have entered wrong there. I didn't do anything different than last time. Only this time I didn't pay for 30 days, but for a year. And the last time it worked without any problems.

**Comment by Trevor-Austin** [comment]
I'm getting the same issue for a new 30 day license

**Comment by derekhe** [comment]
Sorry for the inconvenience, I am looking into this problem&nbsp;





------------------ Original ------------------
From: mnpostema32 ***@***.***&gt;
Date: Mon,May 15,2023 4:00 AM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Google Maps Pro License (Issue#393)





 
I'm getting the same issue for a new 30 day license

**Comment by Model104** [comment]
Hope you don't mind me enquiring here. I purchased a 30 day license a couple of days ago but have not yet received it. Did you receive my order? :)

**Comment by PotipharII** [comment]
> Sorry for the inconvenience, I am looking into this problem&nbsp;
> […](#)
> ------------------ Original ------------------ From: mnpostema32 ***@***.***&gt; Date: Mon,May 15,2023 4:00 AM To: derekhe ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] Google Maps Pro License (Issue#393) I'm getting the same issue for a new 30 day license — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Is there a solution now?

**Comment by derekhe** [comment]
I think it is good now. The license server is back online.
