### ISSUE TITLE
License submission keeps failing

### ISSUE THREAD

**Issue by Trevor-Austin** [derekhe/msfs2020-map-enhancement#394]
Hi, Paid $5 by buy me a coffee but each time I try and submit a license application it says that it failed and to check my input?

**Comment by LeightonThompson** [comment]
Same issue here but I paid via PayPal.

**Comment by derekhe** [comment]
Fixed





------------------ Original ------------------
From: LeightonThompson ***@***.***&gt;
Date: Mon,May 15,2023 8:35 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] License submission keepsfailing (Issue #394)





 
Same issue here but I paid via PayPal.

**Comment by derekhe** [comment]
fixed





------------------ Original ------------------
From: Trevor-Austin ***@***.***&gt;
Date: Mon,May 15,2023 2:32 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] License submission keeps failing(Issue #394)





 
Hi, Paid $5 by buy me a coffee but each time I try and submit a license application it says that it failed and to check my input?

**Comment by Trevor-Austin** [comment]
Thanks.

I’ll try again this evening.

On 15 May 2023, at 02:58, hesicong ***@***.***> wrote:

﻿

fixed





------------------ Original ------------------
From: Trevor-Austin ***@***.***&gt;
Date: Mon,May 15,2023 2:32 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] License submission keeps failing(Issue #394)






Hi, Paid $5 by buy me a coffee but each time I try and submit a license application it says that it failed and to check my input?
