### ISSUE TITLE
Google maps no longer works, if i try bing (latest) it works!

### ISSUE THREAD

**Issue by eydrianf** [derekhe/msfs2020-map-enhancement#397]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

MSFS steam version,

latest beta for AAU2

seems microsoft has a new way to block this?

today i noticed that the google map version (not pro) is no longer working only if i select bing latest it would load, i notice this on the main loading screen when selecting the airport after i load its true the google maps images are not loading?

could the beta AAU2 causing this?

**Comment by Nathan-Shea** [comment]
#396

**Comment by derekhe** [comment]
I'm investigating the problem.

**Comment by derekhe** [comment]
Fixed in this version: https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.1.7
