### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by Antsy1988** [derekhe/msfs2020-map-enhancement#398]
hiho i have the mod version 7.1.7 (latest Stable version) and have problems with the google Maps Server (not Pro).

I am getting the following message:

Image server test failed

Unable to access remote image server

If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.
If you are using a proxy to connect to the remote server, please ensure that the proxy is working.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.

Bing Maps (latest) and  ArcGIS work

i have the game on steam.

i have no problems on googlemaps and i dont use a proxy.

a little update as i´m a typing this report:

if i connect to bin maps first (starting and stopping) and THEN try Google Maps server it connects 8 out of 10 times

**Comment by derekhe** [comment]
Your network to google may not be quite stable. You can try google server 2 to see if it is better.

**Comment by Antsy1988** [comment]
i dont have pro
