### ISSUE TITLE
Still no Pro License

### ISSUE THREAD

**Issue by Model104** [derekhe/msfs2020-map-enhancement#399]
Hi, I purchased a 30 day license 3 days ago but have not yet received it. Did you receive my order? :)

**Comment by derekhe** [comment]
Did you fill the form? https://appsmith.aiflygo.com/app/home-64604e00f9a0567cd9600e43

**Comment by Model104** [comment]
Hi ,Yes , I filled in the form and paid via Pay Pal. I wrote ‘App’ in the Pay Pal description. Sent from Mail for Windows From: hesicongSent: 19 May 2023 11:17To: derekhe/msfs2020-map-enhancementCc: Model104; AuthorSubject: Re: [derekhe/msfs2020-map-enhancement] Still no Pro License (Issue #399) Did you fill the form? https://appsmith.aiflygo.com/app/home-64604e00f9a0567cd9600e43—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Model104** [comment]
Hi ,Yes , I filled in the form and paid via Pay Pal. I wrote ‘App’ in the Pay Pal description.

**Comment by Model104** [comment]
I also had clarification that my payment had gone through.

**Comment by derekhe** [comment]
I don't have the record. What's your email address?
