### ISSUE TITLE
Start server failed: access is denied

### ISSUE THREAD

**Issue by drisssouid** [derekhe/msfs2020-map-enhancement#40]
I've been trying to use the most recent version, however I cannot start the server as I keep getting the following error:

>     Start server failed, error: Error: Command failed: mkcert.exe -install -key-file key.pem -cert-file cert.pem kh.ssl.ak.tiles.virtualearth.net khstorelive.azureedge.net *.virtualearth.net *.azureedge.net ERROR: add cert: failed adding cert: Access is denied.

I run it as administrator and anti virus turned off, created an exception rule on windows firewall and none seems to work.

**Comment by derekhe** [comment]
Please have a look at: https://github.com/FiloSottile/mkcert/issues/231#issuecomment-695776701:

**Comment by derekhe** [comment]
Did you fix it?

**Comment by drisssouid** [comment]
Perfect! That workaround worked perfectly, many thanks.

**Comment by derekhe** [comment]
Good to know, will close this.
