### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by alanbeasy** [derekhe/msfs2020-map-enhancement#400]
it would be nice if the cache did not clear itself every time the software updates.  i had 3gb of data loaded and mow i have to download it again.  Not much point in having a cache if that keeps happening.

**Comment by derekhe** [comment]
You can set the cache path into another disk

**Comment by alanbeasy** [comment]
Thanks Derek,
I have successfully created a new location for the cache.
It might be worth putting a page on the User Manual about how to set the
Cache to another disk.
When I first did it the app continued to use the old cache.
I had to do it a few different ways and restart etc. before the app started
using the new location.
Also how to delete the old cache - before selecting a new location or can
you just delete the default cache file manually?
I was not able to transfer the existing cache data to the new cache.

Anyway.....  a few different tips on those things would be handy.
Thanks
Alan
