### ISSUE TITLE
Image Server Test Failed

### ISSUE THREAD

**Issue by ronprice46** [derekhe/msfs2020-map-enhancement#404]
**Describe the bug*Image Server Test Failed*

Please describe the bug in detail to help me understand the scenario
Loading up and using google maps servers seems blocked as i cannot even use google maps on my pc. 
**MSFS version:**
 - msstore or steam "MS Store"
 - MSFS2020 Version [e.g. 22] 1.32.7.0

**Mod version:**
- Mod version 7.1.7 but was using the most recent one when this started

**Device ID**
- Device ID "W9K6Y0C1J3S39K082YCHS5602DNW4CJR98KKGHR1AGYEEXE6BR70"

**Log**
- Please attach the log zip file Cant find log file

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by Aseinsha** [comment]
yeah I've been having issues with google Maps Server 1 and regular google maps. Google maps server 2 looks to be working though.

**Comment by ronprice46** [comment]
got around it by using a vpn but wish i didnt have to as i cant afford a vpn all the time. It made it where i couldnt even use google maps on my pc

**Comment by ronprice46** [comment]
without vpn i still get this issue and currently having to use bing maps until i get a fix

**Comment by derekhe** [comment]
There is no way from my side to work around the rate limitation from google server. Please use some VPN.
Another way is to use other maps, google maps are not always the best.
