### ISSUE TITLE
Apple Maps

### ISSUE THREAD

**Issue by TommyButch** [derekhe/msfs2020-map-enhancement#405]
**Describe the bug**
Offline issue with the apple maps...

Please describe the bug in detail to help me understand the scenario
i get put to offline mode, ive tried everything network to normal to enhanced high LOD to off windows optimization ive tried the beta version, alpha version and normal all still same issue, its a shame how such a great add on but i cant use it as off this, no one else i know gets the issue but me, ive asked in the fenix discord, pmdg and the developers says its this causing the issue, all i can think of is like you said the connection stability but is there a way to improve this ? and there is surely a way to fix it, ive tried using a VPN still having the issue,
be great to hear and try fix this, im very sorry for the inconvenience but like i said  its a shame i cant use this as apple is the best in my opinion and im getting issues.
Thanks

**MSFS version:**
 - msstore or steam
 - MS STORE
 - MSFS2020 Version [e.g. 22]
 - 1.32.7.0

**Mod version:**
- Mod version
- 7.2.0

**Device ID**
- Device ID
- 3KM4NMHPKCBJSJ7NRXVENVEHSNQ5MAK7APCRN0W4EWC7SN22VJTG

**Log**
- Please attach the log zip file 
Heres the logs maybe you can see if any of these tell you anything about why im getting these
[log20230529.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11593782/log20230529.txt)

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Again very sorry for the inconvenience opening another but this addon is just amazing and im determined to get this add on working
many thanks,

**Comment by derekhe** [comment]
I see from the log there are some issues happening. I'm investigating, please stay tunned.

**Comment by TommyButch** [comment]
awesome thanks derek :)

**Comment by TommyButch** [comment]
Hey @derekhe any news how its going ?

**Comment by TommyButch** [comment]
@derekhe do you need more information ?  any updates ?

**Comment by derekhe** [comment]
Still in progress, I had to run tests to get why. It is working fine on my end at the moment.

**Comment by derekhe** [comment]
I tried today for a longer flight and experience once after 1 hour of flight. I will try more to find out why.

**Comment by derekhe** [comment]
This is time consuming, so please stay tunned.

**Comment by TommyButch** [comment]
Ok

**Comment by TommyButch** [comment]
@derekhe when i load in sim and i get this with apple (pro) this doesnt happen with any other and im wondering if this could be reason as it doesnt load in tiles 
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/132608573/cf9ae128-e33a-41a2-aefd-8f7e246952d4)
also when i try click on gates and stuff with apple maps it doesn't actually let me or anything sometimes this may be with apple as im only seeming to get the problem with apple and not any others.
Just info if that will hopefully help you out.

**Comment by TommyButch** [comment]
sometimes i go back to main menu then the who,e world map is like blue where nothing has loaded in using apple maps or it does in the screenshot above ^ when you load in you get the 'bandwidth too low you have been switched to offline mode'

**Comment by TommyButch** [comment]
Hey Derek,
Just tried a few more troubleshoot for apple maps,
-Online Functionality off when i load in then back on, flew for a bit then offline mode again.
-Normal and Enhanced both tested and get the same result. Offline Mode.
- 1 thing i noticed is i get connection lost, 'switched to offline mode bandwidth'  that error, then i stay on the bandwidth error i get successfully connected back but with offline textures still.
- This is the logs where i got offline again,
- [log20230614.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11740292/log20230614.txt)

**Comment by TommyButch** [comment]
Hey Dereke, I hope you are well 🙂 . I am pleased to read that you are working on a fix, and I am grateful for your support. Although it has been disappointing that I have not been able to use your product to its full potential. Therefore, would it be possible to get another month's key, please? Or at least give me another month once you have published a fix, as I haven't been able to use what I bought.
Regards,
Tom

**Comment by derekhe** [comment]
Please try 7.2.1, I optimized the loading for apple maps and please try.

**Comment by TommyButch** [comment]
Yeah I tried the new update and got the error as soon as I loaded into the airport.On 19 Jun 2023, at 10:25 am, hesicong ***@***.***> wrote:﻿
Please try 7.2.1, I optimized the loading for apple maps and please try.

**Comment by derekhe** [comment]
Please try this version, I found the problem and did a fix for it:

https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.2.2

**Comment by TommyButch** [comment]
Ok thanks ill try it now

**Comment by TommyButch** [comment]
Hey Dereke, hope your doing good 🙂 . I am pleased to tell you my issue is fixed I am grateful for your support throughout. it has been disappointing that I have not been able to use your product to its full potential. Therefore, would it be possible to get another month's key, please? as I haven't been able to use what I bought for this month.  I am interested in buying the yearly licence but just need check first that everything is working on my end. Thanks Derek
Regards,
Tom
