### ISSUE TITLE
Tiles loading in small square around plane.  Beyond is default.

### ISSUE THREAD

**Issue by AK2177** [derekhe/msfs2020-map-enhancement#406]
For a while now I'm getting the tiles loading in small square around plane.  Beyond is default.  Ive tried LOD 400, Clearing all cache.  Disabling all cache etc.  Deleting and reinstalling program but nothing solves this.  I really want to use your program but this issue just kills the idea completely.  Used to work great and now I don't know whats wrong.  What else could I possibly try to fox this issue and start enjoying your program again?

 - MS Store Version

**Mod version:**
7.2.0. actually all after 6.x.x

**Comment by derekhe** [comment]
Could you give some screenshots?

**Comment by AK2177** [comment]
![Clipboard01](https://github.com/derekhe/msfs2020-map-enhancement/assets/134967783/875ae360-b296-4b9c-8d91-729fe0b1a457)
![Clipboard02](https://github.com/derekhe/msfs2020-map-enhancement/assets/134967783/976611a2-dd44-4396-a76e-9d94871cf9b2)
![Clipboard03](https://github.com/derekhe/msfs2020-map-enhancement/assets/134967783/81d7c867-3db2-41e9-af05-ba5a522ba8cf)

**Comment by AK2177** [comment]
Ive gone high just to emphasize the issue but the changing tiles can be seen forming ahead at nearly any altitude and it totally kills your wonderful app.  Ive tried everything I know because this issue never occurred in the past.  Any help would be appreciated.

**Comment by derekhe** [comment]
I see, what's the map are you using? I guess it is bing (latest)?

**Comment by AK2177** [comment]
I've done the LOD 400, cache clear, cache off, cache on, physically deleted cache and let it build new one etc.  Even deleted program and reinstalled... Older versions, newest.  Nothing seems to work.  Thats why I decided to speak to you, who is the creator himself.
