### ISSUE TITLE
new licence

### ISSUE THREAD

**Issue by chris83600** [derekhe/msfs2020-map-enhancement#411]
HI 
can i have new licence because i changed my hardware 

My device  GQMECR33AEPQ8AGYSCBYB00BKV6TYPDERRCN526Q8Q3E66B11D5G the licence i received doesnt work 
thanks

**Comment by derekhe** [comment]
Please use this link to refresh the license: https://appsmith.aiflygo.com/app/refresh-645f90d7f9a0567cd9600e30

**Comment by chris83600** [comment]
yes i used this link to refresh my licence but doesnt work...

**Comment by derekhe** [comment]
What’s your new deviceid&nbsp;





------------------ Original ------------------
From: chris83600 ***@***.***&gt;
Date: Mon,Jun 5,2023 8:05 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] new licence (Issue #411)





 
yes i used this link to refresh my licence but doesnt work...

**Comment by chris83600** [comment]
This is my Device ID GQMECR33AEPQ8AGYSCBYB00BKV6TYPDERRCN526Q8Q3E66B11D5G Envoyé à partir de Courrier pour Windows De : hesicongEnvoyé le :lundi 5 juin 2023 14:39À : derekhe/msfs2020-map-enhancementCc : chris83600; AuthorObjet :Re: [derekhe/msfs2020-map-enhancement] new licence (Issue #411) What’s your new deviceid&nbsp; ------------------ Original ------------------ From: chris83600 ***@***.***&gt; Date: Mon,Jun 5,2023 8:05 PM To: derekhe/msfs2020-map-enhancement ***@***.***&gt; Cc: hesicong ***@***.***&gt;, State change ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] new licence (Issue #411) yes i used this link to refresh my licence but doesnt work... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt; —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by chris83600** [comment]
my DEVICE ID  GQMECR33AEPQ8AGYSCBYB00BKV6TYPDERRCN526Q8Q3E66B11D5G

**Comment by derekhe** [comment]
The email has been sent out, please check if the email is in your spam folder: 
<img width="1201" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/79d25a8c-bc9a-45d8-818e-2cead50be429">

**Comment by chris83600** [comment]
![Capture d’écran 2023-06-05 161548](https://github.com/derekhe/msfs2020-map-enhancement/assets/126764449/7b980c9d-87f6-4a54-99af-986f2489dc6b)

**Comment by chris83600** [comment]
Sir
I wrote to you but never answered or helped me with my license problem.
today it works by going from version 7.20 to 7.21
It's really a shame on your part because we are customers..
Cordially

**Comment by derekhe** [comment]
Sorry, the issue was fixed in 7.2.1 because of the license file was locked by some application and the mod can't delete the old one. I forgot to reply your ticket. Please contact me and I will give you extra 1 month for compensation.
