### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by Gord21731** [derekhe/msfs2020-map-enhancement#413]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by Gord21731** [comment]
Image server test failed

Unable to access remote image server

If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.
If you are using a proxy to connect to the remote server, please ensure that the proxy is working.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information. 
DeviceID: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G

**Comment by Gord21731** [comment]
Hello! Such a problem arose two days ago! Up to this time everything worked perfectly! When you start downloading Art GIS maps, you see a window with the text:
Image Server Test failed

Unable to access remote image server

If you use Google Maps, please make sure you can open https://www.google.com/maps in your browser. Google may block you due to a large number of requests.
If you are using a proxy to connect to a remote server, please make sure that the proxy is working.
Please also visit the FAQ page for more information.
Can you tell me what the problem is and how to solve it, or is work underway to solve this problem?
Device ID: EAEYQBHYT06BRY51X6QF6SM0645SGG1VW0S969CSJJ8F9P6XRE7G

**Comment by ussthp** [comment]
Hello I got same issue, just happened in recent two days. I can open https://www.google.com/maps normally and confirmed my proxy is working. 
I realized that the problem appreared when I select 'China HD 中国定制超清地图2021(Pro)' or 'China HD 中国定制超清地图2022(Pro)', then whichever map I selected under 'Select a mixed map' I will always get this error. But if I selected a map other than two above China HD maps, I will not get the 'Image server test failed' message except one exception which is the last 'Mapbox' option.

My app version is 7.2.0(Pro), and MSFS2020 is Store version.

**Comment by ussthp** [comment]
> > Hello I got same issue, just happened in recent two days. I can open https://www.google.com/maps normally and confirmed my proxy is working. I realized that the problem appreared when I select 'China HD 中国定制超清地图2021(Pro)' or 'China HD 中国定制超清地图2022(Pro)', then whichever map I selected under 'Select a mixed map' I will always get this error. But if I selected a map other than two above China HD maps, I will not get the 'Image server test failed' message except one exception which is the last 'Mapbox' option.
> > My app version is 7.2.0(Pro), and MSFS2020 is Store version.
> 
> The China HD map may only works in China mainland. Please don't select it if you are oversea.

I'm in mainland China. The thing is that the app was working pretty well for pretty long time until two days ago.

**Comment by ussthp** [comment]
Didnt change anything but give a try today, and it just resumed to normal, I can use HD again...great but weird.

**Comment by Excreozeus** [comment]
Hello, regarding for the same issues, got trouble when accessing the Google Maps Server (non pro version) after recent update. I have no issues opening https://www.google.com/maps and accessing the google maps pro version. any idea for this issues? 
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/112015843/2fa951f2-60a6-485d-b799-9be1221a2536)
