### ISSUE TITLE
license is blocked

### ISSUE THREAD

**Issue by rscarter043** [derekhe/msfs2020-map-enhancement#417]
When loading, I get a message "License is blocked".  I just purchased a yearly license for Google Maps Server.  It worked fine for a day or two.

**MSFS version: 2020**
 - msstore
 - MSFS2020 Version [e.g. 22]

**Device ID**
- Device ID 3EAYPCZWT462PQN5NMDFKQJXCBC4A3K5RRZX3QTG8NBK1RRH3H70

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
This is because I can't find your payment information on buymeacoffee and I contact you through email but no reply. Please reply me your payment receipt and I will unlock you.

**Comment by rscarter043** [comment]
How do I pay you.  The info page will not allow me to click on submit.

**Comment by derekhe** [comment]
Please follow the instruction here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/License

**Comment by derekhe** [comment]
If buymeacoffee doesn't work, you can use paypal. After your payment, give me the transaction id and I will unlock you.

**Comment by rscarter043** [comment]
I have tried this repeatedly.  It will not take me to a page to pay via Paypal or BuyMeACoffee.

**Comment by derekhe** [comment]
Ok, maybe the browser block you to a new window or tab?
You can try the following url:
* https://www.buymeacoffee.com/derekhe
* https://www.paypal.com/paypalme/siconghe?country.x=C2&locale.x=en_US

**Comment by rscarter043** [comment]
Richard Carter, here's your receipt.
Hello, Richard Carter
[PayPal]


You sent $30.00 USD to 贺思聪


YOUR NOTE TO 贺思聪

[quote]

Map Enhancement
[quote]


Transaction Details

Transaction ID
75B74846KU906053H<https://www.paypal.com/cgp/app-redirect?intent=txn_details&src=RT000417_txn_id&ref_id=75B74846KU906053H&v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>
Transaction date
June 17, 2023

________________________________

Money sent
$30.00 USD


Paid with:

MASTER_CARD x-1727
$30.00 USD


This transaction will appear on your statement as PAYPAL *HESICONG

________________________________

You paid
$30.00 USD

贺思聪 will receive
$30.00 USD

________________________________


Shipping Address


555 Oak Street
Indiana, PA 15701
United States

________________________________


Please note it may take a little while for this payment to appear in the Activity section of your account.

Get the Details<https://www.paypal.com/us/cgp/app-redirect?intent=summary&src=get_the_details&v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>

________________________________

________________________________
[PayPal]
________________________________

Help & Contact<https://www.paypal.com/us/smarthelp/home?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817> | Security<https://www.paypal.com/us/webapps/mpp/paypal-safety-and-security?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817> | Apps<https://www.paypal.com/us/webapps/mpp/mobile-apps?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>
[Twitter]<https://twitter.com/PayPal?v=1%2C0.1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>
[Instagram]<https://www.instagram.com/paypal/?v=1%2C0.1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>
[Facebook]<https://www.facebook.com/PayPalUSA?v=1%2C0.1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>
[LinkedIn]<http://www.linkedin.com/company/1482?trk=tyah&v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>


PayPal is committed to preventing fraudulent emails. Emails from PayPal will always contain your full name. Learn to identify phishing<https://www.paypal.com/us/webapps/mpp/security/suspicious-activity?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>


Please don't reply to this email. To get in touch with us, click Help & Contact<https://www.paypal.com/selfhelp/home?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>.


PayPal Customer Service can be reached at 888-221-1161.


Not sure why you received this email? Learn more<https://www.paypal.com/us/smarthelp/article/why-am-i-receiving-emails-from-paypal-when-i-dont-have-an-account-faq4172?v=1&utm_source=unp&utm_medium=email&utm_campaign=RT000417&utm_unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&ppid=RT000417&cnac=US&rsta=en_US%28en-US%29&cust=4LRBW26QPUFSU&unptid=e50711d6-0d1f-11ee-8332-3cfdfef04c7d&calc=f6627634d502a&unp_tpcid=sendmoney-push-sender&page=main%3Aemail%3ART000417&pgrp=main%3Aemail&e=cl&mchn=em&s=ci&mail=sys&appVersion=1.178.0&xt=104038%2C124817>

Copyright © 1999-2023 PayPal, Inc. All rights reserved. PayPal is located at 2211 N. First St., San Jose, CA 95131.

PayPal RT000417:en_US(en-US):1.6.0:f6627634d502a

**Comment by derekhe** [comment]
Unblocked please try. And I will delete this ticket as it contains personal information.
