### ISSUE TITLE
Memory leak? Processor hogging problem.

### ISSUE THREAD

**Issue by RealDrJester** [derekhe/msfs2020-map-enhancement#419]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - Steam
 - MSFS2020 Version: 1.33.8
**Mod version:**
- 7.2.1

**Device ID**
- PBXN469SQKYFPFYGM9XXKVFTV15QR3TSP66F010960N5JBZMR670

**Log**
- Unsure where the log is.

**Screenshots**

**Additional context**

After flying through Europe, from Dublin to Leipzig, the Leipzig to Dublin, without closing the simulator and the program will cause a processor hog after more than an hour of use. To the point it will consume so many cycles that the temperature will increase from normal 60/65C to 72C and eventually 82C, and cause massive stuttering in the game, other programs running in the background to actual freezes which would last over 3 seconds. The solution was to close the map enhancement program, and all returned to normal, with no stuttering or freezes.  This problem was not present in the previous versions. 

Summary: After more than an hour or 2 hours of use, Map Enhancement program will consume so many processor cycles that everything will crawl and increase temperature.

**Comment by derekhe** [comment]
Please try to capture the CPU usage for this app.
And what's your CPU?

**Comment by RealDrJester** [comment]
How do one capture CPU usage on this? 
All I could do was check the task manager and it was around 15% to 30% whenever it I saw the freezing/stuttering. 

i7 9700k 3.6GHZ clocked at 4.9Ghz.

**Comment by derekhe** [comment]
Please check your CPU's cooling and the actual frequency (use HWINFO64). I see someone has colling issue and the cpu goes lower to 1.1G because of the heating and the whole system get stuck.
