### ISSUE TITLE
Only loading 1 image replacement

### ISSUE THREAD

**Issue by SloppyPancake66** [derekhe/msfs2020-map-enhancement#42]
I open and run the map replacer, and it only shows one image.  Is it supposed to look like that? Could it possibly be my end?  I uninstalled and reinstalled it a couple times and that did not seem to fix the issue.  I can also paste a log dump if anyone would like to take a look at that.
![image](https://user-images.githubusercontent.com/68626417/151688414-55cf863c-202b-4ba0-ba9e-cc6e0b99d45c.png)

**Comment by SloppyPancake66** [comment]
It is now having an issue with the Image Server Access.  it just seemed to stop working a few minutes ago.

**Comment by derekhe** [comment]
Please provide these information:
**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Comment by SloppyPancake66** [comment]
Version - Steam
Please explain what you mean By 'version' is that game version, app version, or something else entirely
Main - [main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965390/main.log)
Main, Old - [main.old.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965394/main.old.log)
Renderer - [renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965395/renderer.log)

**Comment by derekhe** [comment]
Game version

**Comment by derekhe** [comment]
Please also give the logs in :  (INSTALLATION PATH)\resources\extra\nginx\logs

**Comment by SloppyPancake66** [comment]
I'm not sure what version I have, other than whatever the current updated version of msfs is, and its GOTY edition, if that matters. [error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965403/error.log)

**Comment by derekhe** [comment]
Please give me all nginx logs, not the error.log one

**Comment by SloppyPancake66** [comment]
It only allowed me to paste the one error log

**Comment by SloppyPancake66** [comment]
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965409/khstore-access.log)
This is the only other one it will let me paste right now

**Comment by SloppyPancake66** [comment]
Most of them are just blank text documents anyways, I have no idea why

**Comment by SloppyPancake66** [comment]
They seem to have updated after I started my sim.  Heres all the ones it will let me paste
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965420/khstore-access.log)
[localgoogle-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965421/localgoogle-access.log)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965422/virtualearth-access.log)

**Comment by derekhe** [comment]
Please try restart the mod (maybe restart computer) and run it agian.

**Comment by SloppyPancake66** [comment]
Redownloaded it onto another drive
restarted mod, (force quit, then open as administrator)
Restarted computer
None of these seemed to do anything

**Comment by derekhe** [comment]
Please try latest version

**Comment by SloppyPancake66** [comment]
Uninstalling and reinstalling the latest updated version has not fixed it for me

**Comment by SloppyPancake66** [comment]
It is successfully connecting to both servers, however it is having a problem like the original post issue.  It will only show 1 image replaced.  it is also interacting with my sim in a way that is strange, it turns of the photogrammetry and defaults to the MSFS gross look.
IMAGE - [image](https://user-images.githubusercontent.com/68626417/151731612-5e6ca6b5-5162-4852-9a29-4dfadcb058a6.png)
Steam Version, 1.21.18.0
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967662/main.log)
[main.old.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967666/main.old.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967669/renderer.log)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967671/error.log)
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967672/khstore-access.log)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967675/virtualearth-access.log)

**Comment by derekhe** [comment]
Good to know.

**Comment by zhang-zeyu** [comment]
@SloppyPancake66 Hi I have save issue with you, can you please tell me how to solve this?
