### ISSUE TITLE
my 20gb cache no longer work

### ISSUE THREAD

**Issue by eydrianf** [derekhe/msfs2020-map-enhancement#421]
was the cache format change? i cannot get my 20gb cache working it show 0mb

i reverted back to 7.20

**Comment by eydrianf** [comment]
it took months to cache all my location, why make an update that changes the cache? i can skip google limitation with the cache

**Comment by derekhe** [comment]
Sorry I upgrade the structure of the cache file to support rolling cache. I can't make it compatible with old version at the moment.

**Comment by eydrianf** [comment]
I derek,

understood, can you make an option for users in future release that uses the old cache and dont want the rolling and has over 20GB of data which help bypass google limitation after long flights where google limits me from downloading?

it would be great if not i would need to redo it and may get limited again :(

Please consider this.

**Comment by derekhe** [comment]
Hmm, making two caches together will confuse other people as well. The intention of the cache is for cache data for faster loading next time, not bypass some limitation (although few people doing this).

**Comment by N754DW** [comment]
version 7.2.2

Every time I start the program the cache is showing that it is back to zero. Is that correct?

**Comment by derekhe** [comment]
I think it should be a bug. Let me have a look later.

**Comment by N754DW** [comment]
> I think it should be a bug. Let me have a look later.

I think it might be that the program says the cache is at 0Mb at startup, but then shows the correct value after it does the first write. I'm still checking.

**Comment by derekhe** [comment]
> > I think it should be a bug. Let me have a look later.
> 
> I think it might be that the program says the cache is at 0MB at startup, but then shows the correct value after it does the first write. I'm still checking.
> 
> EDIT: Confirmed, shows 0MB in cache until sim gets to main start screen, then the cache size updates to the correct value.

Has been fixed in 7.2.3
