### ISSUE TITLE
Late Image loading 

### ISSUE THREAD

**Issue by clemi048** [derekhe/msfs2020-map-enhancement#423]
**Describe the bug**

Hey, 
just wann know if there are any solutions to reduce image loading times as sometimes images need me to pass right above them to load into the sim.

**MSFS version: 1.33.8.0**
 - msstore 

**Mod version:**
- Mod version 7.2.2
- Bing maps (latest)

**Device ID**
- 3J32XYC8MPT9C4W8EG8VVTAVK3HT651B52M2B84T9T5VW4NFT6P0

**Log**
- Please attach the log zip file 
- 
[logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/11857835/logs.zip)

**Screenshots**

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/137645225/3cb3fe12-d7e8-45d8-9ab2-07e657d7b593)

**Comment by derekhe** [comment]
Sorry I don't know what you mean, could you clarify?
