### ISSUE TITLE
Cache size

### ISSUE THREAD

**Issue by alanbeasy** [derekhe/msfs2020-map-enhancement#424]
I am wondering if this is normal.
I have my Cache path set for D: Drive
![Path](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/6959b52f-fb58-42a4-9b8a-9c2b957ea019)

The cache size in my location is about 3.5GB
![Cache Database Folder](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/405ca552-6687-44a1-8b7b-30e72a19fdcd)
That is OK because the location is plenty big enough for the cache to be any size.
It keeps growing OK each time I fly

What I do not understand is why the main Enhancement window shows the cache size always smaller than the size in the location?
![Map Enhance](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/b1cac9b8-3899-448b-b082-1a3552392e14)

 - MSFS2020 latest Version
 -  - msstore

- Device ID Y8YBCKYV2TY3D1KKETYKYQ7AAYZ795ZDHWRSYC18TG7K50Q8YFGG

**Log**

[log20230625.txt](https://github.com/derekhe/msfs2020-map-enhancement/files/11858943/log20230625.txt)

**Comment by derekhe** [comment]
Thanks for the reporting, I will have a look. Now it calculates how much "real content" inside the cache because considering the rolling cache scenario, for example, you set the limitation to 10G, even the disk cache file is 10G, inside the cache it may not occupy 10G space.

**Comment by alanbeasy** [comment]
I think I understand.  I was watching both while I was flying.
Both the cache size and the size shown by the map window were increasing.

They seem to be increasing about the same amount so I was wondering if the
extra 1000mb on the cache became invisible (junk) to the program.

I would hope it would be stable so that once we have downloaded several GB
images we do not have to start again.

**Comment by derekhe** [comment]
I think I will add some cache management functional and offline caching is still in progress. So, you can share the cache with others. (Not promised and it is low priority for me at the moment)

**Comment by alanbeasy** [comment]
Ok, thanks.
