### ISSUE TITLE
Google maps stuck

### ISSUE THREAD

**Issue by github23128998** [derekhe/msfs2020-map-enhancement#425]
**Describe the bug**

even when I don't start the app the google map mod is running

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]
 - steam version

**Mod version:**
- Mod version
- latest from flightsim.to

**Device ID**
- Device ID

**Log**
- Please attach the log zip file 

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by andymp425** [comment]
I have the same problem.... any help?

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#the-mod-damaged-my-msfs2020-and-msfs2020-cant-load-any-images
