### ISSUE TITLE
Slow loading maps (normal and enhanced)

### ISSUE THREAD

**Issue by eydrianf** [derekhe/msfs2020-map-enhancement#426]
Hi,

I noticed slow loading of maps when doing long flights over lands, switching back and forward to normal and enhanced sometime works.

Iam using google maps image server pro 1

Any tips?

**Comment by eydrianf** [comment]
Any future improvement?

And whats the limit google normal limit the connection?

**Comment by derekhe** [comment]
I have no idea about this problem. I think it related to internet access
problem. I don’t know the limitations of google maps and I never meet it.
Perhaps it is because of I am using vpn to access google

eydrianf ***@***.***>于2023年7月11日 周二13:59写道：

**Comment by aaronleaver** [comment]
how do i go about getting google maps to work with msfs and where to find ip address

**Comment by Bodenseeler742** [comment]
Is this a fake?

 

Von: aaronleaver ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 16:03
An: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [derekhe/msfs2020-map-enhancement] Slow loading maps (normal and enhanced) (Issue #426)

 

how do i go about getting google maps to work with msfs and where to find ip address

**Comment by Bodenseeler742** [comment]
I want support by your side mot more questions

 

Von: aaronleaver ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 16:03
An: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [derekhe/msfs2020-map-enhancement] Slow loading maps (normal and enhanced) (Issue #426)

 

how do i go about getting google maps to work with msfs and where to find ip address

**Comment by Bodenseeler742** [comment]
When you can´t support ? please send my money back

 

Von: aaronleaver ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 16:03
An: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [derekhe/msfs2020-map-enhancement] Slow loading maps (normal and enhanced) (Issue #426)

 

how do i go about getting google maps to work with msfs and where to find ip address
