### ISSUE TITLE
Can't pass the image access check

### ISSUE THREAD

**Issue by bdomi2** [derekhe/msfs2020-map-enhancement#43]
After updating to v3.1.0 I can't pass the image access check. It does pass the Nginx server access check. I have checked that the program is allowed through firewall and is run as administrator. I have also tried different servers.

 - MSFS2020 version: [msstore]
 - MSFS2020 Version [1.21.18.0]

Log

[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965434/renderer.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965432/main.log)
[main.old.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965433/main.old.log)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965435/error.log)

**Comment by bdomi2** [comment]
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965438/virtualearth-access.log)

**Comment by bdomi2** [comment]
[localgoogle-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965439/localgoogle-access.log)
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965440/khstore-access.log)

**Comment by aurelbdx** [comment]
Same problem for me
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7965503/renderer.log)

**Comment by derekhe** [comment]
Please try latest version

**Comment by AntonioSanm** [comment]
same here with v3.1.1
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966390/renderer.log)

**Comment by Kram747** [comment]
same here with v3.1.1 no change with system or software

**Comment by Kram747** [comment]
reloaded 3.0.8.0 works ok :)))
on shutdown updates exe to  3.1.1.0 then the image access check fails :(((

**Comment by assassin349** [comment]
I had some problems initially with 3.1.1 and eventually got mine to work. I went to the "Cache" tab, hit "Clear Cache," and then hit "Reset to Default." Then, I went to C:\Windows\System32\drivers\etc and deleted the hosts file (make sure you also delete it from your Recycle Bin in Windows).

**Comment by Kram747** [comment]
> I had some problems initially with 3.1.1 and eventually got 3.1.1 to work. I went to the "Cache" tab, hit "Clear Cache," and then hit "Reset to Default." Then, I went to C:\Windows\System32\drivers\etc and deleted the hosts file (make sure you also delete it from your Recycle Bin in Windows)

Tried this fix still getting  image access check fails
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967113/error.l

[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7967118/khstore-access.log)

**Comment by bdomi2** [comment]
3.1.1 update has fixed the issue for me so far.

**Comment by derekhe** [comment]
Please all upgrade to latest 3.2.1, will close this now.
