### ISSUE TITLE
Any way to get it working with Wine / Proton ?

### ISSUE THREAD

**Issue by Sh33n** [derekhe/msfs2020-map-enhancement#430]
Backend server not starting
Detail : Error : Reached Max Retry

**MSFS version:Steam, latest**

**Mod version:7.2.2**

**Log (proton.log)**

**Additional context**

I'm playing MSFS2020 on steam Linux using Proton Experimental, it works great.
I've been able to install msfs2020-map-enhancement into my wineprefix
When I start the program : Backend server not starting

I'm not using port 443 or 42098.
Proton is using admin account.
I can reach Google maps (no need vpn).

I know your program is designed for Windows, maybe you'll have an idea, it would be great ;)

Hardware : Ryzen 5900X / GTX 3070Ti / 32 Gb / Archlinux 

[proton.log](https://github.com/derekhe/msfs2020-map-enhancement/files/11987071/proton.log)

**Comment by derekhe** [comment]
Sorry I have no idea about this. I don't think the app can run in a wine environment because it depends on a lot of win 10 dependencies.

**Comment by Sh33n** [comment]
Thanks for your reply.
I'll update this post if I find something.
