### ISSUE TITLE
How to uninstall / revert to default msfs bing maps?

### ISSUE THREAD

**Issue by andymp425** [derekhe/msfs2020-map-enhancement#431]
I am not pleased with the mod and would like to have defaul msfs bing maps back. but even after uninstalling, clearing my cache, re signing into xbox live account, switching offline and back online, even resetting my windows 11 system did not help. I still get google maps injected into the sim. airports and scenery not loading in correctly.m this mod broke my flight sim. in some spaces there are no buildings at all... pls help

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#the-mod-damaged-my-msfs2020-and-msfs2020-cant-load-any-images
