### ISSUE TITLE
Bug on the world map screen

### ISSUE THREAD

**Issue by YBau** [derekhe/msfs2020-map-enhancement#433]
**Describe the bug**
Hello,
At a given zoom, on the the world map, the pictures do not match terrain (see the screenshot, I'm obver Canada but I can see South-America, Africa in the right corner and Antartica instead of mexico. This bug disappear if I zoom in, and partially disappear if I zoom out (South America doesn't disappears but other tiles does). 

**MSFS version:**
 - msstore
 - MSFS2020 Version : latest ?

**Mod version:**
- 7.2.2

**Device ID**
- 53KE6XBNPGCJF9KSVV15Q0DWW9ABJ1HEE0HMY05E0P8JYRMJMHA0

**Log**
[log20230711.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/12016687/log20230711.zip)

**Screenshots**

![Capture d'écran 2023-07-11 175543](https://github.com/derekhe/msfs2020-map-enhancement/assets/105671765/10cbf074-77d2-4dea-ba82-36666ead630f)

**Comment by derekhe** [comment]
Yes, I see this bug and wondering why and how to fix it :)

**Comment by derekhe** [comment]
Fixed in 7.2.3
