### ISSUE TITLE
Map Enjancement 7.22.2 Pro Issue

### ISSUE THREAD

**Issue by Bodenseeler742** [derekhe/msfs2020-map-enhancement#434]
**Describe the bug**
cant start Pro Version
Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore
 - MSFS2020 Version [e.g. 22]
1.33.8.0
**Mod version:**
7.22.2 (Pro)

**Device ID**
GT6G63V9Z55E2FFQ3GBDT6J0NKRZZ6GRQ0X05KW9XRQNGB75GBKG

**Log**
WHERE CAN I FIND IT?

**Screenshots**
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/58629703/090facdf-cf0d-4b04-9399-0f06b255f24f)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
once had run. now it doesn´t anymore- I become very angry

**Comment by Bodenseeler742** [comment]
when can i expect with an solution for my problem?

**Comment by harutoshinakagawa** [comment]
Even if mapenhancement ver7.2.2 starts, it ends immediately.
I checked the task manager and it's not running.

windows 10 home 64bit 
MSF ver 1.33.8.0 

![Image3](https://github.com/derekhe/msfs2020-map-enhancement/assets/95943716/fc4d6aad-0ac6-4b34-b573-8242d9a18bfa)
![Image1](https://github.com/derekhe/msfs2020-map-enhancement/assets/95943716/699c381d-4462-47a6-85c5-4dcff9162965)
![Image2](https://github.com/derekhe/msfs2020-map-enhancement/assets/95943716/ebd8cec9-d4f9-47ea-b43e-cfb8d5410a76)

**Comment by aaronleaver** [comment]
how do i get the google ip adress from got no clue as i want to get the google server 2 pro
Device ID E7VW7AM8EKVHRPYWF6XNHV1FEFNTDWV248ES13ZW2YVRTJW573CG

**Comment by Bodenseeler742** [comment]
I have still nor idea how to solve

I hvae  only idea my host file is damaged…

How can i repair it ?

 

Von: aaronleaver ***@***.***> 
Gesendet: Donnerstag, 13. Juli 2023 15:59
An: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: Bodenseeler742 ***@***.***>; Author ***@***.***>
Betreff: Re: [derekhe/msfs2020-map-enhancement] Map Enjancement 7.22.2 Pro Issue (Issue #434)

 

how do i get the google ip adress from got no clue as i want to get the google server 2 pro
Device ID E7VW7AM8EKVHRPYWF6XNHV1FEFNTDWV248ES13ZW2YVRTJW573CG

**Comment by aaronleaver** [comment]
Ok cheers

**Comment by harutoshinakagawa** [comment]
> ここに FAQ ページがあり、今後の解決策を見つけてください: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ

この回答はかなり失礼です。質問する時は同様の問題がないか調べてから質問します。
安易な回答は止めてください。
私の場合の原因を調べるよう方法はないでしょうか。
MapEnhancementが起動して、直ぐに、終了してしまうのは使用して２年近くなりますが、
初めての現象です。
誠意のある対応お願いいたします。

**Comment by derekhe** [comment]
> 

The solution is in the FAQ page, and you had to fix it by yourself. If you don't like this and please write an email and your payment detail to hesicong at gmail.com for refund.

**Comment by derekhe** [comment]
> 



> > ここに FAQ ページがあり、今後の解決策を見つけてください: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ以下是常见问题解答页面，用于查找将来的解决方案：https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ
> 
> この回答はかなり失礼です。質問する時は同様の問題がないか調べてから質問します。这个答案很粗鲁。 提问时，请在提问前检查是否有类似问题。 安易な回答は止めてください。  请停止给出简单的答案。 私の場合の原因を調べるよう方法はないでしょうか。 有什么方法可以找出我的情况的原因吗？ MapEnhancementが起動して、直ぐに、終了してしまうのは使用して２年近くなりますが、 自MapEnhancement开始并立即结束以来已经快2年了。 初めての現象です。  这是第一次发生这种情况。 誠意のある対応お願いいたします。  请真诚回复。

You can try run the application in the command prompt (cmd.exe) and see if there is any output, the correct output should like:
<img width="814" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/44185e8c-1d2f-4b61-b601-80c1e36a982b">

**Comment by harutoshinakagawa** [comment]
MapEnhancement正常に起動しました。ありがとうございます。失礼をお詫びいたします。これからも長いお付き合い、お願いいたします。Sapporo,Japan

**Comment by harutoshinakagawa** [comment]
先日は勝手なことを言ってすいませんでした。GoogleEarthが表示されないとどうしてもイライラ。
それとCommandpromptは知識不足で、理解できませんでした。
ver7.2.3になってMapEnhancementがBackgrundで動いていますが、これはただしいのですか？
それとも、私だけの状態でしょうか？Googleの画像表示は通常だと思います。
実行時のTaskManegerの画像を添付いたします。
![taskmaneger_01](https://github.com/derekhe/msfs2020-map-enhancement/assets/95943716/9a4ce729-5afa-43cd-9177-8edc5b1f7398)
![taskmaneger_02](https://github.com/derekhe/msfs2020-map-enhancement/assets/95943716/175a538f-a8ca-43bc-9966-f5521523f948)
