### ISSUE TITLE
software says tiles are loading but all terrain is dark grey

### ISSUE THREAD

**Issue by emt3072** [derekhe/msfs2020-map-enhancement#437]
software says tiles are loading but all terrain is dark grey.
I have emptied cache. used only msfs cache and tried only the app cache and its still has not loaded tiles. if reset the game restarted come computer an no change.

7.2.3pro
 steam
 - MSFS2020 Version 1.33.8.0

**Comment by derekhe** [comment]
Please check this: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#ground-is-blury
