### ISSUE TITLE
Textured loaded in HGS in PMDG

### ISSUE THREAD

**Issue by Crudelis98** [derekhe/msfs2020-map-enhancement#439]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore 
 - MSFS2020 Version [latest]

**Mod version:**
- 7.22.3 (latest)

**Device ID**
- pref not to share right now

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible
-
**Additional context**
One tile of map is loaded in place of HGS in plane PMDG, it looks like minimap instead of HGS.

**Comment by derekhe** [comment]
Any more detail?
