### ISSUE TITLE
Stutters and sound bugs when using the mod

### ISSUE THREAD

**Issue by Patlezinc** [derekhe/msfs2020-map-enhancement#44]
**Describe the bug**
Stutters and sound bugs when using the mod, while loading pictures of the terrain

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: last one

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

Happens with all the servers (google and new Bing). Related to pictures loading. Sound and stutter issues happening while loading earth map (while zooming) or ingame when loading terrain textures. No happening with default bing.
Sound issue is generation of "parasite" sounds.
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966197/khstore-access.log)
[localgoogle-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966198/localgoogle-access.log)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966199/virtualearth-access.log)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966200/error.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966190/main.log)
[main.old.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966191/main.old.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7966192/renderer.log)

**Comment by derekhe** [comment]
I see the traffic is good. What's your PC's configuration?

**Comment by Patlezinc** [comment]
I5 11600K with a 3060 Ti and 32 GB of DDR4. Only SSD. I guess I am fine on this side 😅.
Do you want a video?

**Comment by Patlezinc** [comment]
I have made some tests and it seems that terrain detail (terrain lod) is implicated (the one going up to 400). I usually use 350 with Bing but seems too high with GoogleMaps. 250 is better. What value are you using?

**Comment by derekhe** [comment]
Will close this as it not realted to this mod. I use 350 which is good. 400 is tough for 3070.
