### ISSUE TITLE
Trouble signing into FlightSim.to

### ISSUE THREAD

**Issue by hrosenson** [derekhe/msfs2020-map-enhancement#442]
This may be logged already but can't find the report.   In the last week or two, I'm having trouble signing into Flighsim.to.  Keep getting SKIP and NEXT messages.  Even if I get a VERIFY request, screen will flip to NEXT.  Anyone else having this recent issue with Flightsim.to?

**Comment by derekhe** [comment]
Hello, I think this is for my product's discussion not for Flightsim.to so I closed this.
