### ISSUE TITLE
After updating to newest version of mod, I can't play with the mod

### ISSUE THREAD

**Issue by DylanDevelops** [derekhe/msfs2020-map-enhancement#444]
**Describe the bug**

Since updating the mod to 7.3.0, It throws this error when trying to launch msfs2020 or sometimes like in this case, just botting up the software.

**MSFS version:**
 - steam
 - Most recent version of msfs2020

**Mod version:**
- 7.3.0

**Device ID**
I can't get to it because of the error.

**Screenshots**

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/48571264/62a77356-2bfa-4b3b-9db2-7f7b312901bf)

**Comment by derekhe** [comment]
Please try previous version and see if it works. 7.3.0 doesn't change too much compare to 7.2.x

**Comment by harutoshinakagawa** [comment]
先日は大変失礼いたしました。よく理解できていませんが、7.3.0にしてからTextureの描画速度が、各段に向上しました。
今迄で最高の描画速度です。MapEnhancementはBackGrundで動いていますが、正しい動作ですね。
PC性能が大幅にアップしたようようで非常に快適です。ニューヨークも見違えるように綺麗になりました。
本当にありがとうございました。
