### ISSUE TITLE
Not sure if I am doing something wrong here but...

### ISSUE THREAD

**Issue by TK14188** [derekhe/msfs2020-map-enhancement#445]
Please describe the bug in detail to help me understand the scenario

 - steam
 - MSFS2020 Version 1.33.8.0

**Mod version:**
- Mod version 7.3.0

**Device ID**
VBBZEAGXRJ9M8V83VYZ6TXPQ2SH6CYBHERFBMJ5KXSMHY4Z85X50

**Screenshots**

(https://github.com/derekhe/msfs2020-map-enhancement/assets/141183761/9f3378ae-ae80-4b4c-935a-0022c55b8383)

**Additional context**

Sooo, it is showing like it is loading a bunch of stuff via the screenshot I am showing. But the area I am testing it on, shows nothing?  Nothing looks any different than before I installed the mod.  Correct me if I am not understanding but this should be pulling images from google maps/earth... but it does not appear to be pulling data thats at least any newer than bing was?  Nothing looks any different.

**Comment by derekhe** [comment]
Hi, this mod needs special care about it, please find it out here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ

Make sure you done everything for setup check.

**Comment by TK14188** [comment]
I did though. I've verified all of this. I guess what I need to verify is
this.  Say I find my house. I can see my driveway. And it has a boat in it.
That means the data being pulled is at LEAST 10 years old.  But if I get on
Bing or Google it currently shows my car in the drive way. Which is what
makes me think it's not showing up to date?
