### ISSUE TITLE
Photogrammetry does not fully load and looks blurry/melted when the mod's cache is enabled

### ISSUE THREAD

**Issue by tylertran349** [derekhe/msfs2020-map-enhancement#446]
**Describe the bug**

When the mod's cache is enabled (my in-game rolling and manual caches are both disabled), most of the time, photogrammetry does not load fully, resulting in blurry and melted photogrammetry. When the mod's cache is disabled, photogrammetry loads normally and looks normal. Is there any way to fix this?

**MSFS version:**
 - Steam
 - MSFS2020 Version 1.33.8.0

**Mod version:**
- 7.3.0

**Device ID**
- 0B5HM7400QYQCQKMNXCZ2V7E8204KJB3A6W12QJF56GJJ7NVMVF0

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
I have high LOD enabled. I am using Bing Maps in the mod.

**Comment by derekhe** [comment]
Do you put the cache into a SSD or HDD? HDD is very slow and will cause this issue.

**Comment by derekhe** [comment]
Also I will optimize the photogrammetry cache in future

**Comment by tylertran349** [comment]
I use a Samsung 980 NVMe SSD for the cache.

**Comment by tylertran349** [comment]
> Do you put the cache into a SSD or HDD? HDD is very slow and will cause this issue.

I use a Samsung 980 NVMe SSD for the cache.

**Comment by derekhe** [comment]
Please try set the network setting to "Normal" instead of "Enhanced"

**Comment by Aseinsha** [comment]
I also have this issue, before I use to set the cache to my NAS but starting few months ago, it didn't like that, so I put it on my NVME SSD, but now even that's not good enough (using HIGH LOD) so I've had to disable cache mode entirely unfortunately.

**Comment by EricFlight** [comment]
Same issue here with 7.3.1

Cache file is on my fastest SSD drive. Tried normal and enhanced...still loads blurry and slow

**Comment by derekhe** [comment]
> Same issue here with 7.3.1
> 
> Cache file is on my fastest SSD drive. Tried normal and enhanced...still loads blurry and slow
> 
> Cache size shows full sizes and then 0MB back and forth. Sometimes only shows part of the Cache Size (about 1/2 of it)
> 
> If I don't enable the cache it loads everything fine.

Please give me your device id

**Comment by EricFlight** [comment]
> > Same issue here with 7.3.1
> > Cache file is on my fastest SSD drive. Tried normal and enhanced...still loads blurry and slow
> > Cache size shows full sizes and then 0MB back and forth. Sometimes only shows part of the Cache Size (about 1/2 of it)
> > If I don't enable the cache it loads everything fine.
> 
> Please give me your device id

Device ID is NRFD3ZHV2RY47DE48AX9JNVXNJAY3G9FTJQDCMQA91RZH8A3H5Y0

**Comment by EricFlight** [comment]
Trying 7.3.4 right now with cache enabled...will report back findings

Device ID is NRFD3ZHV2RY47DE48AX9JNVXNJAY3G9FTJQDCMQA91RZH8A3H5Y0

**Comment by derekhe** [comment]
I tried yesterday flying one hour without issue,please also have a try&nbsp;





------------------ Original ------------------
From: mnpostema32 ***@***.***&gt;
Date: Fri,Oct 13,2023 9:57 AM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Photogrammetry does not fullyload and looks blurry/melted when the mod's cache is enabled (Issue #446)





 
Trying 7.3.4 right now with cache enabled...will report back findings
 
Device ID is NRFD3ZHV2RY47DE48AX9JNVXNJAY3G9FTJQDCMQA91RZH8A3H5Y0
