### ISSUE TITLE
slow loading (bing latest)

### ISSUE THREAD

**Issue by eydrianf** [derekhe/msfs2020-map-enhancement#448]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
steam
 - MSFS2020 latest version

**Mod version:**
- latest version

**Screenshots**

https://ibb.co/yPmktYp
https://ibb.co/mSyZBMJ

Please provide me screenshots for the mod and msfs2020 if possible

Bing latest is super slow when loading images, can this be look into or fixed?
check screenshot of issue.

I have 250MBPS internet super fast.

**Comment by derekhe** [comment]
Please check your network. And if you turned on the mod's cache and you put it into HDD, please turn it off.
