### ISSUE TITLE
GOOGLE MAPS IMAGE SERVER ACCES FAILED

### ISSUE THREAD

**Issue by pilotogZ** [derekhe/msfs2020-map-enhancement#45]
Hello I got an issue in Google Map Replacement... When I start it,Says Image Server Acces is failed here is an screenshot I hope i can fix [it
![Screenshot (29)](https://user-images.githubusercontent.com/94227146/151709176-53e131d3-a71a-4a8d-a59f-9f8319d381b7.png)
.

**Comment by assassin349** [comment]
I got mine to work (version 3.1.1). I went to the "Cache" tab, hit "Clear Cache," and then hit "Reset to Default." Then, I went to C:\Windows\System32\drivers\etc and deleted the hosts file (make sure you also delete it from your Recycle Bin in Windows).

**Comment by derekhe** [comment]
Yes, it was a cache location problem. Will close this.
