### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by Marius234987** [derekhe/msfs2020-map-enhancement#450]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam Yes
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version 7.3.0

**Device ID**
- Device ID 26XX376JK4DFR4WE0SE205EHNHYQPECMXM7ZZJ67G8SBN6CKW2A0

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Hello, a problem no longer works key why now different number but install new Windows 11 can not paid again paid 30$ 365 day paid twice and please help ?
greet Marius 🙁
![Bild_2023-08-13_141233436](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/1d6c1476-baba-4cbd-abb5-5e5b31c09450)

**Comment by derekhe** [comment]
Please request a new license here
https://appsmith.aiflygo.com/app/refresh-645f90d7f9a0567cd9600e30

Marius234987 ***@***.***>于2023年8月13日 周日20:13写道：

**Comment by Marius234987** [comment]
have already made but send 5 times. does not come SPAM

**Comment by Marius234987** [comment]
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/8fc90553-5bc3-476e-a422-8499841b758d)

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/142149809/1bedb230-4b3e-4b35-b41b-61cc12831589)

**Comment by Marius234987** [comment]
:(

**Comment by Marius234987** [comment]
I don't think it's good 👎 no answer already cheeky

**Comment by derekhe** [comment]
I think the problem already resolve, I will close this.
