### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by wyndsan** [derekhe/msfs2020-map-enhancement#452]
Trying to install the map enhancement that will allow me to use or try Google Maps instead of Bing. I get the image server test failed and it suggests trying three things:

1. Disable any global proxies. I checked and I have no proxies whatsoever.

2. Disable any game accelerator. In Windows 11 where I'm told that this switch should be it does not show up. Looking further I am told that if it does not show up this means your device does not support it and therefore that also does not apply.

3. Create a new host file. I did this also by moving the old host file restarting the computer so that it generated a new host files.

All of the above changed nothing and I'm still getting image server test failed. I get this whether I choose Google Maps or the new Bing maps, or any other map in the list. I would also add that I am running it as an administrator.

**Comment by derekhe** [comment]
Please check: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#hosts-file-issues

**Comment by wyndsan** [comment]
First of all thank you very much for responding. From what I have seen online I would dearly love to try this program.

If I am reading the FAQ correctly Host file issues are three items:

1. Damaged host file - I have deleted and recreated the host file multiple times. I then saw that the host file was actually empty so I went to Microsoft and followed their instructions to reset the host file to the default condition. That appeared to just leave it empty but also with a set of directions on how to modify it if one chose to do so.

2. Antivirus program - I have never had any problems opening the host file with a file management program. However I followed the instructions to disable my antivirus program (I use Windows defender) and then ran the program again.

3. Read only permission- I checked the host file properties and it is not set to read only.

In addition, one time the program even failed to load and when I pressed the reload button it gave me a longer list of things to attempt. Following those I uninstalled the program, redownloaded a fresh copy, and reinstalled the program. None of that has had any effect whatsoever and I still continue to get the same error message every time. As I've said having seen multiple youtube comparison shots I would really like to be able to have this mod.

Hoping maybe you have some additional suggestions. As a line from an old poem says "Hope Springs Eternal within the human heart. . ." and I hope I don't strike out.

**Comment by wyndsan** [comment]
Derek please don't leave me stranded now. After seeing examples of how MSFS looks using Google Maps instead of Bing, it just hurts now every time I fly. Please, is there no hope? Please let me know one way or the other so I can either finally succeed in using this mod or slit my wrists

**Comment by derekhe** [comment]
Please try "Bing (Latest)" first which is more stable. If it works, then your google access may be blocked. Please try different google servers.

**Comment by wyndsan** [comment]
Thanks for getting back to me. I had tried that previously, but I just now tried it twice again, and it gives me the same result. I'm starting to feel like the poster child for Einstein's definition of insanity - "When you try the same thing over and over again expecting a different result." Next?
