### ISSUE TITLE
Apply hosts change failed (See attached file)

### ISSUE THREAD

**Issue by Rencath** [derekhe/msfs2020-map-enhancement#453]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario
![Desktop Screenshot 2023 08 17 - 06 40 37 27](https://github.com/derekhe/msfs2020-map-enhancement/assets/130541895/17383659-a506-4efd-80e5-a075bca354f2)

**MSFS version:**
 - msstore 
 - MSFS2020 Version [e.g. 22] 1.33.8.0
![Desktop Screenshot 2023 08 17 - 06 40 37 27](https://github.com/derekhe/msfs2020-map-enhancement/assets/130541895/efa0e107-6c76-4497-b6b5-b0160a7a6749)

**Mod version:**
- Mod version 7.3.0

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
![Desktop Screenshot 2023 08 17 - 06 40 37 27](https://github.com/derekhe/msfs2020-map-enhancement/assets/130541895/712afd71-cf11-45e5-860f-a343353440f6)

**Comment by derekhe** [comment]
Please refer to :https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#hosts-file-issues
