### ISSUE TITLE
My device is blocked, i don't know why.

### ISSUE THREAD

**Issue by Kronle** [derekhe/msfs2020-map-enhancement#454]
**Deescribe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- 7.3.0

**Device ID**
- NT96SRDMF0J16157BPGTVXQKB4TQX4241EGAY84WPTR2HAFFG8BG
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/142589946/5cc40c9b-77c2-4411-a494-2764a3c04b27)

**Comment by derekhe** [comment]
Please contact me with your payment receipt: hesicong at gmail.com
