### ISSUE TITLE
Texture loaded in HGS in PMDG

### ISSUE THREAD

**Issue by GLF5** [derekhe/msfs2020-map-enhancement#460]
Hi, I use pmdg and when I use map mode, I get a problem with the HGS panel in pmdg If you don't use map mode, the problem will be solved, but there has been this problem for a long time Is there a possibility that it can be solved?
![ASDCV](https://github.com/derekhe/msfs2020-map-enhancement/assets/144322726/598d3193-b01f-45d6-82c1-e16055229115)

**Comment by derekhe** [comment]
The map is not provided by msfs so I cannot do anything for it

GLF5 ***@***.***>于2023年9月7日 周四09:57写道：
