### ISSUE TITLE
Magick- files in TEMP folder

### ISSUE THREAD

**Issue by Aseinsha** [derekhe/msfs2020-map-enhancement#461]
**Describe the bug**

When using the application with cache mod disabled, the application seems to be creating Magick-**** files in %temp% and not clearing these upon exist. 

**MSFS version:**
 - Steam
 - MSFS2020 Version 1.34.10.0

**Mod version:**
- 7.3.0

**Device ID**
- SK3F0RSTF58W1K50DN6RW999VVSBNMV16E57YBQ8HZX2P1W99RHG

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

I usually have to run del Magick-* on the %temp% directory after each flight, it would be great if this was added to the application so for example when clicking stop it would clear Magick-* files in temp.

**Comment by derekhe** [comment]
Sure i will have a look.

Aseinsha ***@***.***>于2023年9月9日 周六00:10写道：

**Comment by derekhe** [comment]
This shouldn't see now, please have a look.
