### ISSUE TITLE
Mod isn't working at all

### ISSUE THREAD

**Issue by gstotzem** [derekhe/msfs2020-map-enhancement#464]
**Describe the bug**

Everything was fine for a few days after installing and purchasing the pro version in August. Since about two weeks the mod does not work at all. Regardless of the selected map set and quality, no recognizable other textures are loaded. I have done all the checks and options listed in the FAQ (e.g. network mode, clear cache) without any improvement. After starting the app and activating it, 2 or 8 images are loaded and that's it. No change during further flight time, but also no error messages.

**MSFS version:**
 - msstore 
 - MSFS2020 Version [1.33.8.0]

**Mod version:**
- 7.3.0

**Device ID**
RKB1FYWMFAQMTFTXJNDP6G17V88KTADJKSTQRTM7BPTY95PPC1TG

**Screenshots**
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/96858901/e6a01b90-d9fc-419c-ac9a-e535cd81325c)
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/96858901/979c3f18-9bcf-4f61-ae7b-7d4d5d74f5ee)
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/96858901/1f9faacb-1738-4ab9-a4e2-fc170abd9b78)
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/96858901/b3f6aded-dada-428b-a028-1620885b8dbc)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Could you tell me what's exact the options you checked compared to the manual? https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#english-user-manual

**Comment by gstotzem** [comment]
Yes, sure.

 

I checked/verfied

 

*	BING Data World Graphics is ON
*	Rolling Cache is OFF
*	Status is ONLINE
*	Google.com/maps in browser, satellite images are loading without problems
*	Etc/hosts isn’t  read-only
*	Cleared the cache inside the mod
*	Tested with Setting „ Bing (latest)“
*	Changed network mode from „Enhanced“ to „Normal“ 
*	Tested with „normal LOD“ and „high LOD“

 

Von: hesicong ***@***.***> 
Gesendet: Montag, 18. September 2023 15:54
An: derekhe/msfs2020-map-enhancement ***@***.***>
Cc: gstotzem ***@***.***>; Author ***@***.***>
Betreff: Re: [derekhe/msfs2020-map-enhancement] Mod isn't working at all (Issue #464)

 

Could you tell me what's exact the options you checked compared to the manual? https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#english-user-manual

**Comment by gstotzem** [comment]
Problem solved!
I have a central ad blocker on my local network (pihole server) and the URL for downloading the images is blacklisted. I can't explain it 100% because it worked once for a few days and I definitely didn't make any changes to the blacklist.

![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/96858901/84f916bb-1161-4192-a599-a3dd6e5f479e)
