### ISSUE TITLE
Google map update

### ISSUE THREAD

**Issue by dakhir44** [derekhe/msfs2020-map-enhancement#467]
**Describe the bug*the Matterhorn mountain and older than on Google Earth

**MSFS version:**
 -  steam
 - MSFS2020

**Mod version:**
- Mod version 0
![Capture d’écran (1311)](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/9b6d4fe6-6827-4493-bf9e-de4cc7f304ec)

**Device ID**
- PC

Please provide me screenshots for the mod and msfs2020 if possible

**Comment by dakhir44** [comment]
I use Google Map Pro

**Comment by dakhir44** [comment]
Pourquoi le logiciel ne permet pas d'avoir des carte plus précis par exemple sur la photo ci dessus le pic de cervin, identique a google Heath? 

 Why doesn't the software allow you to have more precise maps, for example in the photo above, the Matterhorn peak, identical to Google Heath?

**Comment by derekhe** [comment]
Please switch to google server 2 to have a look. This server is always latest.

**Comment by dakhir44** [comment]
Hello I just started msfs to check with google map2, internet 880Mb/s reception
![Uploading Capture d’écran (1315).png…]()

**Comment by dakhir44** [comment]
![Capture d’écran (1317)](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/94c847e7-a655-4a00-8393-c3891f8fd8b1)

**Comment by dakhir44** [comment]
Hello I just started msfs to check with google map2, internet 880Mb/s reception

**Comment by dakhir44** [comment]
![Uploading Capture d’écran (1316).png…]()

**Comment by dakhir44** [comment]
![Capture d’écran (1318)](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/b84771cc-b1b9-4bc7-bbcb-651e5cc31a3e)

**Comment by dakhir44** [comment]
why don't you use Google EARTH instead of Google Maps?

**Comment by dakhir44** [comment]
![Capture d’écran (1319)](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/829438bc-be5d-40e2-b870-66ab69308600)

**Comment by derekhe** [comment]
Why you say the google earth is newer than google maps?
The date in google maps shows it is from 2021.

**Comment by dakhir44** [comment]
the colors are different![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/a24d9023-35d1-410e-ba56-ddf76502c8a5)

**Comment by dakhir44** [comment]
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/145918363/0460e059-92ef-4a4c-bd14-c5bd71c4ef62)

**Comment by dakhir44** [comment]
the first is Google Maps and the second is Google Earth

**Comment by dakhir44** [comment]
in msfs it displays the colors of google Map but not of google Earth, I looked with apple map there the colors correspond well.

**Comment by derekhe** [comment]
I checked this area again and the one you see in google earth is photogrammetry data, which is 3D scanned result and it is different from the one you see in google maps. I can't fix but you can switch to another map source to avoid this issue.

**Comment by dakhir44** [comment]
THANKS!
