### ISSUE TITLE
Photo Real Terrain is LOAD only a few miles around the aircraft

### ISSUE THREAD

**Issue by levelupsim** [derekhe/msfs2020-map-enhancement#469]
**Describe the bug**

I'm on the latest version and I'm using the mapbox server, i encountered the following bug (see photo below).
Photo Real Terrain is LOAD only a few miles around the aircraft during the entire flight.
The cache is enabled but it makes no difference.

**MSFS version:**
 - Steam
 - MSFS2020 Version [1.33.8.0]

**Mod version:**
- 7.3.1 Pro

**Device ID**
- ERQ55E15PMB2W1KZ3HGEN1WKD9F1HPSEYE99GW8QHT58QYRZXBK0

**Screenshots**
![Captura de tela 2023-09-26 022125](https://github.com/derekhe/msfs2020-map-enhancement/assets/81846255/6f865bff-8e06-4fad-a89b-b4434b138469)

**Additional context**

**Comment by derekhe** [comment]
Please adjust your terrian lod to above 250
Also make sure you have a good internet access

**Comment by levelupsim** [comment]
> Please adjust your terrian lod to above 250 Also make sure you have a good internet access

I play on ultra and my internet is a 750MB fiber optic link. I don't know what is causing this, but I will try other servers.
