### ISSUE TITLE
cache not loaded

### ISSUE THREAD

**Issue by AndyCYXU** [derekhe/msfs2020-map-enhancement#470]
**Describe the bug**
since newest version 7.3.1 every time i open the mod/app i have to go to settings and select cach file,, if not, on first page it always says cache file 0MB, when i choose the cach file then it loads and says xxx MB etc.
Please describe the bug in detail to help me understand the scenario
it is a new cache file so that is why it is so small

**MSFS version:**
msfs store version

**Mod version:**
- Mod version 7.3.1

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/1624627/796d7612-6fda-4a89-b870-39f6646469f1)

**Comment by derekhe** [comment]
I see there is a bug, will fix it

**Comment by AndyCYXU** [comment]
this is still broken, after starting app i need to go to settings (do nothing) go back to start and then start it, then it says it loads the cache file

**Comment by derekhe** [comment]
The cache bug is fixed in 7.4.0, please have a try.
