### ISSUE TITLE
Just got the pro version and not seeing any changes.. 

### ISSUE THREAD

**Issue by SunTiger81** [derekhe/msfs2020-map-enhancement#473]
I live in Miami, FL.  The default sim looks very good in this aera, but it not updated (old bing data I guess)  there are a few big buildings here that show not even up yet that are 5 - 8 years old.   Anyway,  I figured this would be a great mod as it would pull recent data from all the map options.

No change.

I deleted all cache and have it off.  I read everything in the FAQ and have it all setup the right way.   Why am I not seeing any changes?  If I go to any of the map sites and look at the same area, it looks updated like it should.  But, nothing makes it into the sim.

**Comment by derekhe** [comment]
If you switch maps and no difference, then it means your setup is incorrect.
