### ISSUE TITLE
Map Enhancement :Blocked does not work

### ISSUE THREAD

**Issue by welyy55** [derekhe/msfs2020-map-enhancement#476]
**Describe the bug**
Mr.derekhe 

1-Hello my friend, the Map Enhancement is still not working (it has not been working one week )

when running, with a message:  (Device is blocked)
I deleted the app and installed it more than once and it does not work either.. What is my problem and are there any solutions? I am a Pro subscriber.

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Map Enhancement 7.3.1

**Device ID**
TNBPJJKQK8Z14T7597D8D0ZX7929BRNH4SEPVQF32B0BN6MAQWVG
![paypal1](https://github.com/derekhe/msfs2020-map-enhancement/assets/72016889/673f3eff-97ca-47d7-9f24-5651b05dac8a)

**Screenshots**
![map enhancedment](https://github.com/derekhe/msfs2020-map-enhancement/assets/72016889/e15e3d6f-abe7-4aad-a8e6-25251696d385)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
It is good now.
