### ISSUE TITLE
Google Maps Server Problem

### ISSUE THREAD

**Issue by Boblate** [derekhe/msfs2020-map-enhancement#477]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
  steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
7.3.1

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible
This happens after pressing the Start button for Google Maps Server

**Additional context**
![Clipboard01](https://github.com/derekhe/msfs2020-map-enhancement/assets/147001848/917ad949-51e6-40b0-863d-44fa2442000e)

**Comment by derekhe** [comment]
Make sure you start with msfs2020 microsoft store version. If not, check the settings and switch to "Steam"
