### ISSUE TITLE
Mapbox Pro Image Server Test Failed

### ISSUE THREAD

**Issue by levelupsim** [derekhe/msfs2020-map-enhancement#480]
**Describe the bug**

Mapbox Pro Image Server Test Failed.

**MSFS version:**
 - Steam
 - 1.34.16.0

**Mod version:**
- 7.3.1 Pro

**Device ID**
- ERQ55E15PMB2W1KZ3HGEN1WKD9F1HPSEYE99GW8QHT58QYRZXBK0

**Screenshots**

![Screenshot_3](https://github.com/derekhe/msfs2020-map-enhancement/assets/81846255/656128ae-2fe4-40ad-a5e7-05d0510a9968)

**Additional context**

**Comment by levelupsim** [comment]
??

**Comment by levelupsim** [comment]
Can you answer me why I can't use MapBox Pro? I bought a license just to use this server and it simply doesn't work...

**Comment by derekhe** [comment]
Could you try other provider to test if your setup has trouble? Mapbox pro is working on my side, so please try other maps first.

**Comment by levelupsim** [comment]
All other servers work, only MapBox Pro has this problem.

**Comment by derekhe** [comment]
Please try now. I updated some tokens.

**Comment by derekhe** [comment]
Please try https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.3.4
