### ISSUE TITLE
Google map enhancement

### ISSUE THREAD

**Issue by bobbywhite1958** [derekhe/msfs2020-map-enhancement#483]
**Describe the bug**
Would like to delete
Please describe the bug in detail to help me understand the scenario

steam

Would like to delete this program, but don't know how

**Comment by derekhe** [comment]
Just uninstall it then

**Comment by bobbywhite1958** [comment]
Easier said than done.  Do you know the procedure or steps to uninstall?

**Comment by matthewvh** [comment]
If you go to your program files and select MSFS Map Enhancement, there's an option to uninstall
