### ISSUE TITLE
Reached Max try

### ISSUE THREAD

**Issue by matthewvh** [derekhe/msfs2020-map-enhancement#485]
Please describe the bug in detail to help me understand the scenario
This affects all versions but the one I have downloaded is 7.3.4. I have the 443 and 42098 ports only open for this program. I have whitelisted the application in the firewall and done multiple reinstalls but I keep getting this error. Any idea?

**MSFS version:**
 - Steam
 - MSFS2020 Version 1.34.16.0

**Mod version**
- 7.3.4

**Device ID**
- CVMXT3QMBPWV1JJZCXJ06MQP2DZX89DW77KYXXFTBR1FG2WY6CQ0

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/97539790/3fb94a42-c7e7-46c1-bfa8-38b6058970ad)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I will close this because it is already fixed.
