### ISSUE TITLE
Problem at Vienna airport

### ISSUE THREAD

**Issue by palwol7014** [derekhe/msfs2020-map-enhancement#486]
**Describe the bug**

When using this world modification. Part of the LOWW airport scenery is blurry, as if part of the area was not loaded into the server. The problem occurs regardless of whether Map Enhacment is used in the pro or free version. The dark line on the tarmac is caused by a default scenery error.

**MSFS version:**
 -  steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- 7.3.4

**Device ID**
- 1BPAGKM4YW3HJ1VEKVDFKK5CKN5AEXV1KH714QGYVG47EWVTY1F0

**Screenshots**
![Bez nazwy](https://github.com/derekhe/msfs2020-map-enhancement/assets/124891146/eaeb161c-9ef5-4043-a34d-a5ffeb84b028)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
This is caused by the photogrammetry data and I can't fix. Please have a look if you turn it off.
