### ISSUE TITLE
Ground textres

### ISSUE THREAD

**Issue by rob1183** [derekhe/msfs2020-map-enhancement#487]
**Describe the bug**
Ground texture remain blurry until after landing
Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore

**Mod version:**
latest

**Screenshots**
![map](https://github.com/derekhe/msfs2020-map-enhancement/assets/149868801/22414217-81e9-44c7-8482-18c95ba8bb30)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please try latest 7.4.0, see if it is fixed.
