### ISSUE TITLE
Image Server Test Failed 

### ISSUE THREAD

**Issue by cvandenberg01** [derekhe/msfs2020-map-enhancement#489]
**Describe the bug**

I am getting the error "Image Server Test Failed" when launching the program.  I usually use BING (latest) but none of the servers are working.  I don't use a proxy or antivirus, and it was working a couple of days ago.  Is there something I am missing?

**MSFS version:**
 - Steam
 - MSFS2020 Version 1.34.16.0

**Mod version:**
- Mod version 7.3.4

**Device ID**
- 108B1B9D-1B6A-4B14-9084-0CE81625A332

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
I looked in the FAQ and didn't see a solution, but I could be missing something.  Thanks for your help.  Chad Vandenberg

**Comment by derekhe** [comment]
Dif you fix it

**Comment by cvandenberg01** [comment]
Seems to have fixed itself.  I didn't have to do anything but now it works.
