### ISSUE TITLE
Image Server Access Check fails when Cache is enabled

### ISSUE THREAD

**Issue by XM9G** [derekhe/msfs2020-map-enhancement#49]
**Describe the bug**
When I enable cache in the mod, the Nginx Server Access Check works but not the Image Server Access Check.

**Desktop (please complete the following information):**
 - MSFS2020 version: MS Store
 - MSFS2020 Version 1.22.2.0

**Log** 
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7976694/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/7976701/renderer.log)

**Comment by derekhe** [comment]
Yes it may has some issue using cache, suggest don't use it at the moment until it get stable enough.
