### ISSUE TITLE
Cache being 'Force Disabled' even with NVME SSD (v7.4)

### ISSUE THREAD

**Issue by oodrdoo** [derekhe/msfs2020-map-enhancement#493]
**Describe the bug**

I've just downloaded the newly updated 7.4 version and find that the Cache is being disabled even though my system has a NVME SSD at > 1600MB/sec. Please allow this feature to be optional in the settings. I've used version 7.3.4 for many weeks with no disconnection issues - I'm confident my system has no issues and so this cache disable is not needed and is being triggered in error. (System is 7800x3D/RTX 4090/Pro version of enhancement. 

**MSFS version:**
Store
1.35.14.0

**Mod version:**
7.4

**Device ID**

13G7RK8FB3WM7MZ03B632N6XR8PYY9X1VW6C60YGNGMEWFJB9RG0

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by oodrdoo** [comment]
Edit: This is on Bing Maps )Latest) with High LOD enabled. I also have a 500mbps fibre internet connection dedicated to my MSFS PC.

**Comment by EricFlight** [comment]
> Edit: This is on Bing Maps (Latest) with High LOD enabled. I also have a 500mbps fibre internet connection dedicated to my MSFS PC.
> 
> I think your detection criteria is too sensitive.

For now I would go back to 7.3.4. I was one of the ones having problems with being kicked off so he tried for 7.4.0 to solve my problems. I'm testing it now

**Comment by oodrdoo** [comment]
Eric - ah so you were having server disconnect problems on 7.3.4 even with a more capable internet and NVME than I have. That would lead me to believe that it may be geographical and/or server based problem as I've never had a server disconnect although to be fair I've only been using the mod for about 3 weeks. I'm UK based. Are you USA?

**Comment by derekhe** [comment]
Thanks for the feedback. Maybe the threshold set to too low, I will have a look.

**Comment by derekhe** [comment]
If after disabling cache it still report connection issue, then you can have a look if the loading speed is slow (by watch how many bandwidth it consumes from the task manager)

**Comment by EricFlight** [comment]
It's not that. It works fine with cache off.

Eric

**Comment by oodrdoo** [comment]
Thanks Derek. I'm happy to test any modifications you make prior to release if that would helpful to you. 

Would it be possible to add the 'Force Disable Cache' as an option?

**Comment by derekhe** [comment]
Please have a try latest 7.4.1-beta

**Comment by EricFlight** [comment]
I will try to get to it tonight. Thank you for your work

Eric

**Comment by EricFlight** [comment]
> Please have a try latest 7.4.1-beta

7.4.1 beta seems to be working. Had not had the cache be forced disabled at all and is working without being kicked off data as of now. I'll keep testing.

**Comment by derekhe** [comment]
Glad to hear it





------------------ Original ------------------
From: mnpostema32 ***@***.***&gt;
Date: Tue,Nov 14,2023 6:24 AM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cache being 'Force Disabled'even with NVME SSD (v7.4) (Issue #493)





  
Please have a try latest 7.4.1-beta
  
7.4.1 beta seems to be working. Had not had the cache be forced disabled at all and is working without being kicked off data as of now. I'll keep testing.

**Comment by EricFlight** [comment]
> Please have a try latest 7.4.1-beta

Just curious....what did  you change? It's still working as of now with cache on

**Comment by EricFlight** [comment]
Started getting connection lost but not kicked off data....will keep testing..it reconnects after a while so thinking it's the Microsoft servers

**Comment by EricFlight** [comment]
It worked for a while but now I'm getting kicked off data again. It's around KDTW if that means anything...lol

**Comment by derekhe** [comment]
Please check the error number in the network, if that increases you have server access issue





------------------ Original ------------------
From: mnpostema32 ***@***.***&gt;
Date: Tue,Nov 14,2023 11:01 AM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cache being 'Force Disabled'even with NVME SSD (v7.4) (Issue #493)





 
It worked for a while but now I'm getting kicked off data again. It's around KDTW if that means anything...lol

**Comment by EricFlight** [comment]
> Please check the error number in the network, if that increases you have server access issue
> […](#)
> ------------------ Original ------------------ From: mnpostema32 ***@***.***&gt; Date: Tue,Nov 14,2023 11:01 AM To: derekhe ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] Cache being 'Force Disabled'even with NVME SSD (v7.4) (Issue #493) It worked for a while but now I'm getting kicked off data again. It's around KDTW if that means anything...lol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

So...rebooted computer and started in a new place. Error is 0 on Network. Cache was loading and it kicks me off the microsoft server as well as kicks me off photogrammetry. It also says Unable to access remote image server on Google Maps Server 2 and 1. I am able to access maps.google.com so I know that the server is up and working so I don't know what's going on. It doesn't seem to be a cache thing now..seems to be a can't connect to Google only through the Map Enhancement. It was working for hours this afternoon.

**Comment by oodrdoo** [comment]
This beta (7.4.1) has fixed the the issue of the cache being 'Force Disabled' for me. I've tested in the usual places I fly (i.e. data already in the cache) as well as new places (i.e. data being added to the cache). I have only tested for about 1 hour but no issues.
I've also not seen any server disconnects. The 'NETWORK' Error statistic is showing zero. 
Note I've limited my testing to 'Bing Maps (Latest)' as this is the data source I was using when the issue first arose. I'll test other maps and update if any issues seen.

**Comment by derekhe** [comment]
> > Please check the error number in the network, if that increases you have server access issue
> > […](#)
> > ------------------ Original ------------------ From: mnpostema32 _**@**_._**> Date: Tue,Nov 14,2023 11:01 AM To: derekhe _**@**_.**_> Subject: Re: [derekhe/msfs2020-map-enhancement] Cache being 'Force Disabled'even with NVME SSD (v7.4) (Issue #493) It worked for a while but now I'm getting kicked off data again. It's around KDTW if that means anything...lol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> So...rebooted computer and started in a new place. Error is 0 on Network. Cache was loading and it kicks me off the microsoft server as well as kicks me off photogrammetry. It also says Unable to access remote image server on Google Maps Server 2 and 1 after I load in the sim (doesn't say this when I boot up Map Enhancement). I am able to access maps.google.com so I know that the server is up and working so I don't know what's going on. It doesn't seem to be a cache thing now..seems to be a can't connect to Google only through the Map Enhancement. It was working for hours this afternoon.
> 
> I'm shutting it down for the night and will try tomorrow to see if it was a Google server problem. I will report back

Google maps may always have issue because google may throttle you. Please try other pro maps.

**Comment by EricFlight** [comment]
Now it keeps kicking me off photogrammetry after loading with cache on. Map Enhancement will not pass the image server test on any server (Google, Apple, Bing, etc....)

Definitely a Map Enhancement problem

**Comment by EricFlight** [comment]
Got my license file to stay on the program some how now......seems to be working again....will, again, report back

**Comment by EricFlight** [comment]
Streaming a flight right now and it kicked me off microsoft servers and data again. See latest stream at twitch.tv/ericlfight at around the 1:17:00 mark

**Comment by oodrdoo** [comment]
@derekhe - I'm happy to close this issue as fixed unless you want to continue the conversation with @EricFlight ?

**Comment by EricFlight** [comment]
I want to continue as to what I said last night. The Map Enhancement mod
does not work still

**Comment by EricFlight** [comment]
Ran it again today offstream. I can confirm it stops working when my license info somehow changes from being fine to No License. This is the only problem I think which is why it blocks me from accessing any server. Have any suggestions for my license to keep working and loaded in Map Enhancement? (is good through December 23, 2023 and had no problems on earlier versions)

**Comment by derekhe** [comment]
Please use latest 7.4.3
