### ISSUE TITLE
Pre-cache certain regions

### ISSUE THREAD

**Issue by Vitold69** [derekhe/msfs2020-map-enhancement#494]
In some areas, i.e. Japan, Bing maps (latest) have hi-res quality images. So when you are flying fast (jet liner, 150 knots on approach) and low (1500 ft and below) the Flight Sim became a jerking slideshow. Images download speed at that moment is about 10-12 MB/s, I believe the Bing maps servers have a kind of bottle neck there, So it would be nice if you implement pre-cache feature to choose level and area.  So anyone can cache areas around airports to avoid stuttering. Thanks.

**Comment by FinalLightNL** [comment]
> I planned to do this in near future.

would be a great feature, also if you can please make it cache the lowest altitude maps only.
as some maps change quality levels at different altitudes, sometimes it's a completely different map look (apple maps, mapbox etc)

**Comment by derekhe** [comment]
Yes, this is recommended way.
