### ISSUE TITLE
I have the same issue as Amoresia

### ISSUE THREAD

**Issue by hoffel** [derekhe/msfs2020-map-enhancement#496]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please use latest 7.4.3

**Comment by hoffel** [comment]
Thanks Derek,

 

Cheers,

Mark
