### ISSUE TITLE
 nuova edizione beta 7.4.1. PRO 

### ISSUE THREAD

**Issue by SPUVRT** [derekhe/msfs2020-map-enhancement#497]
-Ho appena installato su SSD la nuova edizione beta 7.4.1. PRO e scopro che questa non viene caricata dal simulatore MSFS2020 (MS store ) edizione 1.34.16.0. In precedenza la Vs applicazione funzionava bene. Vorrei una risposta semplice da capire. 
- Device IDDBAE1TFYZ4832Y7CD7W0HFRJKJQF83WWN6HVA0ZDP6GXT94APY10

**Comment by derekhe** [comment]
Please use latest 7.4.3

**Comment by SPUVRT** [comment]
Thankyou

Inviato da iPhone

Il giorno 17 nov 2023, alle ore 13:06, hesicong ***@***.***> ha scritto:

﻿

Please use latest 7.4.3
