### ISSUE TITLE
problem with beta edition 7.4.1 map enhancement

### ISSUE THREAD

**Issue by SPUVRT** [derekhe/msfs2020-map-enhancement#499]
-I have just installed the new beta edition 7.4.1 on SSD. PRO and I find that this is not loaded from the MSFS2020 simulator (MS store ) edition 1.34.16.0. Previously, your application worked fine. I would like an answer that is simple to understand.

**Device ID**
- DBAE1TFYZ4832Y7CD7W0HFRJKJQF83WWN6HVA0ZDP6GXT94APY10

**Comment by derekhe** [comment]
That's a msfs's issue not this mod's issue. Please use latest version and I will close this.
