### ISSUE TITLE
No photogrammetry Sydney when the tool is on and injects data

### ISSUE THREAD

**Issue by AviatorETSI** [derekhe/msfs2020-map-enhancement#50]
Hi derekhe,

thanks a lot again for this great piece of software. I already donated. After WU 7 I tried a flight in Sydney, but I was dissapointed, as it was not photogrammetric. When I start the sim without your app the photogrammetry is back again.
In other cities like Munic the combination of google + photogrammetry works fine.

Any ideas?

Thanks in advance.

Regards Tobi

**Comment by derekhe** [comment]
Fixed in 3.2.2, please try

**Comment by AviatorETSI** [comment]
Works again! Thanks a lot!!!

**Comment by AviatorETSI** [comment]
You are great!
