### ISSUE TITLE
选择谷歌地图一直断线了，继了再连，又一会儿断了。造成 FS2020为离线模式

### ISSUE THREAD

**Issue by win777552** [derekhe/msfs2020-map-enhancement#504]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by win777552** [comment]
我用7。22版本就没有这种事情发生，但是你们却要求强制升级最新版，最新版连接谷歌地图有问题。一直继线

**Comment by EricFlight** [comment]
> This didn't happen to me when I used version 7.22, but you asked for a forced upgrade to the latest version. The latest version has problems connecting to Google Maps. straight line

Is your license still loaded in Map Enhancement when it causes FS2020 in offline mode? Wondering as I have the same problem in another inquiry

**Comment by derekhe** [comment]
> 我用7。22版本就没有这种事情发生，但是你们却要求强制升级最新版，最新版连接谷歌地图有问题。一直继线

访问谷歌的问题请自行解决，一般情况下是和你的代理之类的有很大关系。你可以试试Bing (Latest)或者ArcGIS，非常稳定的两个图源。如果他们两个还有问题，那还需要排查。

**Comment by derekhe** [comment]
@EricFlight I finally find out the possible issue in cache module cause the backend service crash. Please try https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.4.5-beta

**Comment by win777552** [comment]
thanks ,,,



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月23日(星期四) 晚上10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [derekhe/msfs2020-map-enhancement] 选择谷歌地图一直断线了，继了再连，又一会儿断了。造成 FS2020为离线模式 (Issue #504)





 
@EricFlight I finally find out the possible issue in cache module cause the backend service crash. Please try https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.4.5-beta
