### ISSUE TITLE
MSFS Map Enhacement pro 7.4.4 backend fail

### ISSUE THREAD

**Issue by sammy2198** [derekhe/msfs2020-map-enhancement#505]
**Describe the bug**
I'm getting all sorts of issues. First issue when launching the app it gives me the "backend Server start failed. " Also "install certificate error"

Please describe the bug in detail to help me understand the scenario

I tried all that suggested. I killed the 443 port as well as anything processing on port 42089. Ran as Admin every time. I turned off my antivirus as well as added this application as an exception while it was on. Some times I am able to get through this problem but then "install certificate error comes up after" I made sure all my settings in MSFS are correct  such as cache being off etc. I  have tried numerous different things including closing every single program to make sure nothing is using those ports and also this was never a problem before updating to 7.4.4. I went ahead completely re-installed 2 times and didn't make a difference either. 

**MSFS version:**
 - msstore 
 
 - MSFS2020 Version
 7.4.4

**Mod version:*
- Pro version

**Device ID**
- B3H7ZGRBCRJJJBVFH4GEMF058B3C9BF9692PSQVW3241WEFR7W0G

**Screenshots**
![2nd issue](https://github.com/derekhe/msfs2020-map-enhancement/assets/151571673/3efc388e-9fd5-4397-9c2d-4f298624d8b1)
![1st issue ](https://github.com/derekhe/msfs2020-map-enhancement/assets/151571673/d7aa4a83-b809-426a-a940-3dac7cd70d51)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
I think the user permission has some issue regarding your setup. Normally a true administrator account won't have these issues for install certificate. Please double check if you are using a administrator account.

**Comment by sammy2198** [comment]
Thank you for the suggestion. I went ahead and checked and it seems like I have full administrator rights. See screenshot attached! 

![Screenshot 2023-11-24 172839](https://github.com/derekhe/msfs2020-map-enhancement/assets/151571673/550bda75-20b6-4702-b321-31105dd7d270)

**Comment by sammy2198** [comment]
Problem seemed to go away after updating to 7.4.6!
