### ISSUE TITLE
Map Enhancement 7.4.5 BETA Loading issue

### ISSUE THREAD

**Issue by Justinza23** [derekhe/msfs2020-map-enhancement#507]
Dear Sir,

I have a paid version of MAP Enhancement, however after the latest update I have errors coming up when the appliaction loads textures into MSFS. 

Kindly see the attached photo, it is displaying errors under the Network Section.

Many Thanks
Justin 
![Screenshot 2023-11-23 220212](https://github.com/derekhe/msfs2020-map-enhancement/assets/151879757/6129e3ba-2ab0-4914-8836-bf44b82aa986)

**Comment by derekhe** [comment]
The error doesn't matter too much. Using google if you fly over sea, it normally report error because the images are not there in google.

**Comment by eydrianf** [comment]
> The error doesn't matter too much. Using google if you fly over sea, it normally report error because the images are not there in google.

Can you make sure it doesnt download  texture when flying over water?

**Comment by eydrianf** [comment]
> The error doesn't matter too much. Using google if you fly over sea, it normally report error because the images are not there in google.

Can you make sure it doesnt download ground/water texture

**Comment by Justinza23** [comment]
Hello,

How can I be able to do that? This is the first time I have these errors.
Before it never happened.

Thanks
Justin
