### ISSUE TITLE
 Google servers are blocked. You should set up a proxy first.

### ISSUE THREAD

**Issue by fcerra** [derekhe/msfs2020-map-enhancement#508]
I have this problem, how can I solve it? My is: Google Maps Server (Pro) provides tuned color and resolution. In some places, Google servers are blocked. You should set up a proxy first.

Server 1 has 4 load-balanced servers and the mod will randomly pick one to use.

Please describe the bug in detail to help me understand the scenario
the app does not load google maps but starts msfs with bing maps

**MSFS 2020 13.34.16:**
 - msstore 
 - MSFS2020 Version 13.34.16[e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**
<img width="547" alt="Screenshot 2023-11-24 062435" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/32234012/f12a9995-53ec-4299-a9d6-a390ae2b4659">

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please try other maps. See here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#68-google-maps-are-not-loading

**Comment by fcerra** [comment]
I am having this problem again: Google Maps Server (Pro) provides tuned colour and resolution. Google servers are blocked in some places. You should set up a proxy first.

Server 1 has 4 load balanced servers and the mod will randomly choose one to use:
What should I do?
