### ISSUE TITLE
Image Server not working 

### ISSUE THREAD

**Issue by zaelu** [derekhe/msfs2020-map-enhancement#51]
**Describe the bug**
after version 3.0.0 3.2.2 inclusive Image Server is not working 

**Screenshots**
![1111](https://user-images.githubusercontent.com/6780170/152233913-1be69c3d-f637-49e8-a511-b4a02551e927.jpg)

**Desktop (please complete the following information):**
 - MSFS2020 version: steam but the problem appears without game started
 - MSFS2020 Version WU7 Australia

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- [appdata_logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/7989896/appdata_logs.zip)

- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs
[logs.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/7989881/logs.zip)

**Additional context**
-

**Comment by derekhe** [comment]
Please try disable the cache

**Comment by derekhe** [comment]
Do you fix it?

**Comment by PetziK** [comment]
hey derekhe, just downloaded. looks good for now!. Is it true you disabled the cache?
Should I activate the ingame cache again?
Thanks, 
Peter

**Comment by derekhe** [comment]
Yes I disabled the cache at the moment and fixing it.
Yes you can enable rolling cache.
