### ISSUE TITLE
Backend still causing issues 7.4.5b AND 7.4.6

### ISSUE THREAD

**Issue by matthewvh** [derekhe/msfs2020-map-enhancement#510]
still getting the backend server failure that has been int he prior issues

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - steam
 - 1.34.16.0

**Mod version:**
- 7.4.5 beta

**Device ID**
- CVMXT3QMBPWV1JJZCXJ06MQP2DZX89DW77KYXXFTBR1FG2WY6CQ0

**Screenshots**Core screenshot below

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/97539790/6d783832-7ed3-4d05-a654-a19809d00944)

**Additional context**

**Comment by derekhe** [comment]
This is your account's permission error, you don't have enough permission to install an certificate.

**Comment by matthewvh** [comment]
Where would I go to fix this if my account is the only account on the computer and i run it as the administrator? I have never run into the error until the last few weeks and the computer is the same one

**Comment by matthewvh** [comment]
My permissions show my account IS the Administrator account so not sure how I don't have enough permissions?
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/97539790/886f52fb-cc71-4467-b923-455d0ec7fc4d)

**Comment by matthewvh** [comment]
Just wanted to add I am getting this in 7.4.6 as well

**Comment by derekhe** [comment]
I think it maybe your antivirus blocks you.

**Comment by matthewvh** [comment]
I don’t have the antivirus protection enabled

**Comment by matthewvh** [comment]
why was this closed? i still have the issues
