### ISSUE TITLE
problema con il server

### ISSUE THREAD

**Issue by gobbone** [derekhe/msfs2020-map-enhancement#518]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by gobbone** [comment]
if you are using google maps ,please ensure that you can open, www.google,com maps,in your browser,you may be blocked by google due to a large number of request,if you are using a proxy to connect to the remote server,please ensure that the proxy is working,please also visit faq page for for more information,I bought the one year version this morning, can you help me with this message?Can anyone help me, since I paid and can't use the service, how can I solve it?

**Comment by derekhe** [comment]
I can't solve the google maps access issue. The images are loaded from google not my server. And the payment is not include the map copyright. You can switch to other servers. Google maps are not always best.

**Comment by gobbone** [comment]
which servers?

**Comment by gobbone** [comment]
it seems server 2 is ok
