### ISSUE TITLE
port443

### ISSUE THREAD

**Issue by syltremb** [derekhe/msfs2020-map-enhancement#52]
**Describe the bug**
I have this message when it open :443 Port is using, the mod won't work. Please close any application using 443 port. Look at the FAQ page here: https://github.com/derekhe/msfs2020-google-map/wiki/FAQ#443-port-is-occupied

**Screenshots**

**Desktop (please complete the following information):**
MSFS2020 Windows version

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8010656/main.log)

**Comment by h0wardch3ng** [comment]
```
netstat -aon | findstr (Port Number) 
```

```
tasklist | findstr (PID Number)
```

Check answer is Chrome or any other browser.
Close all browser and restart MME again.

**Comment by derekhe** [comment]
Will close this as I can't help on this

**Comment by syltremb** [comment]
I think is probably the solution to look around the browser.
