### ISSUE TITLE
host file acces denied

### ISSUE THREAD

**Issue by Bodenseeler742** [derekhe/msfs2020-map-enhancement#520]
i can´t connect to google map
I got message:
![grafik](https://github.com/derekhe/msfs2020-map-enhancement/assets/58629703/56e8206f-e4bc-414e-b1ca-74070ff548a4)

**MSFS version:**
 - msstore 
 - MSFS2020 Version1.35.21.0

**Mod version:**
- 7.4.6

**Device ID**
GT6G63V9Z55E2FFQ3GBDT6J0NKRZZ6GRQ0X05KW9XRQNGB75GBKG

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
![2023-12-25_15h50_18](https://github.com/derekhe/msfs2020-map-enhancement/assets/58629703/90a3bcd0-a463-4f98-b6a0-628b4e833bce)

**Comment by derekhe** [comment]
Please have a try the 7.5.3 version
