### ISSUE TITLE
Map Enhancement Error

### ISSUE THREAD

**Issue by Maveric1979** [derekhe/msfs2020-map-enhancement#521]
Hello,
i don't need to use Map Enhancement, i have Network error

**MSFS version: 1.35.21.0
 - msstore 
 - MSFS2020 Version 

**Mod version: 
- Mod version 7.4.6

**Device ID**
- WG7Z892NZCN74P5A5QZ33VXFXN9WPHRWE51PZJZ9QYYN5C457PTG

![MAP ENHANCEMENT 7 4 6](https://github.com/derekhe/msfs2020-map-enhancement/assets/154898891/db56e9af-b60f-4eb4-94fb-e8ca826b7f3e)

Thank's for your help

**Comment by derekhe** [comment]
Please first go through the manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Comment by Maveric1979** [comment]
I already read the FAQ, but I didn't find a solution.

Do you have an idea?

Thanks in advance

**Comment by bwernli** [comment]
This means that you have NO errors. 0=Zero :-)
