### ISSUE TITLE
startup very slow i'm getting server errors when trying to start the program!

### ISSUE THREAD

**Issue by levelupsim** [derekhe/msfs2020-map-enhancement#522]
**Describe the bug**

Please remove the random screens on startup, this is making the startup very slow i'm getting server errors when trying to start the program! leave only a background image on startup. Thanks!

**MSFS version:**
 - steam
 - MSFS2020 Version 1.35.21.0

**Mod version:**
- 746

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by levelupsim** [comment]
again and again.... 
V. 7.5.2
![Captura de tela 2024-01-02 132100](https://github.com/derekhe/msfs2020-map-enhancement/assets/81846255/3580b6ea-5a46-4f29-bf40-34e181d249b8)

**Comment by Soulreaver1977** [comment]
Same problem here!

**Comment by derekhe** [comment]
I found the problem and fixed in 7.5.3, please update.
