### ISSUE TITLE
7.5.1 Installer will not run. Formerly using 7.4.x Beta but today it notified as being "too old" then shutdown. Uninstalled "old" beta and tried 7.5.1 but unsuccessful. Win 23H2.11 23

### ISSUE THREAD

**Issue by CalmTodd** [derekhe/msfs2020-map-enhancement#525]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please use latest version. And please check the FAQ page for user manual.

**Comment by Calluhan** [comment]
I also have this issue - the latest stable version is 7.4.6 - which I have manually downloaded - even with this version I get 'version is too old' and nothing will start

**Comment by derekhe** [comment]
Must upgrade to 7.5.1





------------------ Original ------------------
From: Calluhan ***@***.***&gt;
Date: Mon,Jan 1,2024 10:47 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] 7.5.1 Installer will not run.Formerly using 7.4.x Beta but today it notified as being "too old" thenshutdown. Uninstalled "old" beta and tried 7.5.1 but unsuccessful. Win 23H2.1123 (Issue #525)





 
I also have this issue - the latest stable version is 7.4.6 - which I have manually downloaded - even with this version I get 'version is too old' and nothing will start

**Comment by CalmTodd** [comment]
Just tried another download of "the latest" 7.5.1 installer and it does start; confirmed by monitoring task manager. Nothing loads or runs. Plus, I also miss the automatic updating that prior versions featured.

**Comment by Calluhan** [comment]
> Must upgrade to 7.5.1
> […](#)
> ------------------ Original ------------------ From: Calluhan ***@***.***&gt; Date: Mon,Jan 1,2024 10:47 PM To: derekhe/msfs2020-map-enhancement ***@***.***&gt; Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] 7.5.1 Installer will not run.Formerly using 7.4.x Beta but today it notified as being "too old" thenshutdown. Uninstalled "old" beta and tried 7.5.1 but unsuccessful. Win 23H2.1123 (Issue #525) I also have this issue - the latest stable version is 7.4.6 - which I have manually downloaded - even with this version I get 'version is too old' and nothing will start — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Thank you - github was still showing 7.4.6 until just now...must be a regional server issue

**Comment by CalmTodd** [comment]
Error: trying again. Just tried another download of "the latest" 7.5.1 installer and it does NOT start; confirmed by monitoring task manager. Nothing loads or runs. Plus, I also miss the automatic updating that prior versions featured.

**Comment by CalmTodd** [comment]
Problem with installer resolved! Was being blocked by Win 11 23H2 due to coming from another computer. Just had to uncheck the block option and everything seems to working fine.
