### ISSUE TITLE
Having issues

### ISSUE THREAD

**Issue by BELLA1706** [derekhe/msfs2020-map-enhancement#528]
I just bought your software and activated it every type of map I choose it says old version and nothing change or upload .Do you have a quick guide to use this software 

Thanks 

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 -  
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**W20S4NV5RA7378SDRN6DR8SR09D3AMT66H3YXVGDXYBD8JW8Q4AG
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
The latest version is here: https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.5.1
