### ISSUE TITLE
Version 7.5.1 not launching game

### ISSUE THREAD

**Issue by Clselby** [derekhe/msfs2020-map-enhancement#530]
**Describe the bug**

Not launching game since update. 

**MSFS version:**
 - msstore 
 - MSFS2020 Version 1.35.21.0

**Device ID**
RCBR6X5MZ123Z98YPS0SKVEJ3GHZBEQ35A0XZC3N1C0T8102G8VG

**Comment by derekhe** [comment]
Is it working now?

**Comment by Clselby** [comment]
Just installed the new version you released, does not launch the game, but I am able to launch the game manually and the maps work.

**Comment by saviomarco1** [comment]
no parte dopo l'aggiornamento
