### ISSUE TITLE
This version is too old. Please update to the latest version. All functions will be disabled.

### ISSUE THREAD

**Issue by Nono97270** [derekhe/msfs2020-map-enhancement#531]
**Describe the bug**
This version is too old. Please update to the latest version. All functions will be disabled.
When i click start
Please describe the bug in detail to help me understand the scenario
When i click start, this appears : This version is too old. Please update to the latest version. All functions will be disabled.
**MSFS version:**
 - msstore
 - MSFS2020 Version [e.g. 22] : 

**Mod version:**
- 7.4.6

**Device ID**
- idk

**Screenshots**
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/155399154/1f1e9b7c-dcfe-42de-a645-590b560b8d91)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please upgrade to latest version.

**Comment by Nono97270** [comment]
But it's the latest version on Flightsim.to
