### ISSUE TITLE
Load blue squares

### ISSUE THREAD

**Issue by Devilspike27** [derekhe/msfs2020-map-enhancement#533]
**Describe the bug**
Blue squares

Please describe the bug in detail to help me understand the scenario
After 10 minutes flying blue squares appears with Errors

**Mod version:**
7.5.1

**Device ID**
THHSGH1SQWB44QYV710VQYM4M5WE13H1Z04CAMSFG293M1PPN880

<img width="1280" alt="Capture d'écran 2024-01-02 110930" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/155438861/68c70505-7383-43bc-adb4-050f641e0172">

**Comment by Devilspike27** [comment]
<img width="1280" alt="Capture d'écran 2024-01-02 114237" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/155438861/e4801d44-97db-46dc-9d7a-0ed8648c4d23">

**Comment by derekhe** [comment]
I'm aware of problem and will fix it soon.

**Comment by Devilspike27** [comment]
Thanks

**Comment by derekhe** [comment]
I think you installed some cracked version from simplaza which cause this issue. Please confirm.

**Comment by Devilspike27** [comment]
Yes i have test the pro version with simplaza and now i have pay the pro license and have always this issue.

**Comment by derekhe** [comment]
Please try 7.5.2 I just released, fixed the problem caused by the cracked version

**Comment by Amorisia** [comment]
By my side I did not tried the cracked version but I have the blue square problem too. I thought it was the cache, but got it again just now. I will try 7.5.2 next flight. Thank you.

**Comment by Devilspike27** [comment]
I've tested several places and it's perfect again, thank you.
