### ISSUE TITLE
Version too old error

### ISSUE THREAD

**Issue by presto25** [derekhe/msfs2020-map-enhancement#534]
I received notification of needed update.   Updated to 7.4.6_6kGdl

PS:  Love the app!! 

Please describe the bug in detail to help me understand the scenario
I run the program As administrator and I either get a server error (which I reload) then receive a Version to old error.   

Uninstalled and reinstalled.   same error
Added App to firewall exclusion

**MSFS version:**  Latest  SU14
 -  steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version 7.4.6_6kGdl

**Device ID**
- Device ID  ???

 
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/77365267/579f7de8-ac59-420b-9db5-760c28e2c044)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by KolosovV** [comment]
Last version is 7.5.2. You can download it via Release here on GitHub and update.

**Comment by presto25** [comment]
Thank you!!!  The version i have is the version currently on flightsim.to

**Comment by presto25** [comment]
File from Github solved problem.  Thanks
