### ISSUE TITLE
Offline maps loading

### ISSUE THREAD

**Issue by YTmmatt** [derekhe/msfs2020-map-enhancement#541]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario
When I view the world to select the airport I want to fly out of, the world appears offline. If I load into the game anyway, it sometimes loads the Google scenery but usually doesn't. If I go back to the main menu and view the world again, sometimes it shows Google scenery and then everything is fine but the last 5 times I've tried that, it doesn't work. It shows me offline scenery only. The FAQ says to ensure that I have the correct region set but there's no info on how to do that.

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.35.21.0

**Mod version:**
7.5.2

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please check out the manual see if any setting is wrong: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#4-use
