### ISSUE TITLE
Crack source code 

### ISSUE THREAD

**Issue by ilyabumblebee** [derekhe/msfs2020-map-enhancement#542]
Hi!

You said crack had some hidden files injection, or something like that. So if you need I have found it's source (and it doesn't do this lol).

Let me know.

**Comment by derekhe** [comment]
Thanks for your cracking :)

Ilya Bumblebee ***@***.***>于2024年1月4日 周四09:51写道：

**Comment by ilyabumblebee** [comment]
:(

if (!licenseContent.Contains("<Type>Standard</Type>") || licenseContent.Contains("Made With Love"))

Why don't you like Made With Love string ?
