### ISSUE TITLE
this software worked well on all previous versions up to 7.5.2

### ISSUE THREAD

**Issue by sikorsky77** [derekhe/msfs2020-map-enhancement#548]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN **(YES)**
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
this great software worked well on all previous versions up to 7.5.2 i used until yesterday, today it asks me to update in version 7.5.3, what i did
and now i have this windows message box
---------------------------------------------------------------------------------------------------------------------------------------
Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:

1. Run in administrator mode **(already launched like that since the first releases)**
2. Close any software that occupies 443 or 42098 port **(not used port by checking with SysInternal TCP View Tool)**
3. Add this software into antivirus whitelist **(done in Bitdefender total security suite)**
    i also stop the BiteDefender VPN ( i discovered that some others MSFS 2020 software addon doesn't like the VPN usage)
4. Completely reinstall this software **(as usual process , uninstall , restart PC , install v7.5.3 in admin mode and in the standard proposed folder)**
5. Visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) and [Issue page](https://github.com/derekhe/msfs2020-map-enhancement/issues) **(done)**
Detail: Error: **Reached max retry, i didn't find something related to**
------------------------------
**version 7.5.3, Windows 11 pro 23H2 , OS build 22631.2861**
----------------------------------------------------
host file
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
#99.86.4.77 1uzxr3b3jraw5nlmnvbsikiioud2vilw5.web-networking.com
#35.162.78.161 geoip.pango-paas.co
----------------------------------------------------------------------------------------------------------

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Could you try run the core.exe inside the installation folder in command prompt with administrator? And capture the output or take a screenshot for me.







------------------ Original ------------------
From: sikorsky77 ***@***.***&gt;
Date: Sat,Jan 6,2024 11:43 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] this software worked well on allprevious versions up to 7.5.2 (Issue #548)





 
Before you raise a bug
 
[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN (YES)
 [] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/
 
Describe the bug
 this great software worked well on all previous versions up to 7.5.2 i used until yesterday, today it asks me to update in version 7.5.3, what i did
 and now i have this windows message box
 
Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:
  
Run in administrator mode (already launched like that since the first releases)
 
Close any software that occupies 443 or 42098 port (not used port by checking with SysInternal TCP View Tool)
 
Add this software into antivirus whitelist (done in Bitdefender total security suite)
 i also stop the BiteDefender VPN ( i discovered that some others MSFS 2020 software addon doesn't like the VPN usage)
 
Completely reinstall this software (as usual process , uninstall , restart PC , install v7.5.3 in admin mode and in the standard proposed folder)
 
Visit FAQ page and Issue page (done)
 Detail: Error: Reached max retry, i didn't find something related to
  
 
version 7.5.3, Windows 11 pro 23H2 , OS build 22631.2861
 
host file
 
Copyright (c) 1993-2009 Microsoft Corp.
 

 
This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
 

 
This file contains the mappings of IP addresses to host names. Each
 
entry should be kept on an individual line. The IP address should
 
be placed in the first column followed by the corresponding host name.
 
The IP address and the host name should be separated by at least one
 
space.
 

 
Additionally, comments (such as these) may be inserted on individual
 
lines or following the machine name denoted by a '#' symbol.
 

 
For example:
 

 
102.54.94.97     rhino.acme.com          # source server
 
38.25.63.10     x.acme.com              # x client host
 
localhost name resolution is handled within DNS itself.
 
127.0.0.1       localhost
 
::1             localhost
 
#99.86.4.77 1uzxr3b3jraw5nlmnvbsikiioud2vilw5.web-networking.com
 #35.162.78.161 geoip.pango-paas.co
 
Device ID
  
Device ID
  
Screenshots
 
Please provide me screenshots for the mod and msfs2020 if possible
 
Additional context
 Add any other context about the problem here.

**Comment by b80b** [comment]
> Could you try run the core.exe inside the installation folder in command prompt with administrator? And capture the output or take a screenshot for me.
> […](#)
> ------------------ Original ------------------ From: sikorsky77 ***@***.***&gt; Date: Sat,Jan 6,2024 11:43 PM To: derekhe/msfs2020-map-enhancement ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [derekhe/msfs2020-map-enhancement] this software worked well on allprevious versions up to 7.5.2 (Issue #548) Before you raise a bug [] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN (YES) [] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/ Describe the bug this great software worked well on all previous versions up to 7.5.2 i used until yesterday, today it asks me to update in version 7.5.3, what i did and now i have this windows message box Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application: Run in administrator mode (already launched like that since the first releases) Close any software that occupies 443 or 42098 port (not used port by checking with SysInternal TCP View Tool) Add this software into antivirus whitelist (done in Bitdefender total security suite) i also stop the BiteDefender VPN ( i discovered that some others MSFS 2020 software addon doesn't like the VPN usage) Completely reinstall this software (as usual process , uninstall , restart PC , install v7.5.3 in admin mode and in the standard proposed folder) Visit FAQ page and Issue page (done) Detail: Error: Reached max retry, i didn't find something related to version 7.5.3, Windows 11 pro 23H2 , OS build 22631.2861 host file Copyright (c) 1993-2009 Microsoft Corp. This is a sample HOSTS file used by Microsoft TCP/IP for Windows. This file contains the mappings of IP addresses to host names. Each entry should be kept on an individual line. The IP address should be placed in the first column followed by the corresponding host name. The IP address and the host name should be separated by at least one space. Additionally, comments (such as these) may be inserted on individual lines or following the machine name denoted by a '#' symbol. For example: 102.54.94.97 rhino.acme.com # source server 38.25.63.10 x.acme.com # x client host localhost name resolution is handled within DNS itself. 127.0.0.1 localhost ::1 localhost #99.86.4.77 1uzxr3b3jraw5nlmnvbsikiioud2vilw5.web-networking.com #35.162.78.161 geoip.pango-paas.co Device ID Device ID Screenshots Please provide me screenshots for the mod and msfs2020 if possible Additional context Add any other context about the problem here. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

Hi, I have the same problem. I tried your solution but it still doesn't work...

**Comment by ilyabumblebee** [comment]
Guys, it's ok. Malware got injected successfully. Now you are banned from opening several sites, and maybe something else. 🤣

**Comment by b80b** [comment]
> Guys, it's ok. Malware got injected successfully. Now you are banned from opening several sites, and maybe something else. 🤣

????

**Comment by sikorsky77** [comment]
???

**Comment by derekhe** [comment]
> > Guys, it's ok. Malware got injected successfully. Now you are banned from opening several sites, and maybe something else. 🤣
> 
> ????

Don't care about the cracker.

**Comment by derekhe** [comment]
@sikorsky77 @b80b please try the following
steps:
1. Open Command Prompt in administrator mode

3. type the following to go to the default installation folder
```cd "C:\Program Files\MSFS2020 Map Enhancement\resources\core\release"```

4. You should see:
<img width="520" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/4a2c411b-1e26-423a-957f-0924c76ec318">

5. type ```dir core.exe``` will show you the file
<img width="440" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/a8bec7f1-6ccd-4827-9871-cfe8fbdae8b9">

6. type ```core.exe``` will run the backend server and will show:
<img width="593" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/df9c9f15-b901-48e3-b4e3-3e7ca430df29">

Please take this screen shot for me to diagnose.
I made some protection for latest version so it may have some issues in some environment.

**Comment by sikorsky77** [comment]
hi Derekhe
here the result of core.exe execution , it seems that i have an issue with .NET application , but why these error was not present one day before in version 7.5.2, it's a mistery
i am going to do the update of .NET , i will inform you about the result
thanks for support me
Thierry

**Comment by derekhe** [comment]
I can't see anything. Did you uploaded something?

**Comment by sikorsky77** [comment]
Hi Derekhe
i have installed .NET runtime version 8.0.0 , restarted the PC and now am happy to say that version 7.5.3 works well
i also ran the core.exe and it gave me theses informations
C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>core
[13:50:43 INF] App started ver=7.5.3.0 device id=GBVP253H8DDRJN6EX1MZDEPR4BV8BEQ6Z93PK573A5W1NBVQ8D8G
[13:50:43 INF] Starting server
[13:50:43 INF] Configuring YARP WebProxyConfig { Address = , BypassOnLocal = , UseDefaultCredentials =  }

the last question that's out of your hands is: why Windows Update hasn't updated .NET version 6.5.3 to the latest version 8.0.0?
many thanks for your patient support
Best regards
Thierry

**Comment by b80b** [comment]
> @sikorsky77 @b80b please try the following steps:
> 
> 1. Open Command Prompt in administrator mode
> 2. type the following to go to the default installation folder
>    `cd "C:\Program Files\MSFS2020 Map Enhancement\resources\core\release"`
> 3. You should see:
> 
> <img alt="image" width="520" src="https://private-user-images.githubusercontent.com/1734077/294760855-4a2c411b-1e26-423a-957f-0924c76ec318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTY3NTAsIm5iZiI6MTcwNDcxNjQ1MCwicGF0aCI6Ii8xNzM0MDc3LzI5NDc2MDg1NS00YTJjNDExYi0xZTI2LTQyM2EtOTU3Zi0wOTI0Yzc2ZWMzMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTIyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY3NTViZjFjM2FhZDlkY2RlNzVhMzhjNGIxZjVmZGVmZjA5Yjc4NWM3OTM1ZTAxMDZjZjQwYjc4ZWMwNGVlZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bHzWCgbhs8UGqf4DdBgju5T5_ywI2QLq4H1hAubcxBk">
> 5. type `dir core.exe` will show you the file
> 
> <img alt="image" width="440" src="https://private-user-images.githubusercontent.com/1734077/294760910-a8bec7f1-6ccd-4827-9871-cfe8fbdae8b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTY3NTAsIm5iZiI6MTcwNDcxNjQ1MCwicGF0aCI6Ii8xNzM0MDc3LzI5NDc2MDkxMC1hOGJlYzdmMS02Y2NkLTQ4MjctOTg3MS1jZmU4ZmJkYWU4YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTIyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjYwMWU5NWY2ZWE5YTI1ZDI1OTczZjIyMmZjYTA5ZTI0MmE3ZDI1OGU2YzExOWU4OTZhN2E5YTBmYWRkZWM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bd1YNYlSeWqClbAplDXtx-1Zw_qyhCwjmVaGPWmHirE">
> 6. type `core.exe` will run the backend server and will show:
> 
> <img alt="image" width="593" src="https://private-user-images.githubusercontent.com/1734077/294760947-df9c9f15-b901-48e3-b4e3-3e7ca430df29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTY3NTAsIm5iZiI6MTcwNDcxNjQ1MCwicGF0aCI6Ii8xNzM0MDc3LzI5NDc2MDk0Ny1kZjljOWYxNS1iOTAxLTQ4ZTMtYjRlMy0zZTdjYTQzMGRmMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTIyMDUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiMzA1YTZhOTU3ZDk0Y2JmNGIxMmZjYTg3M2IxYzU4ODEzNjcyMDg1ODM5MWJmOGEyNWZhYzU1OTE3YzM0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r2ADpvktJJ_gLKL_EDYRZZMAp_s7UNaGu8b6QkkBevI">
> Please take this screen shot for me to diagnose. I made some protection for latest version so it may have some issues in some environment.
Thanks, that worked.

**Comment by sikorsky77** [comment]
it seems that there is something related to the latest .NET 8.0.0 version if it is not installed
i helped in flightsim.to an user with a similar message related to version 8.0.0 and it works also for him
question : do you check when we start V7.5.3 if the .NET is uptodate to the lastest version ?

**Comment by derekhe** [comment]
In the installation process, it will install .net 8 automatically. Maybe there is something wrong with it or it was cancelled by mistake. I will add this into manual so others may know the possible problem.

**Comment by sikorsky77** [comment]
great for us , Derekhe and thanks for your reactivity
Best regards
Thierry

**Comment by vignirmarg** [comment]
Hi! Have been using this for some time and all was good until the update. Now it just loads the first two images and nothing more. Have updated to .net 8  - allowed through the firewall - Uninstalled - 
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/156244950/a1759203-19f2-459d-97e5-5747385b95ab)

**Comment by sikorsky77** [comment]
Hi Vignirmag
can you run the cmd windows (in admin mode) to execute the core.exe 
input cd "C:\Program Files\MSFS2020 Map Enhancement\resources\core\release" and enter
input core.exe and enter
what is the result of the core command ?

**Comment by vignirmarg** [comment]
C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>core.exe
[11:21:55 INF] App started ver=7.5.3.0 device id=7R4CZMF61JMQXJMDBQBH6MYG1E479S2NCFVTX3PWS83BSXY286ZG
[11:21:55 INF] Starting server
[11:21:57 INF] Configuring YARP WebProxyConfig { Address = , BypassOnLocal = , UseDefaultCredentials =  }

C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>

**Comment by sikorsky77** [comment]
Hi Derekhe
Vignirmarg seems have a good installation of your software and the good Release of .NET, 
_C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>core.exe
[11:21:55 INF] App started ver=7.5.3.0 device id=7R4CZMF61JMQXJMDBQBH6MYG1E479S2NCFVTX3PWS83BSXY286ZG
[11:21:55 INF] Starting server
[11:21:57 INF] Configuring YARP WebProxyConfig { Address = , BypassOnLocal = , UseDefaultCredentials = }
C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>_

but he has an issue after starting the application with flight simulator 2020
see below his original post
https://github.com/derekhe/msfs2020-map-enhancement/issues/548#issuecomment-1885681923

when he start and use MSFS 2020 , only 2 images are loaded
Have you an idea for him about this kind of issue or an explainations on this ?
Thank
Thierry

**Comment by vignirmarg** [comment]
Do you have any idea why this isn´t working for me after the update?

**Comment by sikorsky77** [comment]
Hi Vignirmarg
could you create a new post for Derekhe , the creator of this addon with the text below and your picture
 showing only loaded image. i think that Derekhe suppose we are only discussing together.
--------------------------------------------------------------------------------------------------------------------------
I ran based on Thierry suggestion the core.exe to see if installation is correct and it seems that it is the case( no error message),
C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>core.exe
[11:21:55 INF] App started ver=7.5.3.0 device id=7R4CZMF61JMQXJMDBQBH6MYG1E479S2NCFVTX3PWS83BSXY286ZG
[11:21:55 INF] Starting server
[11:21:57 INF] Configuring YARP WebProxyConfig { Address = , BypassOnLocal = , UseDefaultCredentials = }
C:\Program Files\MSFS2020 Map Enhancement\resources\core\release>

but I have an issue after starting the application with flight simulator 2020
when the software start and run with MSFS 2020 , only 2 images are loaded
Have you an idea for this kind of issue or an explainations on this ?
Thank
Vignirmarg

**Comment by derekhe** [comment]
@sikorsky77 please find the manual and check the use section, make sure everything is setup correctly: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#4-use
