### ISSUE TITLE
Can Not Select a Map Server

### ISSUE THREAD

**Issue by matthewttt** [derekhe/msfs2020-map-enhancement#55]
MSFS2020 Map Replacement  v3.2.2 opens  normally,  passes Server Check and then functions normally. However, under the Map Server tab, the server choices buttons like mt.google.com etc, are not active. Also, the Mapbox Access Token input area is inactive. Please advise on how to fix it. Thanks, Matthew

**Comment by derekhe** [comment]
It is working on my side, I don't know what is wrong. Any video or screenshots please give to me.
