### ISSUE TITLE
Backend server start failed -  Detail: Error: Reached max retry-

### ISSUE THREAD

**Issue by stwalvn** [derekhe/msfs2020-map-enhancement#553]
Got the same  Error

Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:

Run in administrator mode
Close any software that occupies 443 or 42098 port
Add this software into antivirus whitelist
Completely reinstall this software
Visit FAQ page and Issue page
Detail: Error: Reached max retry-------  I don I  I know to do. Their is nothing on port 42098 or 4454 Have reinstalled to many time as addmin -- Had it  allow in Firewall & turn off Firewall; Still not working on my Decktop, but works on laptop!! Please Help

**Comment by stwalvn** [comment]
Hear is   "core.exe" file.

<img width="677" alt="image" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/83795176/c00f4626-78ca-441e-931c-b946463a763f">
[
![Screenshot 2024-01-08 094037](https://github.com/derekhe/msfs2020-map-enhancement/assets/83795176/39ffcfda-82ef-44ff-9f0a-82f347b91e51)
](url)

**Comment by sikorsky77** [comment]
Hello stwalvn 
the purpose of this core.exe is to give you informations related to the error
for my case, it was due to the fact that my version of Windows ".NET" was not uptodate to 8.0.0
after updating it , version 7.5.3 works
for your case , it seems that you have a similar problem related to a ".NET" 8.0.0 file or a set of files that are not well installed or maybe your ".NET" install is broken

**Comment by sikorsky77** [comment]
to check the installed  ".NET" Version
open a windows CMD in administrator mode
enter dotnet -- info
you should have an answer like that
------------------------------------------------------------------
"Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71
  RID:          win-x64
.NET SDKs installed:
  No SDKs were found.
.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Other architectures found:
  None
Environment variables:
  Not set
global.json file:
  Not found
Learn more:
  https://aka.ms/dotnet/info
Download .NET:
  https://aka.ms/dotnet/download

**Comment by stwalvn** [comment]
Thank you for the Quick response, I will try and get back with you. --  I Really  LOVE THIS APP, BEEN USEING it from the Beginning

**Comment by sikorsky77** [comment]
yes me too , moreover we can choose Googlemaps servers or Latest updated Bingmaps servers while MSFS2020 use older images servers

**Comment by stwalvn** [comment]
:) :) :)  THANK YOY -  THANK YOU -  THANKYOU So Much ; 
& also telling me to run the net as Admin; I had to ran two time, I do believe the 1st time I DID Not run as AMIN!      So Glad I found a way to talk to someone that could help. Happy New Year!
