### ISSUE TITLE
Google Maps Server 1 Pro not loading after crossing ocean

### ISSUE THREAD

**Issue by Bex1985** [derekhe/msfs2020-map-enhancement#554]
Hi, 

im on the latest build and have a pro license. 
When I use Google Maps Server 1 Pro im now getting error that it is not loading. So I mostly have to use Google Maps Server2 Pro, which is working most of the time. 

After restarting the app I can sometimes use the Google Maps 1. It’s working fine, till I reach the Atlantic Ocean. While crossing the ocean it’s not loading and the number of errors is increasing constantly, when reaching land again it sometimes continues loading, most of the time not. I have to change to Google Maps Server 2 to continue loading.

it was working fine about three to four builds ago.

**Comment by derekhe** [comment]
I can't fix the google map's access issue.
