### ISSUE TITLE
Can't get pass issue with host file

### ISSUE THREAD

**Issue by kklosterman** [derekhe/msfs2020-map-enhancement#557]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

Getting error about "apply hosts change failed"

Please describe the bug in detail to help me understand the scenario
Apply hosts change failed

Unable to patch hosts file. Please try:

Run as administrator.
Turn off your antivirus and restart your computer.
Check if any tools inside your antivirus are protecting your system.
Add this mod into white list.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.
Error detail: The process cannot access the file 'C:\Windows\system32\drivers\etc\hosts' because it is being used by another process.

**Map Enhancement version:**
7.5.3

**Device ID**
- Device ID ?

**Screenshots**
Added the file map enhancement file and location to the webroot allow section. 
IF webroot is disabled works ok. But can't figure out how to fix issue with the hosts file as it will not allow me to add that file
location to the webroot by picking the location or typing in the file as "add file"
checking the FAQ sections of the manual can't continue from there.
I did add what I could to the security section of the hosts file.  See below.
![host Screenshot 2024-01-17 193055](https://github.com/derekhe/msfs2020-map-enhancement/assets/49594169/43a5442c-ac38-4ad6-a9b9-e44f0491988b)

**Additional context**

**Comment by derekhe** [comment]
Please check if your antivirus blocks the hosts modification. Some
antivirus protects the hosts file.

kklosterman ***@***.***>于2024年1月18日 周四08:34写道：

**Comment by kklosterman** [comment]
Going to the webroot advanced options, and then shields and un checking the 
Prevent any program from modifying the HOSTS file did the trick. 
Thanks for helping me find it.
