### ISSUE TITLE
Should the map view inside the software be a moving map ?

### ISSUE THREAD

**Issue by ypaul123** [derekhe/msfs2020-map-enhancement#559]
**Describe the bug**

In the software, in MAP view, should the blue aircraft be moving ? It **_doesn't_** here... 

**Map Enhancement version:**

version 7.5.3(pro)

**Device ID**

PQ0VMR7K3V9PKNNAK6XSHF63KYA3EMAR8TDG417D2X2JMDXJ7540

**Screenshots**

https://imgur.com/qp2Zywm

**Additional context**

using the MapBox(pro) map

Thanks in advance for your help.

**Comment by derekhe** [comment]
yes, the map doesn’t move at the moment. It is still in development.
