### ISSUE TITLE
Loaded images limit..?

### ISSUE THREAD

**Issue by utkrishtm** [derekhe/msfs2020-map-enhancement#561]
**Before you raise a bug**

[x] For using this app, I have read and tried the solution mentioned in the manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Describe the bug**

It seems that there is a limit to the amount of images that are loaded into the sim. I flew multiple times, and after about 90,000 images loaded into the sim, the software would stop loading more images. It would cause the terrain to not load properly and look horrible. I tried changing the network settings from Enhanced to normal as well.

**Map Enhancement version:**
7.5.3 (Pro)
Bing Maps (latest) or Google Maps Pro Server 1

**Device ID**
0R97EWXY6N5HHTXC0VFP70KR7NYD0F0P1VNW1WRX3BXPVCG4VPCG

**Screenshots**

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/fc5ef4b9-35c6-410f-bad3-75049803432b)

**Comment by utkrishtm** [comment]
Possible for you to guide me or let me know where exactly to look to fix this issue?

**Comment by paulwain** [comment]
Did you find a fix for this @utkrishtm 

I think I may have the same problem - did 4 flights today using google server pro - on the last flight had poor quality textures. When i exited MFS and tried to reloaed the app - I get this message now...

![Untitled](https://github.com/derekhe/msfs2020-map-enhancement/assets/155645900/31eebd7e-2a5d-4009-8cb7-15585f26dbac)

**Comment by derekhe** [comment]
Please have a look here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#68-google-maps-are-not-loading

**Comment by utkrishtm** [comment]
I uninstalled the program and reinstalled it. Change the network from enhanced to normal and its working fine for now.

**Comment by utkrishtm** [comment]
I uninstalled the program and reinstalled it. Change the network from enhanced to normal and it is working fine for now.
