### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by spock5401986** [derekhe/msfs2020-map-enhancement#562]
I'm getting errors on the network, should I be worried about these?
Are the normal? The last flight I had around 2000 errors.

**Comment by spock5401986** [comment]
Still happening with Bing maps (latest)

**Comment by spock5401986** [comment]
![Untitled](https://github.com/derekhe/msfs2020-map-enhancement/assets/75446223/40dad9b2-7308-4bbf-87a2-6edaad2bc88c)

**Comment by paulwain** [comment]
I was wondering the same - The program seems to be working so I guess its normal? I dont know lol
