### ISSUE TITLE
After the version update, the quality of China's ultra clear maps has seriously declined?

### ISSUE THREAD

**Issue by jiachren** [derekhe/msfs2020-map-enhancement#564]
device ID：BN5XG3068VRCWS263K946JW2TX1JHYEDC02738G6FYDYBHE5X8G0
Map Enhancement version:
7.5.3 (Pro)
Customized ultra clear maps for China and the latest Bing maps

I haven't used this software for several months, but I started using it again recently. After updating the version, I found that the landscape in China has become particularly blurry, and from a distance, it's basically just a bunch of color blocks. When I observed the ground up close, I found that there were no 3D objects on the ground, which was never the case before.
I have tried setting the network setting to normal, but it has not worked

**Comment by Vitold69** [comment]
Just curious. Is f.ng Chinese government still requires to shift map coordinates?

**Comment by derekhe** [comment]
I have no idea





------------------ Original ------------------
From: Vitold69 ***@***.***&gt;
Date: Fri,Mar 1,2024 2:04 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] After the version update, thequality of China's ultra clear maps has seriously declined? (Issue #564)





 
Just curious. Is f.ng Chinese government still requires to shift map coordinates?
