### ISSUE TITLE
Macafee antivirus keeps quarantining core.dll

### ISSUE THREAD

**Issue by lemecdewigan** [derekhe/msfs2020-map-enhancement#566]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Macafee anti virus keeps quarantining the file  "core.dll"   in the enhancement tool version 7.5.3

**Comment by Diminou82** [comment]
Same for me, I try to add all the repository inside the white zone of macafee but each time i launch the MSFS enhancemement software, the core.dll goes to quarantine.

**Comment by lemecdewigan** [comment]
Seems there's no solution ? so I've deleted the enhancement tool from my system

**Comment by derekhe** [comment]
That's the antivirus program's issue and I have no idea about them.
