### ISSUE TITLE
Comment  être certain que j'ai bien la carte google Mapp et non celle de Bing

### ISSUE THREAD

**Issue by Fred870555** [derekhe/msfs2020-map-enhancement#569]
Bonjour, j'ai installé comme  indiqué  sur la procédure d'installation  MSFS2020 Map Enhancement. 7.5.4  et Je n'ai aucun message d'erreur. En revanche, je n'arrive pas à être certain que j'ai bien les cartes Google Mapp et non celles de Bing.
Existe t-il un moyen de le vérifier?
Merci pour votre précieuse aide.
Bien cordialement
Fred

**Comment by derekhe** [comment]
Please have a look the user manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
