### ISSUE TITLE
it did not work for me

### ISSUE THREAD

**Issue by ModSaturn** [derekhe/msfs2020-map-enhancement#570]
Hey thanks for this amazing tool, but it did not work for me i followed all the instruction , still getting the msfs game map! any idea ?
Cheers

**Comment by derekhe** [comment]
Please follow the manual and check every settings: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Comment by ModSaturn** [comment]
alright i think it will not work cause my game can only works offline .
