### ISSUE TITLE
WHAT ABOUT MY LICENSE SHIPPING I PAID 2 TIMES 5 DOLLARS PLEASE SEND ME MY ACTIVATED PACKAGE NOW

### ISSUE THREAD

**Issue by capiadrian** [derekhe/msfs2020-map-enhancement#571]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by capiadrian** [comment]
WHAT ABOUT MY LICENSE SHIPPING I PAID 2 TIMES 5 DOLLARS PLEASE SEND ME MY ACTIVATED PACKAGE NOW

**Comment by capiadrian** [comment]
helloooooooo

**Comment by capiadrian** [comment]
WHAT ABOUT MY LICENSE SHIPPING I PAID 2 TIMES 5 DOLLARS PLEASE SEND ME MY ACTIVATED PACKAGE NOW

**Comment by capiadrian** [comment]
pleaseeee hellpppp

**Comment by derekhe** [comment]
There is a new process and please follow: https://github.com/derekhe/msfs2020-map-enhancement/wiki/License
