### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BrokenGabe** [derekhe/msfs2020-map-enhancement#572]
What is the license for, i'd have no problem paying to help support this little project, but I don't see what the license is actually for, what does features does this unlock? no descrption for license use.

**Comment by psouthan** [comment]
I'd like to know the answer too! I'd also like to know do you have to link your license everytime you start MSFS 2020?

Thanks 

Paul

**Comment by derekhe** [comment]
No, just once.

**Comment by derekhe** [comment]
> What is the license for, i'd have no problem paying to help support this little project, but I don't see what the license is actually for, what does features does this unlock? no descrption for license use.

For features and maps marked as Pro

**Comment by psouthan** [comment]
Thank you for your response.

Paul
