### ISSUE TITLE
Proxy Connection in China.

### ISSUE THREAD

**Issue by psouthan** [derekhe/msfs2020-map-enhancement#574]
Hello, Please can you help? I have a licence for Google Map Enhancement. I live in China. I use a VPN, but this renders my connection slower than normal. 

Please can you tell me how to set up a proxy (whatever that is) so that I can connect to the goole map servers without using my VPN, or rather where on earth do I get a proxy address from?

Many Thanks

Paul

**Comment by derekhe** [comment]
The Chinese manual is here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-CN#614-proxy-settings
If you use VPN, please use exclude this app and setup a socks or http proxy for this app.
The proxy setting should be figured out by yourself and I have no addition support for it.
