### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yiahn0314** [derekhe/msfs2020-map-enhancement#575]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version: 365days

**Device ID**
- Device ID: yiahn0314@naver.com

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
![K-003](https://github.com/derekhe/msfs2020-map-enhancement/assets/45083106/821a007b-d93d-49f5-b111-cd4aa296b7e5)

**Comment by yiahn0314** [comment]
![K-004](https://github.com/derekhe/msfs2020-map-enhancement/assets/45083106/5f171229-386a-41aa-84f2-97bf99152d27)
![K-005](https://github.com/derekhe/msfs2020-map-enhancement/assets/45083106/f9231213-07eb-4447-93e6-042cc6a0deb6)
![K-006](https://github.com/derekhe/msfs2020-map-enhancement/assets/45083106/8d3c8abe-3b7e-465c-91b8-a65f5ea48444)

**Comment by yiahn0314** [comment]
Pls find the way to install your product without failure.
And if is mot possible, I want to refund my payment ASAP.

**Comment by derekhe** [comment]
Could you try upgrade to 7.5.5?

**Comment by BurnleyNuts** [comment]
Hi, I have exactly the same issue. My program was working fine until I updated to V7.5.3. I saw the new version is available as mine auto updated anyway so hoped it might cure the problem. I installed v7.5.5 but still have the same as above and I've tried the solutions mentioned also.

**Comment by BurnleyNuts** [comment]
Not here, my Norton came up with a 'this product doesn't have a digital signature' message I think. I've reinstalled with firewall and anti virus off but just get the same error. It went on to auto install v3.5.5 also.

**Comment by derekhe** [comment]
These old antivirus software always have issue. Please try to disable them or add software to whitelist.

**Comment by BurnleyNuts** [comment]
It's not my firewall or anti virus, I've had everything turned off and also allowed the MSFS Map Enchancement program in the white list too. The probgram isn't being blocked by firewall.

**Comment by yiahn0314** [comment]
Even though, when I disable the all kinds of antivirus, the result is the same error conditions.
So, Pls refund to my account ASAP.
Thanks
-----Original Message-----

**Comment by yiahn0314** [comment]
Hi, My problem is the exactly same with you.
-----Original Message-----

**Comment by yiahn0314** [comment]
I already upgrade to the newest version of 7.5.5.
But the result is the same as before.
-----Original Message-----

**Comment by derekhe** [comment]
Sorry I have no idea about this issue now and if you paid, please ask write an email to hesicong@gmail.com and ask for refund.
