### ISSUE TITLE
Using Map Enhancer leads to high CPU temperature

### ISSUE THREAD

**Issue by DocScotti** [derekhe/msfs2020-map-enhancement#578]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Using map enhancer leads to high temperature while the flight is loading.>95°C
Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
7.5.3
**Device ID**
-JGERPAFZN5TMWVJQF75VX3PT01VJ43GMS8KEDH5ZY7WNFDSMEFE0

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please upgrade your CPU or CPU cooling system.

**Comment by DocScotti** [comment]
I am having a I9-11900K and a watercooling.When I changed the settings to load HD Images only in flight,it became better.

**Comment by derekhe** [comment]
Cool
