### ISSUE TITLE
Map updates in "World Map" but not in game

### ISSUE THREAD

**Issue by JackoKemp** [derekhe/msfs2020-map-enhancement#579]
**Describe the bug**

I have followed the steps in the manual and checked all settings. Everything including loaded value increases as expected. I am online in game. When I click on the world map I can see all the updated maps (I am using google) as expected. When I load into game the map does not reflect what I saw on the world map. Everything seems to be the old maps. I definitely started the software before MSFS.

**Map Enhancement version:**
Google Maps Server

Please help.

**Comment by derekhe** [comment]
I think it is photogrammetry data which covers the satellite images.
You can try disable photogrammetry  in the game setting and see if any thing changed.
