### ISSUE TITLE
Apply Hosts Change Failed Issue

### ISSUE THREAD

**Issue by OkalayaYT** [derekhe/msfs2020-map-enhancement#580]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

I keep getting this annoying error when I click the start button, and I did everything that the error message told me, and also trying everything AV Related.

**Map Enhancement version:**
- 7.5.5

**Device ID**
- 7QHVBA7M9MCNE1MSRYH29CJ7WDTWSYV4JZKT3TXATG1S49AAAM9G
**Screenshots**

![Captura de pantalla 2024-02-18 201513](https://github.com/derekhe/msfs2020-map-enhancement/assets/160411858/640fc945-90a8-45ab-ab24-4374857d3761)

**Additional context**
Please Tell me what's the problem and how to solve it.
Thanks.

**Comment by derekhe** [comment]
Please try disable any hosts protect feature in AV.

**Comment by OkalayaYT** [comment]
I have Kaspersky and I don't find any hosts thingy

**Comment by derekhe** [comment]
https://www.google.com/search?q=Kaspersky+hosts+file+lock&oq=Kaspersky+&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDsyBggCEEUYOTIKCAMQABixAxiABDINCAQQABiDARixAxiABDINCAUQABiDARixAxiABDIKCAYQABixAxiABDIKCAcQABixAxiABDIGCAgQRRg80gEIMzM2OGowajGoAgCwAgA&sourceid=chrome&ie=UTF-8

**Comment by derekhe** [comment]
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/1734077/c11abe16-59f6-4a83-863b-799a42321626)
