### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by tkemp238** [derekhe/msfs2020-map-enhancement#582]
I'm not getting an error but MSFS just doesn't load. The image shows that this is all I get when I run your app. I disabled virus and firewall. Uninstalled virus. Tried the Proxy server but still get nothing. I made sure MSFS cache is ruened off and Bing Map and Photogametry are both loaded. Everything worked fine before I had to reinstall windows 11 and reinstall MSFS, so I am not sure what else to do,

![failed](https://github.com/derekhe/msfs2020-map-enhancement/assets/154404856/3cd8e218-c476-4ef5-bf1d-a8ccf7dc541b)
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by Vitold69** [comment]
Looks like after reinstalling Windows there is no access to the hosts file. Have you checked what's inside hosts file when you start the program?

**Comment by tkemp238** [comment]
I have not. What should I be looking for exactly?

Troy

**Comment by Vitold69** [comment]
The hosts file must contain the following lines AFTER you start the msfs2020-map-enhancement:
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

If not this means the program doesn't have access to hosts file.

**Comment by tkemp238** [comment]
This is what I have:

#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

**Comment by Vitold69** [comment]
Then I don't know. Ask comrade Derek

**Comment by derekhe** [comment]
Please check if the settings is correct: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#4-use
