### ISSUE TITLE
Conflict with Fenix A320 Block V2?

### ISSUE THREAD

**Issue by yuinma** [derekhe/msfs2020-map-enhancement#584]
After many times test, I found Map enhancement 7.5.6 made FNX320 V2 malfunctioned. I use proxy in Map enhancement. I don't know why.
Running MSFS without map enhancement, FNX320 V2 works well. 
Just ignore this report if I'm wrong, it's only a little clue for bug fix.

**Comment by derekhe** [comment]
It doesn't. There are lots of users using V2
