### ISSUE TITLE
DETAIL: Error: Reached Max retry

### ISSUE THREAD

**Issue by Feifan1010** [derekhe/msfs2020-map-enhancement#586]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
The bug happens every time after 7.5.6 update.
Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version
7.5.6
**Device ID**
- Device ID
7EB24053-9042-4DD9-A5BE-D9FCFA3C6E18
**Screenshots**
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/124132006/ad42a663-d5e7-4dc0-92cc-7e6c3df964bc)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please try the mentioned solutions on the dialog.

**Comment by TSKSmile** [comment]
i have the same issue, and i have followed each step in the dialog (multiple times)...

**Comment by JCLG2823** [comment]
Hello the team of MSFS2020 Map Enhancement.
After the v7.5.9 just released=>Same issue for me and follow each step....

**Comment by JCLG2823** [comment]
Hello everyone,
Solved when reinstall v7.5.9...
