### ISSUE TITLE
Hybrid Map problem

### ISSUE THREAD

**Issue by CharlesHill56** [derekhe/msfs2020-map-enhancement#587]
I have created a new Hybrid map but when I save it and copy it to the Map Enhancement program folder it doesn't work
Am I doing something wrong?
I get the error that the cache file is missing but its not

**Comment by derekhe** [comment]
Please paste the config and your device id

**Comment by CharlesHill56** [comment]
I found out what was wrong, in the properties of my new region I put in “uk&Ireland” instead of just “map”
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/70275344/f5d1a14e-f48e-4a81-b0a6-f47ec407321b)
Thanks for your help!
