### ISSUE TITLE
Some airport ground texures was covered by satellite images.

### ISSUE THREAD

**Issue by martin0607** [derekhe/msfs2020-map-enhancement#588]
No matter which map i use, there will always be some airport ground textures covered by satellite images, whether it's bing or Google maps.
I have upgraded to the latest version 7.5.8, and cleaned in-build cache.
All settings are default, But i dont know if this is a network issue or MSFS issue.

Here are some screenshots, this situation can also occur at other airports.
LOWK:
![Microsoft Flight Simulator Screenshot 2024 03 08 - 21 47 26 37](https://github.com/derekhe/msfs2020-map-enhancement/assets/32560181/eaab1d11-78d9-4bd8-a80a-ff8a866a928d)
![Microsoft Flight Simulator Screenshot 2024 03 08 - 21 47 36 29](https://github.com/derekhe/msfs2020-map-enhancement/assets/32560181/f74c2248-1b58-4d2a-9127-7c40e401277f)
GCXO:
![Microsoft Flight Simulator Screenshot 2024 03 09 - 17 50 14 00](https://github.com/derekhe/msfs2020-map-enhancement/assets/32560181/cf8b23b6-d93f-4fd6-b54e-645406f8db6c)

**Comment by utkrishtm** [comment]
Happens to me as well. my entire airport gets covered by the satellite images. Once I land the 3rd party airport loads in and the entire elevation data screws the landing over. 

https://github.com/derekhe/msfs2020-map-enhancement/issues/589#issue-2177445478

**Comment by derekhe** [comment]
This is a known DX12 issue. I can't fix it until MSFS fix it.

**Comment by utkrishtm** [comment]
not sure if you are also answering my issue here, but i'm not running dx12 nor SU15

**Comment by derekhe** [comment]
It happens for some people and I don't see it at my end. Don't know if something gets wrong for 3rd party airports.
