### ISSUE TITLE
Airport Elevation issues

### ISSUE THREAD

**Issue by utkrishtm** [derekhe/msfs2020-map-enhancement#589]
**Before you raise a bug**

[X] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[X] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

When I am coming in for a landing there are always elevation issues as the application prevents the 3rd party airports from loading in and when I land they load in which causes elevation issues. It doesn't matter which map I use and happens every single time especially recently. 

**Map Enhancement version:**
7.5.8(pro)

**Device ID**
0R97EWXY6N5HHTXC0VFP70KR7NYD0F0P1VNW1WRX3BXPVCG4VPCG

**Comment by utkrishtm** [comment]
@derekhe please, can you respond?

**Comment by derekhe** [comment]
I have no idea about this. Maybe the photogrammetry data is wrong. Could you paste some screenshots?

**Comment by utkrishtm** [comment]
yup let me get some
