### ISSUE TITLE
Image server test failed

### ISSUE THREAD

**Issue by Jacky737737** [derekhe/msfs2020-map-enhancement#591]
Hello,  I cannot connect to any Server, but Apple Maps.

Using MAP Enhencement 7.5.9 (Pro)
Even with diabled ESET AntiVir Firewall, it does not connect.
My Hosts File looks like this:

127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net
127.0.0.1 kh.ssl.ak.tiles.virtualearth.net
127.0.0.1 t3.ssl.ak.tiles.virtualearth.net
127.0.0.1 t2.ssl.ak.tiles.virtualearth.net
127.0.0.1 t1.ssl.ak.tiles.virtualearth.net
127.0.0.1 t0.ssl.ak.tiles.virtualearth.net
127.0.0.1 khstorelive.azureedge.net

I have no Clue, why is that not workin.

Unable to access remote image server

If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.
If you are using a proxy to connect to the remote server, please ensure that the proxy is working.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.

**Comment by derekhe** [comment]
I don't know. Can you open google or bing maps in your browser?

**Comment by Jacky737737** [comment]
Thank you hesicong, its workin now. I guess it was a Firewall Problem. RegardsGesendet mit der mobilen Mail AppAm 23.03.24 um 04:05 schrieb hesicong
                
            
            
                
                    Von: "hesicong" ***@***.***>Datum: 23. März 2024An: "derekhe/msfs2020-map-enhancement" ***@***.***>Cc: "Author" ***@***.***>,"Jacky737737" ***@***.***>Betreff: Re: [derekhe/msfs2020-map-enhancement] Image server test failed (Issue #591)
                
                
I don't know. Can you open google or bing maps in your browser?
