### ISSUE TITLE
backend issue 

### ISSUE THREAD

**Issue by CLAUXlol** [derekhe/msfs2020-map-enhancement#592]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

backend server start failed. done everything 

**Map Enhancement version:**
7.5.9 - Map Enhancement version

**Device ID**
idk? - Device ID

**Screenshots**

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/69122539/b4b0d6a1-10f1-4f41-97b2-fecbe470cff9)

**Additional context**
yesterday was working fine randomally stopped. cant play msfs without it since my msfs photo grammerty wont load at all

**Comment by derekhe** [comment]
I don't have any other recommendations. Please follow the instructions mentioned.

**Comment by CLAUXlol** [comment]
i already tried the suggested instructions. nothing happened still got the issue

**Comment by HeliMan** [comment]
Same problem in my case. I can't start any map server. Always problem with write even though permission is set.

**Comment by alanbeasy** [comment]
Hi Derek,
I am loving MSFS Map enhancement - but I have the same issue today.
I had to do a System Restore to before 7.5.9
When I opened Map Enhancement it did the update thing but then I got the message as shown by [CLAUXlol](https://github.com/CLAUXlol)
I tried 1, 3 and 4 but I don't know how to do number 2
![Screenshot 2024-03-18 170900](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/c00646c0-cc88-4c0d-83eb-b262da6cff6b)

What does Error: Reached max retry mean?

**Comment by derekhe** [comment]
Sorry for late feedback and please follow the steps here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#634-troubleshooting-backend-server-error

**Comment by alanbeasy** [comment]
OK Derek.  Done as instructed.
![Screenshot 2024-03-26 173750](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/0d694199-06dd-4676-bdc4-b052abe967c4)
Error Message.
![MSFS2020 Map Enhancement error ](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/a8807049-4cd0-4dd7-9d4b-3798d2b0235c)

**Comment by derekhe** [comment]
There is an issue with .net runtime and please reinstall the .net frameworks&nbsp;https://dotnet.microsoft.com/en-us/download/dotnet/





------------------ Original ------------------
From: Fearless Swan ***@***.***&gt;
Date: Tue,Mar 26,2024 2:40 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] backend issue  (Issue #592)





 
OK Derek.  Done as instructed.
 Screenshot.2024-03-26.173750.png (view on web)
 Error Message.
 MSFS2020.Map.Enhancement.error.png (view on web)

**Comment by alanbeasy** [comment]
Thanks Derek,  But please be more specific.
Your link goes here.
![Downloads](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/df0b7da6-c5d5-4120-8196-f39e59608f35)
If I select .NET 8.0 (Latest) it goes here:
![Options](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/096fcb1b-f025-464c-b985-bd57a3ef94a9)

Then what???  Which of all these do I select for your app?
Yesterday I installed Desktop Runtime 7.0.17 to make to open another app but the developer specified it so I knew. 
![Screenshot 2024-03-26 173750](https://github.com/derekhe/msfs2020-map-enhancement/assets/123238286/842e7411-3958-48a7-97c9-7a2619e1669d)
