### ISSUE TITLE
LOWW, step in runway 34

### ISSUE THREAD

**Issue by SkyDog** [derekhe/msfs2020-map-enhancement#595]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

I did, raising the terrain LOD to 400 didn't change anything.

**Describe the bug**

I think the screenshot says it all ... theres a step across the runway 34 @ LOWW which causes the aircraft to crash.

![Screenshot 2024-03-24 161925](https://github.com/derekhe/msfs2020-map-enhancement/assets/554751/04d7d5dd-5cdf-487b-b5fa-b6fa18c61a6b)
![Screenshot 2024-03-24 162022](https://github.com/derekhe/msfs2020-map-enhancement/assets/554751/4034a6c6-57c0-4233-af0c-b72c4127ace2)

**Map Enhancement version:**
7.5.9

this isssue is related to the map enhancement tool, doesn't appear without it. clearing cache didn't change anything. Using Bing or Google just changed the textures, not the step in the terrain. Might be related to the blurry texture buf which was reported earlier this year @ LOWW. I am runnig DX11, default scenery.

**Comment by derekhe** [comment]
Please turn off the photogrammetry data and try

Thomas ***@***.***>于2024年3月25日 周一01:46写道：

**Comment by SkyDog** [comment]
> Please turn off the photogrammetry data and try

That worked, step disappeared. But I think that is nothing you can fix on your side?

**Comment by derekhe** [comment]
Yes I can't fix it. MSFS need to fix this.
