### ISSUE TITLE
[Feature] Update Rejection: Update too frequent

### ISSUE THREAD

**Issue by huajidawang666** [derekhe/msfs2020-map-enhancement#598]
#### Motivation

The version is updated very frequently. I wish I had the option to skip the updates instead of being forced to update to the next version.

#### Detailed design

Have the option to skip the updates

#### Alternatives

Datapack update or an update executable, instead of downloading the whole update/installer from Github

**Comment by derekhe** [comment]
Aha thanks for the feedback. This is because issues are fixed and guys have
old versions asked same issue and I needs lot of effort to do the
communication. So I’d rather update to latest versions and save the time to
do development.

Huajidawang666 ***@***.***>于2024年3月31日 周日10:30写道：

**Comment by huajidawang666** [comment]
Thanks derekhe and your feedback. :D
Anyway its ok to keep updated and the software is very good.
Thanks for your devotion.
