### ISSUE TITLE
Apple Maps issue

### ISSUE THREAD

**Issue by pilotadam85** [derekhe/msfs2020-map-enhancement#602]
Hi, i have experienced weird issue with Apple Map pro today.
I noticed today only that some airports in Greece  inner textures is blurry i have attached some pictures to show you what's happening.
the same airports where working fine with no texture issues yesturday

Many Thanks.

**Map Enhancement version:** 7.5.12

![1](https://github.com/derekhe/msfs2020-map-enhancement/assets/166574665/ebe56a6a-4035-4f03-881c-1c413b7a91f7)
![2](https://github.com/derekhe/msfs2020-map-enhancement/assets/166574665/7a2fbb72-0681-474b-88c4-eb2e432daa49)
![3](https://github.com/derekhe/msfs2020-map-enhancement/assets/166574665/44ab7dea-2842-4d95-a400-93b8c52a9439)

**Comment by derekhe** [comment]
I guess there are some areas (military areas?) map provider blurred them in purpose.

**Comment by pilotadam85** [comment]
Hello Derekhe,
Thank you for the clarification
