### ISSUE TITLE
Init cache error

### ISSUE THREAD

**Issue by stratte89** [derekhe/msfs2020-map-enhancement#603]
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/101955267/b6cb8886-cea4-41f0-bd6a-c7c358d4f847)

How do I fix it? If I start the sim without the Enhancement mod, no map appears ingame and its buggy, even after deinstalling map enhancement. I need to fly right now, how to fix?

**Comment by derekhe** [comment]
Upgrade to latest version and setup a cache
