### ISSUE TITLE
After update to 7.5.13 Pro connects to servers badly

### ISSUE THREAD

**Issue by SMN204** [derekhe/msfs2020-map-enhancement#604]
After upgrading to 13 connects to the servers only after several attempts. It was fine in version 12

**Comment by derekhe** [comment]
What's the exact error you see?

**Comment by SMN204** [comment]
![Init Cache Error](https://github.com/derekhe/msfs2020-map-enhancement/assets/60313040/82b8e1f4-f2c6-4302-96e1-2b1af2ab2550)
I have enough disk space
Cache size - 30Gb
![Cache size](https://github.com/derekhe/msfs2020-map-enhancement/assets/60313040/b67986a6-08a1-4070-8f5f-a7b32300ce30)

P.S now connected to the Google Map Pro1 server on the third try.
Also to Google Map Pro2
Maybe it's a problem just today... I'll look at it tomorrow.

**Comment by SMN204** [comment]
Just upgraded to 7.5.14.
It's better! It connects to the server on the first try!

**Comment by kimanzii** [comment]
7.5.14 doesnt work

**Comment by Yurchik-Yurbaz85** [comment]
> 7.5.14 не работает

Did you manage to fix the problem? Doesn't work for me either
