### ISSUE TITLE
New user with 7.5.14 version (PRO version)

### ISSUE THREAD

**Issue by Linlin97232** [derekhe/msfs2020-map-enhancement#605]
I am a new user.
First of all, installing MSFS Map Enhancement is OK
But I can't select these servers:
- Google Maps 1 Pro Server
- Google Maps 2 Pro server
- Google Maps server
I have this problem (see screenshot below)
I have no problem having Google Map from my web browser. It works fine on my PC.

What can I do please?

 👍 
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/167108832/a4ed1a63-f789-40af-9f1a-cc4d96c31f50)

**Comment by Linlin97232** [comment]
Sorry, I didn't specify: No proxy on my network.

**Comment by Linlin97232** [comment]
Hello,
I am on a french caribbean: island : Martinique
And my internet connection is Starlink.

**Comment by AFR7545** [comment]
Having this problem: 
![Capture](https://github.com/derekhe/msfs2020-map-enhancement/assets/95647260/ffc5134f-52f0-4477-83d8-45b653f3a453)

**Comment by Linlin97232** [comment]
here is my device ID, if you need it : 
9D9TA82Y21MRDW0D48JDY6YJJ4185XR2MZACBHX5EJWP4D2J9XEG

**Comment by Linlin97232** [comment]
For information, I tried to select the **new Bing serve**r, and I have also an issue.
But I can acces the Bing map spécify below on my explorer : 
_MSFS's Bing Map is quite old in the game. Selecting this will replace the Bing Map with the latest Bing Map (same as https://www.bing.com/maps/aerial)._
**Unable to access remote image server
If you are using Google Maps, please ensure that you can open https://www.google.com/maps in your browser. You may be blocked by Google due to a large number of requests.**

**Comment by Linlin97232** [comment]
Hello,
I installed a VPN and it seems to work now !!!
My IP address was blocked by google server

**Comment by AFR7545** [comment]
Now i'm realy tired of having issues when starting up the software: 
![Capture](https://github.com/derekhe/msfs2020-map-enhancement/assets/95647260/cc394bf7-83a5-408b-b9eb-addd80b83ae0)

**Comment by AFR7545** [comment]
now i'm cuntig: it's making at least 10 times from yesterday i reinstall the soft and trying to use it

**Comment by AFR7545** [comment]
SO??????????????? WHAT I'M SUPPOSED TO DO RIGHT NOW????????????????????????????????????????????

**Comment by Yurchik-Yurbaz85** [comment]
I have the same problem, nothing works, what should I do???

**Comment by kimanzii** [comment]
after selecting a map the screen just goes blank no way to know if there is an error or anything pls fix!

**Comment by derekhe** [comment]
This happens for the first time and I am investigating&nbsp;





------------------ Original ------------------
From: kimanzii ***@***.***&gt;
Date: Wed,Apr 17,2024 7:41 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] New user with 7.5.14 version(PRO version) (Issue #605)





 
after selecting a map the screen just goes blank no way to know if there is an error or anything pls fix!

**Comment by derekhe** [comment]
> Now i'm realy tired of having issues when starting up the software: ![Capture](https://private-user-images.githubusercontent.com/95647260/323140412-cc394bf7-83a5-408b-b9eb-addd80b83ae0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjA4NDQsIm5iZiI6MTcxMzM2MDU0NCwicGF0aCI6Ii85NTY0NzI2MC8zMjMxNDA0MTItY2MzOTRiZjctODNhNS00MDhiLWI5ZWItYWRkZDgwYjgzYWUwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEzMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWJhYmRkNWE2NDM5ODM3YzZiY2Y1ZjA0MWEyOGE0MTAwMDI3M2NjNjczN2FjZTYxNTI4MWRmNzAwMmNkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dzrlZmlW7XqoJWyPhZTiyDwiSUccympeE2TL52p8CeY)

I think this is due to the .net runtime, please reinstall them again.

**Comment by AFR7545** [comment]
> > Now i'm realy tired of having issues when starting up the software: ![Capture](https://private-user-images.githubusercontent.com/95647260/323140412-cc394bf7-83a5-408b-b9eb-addd80b83ae0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjA4NDQsIm5iZiI6MTcxMzM2MDU0NCwicGF0aCI6Ii85NTY0NzI2MC8zMjMxNDA0MTItY2MzOTRiZjctODNhNS00MDhiLWI5ZWItYWRkZDgwYjgzYWUwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEzMjkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWJhYmRkNWE2NDM5ODM3YzZiY2Y1ZjA0MWEyOGE0MTAwMDI3M2NjNjczN2FjZTYxNTI4MWRmNzAwMmNkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dzrlZmlW7XqoJWyPhZTiyDwiSUccympeE2TL52p8CeY)
> 
> I think this is due to the .net runtime, please reinstall them again.

wich i already do like almost 10x today...

**Comment by Yurchik-Yurbaz85** [comment]
Nothing helps!

**Comment by kimanzii** [comment]
> Please try https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.5.15

It works now thanks! I got a cache init error but i fixed this by putting my cache file size limit to 20 instead of 30!
