### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by MikeB7878** [derekhe/msfs2020-map-enhancement#606]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario 
Everything has worked fine until the latest update. Now I'm getting error message. I completed every step in trouble shooting and still getting error message. I have not changed anything on my PC.

**Map Enhancement version:**
- Map Enhancement version
7.5,15
**Device ID**
- Device ID
I don't know where to find
**Screenshots**
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/167589554/ade84f0f-52ac-4a76-8bd1-097b0c4192ed)
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/167589554/33513012-8b1c-42df-a6e9-aea14ca43c01)

Error 
Backend server start failed

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Please Help![](url)

**Comment by derekhe** [comment]
Why the core.dll can't be found? Could you check if the core.dll was deleted by antivirus?

**Comment by MikeB7878** [comment]
Thank you for the quick reply. And I apologize for my delayed response. After reinstalling nvidia drivers and reinstalling map enhancement app I was able to resolve the issue. Cheers!On Apr 19, 2024, at 11:03 PM, hesicong ***@***.***> wrote:﻿
Why the core.dll can't be found? Could you check if the core.dll was deleted by antivirus?
