### ISSUE TITLE
Cant Log into/Get onto my  PAID MAP ENHANCEMENT

### ISSUE THREAD

**Issue by Terrisc61077** [derekhe/msfs2020-map-enhancement#609]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN    (YES - Ive tried all soultions)

[] For license issue, I have read the readme
![Untitled](https://github.com/derekhe/msfs2020-map-enhancement/assets/57339951/c599a2f8-7fe9-4e4a-94ef-fca8aee66fac)
 in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe 

-Not able to connect to 

**Map Enhancement version:**

- Map Enhancement version 7.5.15
-

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
You can't use the same account for different machines. The previous one is blocked automatically. I removed the block and you can try again. If you intent to use in two machines, you need to buy two licenses.
