### ISSUE TITLE
Image Server Access Check

### ISSUE THREAD

**Issue by Captain-Sushi021** [derekhe/msfs2020-map-enhancement#61]
**Image Server Access Check**
Sever check show the Image Server Access Check fail 

**Screenshots**
![Image Server Access Check](https://user-images.githubusercontent.com/70376150/153859709-a7e7fbeb-5b95-459c-b02f-cb50e729df00.JPG)

**Desktop (please complete the following information):**
 - MSFS2020 version: msstore
 - MSFS2020 Version WU7

**Log** 
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8060380/error.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8060385/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8060387/renderer.log)

**Additional context**

**Comment by h0wardch3ng** [comment]
Switch to version 3.2.4

**Comment by derekhe** [comment]
Yes, please switch to 3.2.4

**Comment by derekhe** [comment]
Please also try 4.0.0
