### ISSUE TITLE
Cache issues 

### ISSUE THREAD

**Issue by Vitold69** [derekhe/msfs2020-map-enhancement#611]
What the hell is going on with the cache starting version 7.5.13? Cache is not recognized, not written properly to cache file and so on. 
Your every update works worse and worse!
Returned back to 7.5.12

The CPC is not happy! 😡

**Comment by derekhe** [comment]
What’s the exact the problem ?





------------------ Original ------------------
From: Vitold69 ***@***.***&gt;
Date: Tue,Apr 23,2024 10:13 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cache issues  (Issue #611)





 
What the hell is going on with the cache starting version 7.5.13? Cache is not recognized, not written properly to cache file and so on.
 Your every update works worse and worse!
 Returned back to 7.5.12
 
The CPC is not happy! 😡

**Comment by Vitold69** [comment]
The exact problem is the program do not want to wright to cache file. Every time I have to initialize cache file. And even after that program doesn't want to write to the cache file.
Can you please explain each point. What does it mean exactly. And please use English English not Chinese English. Thank you.

![7 5 17](https://github.com/derekhe/msfs2020-map-enhancement/assets/20175971/89690b06-45d7-4489-8d16-07656d780fe6)

**Comment by derekhe** [comment]
It is explained here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#4-use
My English is just that shit, sorry about that.
