### ISSUE TITLE
Device is blocked

### ISSUE THREAD

**Issue by fredaster8480** [derekhe/msfs2020-map-enhancement#612]
version 7 5 16
au lancement j ai parfois un blocage "device is blocked"
<img width="600" alt="pb map enhancement 2024-04-23" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/167841257/e181d830-1538-4e3d-977b-659d93b06aa1">
<img width="600" alt="pb map enhancement 2024-04-23" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/167841257/788ce8ff-60a0-4f4e-bc49-edd26b92e1a7">
quelle est la solution ?

**Comment by derekhe** [comment]
You can try restarting the application. This is caused by not connected to validation server.

**Comment by fredaster8480** [comment]
j'ai redémarré de nombreuses fois en mode admin ou non admin. Il y a toujours la même réponse échec 8 fois sur dix. Je trouve difficile de se servir de cette application qui fonctionne rarement qu'en pensez vous ?

**Comment by fredaster8480** [comment]
de redémarrage

**Comment by fredaster8480** [comment]
de restart de l'application

**Comment by derekhe** [comment]
Are you able to access this file? https://[gist.githubusercontent.com/derekhe/e667064c00003656e3d43908c3600d84/raw/73ece849e8004974bd3a590195eb4207a4243153/device-blacklist](https://gist.githubusercontent.com/derekhe/e667064c00003656e3d43908c3600d84/raw/73ece849e8004974bd3a590195eb4207a4243153/device-blacklist)

**Comment by fredaster8480** [comment]
quand je clique sur votre lien voila ce que j'obtiens est-ce cela que vous souhaitez ?
<img width="1132" alt="pb map enhancement 2024-04-24" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/167841257/45c19410-561f-4593-b405-866e06b8e00a">
bien cordialement

**Comment by fredaster8480** [comment]
depuis plusieurs jours toujours bloqué. je viens de désinstaller l'application  version 7.5.16 et de réinstaller. Le problème est toujours le même. que dois je faire ?

**Comment by derekhe** [comment]
Please try latest version.

**Comment by fredaster8480** [comment]
essai de 7-5-18 ne fonctionne 
<img width="597" alt="pb map enhancement v 7-5-18 2024-04-27" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/167841257/8bd428d6-ee30-4c02-b014-ca836b718bd0">
pas

**Comment by derekhe** [comment]
What's your device id in the license page?

**Comment by fredaster8480** [comment]
3AFJRYMDPWF3MPP7YKJ77QFK0ZXYX0X5KMAEK99GWPYSDNT96Y2G

**Comment by derekhe** [comment]
I have no idea and I think your network may have some trouble. I can't even see the remote logs which means your logs haven't been sent to the server.

**Comment by derekhe** [comment]
I have no idea and I think your network may have some trouble. I can't even see the remote logs which means your logs haven't sent to the server.

**Comment by fredaster8480** [comment]
Application verification failed

Verification failed.

Reason: Connect to verification server failed. Please try restart this app. Detail: L’adresse demandée n’est pas valide dans son contexte. (mirror.ghproxy.com:443).

c'est quoi "mirror.ghproxy.com:442" que veux dire ce message ?
bien cordialement

**Comment by derekhe** [comment]
This is the server address. I have 4 tries for 2 different server access, but in your case every attempt failed. If you can access the website I provided before, and have system proxy enabled you can try disable the system proxy.

**Comment by fredaster8480** [comment]
les acces demandés fait il y  a 4 jours : voici le résultat. Je n'ai pas de proxy.

<img width="1132" alt="pb map enhancement 2024-04-24" src="https://github.com/derekhe/msfs2020-map-enhancement/assets/167841257/e1de9701-ccbd-4766-99b6-78d89900100f">
 
Pour info votre application fonctionnait bien dans les versions precedentes; depuis il y eu dse maj de windows et votre version a changée. N'y a t rien de ce coté à regarder

**Comment by fredaster8480** [comment]
je suis toujours bloqué avec votre application.
je viens de voir sur le site avec votre application cela : 

[MSFS2020-Map-Enhancement-Setup-7.5.18.exe.blockmap](https://github.com/derekhe/msfs2020-map-enhancement/releases/download/v7.5.18/MSFS2020-Map-Enhancement-Setup-7.5.18.exe.blockmap)

Pouvez vous me dire à quoi cela sert, faut il l'installer en plus de l'autre appli. cela permet il de débloquer l'application ?
Merci d'avance pour votre explication
Bien cordialement

**Comment by derekhe** [comment]
You don’t need this file. It is used for auto updates&nbsp;





------------------ Original ------------------
From: fredaster8480 ***@***.***&gt;
Date: Fri,May 3,2024 2:17 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Device is blocked (Issue #612)





 
je suis toujours bloqué avec votre application.
 je viens de voir sur le site avec votre application cela :
 
MSFS2020-Map-Enhancement-Setup-7.5.18.exe.blockmap
 
Pouvez vous me dire à quoi cela sert, faut il l'installer en plus de l'autre appli. cela permet il de débloquer l'application ?
 Merci d'avance pour votre explication
 Bien cordialement

**Comment by fredaster8480** [comment]
bonjour je viens de faire des recherches. Pour faire fonctionner votre application il faut passer par un VPN. Savez vous comment éviter cela car les performances sont mauvaises ? Bien cordialement

**Comment by derekhe** [comment]
I have no idea. It depends on the network you are using.
