### ISSUE TITLE
Tiles not being downloaded PRO version

### ISSUE THREAD

**Issue by ypaul123** [derekhe/msfs2020-map-enhancement#614]
**Describe the bug**
LOD is very limited, can this be solved ??

Please help, my Terrain LOD is set to 300.

**Map Enhancement version:**
7.5.16
**Device ID**
PQ0VMR7K3V9PKNNAK6XSHF63KYA3EMAR8TDG417D2X2JMDXJ7540

![2024-04-24 18_17_08-Greenshot](https://github.com/derekhe/msfs2020-map-enhancement/assets/10437367/59692ac8-8831-4124-b8be-1ada884dfd1f)
![2024-04-24 18_17_13-Greenshot](https://github.com/derekhe/msfs2020-map-enhancement/assets/10437367/1d8fadf7-bb5b-4f60-a260-56703a5ba485)

**Comment by derekhe** [comment]
I think this is caused by photogrammetry data. The plane below is photogrammetry data and far ahead is satellite images. The can't be fixed.
