### ISSUE TITLE
7.5.18 (pro) - black squares appearing with Apple Maps (new to 7.5.18)

### ISSUE THREAD

**Issue by oodrdoo** [derekhe/msfs2020-map-enhancement#615]
![Screenshot 2024-04-27 174245](https://github.com/derekhe/msfs2020-map-enhancement/assets/18038856/dd03ce24-bd4c-4508-b35a-b2fe028632c8)
![Screenshot 2024-04-27 174436](https://github.com/derekhe/msfs2020-map-enhancement/assets/18038856/ef8a808b-0adc-46cb-8d1c-a7d31815bf47)
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
I've been using Apple Maps pretty much exclusively since purchasing the Pro version some months ago. However with ver 7.5.18 I get black squares both on the World Map and in the game. See screenshots (apologies for color balance - I run in HDR and getting this corrupts the screen grab).
![Screenshot 2024-04-27 175037](https://github.com/derekhe/msfs2020-map-enhancement/assets/18038856/95d1d48e-5d33-4571-a323-d1053a6a14d9)

**Map Enhancement version:**
7.5.18

**Device ID**
19M9JEKKW3VQ99PKHQMQWRMR09PKXB55V1H3FFZD4BESAXF9ATR0

**Screenshots**

**Additional context**

**Comment by derekhe** [comment]
What’s the location?

oodrdoo ***@***.***>于2024年4月28日 周日00:51写道：

**Comment by oodrdoo** [comment]
**It was a problem with the cache being incompatible with the one generated by v7.5.17**

I noticed when I went to try and answer your question of "_What's the location?_" that the squares, which were random, you could zoom in and out of the World Map and sometimes they would disappear and sometimes they would move location, but only ever seemed to be in the location that I flew the most, i.e. UK, USA and NZ. This made me wonder if the cache was to blame so I reset the cache and now no more squares :)

I'd already taken some screen shots for you to replicate so I've attached one of them in case you want to check. Here is the center of the UK (of course these no longer appear with the cache reset).

![Screenshot 2024-04-28 071944](https://github.com/derekhe/msfs2020-map-enhancement/assets/18038856/88a03728-0c14-4ab7-a6fa-e286bfa10e19)

and here is the world view

![Screenshot 2024-04-28 071845](https://github.com/derekhe/msfs2020-map-enhancement/assets/18038856/22dd25e5-0658-412e-a8c2-c6cdc53dc2a9)

**Comment by derekhe** [comment]
Good to know. I changed the tile size to be smaller so it won’t resize again and again. But I ignored the cache issue.😄 thanks for finding this out&nbsp;





------------------ Original ------------------
From: oodrdoo ***@***.***&gt;
Date: Sun,Apr 28,2024 2:34 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] 7.5.18 (pro) - black squaresappearing with Apple Maps (new to 7.5.18) (Issue #615)





 
It was a problem with the cache being incompatible with the one generated by v7.5.17
 
I noticed when I went to try and answer your question of "What's the location?" that the squares, which were random, you could zoom in and out of the World Map and sometimes they would disappear and sometimes they would move location, but only ever seemed to be in the location that I flew the most, i.e. UK, USA and NZ. This made me wonder if the cache was to blame so I reset the cache and now no more squares :)
 
I'd already taken some screen shots for you to replicate so I've attached one of them in case you want to check. Here is the center of the UK (of course these no longer appear with the cache reset).
 
Screenshot.2024-04-28.071944.png (view on web)
 
and here is the world view
 
Screenshot.2024-04-28.071845.png (view on web)
