### ISSUE TITLE
Error when initializing

### ISSUE THREAD

**Issue by alvocom** [derekhe/msfs2020-map-enhancement#616]
I tried loading the app and it generated these error messages:
Error

Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:

Run in administrator mode -ok
Close any software that occupies 443 or 42098 port -ok
Add this software into antivirus whitelist -ok
Completely reinstall this software-ok
Reinstall .NET Runtime and ASP.NET Core Runtime -ok
Visit FAQ page (Troubleshooting backend server error) and Issue page
Detail: Error: Reached max retry

I opened the FAQ and tested core.exe and it failed, as shown below
![Capturar](https://github.com/derekhe/msfs2020-map-enhancement/assets/83669961/ab2312c6-6010-48b5-9bee-72415e12f021)

Thanks

**Comment by derekhe** [comment]
I think you have some problem in the wmic service. Look can search how to fix wmic service issues.&nbsp;





------------------ Original ------------------
From: alvocom ***@***.***&gt;
Date: Wed,May 1,2024 10:49 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Error when initializing (Issue#616)





 
I tried loading the app and it generated these error messages:
 Error
 
Backend server start failed. You must fix this problem before you can use this software. Try the following and restart this application:
 
Run in administrator mode -ok
 Close any software that occupies 443 or 42098 port -ok
 Add this software into antivirus whitelist -ok
 Completely reinstall this software-ok
 Reinstall .NET Runtime and ASP.NET Core Runtime -ok
 Visit FAQ page (Troubleshooting backend server error) and Issue page
 Detail: Error: Reached max retry
 
I opened the FAQ and tested core.exe and it failed, as shown below
 Capturar.PNG (view on web)
 
Thanks

**Comment by alvocom** [comment]
I ran the command "winmgmt /resetrepository" and it worked again.

Thanks a lot for the help
