### ISSUE TITLE
Version 7.5.3 fonctionne pas

### ISSUE THREAD

**Issue by PACODEPLATA** [derekhe/msfs2020-map-enhancement#618]
Version 7.5.3 fonctionne pas
![Capture](https://github.com/derekhe/msfs2020-map-enhancement/assets/169400763/b03a89d4-b2f7-4c32-9520-9dbff1d91abc)

**Comment by derekhe** [comment]
Please find out the latest version: https://github.com/derekhe/msfs2020-map-enhancement/releases
