### ISSUE TITLE
Start Map Enhancement script

### ISSUE THREAD

**Issue by Sandman161** [derekhe/msfs2020-map-enhancement#620]
Hello,

Is there a way to start MAP-Enhancement through a batch script line? Something like:
start "MAP" "C:\Program Files\MSFS2020 Map Enhancement\MSFS2020 Map Enhancement.exe"

If I do this I see al kinds of strange lines appearing in my CMD window. I must be doing something wrong here. Thank you.

**Comment by derekhe** [comment]
If you run it in command line, there are some console outputs from the software, you can ignore them.

**Comment by Sandman161** [comment]
Hi Derek

 


Thanks, is there a way to suppress these?? 


 

Met vriendelijke groet,

Martin Graeff

06-288 49455

 

Groet,

Martin

 

Regards,

Marty Graeff

 

Van: hesicong ***@***.***> 
Verzonden: Wednesday, May 15, 2024 3:59 PM
Aan: derekhe/msfs2020-map-enhancement ***@***.***>
CC: Sandman161 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [derekhe/msfs2020-map-enhancement] Start Map Enhancement script (Issue #620)

 

If you run it in command line, there are some console outputs from the software, you can ignore them.

**Comment by derekhe** [comment]
I can't see the screenshots if replied by email.

**Comment by Sandman161** [comment]
You mean something like this…?



 

 

Met vriendelijke groet,

Martin Graeff

06-288 49455

 

Groet,

Martin

 

Regards,

Marty Graeff

 

Van: hesicong ***@***.***> 
Verzonden: Wednesday, May 15, 2024 4:09 PM
Aan: derekhe/msfs2020-map-enhancement ***@***.***>
CC: Sandman161 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [derekhe/msfs2020-map-enhancement] Start Map Enhancement script (Issue #620)

 

I can't see the screenshots if replied by email.
