### ISSUE TITLE
App not showing progress and loading the maps

### ISSUE THREAD

**Issue by alexandrewcs** [derekhe/msfs2020-map-enhancement#622]
I Followed all the instructions and installed the application. When I click the start button it satys steady with all the progress data stays in zero and nothing happens. I left it there for many minutes and it stays the same way. Can anybody help me?
![imagem_2024-05-19_153044583](https://github.com/derekhe/msfs2020-map-enhancement/assets/72309979/7acca943-cafc-4916-af2e-03af250453c1)

**Comment by derekhe** [comment]
Please read and follow the manual: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN

**Comment by Alessio828** [comment]
Da manuale errore 0 significa che il programma sta funzionando bene conferma ?

**Comment by derekhe** [comment]
To ensure functionality, open XPlane and initiate the flight sequence.

**Comment by Alessio828** [comment]
Non ho XPlane ma fs2020 . Ho avviato l'app e il volo mi dice errore 0 significa che sta funzionando bene corretto ?

**Comment by Alessio828** [comment]
![Uploading IMG20240526154406.jpg…]()

**Comment by derekhe** [comment]
Why do you use "X-Plane map enhancement". If you need MSFS, please use https://github.com/derekhe/msfs2020-map-enhancement/releases/tag/v7.6.0
