### ISSUE TITLE
Texture popups at airports - after deinstall of Map Enhancement no ingame Map anymore (broke the game)

### ISSUE THREAD

**Issue by stratte89** [derekhe/msfs2020-map-enhancement#624]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version: 7.5.19

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/101955267/79328004-73bf-4336-8a71-aa3bec9d7a99)

I got these weird graphic bugs on Airports, like popping texture tiles also after deinstalling map enhancement and starting the sim the whole map is gone and i am unable to play msfs2020 anymore even after a restart of the sim itself which took me forever it did not got fixed. so i assume i have to reinstall whole windows to uninstall the map enhancement mod?

**Comment by derekhe** [comment]
Please check the user manual&nbsp;





------------------ Original ------------------
From: stratte89 ***@***.***&gt;
Date: Thu,May 23,2024 10:50 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Texture popups at airports - afterdeinstall of Map Enhancement no ingame Map anymore (broke the game) (Issue#624)





 
Before you raise a bug
 
[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
 [] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/
 
Describe the bug
 
Please describe the bug in detail to help me understand the scenario
 
Map Enhancement version:
  
Map Enhancement version: 7.5.19
  
image.png (view on web)
 
I got these weird graphic bugs on Airports, like popping texture tiles also after deinstalling map enhancement and starting the sim the whole map is gone and i am unable to play msfs2020 anymore even after a restart of the sim itself which took me forever it did not got fixed. so i assume i have to reinstall whole windows to uninstall the map enhancement mod?

**Comment by stratte89** [comment]
I deinstalled it like in the manual but its removing the map in the sim. How do I fix that?

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#816-after-exiting-and-re-entering-the-game-the-game-loads-very-slowly-and-displays-the-default-image

**Comment by derekhe** [comment]
For this issue I think you should upgrade to su15 and it should be fixed. In dx12 there was a problem, MS fixed it in su15.

**Comment by stratte89** [comment]
> For this issue I think you should upgrade to su15 and it should be fixed. In dx12 there was a problem, MS fixed it in su15.

thank you, su15 indeed fixed the issue.

**Comment by stratte89** [comment]
> For this issue I think you should upgrade to su15 and it should be fixed. In dx12 there was a problem, MS fixed it in su15.

thank you, su15 indeed fixed the issue.
