### ISSUE TITLE
Detail: Error: Reached max retry

### ISSUE THREAD

**Issue by captdroch** [derekhe/msfs2020-map-enhancement#629]
Hi,
I have followed all suggestions fount in the English FAQ pages to no avail, when I launch the program I keep on getting an error message: Detail: Error: Reached max retry.
Could you please helmp me?
Many thanks in advance!
Best regards,
David

**Comment by derekhe** [comment]
Please have a look: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#844-troubleshooting-backend-server-error

**Comment by captdroch** [comment]
Thank you very much.That did the trick.
Kindest regards,
David

    Le jeudi 30 mai 2024 à 15:49:11 UTC+2, hesicong ***@***.***> a écrit :  
 
 


Please have a look: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#844-troubleshooting-backend-server-error

**Comment by Dman021** [comment]
I also have this issue and have followed the FAQ.  It appears the server starts and stops.   Please see image.  I didn't hit Ctrl+C to stop it.

![CMD screen](https://github.com/derekhe/msfs2020-map-enhancement/assets/171756967/9131e2fe-59e2-4010-ba92-6470e41f5726)

**Comment by derekhe** [comment]
The error message I got was: System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.

Maybe have a look at here? https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permissi
