### ISSUE TITLE
No pop up, not able to install

### ISSUE THREAD

**Issue by Bioride** [derekhe/msfs2020-map-enhancement#63]
**Describe the bug**
I followed all the instructions given in the installer and on the website. But the pop up didn't come up and hence the following error came up shown in the image below. I couldnt upload the log files like that so I uploaded them to drive and sent you the link to access it.

**Screenshots**
![image](https://user-images.githubusercontent.com/100061611/154830783-1505f246-b2ed-40d9-bba4-ce3cdb789338.png)

**Desktop (please complete the following information):**
 - MSFS2020 Version 1.22.2.0

**Log** 
Please provide the logs:
https://drive.google.com/drive/folders/1J2b-RQgFOSvj6fMD59SAK6-H7dwSvUHG?usp=sharing

**Additional context**

**Comment by h0wardch3ng** [comment]
1. Run as admin
2. UAC choose `allow`

**Comment by Bioride** [comment]
Doing that but its showing the same error

**Comment by h0wardch3ng** [comment]
Try
https://github.com/derekhe/msfs2020-map-enhancement/issues/65

**Comment by derekhe** [comment]
@Bioride how's going? fixed or not?

**Comment by derekhe** [comment]
Since long time no reply, I will close this.
