### ISSUE TITLE
How to run map enhancement in user mode for MSFS 2020

### ISSUE THREAD

**Issue by rob7282** [derekhe/msfs2020-map-enhancement#632]
My scratch-built Windows 10 system has two accounts--an administrator account and a user account. For security, I always log on to my user account (non-admin privileges) when using my flight simulator and for email and browsing.

I saw the video on YouTube from IslandSimPilot explaining how to use the map enhancement mod to bring in the latest BING maps. He states that it must be run in user mode, not as administrator. The link is: https://www.youtube.com/watch?v=WzWCfIfxUjs&t=99s

I installed the latest 7.6.1 mod. The issue is that when you install it, you have to provide admin credentials and also provide admin credentials when running the mod. 

I followed the directions by starting the mod, reviewing the settings as per the video, then starting MSFS 2020, and clearing the rolling cache and then re-creating the rolling cache. 

The mod does show that it is connected with the HIGH LOD and shows the data streaming in. 

When starting the flight, the old default BING map still appears. According to IslandSimPilot, if it is run as an administrator, the mod will not bring in the latest BING map--which is happening to me.

So, how does one install this mod without having to use admin credentials? I have looked up on YouTube ways to do this but they all fail.

Any suggestions? Thank you .

**Comment by derekhe** [comment]
This had to use admin
