### ISSUE TITLE
VPN incompatibilities

### ISSUE THREAD

**Issue by fredtostaky** [derekhe/msfs2020-map-enhancement#636]
Hello,

can't tell exactly since which version, but I'm using nordVPN and ME seem denied, or been denied access to the server with active VPN connection :

"Application verification failed
Verification failed.
Reason: Connect to verification server failed. Please try restart this app. Detail: L’adresse demandée n’est pas valide dans son contexte. (mirror.ghproxy.com:443)."

Precision if usefull : I'm able to ping this IP with the active VPN.

I tried to use "split tunneling" of nordVPN with MSFS + Map enhancement ; it's supposed to NOT use VPN connection but ME behaviour is the same, I suspect the split tuneling not to be very efficiency...

**Comment by derekhe** [comment]
I have no idea of these VPNs.
Some VPNs will hijack all traffic into VPN and it will cause problem. You can exclude the applications (MSFS+Map+core.exe)

**Comment by fredtostaky** [comment]
Well ok, I added core.exe that I didn't include in the first place but the message still the same.
I'll maybe make further investigation but for now I'll just deactivate it during playing.

**Comment by fredtostaky** [comment]
Hello derekhe,
I'll trying again to solve this VPN incompatibilities, as VPN are pretty widely used and, could be a pain in the ass to stop every thing else just for one app. Also, the messages in the last version make me think that is should not be complicated to find either a way not to use the VPN (split tunneling) is we can determine which process require straight connection, or an option in the VPN to allow Map Enhancement to works normally.

So with the last version, when my VPN is on, here the message in launching app :
"The connection to the verification server failed. Please try to restart this application or set agent"
Then if I try to push start anyway :
"Device or versions are blacklisted, and the application cannot be started. This problem may caused by connection failure to k.aiflygo.com, you can try VPN or restart the computer"

I already deactivate the VPN for the app MSFS Map Enhancement.exe the connection but still filtered.
Is the main process that access to this address using a web browser API or something ? That can be the case in some libraries.

Bye.
