### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by utkrishtm** [derekhe/msfs2020-map-enhancement#639]
**Before you raise a bug**

[X] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[X] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
I wanted to give this mod another try. I flew in KPHL and I tried different servers and no mod as well. 

The textures are broken and not as clear and crisp as they should be. Every time i restarted the sim, and cleared the cache and photogrammetry. I do not have rolling cache enabled. This happens many times but KPHL is my main airport so attached the images from there. 

Also sometimes the textures don't load up when I'm landing at an airport. Few mins after I land, all the textures start popping up and kills the immersion.

**Map Enhancement version:**
- Map Enhancement version 7.6.1

**Device ID**
- Device ID: B2PNDRY6TJD9RN7NA8TNEV1ZH8VT6G1GRXM7J9SS8SHQPHMGSDG0

**Screenshots**
This is using the google maps server
![googleMapsServer](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/56096316-8270-4859-9990-62529ab5653b)

This is using the bing maps latest server
![bingMapsLatest](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/62ae2b50-89e4-4102-804d-9e6352493a1a)

This is no mod just MSFS
![noMapEnhancementMod](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/57ee3ae4-4fce-416e-82eb-62aa2ab03d40)

**Comment by derekhe** [comment]
I added the cache toggle and you can turn off the cache in 7.6.2. Please try the latest version.

**Comment by utkrishtm** [comment]
Ok, thanks. I will test it out and let you know.

**Comment by utkrishtm** [comment]
I did the same tests as earlier. I am attaching the screenshots of the game and including the mod app as well. Please let me know. I turned off the cache as well and tried both HighLOD and no HighLOD

![img1](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/afda72c6-0653-4e15-9fc8-078af7d7f74b)
![img2](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/4f36cc44-3f38-4241-b129-86a75a743578)
![img3](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/e3ba30b8-1d4b-4648-869e-0e08c3e224f6)
![img4](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/ae59c200-f35a-443e-ae4d-fd68407ac941)
![img5](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/42059853-b537-42d9-91bf-4fdbd788e6e4)

These two images are without the mod running normal maps from MSFS
![img6](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/abeb413a-61c0-4fbd-85e5-bd9217d71b88)
![img7](https://github.com/derekhe/msfs2020-map-enhancement/assets/69091189/a3c53eec-2947-4088-aa26-35b97f48b34b)

**Comment by derekhe** [comment]
You can try tune the network settings from enhanced to normal. Some people faced this problem before and changed the settings to fix this problem.

**Comment by utkrishtm** [comment]
Hey, all these have been on the normal settings.

**Comment by derekhe** [comment]
The you switch to enhanced to have a try





------------------ Original ------------------
From: utkrishtm ***@***.***&gt;
Date: Fri,Jun 7,2024 1:30 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Broken Textures (Issue #639)





 
Hey, all these have been on the normal settings.

**Comment by utkrishtm** [comment]
Same issue in enhanced. The original pics were in normal mode. The updated images are in enhanced.

**Comment by derekhe** [comment]
Then I think you can wait for a while to load the photogrammetry data. You can turn on the in game rolling-cache so that the photogrammetry data can be cached for faster loading.

**Comment by utkrishtm** [comment]
Ok i will try that and let you know if it works
