### ISSUE TITLE
Getting tons of errors like the nginx server is down.

### ISSUE THREAD

**Issue by techieferret** [derekhe/msfs2020-map-enhancement#64]
localhost:39871/last…ge?rnd=1645373233:1 GET http://localhost:39871/last-image?rnd=1645373233 net::ERR_CONNECTION_REFUSED
Uncaught (in promise) RequestError: connect ECONNREFUSED 127.0.0.1:39871
Tried turning off firewall.  Didn't resolve the issue.
I do have 2 servers running on this machine.  BlueIris and Homeseer.  Neither use that port.
Nginx logs show issue.  Not sure what to do about it.
ps.  I am running the beta MSFS update 8.
First error when starting up MSFS: localhost:39871/last…ge?rnd=16
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8104454/error.log)
45376087:1 GET http://localhost:39871/last-image?rnd=1645376087 net::ERR_NETWORK_CHANGED

2022/02/19 17:31:14 [info] 54660#6636: *183 SSL_do_handshake() failed (SSL: error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac) while SSL handshaking, client: 193.118.53.202, server: 0.0.0.0:443
2022/02/19 17:45:57 [info] 54660#6636: *140 client 127.0.0.1 closed keepalive connection
2022/02/19 17:54:50 [info] 54660#6636: *306 client 127.0.0.1 closed keepalive connection
2022/02/19 18:02:37 [info] 54660#6636: *382 client 127.0.0.1 closed keepalive connection
2022/02/19 18:02:45 [error] 54660#6636: *465 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh0231130102013000001.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://[::1]:39871/tiles/akh0231130102013000001.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
2022/02/19 18:02:45 [error] 54660#6636: *465 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh0231130102013000001.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://[::1]:39871/tiles/akh0231130102013000001.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
2022/02/19 18:02:45 [error] 54660#6636: *465 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: kh.ssl.ak.tiles.virtualearth.net, request: "GET /tiles/akh0231130102013000001.jpeg?n=z&g=9591 HTTP/1.1", upstream: "http://[::1]:39871/tiles/akh0231130102013000001.jpeg?n=z&g=9591", host: "kh.ssl.ak.tiles.virtualearth.net"
Update: Managed to fix one problem.  You need a port conflict lookup to change the web port of nginx if there's already another port 80 program running.
But I still have issues with it injecting images into the update 8 version.  It's refusing the connection and then it'll kick into offline mode.

**Comment by h0wardch3ng** [comment]
Try
https://github.com/derekhe/msfs2020-map-enhancement/issues/65

**Comment by techieferret** [comment]
Ok.  Done.  Still not importing any google scenery.  Tried auto inject and that's where the conn refused starts showing up.
I'm not sure how other people are getting this to work, but I never have gotten it to work.  Even the previous versions.

**Comment by h0wardch3ng** [comment]
Try to close all firewalls
BTW, was the program previously prompted to allow self-signed certificate creation when it first started?
![image](https://user-images.githubusercontent.com/2175497/155144412-7b89570c-a196-4b41-83f1-ca1bc6a595e8.png)

**Comment by derekhe** [comment]
@techieferret could you try uninstall and install latest version?

**Comment by derekhe** [comment]
Since no new reply until now, I will close this.
