### ISSUE TITLE
Fenix A320 is not able to fly with this Addon. The plane is Doing own movements which are Not able  to Control. Active sky or Fs realistic are not working with this addon.

### ISSUE THREAD

**Issue by germansimaviation** [derekhe/msfs2020-map-enhancement#640]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
The 

https://github.com/derekhe/msfs2020-map-enhancement/assets/171623960/5cd172eb-d7ee-4f4e-9f2e-e4aaf3a012da

Fenix A320 is not able to fly with this Addon. The plane is Doing own movements which are Not able  to Control. Active sky or Fs realistic are not working with this addon.

https://youtu.be/6X6JXD01Wm4?si=LcvXbaR5BSZno0vv Look at this shakings, and the Controls from the plane without Doing anything on my Joystick.

**Comment by derekhe** [comment]
Please ask fennix for help, doesn’t related to this mod

germansimaviation ***@***.***>于2024年6月5日 周三05:04写道：
