### ISSUE TITLE
Will not pass Integrity Check

### ISSUE THREAD

**Issue by Defender197** [derekhe/msfs2020-map-enhancement#646]
**Describe the bug**

I downloaded all 56 items in the Base Packages area. Placed them in a folder called "Base Packages" and ran the Integrity check. It is failing with 14 errors. All 56 files are indeed the Base Packages folder. Nothing is missing. I've even tried re-downloading a couple of the erroring files and replacing them. They are still erroring. I tried pushing forward and finished installing and setting everything else up, according to the instructions. The program opens and the tiles begin to load but then go beyond 50,000 tiles loaded and nothing happens, so I quit out of it, as per the instructions. 

**Map Enhancement version:**
1.04

**Screenshots**

![Screenshot 2024-06-06 115032](https://github.com/derekhe/msfs2020-map-enhancement/assets/171957885/7e21e199-bd92-4086-af60-c537a459bdf0)

Hopefully the screenshot attached.

**Comment by derekhe** [comment]
Could you take a whole screenshots of your files?
