### ISSUE TITLE
MSFS 2020 Map Replacement v4.0.0

### ISSUE THREAD

**Issue by Convair990A** [derekhe/msfs2020-map-enhancement#65]
When running  the app, In the Server Check , Nginx Server Acces Check  with orange dot wiht a white cross. Image Server Acces Check  with green dot OK.
MSFA2020 version CD´s of Aerosoft.

**Comment by h0wardch3ng** [comment]
C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement
Delete all files in this folder, and restart program again.

**Comment by francsal** [comment]
When I click on inject map, the Nginx Server Access Check is green, but the Image Server Access Check is orange with a white cross. I tried deleting the files on the roaming folder, but still the same. 

![image](https://user-images.githubusercontent.com/100436571/155759450-c0e6b223-9274-4d54-9b25-1187b8dd1abe.png)

**Comment by h0wardch3ng** [comment]
Please provide log files.

**Comment by francsal** [comment]
Ok, I had uninstalled it, reinstalled it to get the logs, and now it's got both greens. Let me test it out and I'll update here.

**Comment by derekhe** [comment]
Since all the problem solved, I will close this.
