### ISSUE TITLE
Issues Starting the Mod

### ISSUE THREAD

**Issue by drendon7** [derekhe/msfs2020-map-enhancement#650]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario
![Capture](https://github.com/derekhe/msfs2020-map-enhancement/assets/123046812/a34f74c5-0a4e-4250-a0b0-15a8228fd163)

I have unistall and reinstall several times, i have turned off the antivirus and still having the same issue when i press start to start the mod.  i keep getting this error, can you assist please..
**Map Enhancement version:**
- Map Enhancement version 7.6.2

**Device ID
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#85-hosts-file-issues
