### ISSUE TITLE
Google maps api blocked my ip adress

### ISSUE THREAD

**Issue by jamesbp106** [derekhe/msfs2020-map-enhancement#652]
**Before you raise a bug**

[✓ ] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[✓ ] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

It seems my IP address is blocked from viewing google maps satellite imagery,. my suspicion is that i use the map enhancent for many hours a day, and that google thinks i am abusing the maps API and banned me. I have attached screenshots showing that maps does not work in any form, (google maps, google earth, map enhancement) unless im connected to a VPN. I've tested this on several computers, and mobile devices and a VPN seems the be the only remedy.

**Map Enhancement version:**
- 7.6.2

**Device ID**
- VFG4Z67Q5KG168RPN5PTCACY5W30Y2QQDCXSARBTRQHX8R3C37N0

**Screenshots**
![Desktop Screenshot 2024 06 09 - 16 29 25 45](https://github.com/derekhe/msfs2020-map-enhancement/assets/140734991/35579953-c6fe-422e-aa9d-8f7d47c1fe5d)
![Desktop Screenshot 2024 06 09 - 16 30 20 24](https://github.com/derekhe/msfs2020-map-enhancement/assets/140734991/65bc1483-2a47-4c1f-b06c-f2f7a8382921)
![Desktop Screenshot 2024 06 09 - 16 25 48 78](https://github.com/derekhe/msfs2020-map-enhancement/assets/140734991/b72731da-ecd7-4a56-a832-5033727d5478)
![Desktop Screenshot 2024 06 09 - 16 24 39 02](https://github.com/derekhe/msfs2020-map-enhancement/assets/140734991/c679fc0d-41d2-4c20-9b33-70559314727b)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please use other pro maps.
