### ISSUE TITLE
Image server test failed.

### ISSUE THREAD

**Issue by jcuellars** [derekhe/msfs2020-map-enhancement#654]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

It started today not working Google Maps and the Bing (newest).

**Map Enhancement version:**
- 7.6.2 Pro
![1](https://github.com/derekhe/msfs2020-map-enhancement/assets/113217083/9f624883-d127-4741-a217-dde7260cba5d)

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by Roman4Eggg** [comment]
Arcgis The same problem

![MSFS2020_Map_Enhancement_fNduZckf0A](https://github.com/derekhe/msfs2020-map-enhancement/assets/149231146/f2c32f9e-a4af-46d6-b45c-e98248a398ba)
