### ISSUE TITLE
Backend Server start failed

### ISSUE THREAD

**Issue by anthonyh23791** [derekhe/msfs2020-map-enhancement#655]
I have tried installing and uninstalling various versions of the program. Every single one has given me the Backend Server start failed error. I have followed all of the steps on the FAQ and have had ZERO luck. I don't know what else to do at this point. I have also checked the core.exe and made sure it was in the exact place it needed to be as well as running the core.exe. I did not receive any errors. Any help would be appreciated.
![2024-06-13 01_09_13-Command Prompt](https://github.com/derekhe/msfs2020-map-enhancement/assets/172574114/c0fa10ac-c13d-4de9-b564-6c12d72de96f)

**Comment by derekhe** [comment]
How about the latest v8 version?
