### ISSUE TITLE
MSFS Offline when not using APP

### ISSUE THREAD

**Issue by Orishek** [derekhe/msfs2020-map-enhancement#656]
**Before you raise a bug**

[yes] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[yes] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

After installment of Map Enhancement I can't use MSFS without it. When I won't start the Map Enhancement and just turn on MSFS, MSFS fails to load data and switches me into offline mode. If I have Map Enhancement opened and not Started, MSFS just works fine. This is not wanted behavior as MSFS still should be usable without starting Map Enhancement mod program.

**Map Enhancement version:**
7.6.2

**Device ID**
Not needed

**Screenshots**

Not needed

**Additional context**
Not needed

**Comment by derekhe** [comment]
This normally happens when you shut down the computer directly. You must click "stop" before you shut down your computer.
To fix this you can open the app again and exit it should fix it automatically.

**Comment by bassmann200** [comment]
Hi,

This doesn’t help - unfortunately. I didn’t shutdown the computer without stopping the Server. I’ve already tried to reopen the App and exiting normally without success. The first issue that I have seen was with running App that no tiles were loaded when MSFS was open (tried in the World Map by selecting different departure Airports) and the „Loaded“ indicator in Homescreen always showed „1“ and „Error: 0“. MSFS always showed Offline Tiles even when switching on/off the Bing World Maps function in Data section of Settings.

BR
Andreas


That’s why I ended up in uninstalling the App but still have the issue in MSFS. However I’m going to give it another try as per your suggestion.

**Comment by bassmann200** [comment]
Re-entering The App and pressing start/Stop + exit App worked. Thanks for the advice!BRAndreasAm 13.06.2024 um 15:46 schrieb hesicong ***@***.***>:﻿
This normally happens when you shut down the computer directly. You must click "stop" before you shut down your computer.
To fix this you can open the app again and exit it should fix it automatically.

**Comment by Orishek** [comment]
Sorry for invalid bug report, in the end it was caused by global error on Bing's side, which resulted in online services issues...
