### ISSUE TITLE
MSFS Stuck in Offline Mode after Unistall Enhancement mod

### ISSUE THREAD

**Issue by Orishek** [derekhe/msfs2020-map-enhancement#657]
**Before you raise a bug**

[yes] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[yes] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

After unistalling Map Enhancement mod, my MSFS is stuck in completely broken state. I am permanently in offline mode, even though I have online functionality turned ON in Settings and MSFS looks like Online function works, however ground textures and autogen is from offline state. My network speed is more than sufficient. I have tried several restarts, without success... I have also tried deleting rolling cache, no success.

I have unistalled Map Enhancement mod exactly by manual, I do not have anything in hosts file, I have also deleted Map Enhancement folder from Roaming. However still MSFS is not loading Map data...

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
7.8.2

**Device ID**
not relevant

**Screenshots**

![20240613122521_1](https://github.com/derekhe/msfs2020-map-enhancement/assets/103373367/37ec25bc-c4e1-4766-aad9-7f3aab1e9f66)

**Additional context**

**Comment by bassmann200** [comment]
Same issue here. MSFS always Shows offline Ground texture no matter if Tool is Running or Not Even After uninstalling.

**Comment by derekhe** [comment]
This normally happens when you shut down the computer directly. You must click "stop" before you shut down your computer.
To fix this you can open the app again and exit it should fix it automatically.

**Comment by Orishek** [comment]
Sorry for invalid bug report, in the end it was caused by global error on Bing's side, which resulted in online services issues...
