### ISSUE TITLE
MSFS always displays stock (offline?) map

### ISSUE THREAD

**Issue by idunno2** [derekhe/msfs2020-map-enhancement#659]
**Describe the bug**
MSFS always displays stock (offline) map

Please describe the bug in detail to help me understand the scenario
Whatever i do (did steps in manual at least twice) it keeps putting in old maps.
REstarted cpu couple of times. Start mod first. All other mods disabled. Deleted hosts file, edited hosts file.

**Map Enhancement version:**

- Map Enhancement version 7.6.2

**Device ID**
- Device ID

**Screenshots**
![Desktop Screenshot 2024 06 13 - 16 02 38 11](https://github.com/derekhe/msfs2020-map-enhancement/assets/148231356/f28ed79c-68c6-4398-8443-f2332d19b210)

**Additional context**

**Comment by derekhe** [comment]
Please check with manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN

**Comment by idunno2** [comment]
I did, and i cant seem to solve it.

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#88-keep-getting-put-into-offline-mode-when-using-this-mod

**Comment by derekhe** [comment]
And you can set your region to us and have a try

**Comment by MajorTomKlaus** [comment]
I have the same problem! Cannot get any online map runnig

**Comment by EisernUnion** [comment]
Its just a coincidence with the outage of bing servers affecting any msfs service.

**Comment by MajorTomKlaus** [comment]
that means? never had this problem.

**Comment by idunno2** [comment]
have followed these steps outlined in the manual: Please have a look this video and set the value to 0: https://github.com/derekhe/msfs2020-map-enhancement/issues/389#issuecomment-1536191538

Set the software to Normal in Network Setting and try again.

**Comment by EisernUnion** [comment]
[idunno2](https://github.com/idunno2) wanted to uninstall map enhancement tool and got still oflfline charts .. but at the same time bing servers etc are offline and the "blurry" maps are connected to map enhancement which is the problem ... its just a coincidence

**Comment by idunno2** [comment]
I've setup the map enhancement to google server.

On Google earth it looks like this:
![Desktop Screenshot 2024 06 13 - 17 15 04 16](https://github.com/derekhe/msfs2020-map-enhancement/assets/148231356/ad11ceaa-ab28-4626-b0d9-87964f94313a)

Bing maps works fine through a browser.. : https://www.bing.com/maps?cp=52.465347%7E5.498471&lvl=13.2&style=h

**Comment by MajorTomKlaus** [comment]
It looks bad! I think there is a server problem! We should wait some time?

**Comment by idunno2** [comment]
This day of filming is wasted anyways.. :(

**Comment by djlaui** [comment]
Hi,  i pass for this today too , what im do:
open map enhancement and see if cache is turn on , 
clear all caches and delete all caches and turn off cache , 
open msfs2020 and delete rolling cahce and restar fs2020
after that thing back normal i think 

hope this infos help

Thank you

**Comment by idunno2** [comment]
It must have been the Bing servers. I just tried different maps and they all work!
This thread may be closed. 
Thank you guys for suggesting it may be a server issue!

**Comment by djlaui** [comment]
For me too , i love this app , so good
But on my friend pc he dosent use right and try to unistall to back things on normal , 
Thank you

**Comment by MajorTomKlaus** [comment]
It work quite normal, unfortunately the Map Enhancement doesn´t creat any traffic, means no bing maps drwan from the app?
