### ISSUE TITLE
Nginx Server Access Check runs endlessly 

### ISSUE THREAD

**Issue by Tombstone0074** [derekhe/msfs2020-map-enhancement#66]
The circle symbol rotates endlessly and there is no error message either. After 15 minutes I stopped the whole thing.
Antivirus and firewall are turned off, host file works. No other program accesses port 443. 

<a href="https://ibb.co/B3SYqTK"><img src="https://i.ibb.co/mTMP6hF/Zwischenablage01.jpg" alt="Zwischenablage01" border="0"></a>

 - MSFS2020 Steam version, all updates done, simupdate 7
 
logs from: (INSTALLATION PATH)\resources\extra\nginx\logs
https://drive.google.com/file/d/14-JfkSzdw2BVwtcjDUYucMj_2ZsvjwsC/view?usp=sharing

**Comment by derekhe** [comment]
Please give me all the logs mentioned on the "Trouble Shooting" page.

**Comment by Tombstone0074** [comment]
Hi
Here are all the log files
thx
https://drive.google.com/file/d/19Kpt2F7MuUkwCpOBRtMzl5tcyhy_wKSl/view?usp=sharing

**Comment by Tombstone0074** [comment]
Addendum: It works perfectly on my wife's PC (same router). A friend installed it to test. Works too. So the problem is with my PC. Have now uninstalled Avast Premium Security, uninstalled malwarebytes, turned off windows firewall. It does not work. Maybe you have an idea. Would like to use your mod.

**Comment by derekhe** [comment]
I think the problem is the nginx is not started. You can try uninstall and install LATEST version in default path ("C:\Program Files\MSFS2020 Map Enhancement\)

**Comment by UberKiller** [comment]
Yeah same problem just leave it in the default path if not the Nginx Server won't get connected it's a strange thing but its happening 

(I have tried even moving to the same driver but a different folder the same result Nginx Server not connecting)

**Comment by derekhe** [comment]
@UberKiller please give me the logs.

**Comment by Tombstone0074** [comment]
> I think the problem is the nginx is not started. You can try uninstall and install LATEST version in default path ("C:\Program Files\MSFS2020 Map Enhancement)

I uninstalled it with Revo uninstaller pro, and installed v. 4.1.0. (5 times)
nothing changed. in taskmanager you can see details about nginx.exe
(Language is german, i´m austrian ;))

![Zwischenablage01](https://user-images.githubusercontent.com/88578895/156824739-a1c806e1-af3e-46ec-a0fb-b4357f0e4d5a.jpg)

**Comment by Tombstone0074** [comment]
... same with 4.2.0 :(

**Comment by h0wardch3ng** [comment]
@Tombstone0074 
Delete all files in
`C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement`
Uninstall this program and download latest installer, install again.

**Comment by Tombstone0074** [comment]
>

**Comment by Tombstone0074** [comment]
If i uninstall your mod, C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement is also gone.

**Comment by a543150176** [comment]
I want to ask if you solved it, I have this problem too

**Comment by Tombstone0074** [comment]
> I want to ask if you solved it, I have this problem too

No, sorry. No chance for me to solve the problem :(
