### ISSUE TITLE
Any of the Google Maps servers are working.

### ISSUE THREAD

**Issue by jcuellars** [derekhe/msfs2020-map-enhancement#660]
**Describe the bug**

Hi, I have been trying to connect with the Google Maps servers for several days without success. I don't have problems in my end seeing the maps directly thru the browser.

The new Bing maps are working okay. 

**Map Enhancement version:**
7.6.2 (Pro)

**Device ID**
- Device ID

**Screenshots**

Screenshot attached. 
![Screenshot 2024-06-13 110042](https://github.com/derekhe/msfs2020-map-enhancement/assets/113217083/0b6cbbdb-f88d-4b2a-82bc-a304c3c18f0b)

**Additional context**

**Comment by jcuellars** [comment]
I talked to fast, and now also the Bing Maps (Latest) are not working. 

Cheers
Jaime

**Comment by derekhe** [comment]
You have network issues and please fix.

**Comment by jcuellars** [comment]
Hi Derekhe,

All other maps are working perfectly, just google maps are the issue. I opened google maps in Chrome and other browser without any problem. I haven't change anything in my local network. 

Jaime
