### ISSUE TITLE
Init cache error : I don't find the solution : my disk have still large space free, where is the cahe file in my pc ? sorry and thank you Derek !

### ISSUE THREAD

**Issue by FRANCK4154** [derekhe/msfs2020-map-enhancement#662]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
![Map-message](https://github.com/derekhe/msfs2020-map-enhancement/assets/112616563/452aa7e0-1960-4386-b411-191ce7ff6abe)

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please check "C:\Users\YOURUSERNAME\AppData\Roaming\msfs2020-map-enhancement"

**Comment by FRANCK4154** [comment]
Hello Drek,
thanks but I don't have a file "appdata" in my user name....??
    Le samedi 15 juin 2024 à 04:43:34 UTC+2, hesicong ***@***.***> a écrit :   

 


Please check "C:\Users\YOURUSERNAME\AppData\Roaming\msfs2020-map-enhancement"

**Comment by FRANCK4154** [comment]
Hello Derek,
thank you for your return but I don't have this file in my user name.....
best 
Franck Desnoyers
    Le samedi 15 juin 2024 à 04:43:34 UTC+2, hesicong ***@***.***> a écrit :   

 


Please check "C:\Users\YOURUSERNAME\AppData\Roaming\msfs2020-map-enhancement"
