### ISSUE TITLE
Problem loading images in the North America

### ISSUE THREAD

**Issue by TomRach** [derekhe/msfs2020-map-enhancement#663]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version 1.0.5 XP 12

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
Images from the North America do not load on the XP12 simulator. It doesn't matter what server I choose, whether Google Maps, Bing or Arc. On 13/06/2024 they loaded without any problems.

**Comment by derekhe** [comment]
Please make sure you have all base packages installed.

**Comment by TomRach** [comment]
> Please make sure you have all base packages installed.

I have all base packages.
![Base Packages 15 06 2024 16_23_38](https://github.com/derekhe/msfs2020-map-enhancement/assets/172894508/35a742a4-77c1-4d8b-b532-ad616e5346c1)

**Comment by TomRach** [comment]
Only the US and Canada don't work for me. From Central America and down, everything works. The day before yesterday everything was ok.

**Comment by derekhe** [comment]
I don't know. Please check if anything else you have installed or removed.

**Comment by TomRach** [comment]
Have you tested it yourself now?

**Comment by derekhe** [comment]
Yes, I tested on every continent.
