### ISSUE TITLE
Old Bing maps are still bing displayed

### ISSUE THREAD

**Issue by Tralfaz888** [derekhe/msfs2020-map-enhancement#666]
Version 7.6.2
Windows 11 PC

I have read the user manual, FAQs and taken the steps to solve the issue. I know to start Map Enhancement first, and start the New Bing maps. I Have deleted my Hosts file. I am online in MSFS and have disabled and cleared my rolling cache. 

After loading a flight, the old Bing maps are still being displayed. I can tell because a hotel in my flight path does not exist in MSFS, but does exist in Bing maps.  I play in VR mostly, and the problem exist in 2D as well. 

When I tab back to the Map Enhancement window I see several thousand frames have been served. 

![map enhance](https://github.com/derekhe/msfs2020-map-enhancement/assets/173308757/11edf83e-8fd1-49b6-a889-7dd0bf4777be)

New Bing Map
![map 2](https://github.com/derekhe/msfs2020-map-enhancement/assets/173308757/b2343ee2-08a2-48b5-989e-0cab710bf9d1)

Old Bing map In MSFS.
![bing 3](https://github.com/derekhe/msfs2020-map-enhancement/assets/173308757/957d8b91-e5e0-4d69-8a47-f3feacea80b6)

**Comment by derekhe** [comment]
This is the photogrammetry data, which is above the ground. You can turn it off to see the real map.
