### ISSUE TITLE
Blurry texture 

### ISSUE THREAD

**Issue by pilotfranklin** [derekhe/msfs2020-map-enhancement#667]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
I’m using map enhancement (Bing Maps latest) and I’m experiencing this issue with some default and pay ware airports When I switch off the map enhancement everything is normal. Any fix for that? And by the way this Airport LOWW.
And installation all per manual. 

**Map Enhancement version:**
- 7.6.2

**Device ID**
MW68QKVYWATRCHP5ZFQEW5HXYHT3QYC0E8ADDV163S6NEPKCVAQ0

![448873000_10232994888682703_4304843348935120702_n](https://github.com/derekhe/msfs2020-map-enhancement/assets/173420079/ecfd7aad-5594-432e-9e13-42c94c0a5f6d)

![448895323_10232994888802706_7708642713055814061_n](https://github.com/derekhe/msfs2020-map-enhancement/assets/173420079/6b700270-f670-4e19-98b8-b3521332205e)

**Comment by derekhe** [comment]
[#599 ](https://github.com/search?q=repo%3Aderekhe%2Fmsfs2020-map-enhancement+LOWW&type=issues)
