### ISSUE TITLE
Just ArcGIS works for me 😢

### ISSUE THREAD

**Issue by jcuellars** [derekhe/msfs2020-map-enhancement#668]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Hi, I have the PRO version and a week ago everything worked like a charm, then Bing Maps are intermitent, and Google Maps were unusable. I haven't moved anything in my local network, I'm not banned from Google because I can access maps with any browser. 

I really don't know what else to do.

**Map Enhancement version:**
Version 7.6.2 (Pro)

**Device ID**
N33B42PHRFK2WBZ1Z0YF8PDSS62B4BM1VYX58CK54JMZ4ZSTXXHG

**Screenshots**
![Screenshot 2024-06-21 150927](https://github.com/derekhe/msfs2020-map-enhancement/assets/113217083/b9857cae-aac8-4107-9858-71ac18c4a9d1)

**Additional context**

**Comment by derekhe** [comment]
You can try different google servers, 1 and 2.
If it doesn't work then your network is blocked by google maps. You can try mapbox pro or apple pro.

**Comment by jcuellars** [comment]
Not sure if my network is blocked, I can acces see maps in Google and Bing without issues. 

This problem started 2 weeks ago.
