### ISSUE TITLE
With Map Enhancement active: MSFS freezes and CTD on loading scenario or also on scenario ready to play

### ISSUE THREAD

**Issue by PatriceCesson** [derekhe/msfs2020-map-enhancement#671]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**
1. I start Map enhancements.
2. On welcome screen, I select Bing latest map and press "Start"
3. Normally Map Enhancement has modified The host file and it closes to the tray area on Windows 10.
4. I start now MSFS (Store version)
5. On welcome screen of MSFS I choose the standard Cessna 172 from MS, I choose the airport (LFRN in France), I chose the time and weather. All is Ok on this.
6. I press Play button in MSFS welcome screen.
7. The scenario is loaded and I can see the initial scenario screen.
8. At that moment SFS freezes during 2-3 seconds.
9. After that MSFS makes a CTD directly on the desktop.
10. Each tests gives the same windows error signature (See snapshot below)
11. I have tried the same actions with MSFS in secured mode and the same crash occurs during the scenario loading process.
12.  This is systematic, whatever is the plane (MS ou addon), the community folder content (almost empty or not)
13. Map enhancement has been working ok in the past (a few months ago)
14. This is the first time I see this behavior.
15. I tried also with Map enhancement cache or no cache: same behavior.

**Map Enhancement version:**
- Map Enhancement version 7.6.2

**Device ID**
- Device ID
- Desktop PC with 32 Gb RAM, Intel processor I7-12700KF - GC NVidia RTX3090 FE.

**Screenshots**
Screenshot of the event viewer in Windows.
![snap084](https://github.com/derekhe/msfs2020-map-enhancement/assets/30781354/a304e68c-3411-4ee9-9363-9f91039744a6)
The parts in green are always the same in all similar crashes.
Event ID: 1000, Task category: 100

**Additional context**

**Comment by derekhe** [comment]
Please test your system's stability using software like cinebench r23. I think there was some RAM issue.
