### ISSUE TITLE
Error: Reached max retry

### ISSUE THREAD

**Issue by Rube-B** [derekhe/msfs2020-map-enhancement#672]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Im getting the same error over and over again, the applications starts but it keeps loading until i get the error as seen in the screenshot.

**Map Enhancement version:**
-  7.6.2

**Screenshots**

![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/161316018/226ef2dc-3ed8-4385-b9c4-c39cf894d565)
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/161316018/a770ae0f-f69e-452c-9ae4-962684279425)

[log.txt](https://github.com/user-attachments/files/16108371/log.txt)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/issues/616

**Comment by Rube-B** [comment]
I tried cmd as admin: winmgmt /resetrepository but it doesn't work. 
The command works but it doesn't fix the issue sadly.
![image](https://github.com/derekhe/msfs2020-map-enhancement/assets/161316018/61a4f243-a899-4d45-929a-0d42d601e137)

**Comment by Rube-B** [comment]
still getting the same issue :(

**Comment by Rube-B** [comment]
Got it fixed: Windows + R type: services.msc, scroll down to "Windows management instrumentation" and make sure its Running!,
Thats it

**Comment by MarkMurithi** [comment]
Mine has refused to work completely
