### ISSUE TITLE
Warning message : Breaking change in >v1.1.0 basepackage / Mesh

### ISSUE THREAD

**Issue by GEC42P** [derekhe/msfs2020-map-enhancement#675]
Xplane 12 Version 1.1.3

1. Getting the warning message "Breaking change in >v1.1.0, please look into the manual ....

what I did and found nothing. I installed yesterday the version 1.1.3 and the Europe and base package.
What to do with this message

2. Flying with the Enhancement Tool about Gotland the whole landscape is flat, flying in south sweden hills are there.
   No addon installed

Regards Manfred

**Comment by derekhe** [comment]
Please follow the latest manual: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN

**Comment by GEC42P** [comment]
Hej,

 

I just used the latest manual, because I did it 4 days ago. 

So I used what’s on the net.

 

And in the manual there is no hint for this message

 

Mit freundlichen Grüssen / med vänlig hälsningar

 

Manfred Flakowski

DE Tel.:  +49 (0)172 710 5402

SE Tel.:  +46 (0)73 976 7633

Email : ***@***.***
Email :  ***@***.***> ***@***.***

Confidentiality Notice:
This message and any attachments are confidential and intended only for use 
by the recipient named above. Unauthorized disclosure, distribution or copying 
of this communication and the information contained in it is strictly prohibited. 
If you are not the intended recipient, please notify us immediately and delete the 
message and any attachments. Thank you.

 

Von: hesicong ***@***.*** 
Gesendet: Dienstag, 9. Juli 2024 14:28
An: derekhe/msfs2020-map-enhancement
Cc: GEC42P; Author
Betreff: Re: [derekhe/msfs2020-map-enhancement] Warning message : Breaking change in >v1.1.0 basepackage / Mesh (Issue #675)

 

Please follow the latest manual: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN

**Comment by GEC42P** [comment]
Hej,

 

you closed it but in the manual (and I have from start the actual version) is not described what the error message means ??

 

Mit freundlichen Grüssen / med vänlig hälsningar

 

Manfred Flakowski

DE Tel.:  +49 (0)172 710 5402

SE Tel.:  +46 (0)73 976 7633

Email : ***@***.***
Email :  ***@***.***> ***@***.***

Confidentiality Notice:
This message and any attachments are confidential and intended only for use 
by the recipient named above. Unauthorized disclosure, distribution or copying 
of this communication and the information contained in it is strictly prohibited. 
If you are not the intended recipient, please notify us immediately and delete the 
message and any attachments. Thank you.

 

Von: hesicong ***@***.*** 
Gesendet: Samstag, 13. Juli 2024 13:35
An: derekhe/msfs2020-map-enhancement
Cc: GEC42P; Author
Betreff: Re: [derekhe/msfs2020-map-enhancement] Warning message : Breaking change in >v1.1.0 basepackage / Mesh (Issue #675)

 

Closed #675 <https://github.com/derekhe/msfs2020-map-enhancement/issues/675>  as completed.
