### ISSUE TITLE
Airport corrupted (works ok if Map Enhancement is off)

### ISSUE THREAD

**Issue by michalboska** [derekhe/msfs2020-map-enhancement#678]
**Before you raise a bug**

[x] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

When at LOWW airport, there is a big reef (like after an earthquake) separating the airport in two parts. One is ok, the other one has very low quality ground textures.
The reef also affects terrain (the plane can crash into it or fall from it). 

This doesn't happen when i start MSFS without this addon being activated (and everything else staying the same).

I also tried to set Network settings from Enhanced to Normal, as per the FAQ.

**Map Enhancement version:**
7.6.2 Pro

**Device ID**
6XFYZA4NG2EQ56NW0HQQMHJ80QHN21C0A30NESY76D7FDYDQK7Y0

**Screenshots**

![Screenshot 2024-07-09 150331](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/aa1310d8-3f1b-4b72-9d09-40631b0c1d08)
![Screenshot 2024-07-09 150435](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/59dce831-287b-4541-9188-ca733c7ca37a)
![Screenshot 2024-07-09 150449](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/a8a0cfb3-6d61-4572-90a5-09b9236ba1ba)
![Screenshot 2024-07-09 150823](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/e78e3501-0c70-48d6-b70f-ab9d9cb6d788)
![Screenshot 2024-07-09 150908](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/f6851bf5-e770-4164-be06-7d56bf1e70d9)
![Clipboard01](https://github.com/derekhe/msfs2020-map-enhancement/assets/7025930/10b2e606-b841-4ff9-90a7-d5231476e966)

**Additional context**

**Comment by derekhe** [comment]
Please check the follow threads: https://github.com/derekhe/msfs2020-map-enhancement/issues?q=LOWW
