### ISSUE TITLE
Image Server Access Check has a cross

### ISSUE THREAD

**Issue by mv0hra** [derekhe/msfs2020-map-enhancement#68]
Image Server Access Check has a cross.

 - MSFS2020 version: msstore/steam
 - MSFS2020 Version 1.23.12.0
 
![Screenshot 2022-03-02 103553](https://user-images.githubusercontent.com/54370406/156352962-141da0da-9d9f-4285-9fd8-9b02e2d603d6.png)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169190/error.log)
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169193/image_server.log)
[khstore-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169195/khstore-access.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169196/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169197/renderer.log)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8169200/virtualearth-access.log)

**Comment by derekhe** [comment]
Please try uninstall and reinstall. Seems the cache option has some issue.

**Comment by mv0hra** [comment]
> 

Perfect, that worked.
