### ISSUE TITLE
Init Cache Error, not enough disk space

### ISSUE THREAD

**Issue by Alexair83** [derekhe/msfs2020-map-enhancement#681]
**Describe the bug**
Hello,
I've set my cache size at 1950 Gb (I have a big SSD drive). When reaching about 96.9 Gb Map Enhancement give me "Init cache error" as per the screenshots included. The only solution for me at this time is to use the "Clear all data" option.
Is it due to a maximum data limit reached ? If yes, what is the max limit ?
Thanks !

**Map Enhancement version:**
7.6.2 (pro)

**Device ID**
Q8FX12TM5YX7Y3NPZFSHEG5XSZRHVAPQM0QVH7QTPBKTFWXS183G

**Screenshots**
![MEissue1](https://github.com/derekhe/msfs2020-map-enhancement/assets/119800920/67a8879d-e41a-4998-8022-bd2156286983)
![MEissue2](https://github.com/derekhe/msfs2020-map-enhancement/assets/119800920/89a4bf65-caa2-46cb-9965-dd3c1645e9d9)

**Additional context**
All security permissions has been given and I still have 1.95 Tb of free space on the SSD drive.

**Comment by derekhe** [comment]
Please set it to a smaller value, like 1800 may solve this issue.

**Comment by Alexair83** [comment]
Hi Derekhe,
Thanks for your reply.
Will set it to 1800 as suggested and will post a result.
Alex
