### ISSUE TITLE
[BUG 8.0.0] Map tiles too bright even tho no color settings are used.

### ISSUE THREAD

**Issue by FinalLightNL** [derekhe/msfs2020-map-enhancement#685]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Something seems off even tho i didn't touch color settings.
All the tiles being loaded in look like they have 500% more brightness.
This was not the case with 7.6.2.

**Map Enhancement version:**
- 8.0.0

**Device ID**
- GRY0ZFV3Q9DFSFPY32G6M4BGSMGSC5JYRNMMG9ND4RYBAKZTCJCG

**Screenshots**

![Screenshot 2024-07-13 163514](https://github.com/user-attachments/assets/74f8d6b1-a841-4ca9-99ca-71c4162f486a)
![Screenshot 2024-07-13 163526](https://github.com/user-attachments/assets/9b510d13-5449-4b69-8743-f3c7551b1d66)

**Additional context**

Not sure what exactly changed here, playing with the color sliders do work still.
but the default colors are wrong, the tiles shown as a preview below the start button look fine.
but in sim it's extremely bright.

**Comment by FinalLightNL** [comment]
nvm it seems to be an issue with the area paderborn with apple maps etc.
other places look fine.

**Comment by derekhe** [comment]
Yes, you can switch to other maps.
