### ISSUE TITLE
download infected. stopped by avast and windows defender

### ISSUE THREAD

**Issue by sandnseaking** [derekhe/msfs2020-map-enhancement#686]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Yes, it is a known issue > 8.0.0 I use a new install and update tool.
The problem is mentioned here: https://docs.velopack.io/packaging/signing,  it needs some advanced setup and it is very costly so I won't take it right now.
You can safely add this app into white list.
