### ISSUE TITLE
Hook failed?

### ISSUE THREAD

**Issue by DochMurder** [derekhe/msfs2020-map-enhancement#687]
**Map Enhancement version:**
- Map Enhancement version - 8.0.2

**Device ID**
- Device ID KMVZT6KD4TT2DGS84EX7S17JPJ68P934GE1W7FZ17PDYQE7MHG1G

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**
![Screenshot 2024-07-13 224534](https://github.com/user-attachments/assets/3d1d8c36-1dc1-446b-8f2b-529055da40a6)

**Comment by derekhe** [comment]
Please run as administrator or you can ignore this information. It just want to open the installed program.

**Comment by DochMurder** [comment]
Thanks, I will do just that. Hoping I got everything taken care of as I love your work but was having major issues just getting maps to render and load. I will post here if anything comes up in a new thread. Keep up the great work and thank you 1000x for such a great enhancement for the simulator.

**Comment by DochMurder** [comment]
Also, I am trying to repurchase the license for the pro verison however it seems the link to pay is not working? Getting a connection issue error on the browser when in fact the network on my end is good. Thanks :)

**Comment by derekhe** [comment]
This one: https://[k.aiflygo.com](https://k.aiflygo.com/)/

**Comment by DochMurder** [comment]
Sorry to get back to you a few days later. Life! Anyways, still just getting this everytime =/ Do you have a Paetron? I would happily go that route if possible!
Thank you again, 
Cheers
![Screenshot 2024-07-16 103520](https://github.com/user-attachments/assets/9887b094-492d-421f-8409-97106d83cae8)
