### ISSUE TITLE
Map Enhancment issue V8.0.2

### ISSUE THREAD

**Issue by Justinza23** [derekhe/msfs2020-map-enhancement#688]
Hi, 

I just downloaded the latest update however just wanted to ask you if this is an error.

If you see the attached pic, next to the HIGH LOD enabled there is the word false showing. Is this a bug? also I noticed that the ground textures are too bright comapared to previous versions.

Thanks
![Screenshot 2024-07-14 122512](https://github.com/user-attachments/assets/2a3888a1-9446-4ec2-a4e9-f4bb6e63f243)

**Comment by derekhe** [comment]
No, it just says the High LOD feature is disabled. You can turn it on in the Settings page.
For the colors, it depends on where you fly. If you don't like it, you can change it on the color settings page.

**Comment by Justinza23** [comment]
Currently my setting is that Load High LOD images only while flying is on,
but High LOD enabled is off

**Comment by derekhe** [comment]
I think there is a bug in the settings config in v8. You should turn the 2 high lod options to on.

**Comment by Justinza23** [comment]
Ok even if i have cache disabled from the sim?

Thanks

**Comment by derekhe** [comment]
It doesn't relate to the cache. There is chance that the satellite images are bright because of google's photogrametry issue, which described here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#810-the-map-color-is-inconsistent-in-various-places

**Comment by Justinza23** [comment]
Ok so i will try to enable to other option too when i will get home. I'll
let you know.
Thanks
