### ISSUE TITLE
no permission to hosts file

### ISSUE THREAD

**Issue by GoldKatt** [derekhe/msfs2020-map-enhancement#69]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

![ergfverfgerf](https://user-images.githubusercontent.com/100983071/156866266-20a37f29-0686-4cf2-aa8c-19001fd3d1bf.png)

every time i try to inject the goggle maps it says "stop server failed error EBUSY: recourse busy or locked open C:winows\system32\drivers\ect\hosts

**Comment by h0wardch3ng** [comment]
delete hosts file
The path is
```
c:\Windows\System32\Drivers\etc\hosts
```
and new a file, name as hosts

**Comment by GoldKatt** [comment]
when i try to delete it it says "the action cant be complete because the file is open in wrvc"

**Comment by derekhe** [comment]
Then it is locked by some program (most likely the antivirus), please check.
