### ISSUE TITLE
fail to start

### ISSUE THREAD

**Issue by firepanther911** [derekhe/msfs2020-map-enhancement#694]
Breaking change in >v1.10 base package.
Server start failed.

**Comment by derekhe** [comment]
What's the error message? Could you give me a screenshot?
And please try the user manual: https://github.com/derekhe/xplane-map-enhancement-release/wiki/Manual-EN

**Comment by firepanther911** [comment]
Here you go. I have tried to put the files correctly into a base package
folder . It wouldn't start.
