### ISSUE TITLE
Custom Hybrid Map problem

### ISSUE THREAD

**Issue by CharlesHill56** [derekhe/msfs2020-map-enhancement#695]
**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by CharlesHill56** [comment]
I am using 8.0.2.0 and cannot use my custom version of the Hybrid map which I created it comes up with an error, see screenshot and my file
![Error](https://github.com/user-attachments/assets/edd4abf2-7f11-4214-989d-bff7cf0b5df4)
[hybrid-map.json](https://github.com/user-attachments/files/16248731/hybrid-map.json)

**Comment by CharlesHill56** [comment]
Actually it doesn't work it comes up with this error after I copy my file into it, I think I gave you the wrong Custom Hybrid file
![Error 2](https://github.com/user-attachments/asse
[hybrid-map.json](https://github.com/user-attachments/files/16249221/hybrid-map.json)
ts/184db492-bce5-4e97-9fa1-6088794d86c2)

**Comment by CharlesHill56** [comment]
Update it works with 7.6.2 but not 8.0.2.0

**Comment by CharlesHill56** [comment]
By the way I do love this mod👍

**Comment by CharlesHill56** [comment]
Hi

It works with the default Hybrid map but not my own created from 7.6.2 which it works in
Can you maybe check my Hybrid map file?

**Comment by derekhe** [comment]
Oh I know the issue. I changed the internal name of the maps. I will update them in the docs.

**Comment by derekhe** [comment]
I updated the names in this doc: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Hybrid-map
Please update them in the json. Sorry for the changes.

**Comment by CharlesHill56** [comment]
﻿So I will have to update all the regions in my custom hybrid map json?

Sent from my iPad

On 17 Jul 2024, at 12:42, hesicong ***@***.***> wrote:

﻿

I updated the names in this doc: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Hybrid-map
Please update them in the json. Sorry for the changes.

**Comment by derekhe** [comment]
Yes





------------------ Original ------------------
From: CharlesHill56 ***@***.***&gt;
Date: Wed,Jul 17,2024 10:42 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Custom Hybrid Map problem(Issue #695)





 ﻿So I will have to update all the regions in my custom hybrid map json? 
 
 Sent from my iPad 
 
 On 17 Jul 2024, at 12:42, hesicong ***@***.***&gt; wrote: 
 
 ﻿ 
 
 I updated the names in this doc: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Hybrid-map 
 Please update them in the json. Sorry for the changes.

**Comment by CharlesHill56** [comment]
I don’t know what I am doing wrong, I thought I changed them all but still getting the same message
Can you please check my json file attached

Regards

Charles

**Comment by CharlesHill56** [comment]
I think I know what is wrong, even though when I clicked the region on the map it showed the change but the json on the right of the map wasn’t changed

**Comment by CharlesHill56** [comment]
Finally got it sorted, thanks for your help

Regards

Charles

Sent from my iPhone

On 17 Jul 2024, at 16:50, Charles Hill ***@***.***> wrote:

﻿
No problem!
