### ISSUE TITLE
Packuwan unwanted spyware

### ISSUE THREAD

**Issue by gitgwa** [derekhe/msfs2020-map-enhancement#697]
More specific malware warning reported by windows security.  Can this be removed from the app?

<img width="388" alt="image" src="https://github.com/user-attachments/assets/325d4ecb-d623-4ae7-a64a-e1fa0c9d2e83">

**Comment by derekhe** [comment]
Please use the latest version 8.0.4: https://github.com/derekhe/msfs2020-map-enhancement/releases
