### ISSUE TITLE
Paetreon ? New Store Link for Map License?

### ISSUE THREAD

**Issue by DochMurder** [derekhe/msfs2020-map-enhancement#699]
#### Motivation

I have been trying to purchase a license for your wonderful program you have here and in the past it has not been an issue until recently maybe about a solid week now. It has motivated me enough to reach out and suggest maybe looking into a subscription program of your work like a Paetreon? 

#### Detailed design

3 TIER MONTHLY Paetreon ? 15 DAY TIER, 30 DAY TIER, 45+ Day Tier 
I just really want to be able to repurchase the license again. I get error after error that its down the current link that is in order to purchase a license. 

#### Alternatives

Cashapp intergrations, Zelle, Venmo, Paypal?

Not in any way shape or form upset that I currently can not buy it and understand You and your team can most likely get busy. I am one supportor who is grateful for the teams work because it gives me a great feeling as the skys do call with this enhancement! 
Thanks <3

**Comment by derekhe** [comment]
Thanks for your feedback. I have done several tries on different provider but only find buymeacoffee and paypal are the best fit.
The pay and license services are built by myself and I don't want to make it too complicated.
If you find any license activation issue, please let me know.
