### ISSUE TITLE
Image server fail to connect

### ISSUE THREAD

**Issue by helibrewer** [derekhe/msfs2020-map-enhancement#70]
electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.
log @ electron/js2c/renderer_init.js:13
08:10:18.103 › Application starting
08:10:20.151 › Starting mod
08:10:20.497 › Start mod result Object
UpdateNotification.vue:35 Object
08:10:20.770 › No update version
08:10:28.503 › Checking image access
08:10:28.513 › Checking nginx server
08:10:28.543 › Nginx server check result 404
08:10:28.544 › Nginx server check passed
08:10:31.578 › Image server error RequestError: connect ECONNREFUSED 127.0.0.1:39871
    at ClientRequest.<anonymous> (chunk-vendors.b34d67f6.js:96360)
    at Object.onceWrapper (events.js:422)
    at ClientRequest.emit (events.js:327)
    at ClientRequest.e.emit (chunk-vendors.b34d67f6.js:70674)
    at Socket.socketErrorListener (_http_client.js:469)
    at Socket.emit (events.js:315)
    at emitErrorNT (internal/streams/destroy.js:106)
    at emitErrorCloseNT (internal/streams/destroy.js:74)
    at processTicksAndRejections (internal/process/task_queues.js:80)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146)
DevTools failed to load source map: Could not parse content for app://./ajv.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./core.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./boolSchema.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./errors.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./code.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./scope.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./util.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./names.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./dataType.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./rules.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./applicability.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./defaults.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./keyword.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./code.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./subschema.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./resolve.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./uri.all.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./validation_error.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./ref_error.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./draft7.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./id.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./ref.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./limitNumber.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./multipleOf.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./limitLength.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./ucs2length.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./pattern.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./limitProperties.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./required.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./limitItems.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./uniqueItems.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./equal.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./const.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./enum.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./additionalItems.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./prefixItems.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./items.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./items2020.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./contains.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./dependencies.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./propertyNames.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./additionalProperties.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./properties.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./patternProperties.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./not.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./anyOf.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./oneOf.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./allOf.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./if.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./thenElse.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./format.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./metadata.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./types.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./formats.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for app://./limit.js.map: Unexpected end of JSON input

**Comment by h0wardch3ng** [comment]
Delete all files in
`C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement`
Uninstall this program and download latest installer, install again.

Please try uninstall and reinstall. Seems the cache option has some issue.

**Comment by derekhe** [comment]
Does it work now?

**Comment by derekhe** [comment]
Close as long time no response.
