### ISSUE TITLE
8.0.4.0

### ISSUE THREAD

**Issue by hOOters69** [derekhe/msfs2020-map-enhancement#701]
Thanks ! This version is good !

**Comment by dermatti2** [comment]
No, it is not! It contains malware again. What is going on here?

**Comment by derekhe** [comment]
> No, it is not! It contains malware again. What is going on here?

Please check the virtus total reports: https://www.virustotal.com/gui/file/3a2fe35a600817604c754be110d27835b6f502fa2cd4a43eb0844c023355377e

If you don't trust my report, you can try upload what you have downloaded.
