### ISSUE TITLE
Blurry LOWW Airport (Bing Maps=)

### ISSUE THREAD

**Issue by EisernUnion** [derekhe/msfs2020-map-enhancement#705]
Same issue as reported before, but im using "the new Bing Maps"
Same here the blurry area is a Triangel RWY 34 - TWY L - TL 35 - RWY 34   .... the border is marked with a thin red line in the pics

If MSFS In-Game Photogrammetry is switched off, it looks fine; if switched back on: Blurry Triangle
![FlightSimulator_WWCgzjBm73](https://github.com/user-attachments/assets/830872f1-11b0-4f19-bd87-07e57df42da1)
![FlightSimulator_QQmBxspCRL](https://github.com/user-attachments/assets/d298b6aa-a594-4eb6-980b-97b02b488e1b)

Im flying ca 110hrs a month, a lot of different aiports ... this small part of LOWW is the only one has this issue, no other airport

Im using new new BING

**Describe the bug**

**Map Enhancement version:**
- 8.0.2.0

57gI4DJgmo

**Comment by derekhe** [comment]
Yes, that is known issue and is from the photogrammetry data in msfs. I can't fix it.

**Comment by EisernUnion** [comment]
I disagree... the blurry area comes up when using the new bing maps

![9Lnl9fKy39](https://github.com/user-attachments/assets/ba533814-6b91-4af8-98dd-18d26ef9a8ca)
![kq6PkCgkm5](https://github.com/user-attachments/assets/a1cd5239-c97e-445f-98e2-38d164980c7b)
