### ISSUE TITLE
Map Enhancement Not Opening

### ISSUE THREAD

**Issue by JacobBasheer787** [derekhe/msfs2020-map-enhancement#707]
I am attempting to install version 8.0.6.0

I will run the installer and complete the proccess. At the end, I will click Run Map Enhancment. The software will open for 2-5 seconds looking like the screenshot included below, then close. I have attempted to re-open it with no succes. The steps I have taken to resolve this issue are the following:

-Uninstall And Reinstall The Software
-Attempt To Install Older Versions Of The Software
-Ensuring 443 And 42098 Ports Are Unoccupied
-Adding The Software As An Exclusion In My Antivirus Software
- Running The Software On An Admin Account
- Running The Software As An Administrator

I would attempt to address the issue further myself, however in the few seconds that the software is open, it doesn't give me information on why this may be happening.

![Screenshot 2024-07-25 123002](https://github.com/user-attachments/assets/7224f6e3-88e2-479b-910b-3c9632ca0d8a)

Thank you very much,
Jacob Basheer

**Comment by derekhe** [comment]
Please give me your device id in the license page.

**Comment by JacobBasheer787** [comment]
Please forgive me if I am wrong, but if the license page is within the app, I will be unable to access it. This is because even after a reinstall, it will only run for a few seconds. If there is another method of obtaining this ID, I would greatly appreciate your assistance. Thank you.

**Comment by derekhe** [comment]
You can try delete all the content inside C:\Users\YOUR_USERNAME\AppData\Roaming\msfs2020-map-enhancement
It will reset to all default and you should be ok on the main page.

Another things is: did you turn on the minimize to try options in the "settings"? 
![image](https://github.com/user-attachments/assets/c68f80c8-e6f8-4bb0-9128-90497bba6617)

If yes, it will go to tray area (right corner of the desktop) and hide.
You can find it here and when you double click it, it will show you the application.
![image](https://github.com/user-attachments/assets/f7c28e1b-8dd4-43e9-82e5-fb97c5a5be81)

**Comment by JacobBasheer787** [comment]
Oh, yes this works. It appears I was being a little.... well.... dumb. Thank you very much for your help!
