### ISSUE TITLE
Still see old map

### ISSUE THREAD

**Issue by combatengr49** [derekhe/msfs2020-map-enhancement#71]
**Describe the bug**
Not sure if it is a bug but I installed the app as instructed, Injected the map as instructed.  Everything seems OK but when I launch MSFS I still see the old map.  At least the age of the map appears to be the same as the original map.  I'm flying in the Provo, Utah area.  I checked the same area with GooglePro and it shows updated buildings, terrain, etc.  So I know that Google Map are up to date.

**Comment by h0wardch3ng** [comment]
Check in-game cache settings，please turn off it.

**Comment by combatengr49** [comment]
Thanks. I’ll try that. I tried using the clear cache tab in the app but it gave me a message that I needed to inject first. I have the auto inject feature turned on.

**Comment by combatengr49** [comment]
Well, tried that that and it appears to download images from google but lol the images appears to be older than the default. At least in the Provo Utah area.  I flew over the apartment bldg where i live which shows on Google Earth but is not there on the Google feed I’m getting through the app.   Is the google feed the same as with Google Earth?  Not sure if the weather overlay is affecting the map.

**Comment by derekhe** [comment]
Yes, it should be the same as Google Earth. You can also try "Bing (Latest)" which is sometimes better than google.

**Comment by combatengr49** [comment]
I cleared the cache again in MFSF and this time it worked and I can see the current Google Earth map.

 

Thank you
