### ISSUE TITLE
Google Maps no longer work (remote image server error)

### ISSUE THREAD

**Issue by LordManhattan** [derekhe/msfs2020-map-enhancement#714]
- Map Enhancement version: 8.0.6.0
- OS: Windows 11 Pro 23H2

Got this error two days ago and it's still not able to access remote image server. Bing works fine. 

![asdasfgsgggasdaefqwe333](https://github.com/user-attachments/assets/b5581f5a-3548-4891-9153-a482237b7457)

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#89-google-maps-is-not-loading
