### ISSUE TITLE
Bandwith problem red pop up

### ISSUE THREAD

**Issue by sclorious1** [derekhe/msfs2020-map-enhancement#717]
I bought 30 days MSFS map enhancement and a few days before it finished it started to give me the red pop up on msfs that says "your connection had an issue while streaming data" and it does this about 30 minutes after takeoff all the time regardless of what map I use.

**Comment by sclorious1** [comment]
It was working perfectly up until a few days ago, in order to fix it ive tried windows update, driver, host file, reinstall, idk what else to do

**Comment by derekhe** [comment]
It's not related to this mod and please check your connection to MSFS server.
