### ISSUE TITLE
MSFS2020 Map Replacement v4.2.0 update help

### ISSUE THREAD

**Issue by JeffHung0361** [derekhe/msfs2020-map-enhancement#72]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

**Comment by h0wardch3ng** [comment]
Delete all files in
`C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement`
Uninstall this program and download latest installer, install again.

Please try uninstall and reinstall. Seems the cache option has some issue.

**Comment by derekhe** [comment]
Does it work now?

**Comment by derekhe** [comment]
Close as long time no response.

**Comment by xxlmash2022** [comment]
> Delete all files in `C:\Users\%USERNAME%\AppData\Roaming\msfs2020-map-enhancement` Uninstall this program and download latest installer, install again.
> 
> Please try uninstall and reinstall. Seems the cache option has some issue.

Helped me, many thx!!!
