### ISSUE TITLE
Starting slow since 8.0.9

### ISSUE THREAD

**Issue by MStallen** [derekhe/msfs2020-map-enhancement#729]
Start-up and getting the first map-part downloaded cost about 1 min. Before (< 8.0.9) it was a few seconds.
Cleared cache, changed network config from advanced to normal, but this did not change anything

**Comment by jydsj** [comment]
您好，我也遇到同样问题。更新后，8.0.9打开地图软件第一次加载时“开始”那里一直在打圈，要等很长时间才能加载出来。
奇怪的是，尝试再次回到8.0.8也变转圈了（同时提示在下载新版），之前所有版本加载都很快。

**Comment by Amorisia** [comment]
> 您好，我也遇到同样问题。更新后，8.0.9打开地图软件第一次加载时“开始”那里一直在打圈，要等很长时间才能加载出来。 奇怪的是，尝试再次回到8.0.8也变转圈了（同时提示在下载新版），之前所有版本加载都很快。

I have the same issue. Can start 8.0.8 and 8.0.9 but need to wait about 5 to 10 minutes (chinese network with VPN). Hope to get a fix to this in next version.

**Comment by derekhe** [comment]
Thanks for reporting, it is good now.
