### ISSUE TITLE
MULTI-COLORED Blocks/Squares Display on Terrain

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [derekhe/msfs2020-map-enhancement#73]
Hi,

I get MULTI-COLORED Blocks/Squares on Terrain displayed on my terrain/ground textures. Does not affect buildings, etc.

**Comment by derekhe** [comment]
Please give me screenshots and locations.

**Comment by JazzyJazzjazzy** [comment]
Hello Sir,

I observed the SAME behavior using BING DEFAULT Map. I suspect it may be a streaming issue and NOT related to your excellent program.

Thank you.

**Comment by derekhe** [comment]
Thanks, I will close this.

**Comment by JazzyJazzjazzy** [comment]
Here is a Screenshot for your curiosity. Peace

![New Bitmap image](https://user-images.githubusercontent.com/40358464/158926559-854922b0-f34b-490f-8999-914f1c34546d.jpg)
![New Bitmap image (2)](https://user-images.githubusercontent.com/40358464/158926562-fb7fa991-be0a-4a50-b644-6808bbf4df0b.jpg)

**Comment by gutch1** [comment]
I had this same issue all over the place. Switching to the khm.google.com option fixed it.

**Comment by JazzyJazzjazzy** [comment]
Thank you. I will try the other server.
