### ISSUE TITLE
MSFS Map Enhancement problem

### ISSUE THREAD

**Issue by klemlao** [derekhe/msfs2020-map-enhancement#734]
The Unzipped .exe wants to install to Program Files (x86) instead of Program Files as an older version did. Is that correct?
When I run the Map Enhancement .exe it deletes the unzipped installer and deletes Map Enhancement.exe from the program folder.

**Comment by derekhe** [comment]
Yes. It is a mistake I made so it installs into (x86) folder. But doesn't matter, it still works :)
