### ISSUE TITLE
Crash to Desktop using 8.0.7, 8.0.8, and 8.0.9

### ISSUE THREAD

**Issue by Madmapper2244** [derekhe/msfs2020-map-enhancement#735]
I have been experiencing numerous crash to desktop while running MSFS.  I went through and removed everything out of my community folder and slowly re-introduced addons back into the sim.  This morning I did a flight with Map Enhancement Mod using 8.0.9 and right after takeoff the sim crashed to desktop. I then went in and deleted the program completely off my computer and re-installed version 8.0.7 and got the same crash to desktop right after takeoff. I am going to completely un-install the program and try again with a previous version. I would like to get this working again. It is a valuable addon to the overall sim experience.   Any help or guidance resolving this issue would be greatly appreciated. 

Thank you,

David 

**Before you raise a bug**

[] For using this app, I have read and tried solution in mentioned by manual: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
[] For license issue, I have read the readme in https://github.com/derekhe/msfs2020-map-enhancement/wiki/License and also filled the form in https://key.aiflygo.com/

**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**Map Enhancement version:**
- Map Enhancement version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by morganthomas757** [comment]
I also had a similar issue, but instead of the one you describe, when launching the 8.0.9 .exe file, my Windows Explorer UI (taskbar, desktop etc.) repeatedly force closes. 

I managed to fix it using a third party tool called Explorer Patcher, but I then uninstalled and reinstalled 8.0.8 to see if it had the same issue, which it did.

Weird stuff going on in these latest builds…

**Comment by derekhe** [comment]
Please have a look if you are using windows preview versions. I received some cases regarding preview version. My system version: 22631.4112 is working well.

**Comment by Madmapper2244** [comment]
> Please have a look if you are using windows preview versions. I received some cases regarding preview version. My system version: 22631.4112 is working well.

I do I know if I am using windows preview version?  I have never heard of that.  I am using a full Windows 11 OS.

**Comment by Madmapper2244** [comment]
Ok I am not using a Windows preview version.  However my OS Build is 22631.4037.  I do have a cumulative update for Windows 11.  I'll download that and see if my build OS matches yours.

**Comment by gitgwa** [comment]
MSFS CTD here too after takeoff; consistent 
Running Win11 23H2 with mixed reality and Reverb G2
Other stuff in my community

- Say Intentions
- Navigraph
- FSLTL
- Black Square taxiways

**Comment by The-SKunkworx** [comment]
Add me to the list.  My MSFS has been rock solid until using  Map Enhancement.  Just got my 3rd CTD in a week.  I like the nice maps but stability is more important.  I'm going to uninstall until this is sorted out.

**Comment by Madmapper2244** [comment]
OK I believe that I figured it out.  Before uninstalling the mod try this out. I downgraded to 8.0.5 and turned off the cache setting within the sim and toggled on the cache within the Map Enhancement Mod.  I was able to do a complete flight without any CTD running the program.  I am now going to see if I can do a complete flight within version 8.0.9.  

David

**Comment by The-SKunkworx** [comment]
Hmmm, I never had the in game cache on though.  I was only using the cache within Map Enhancement but was still getting the CTD.  I wonder if just using 8.0.5 is the key?

**Comment by derekhe** [comment]
This mod has been here for more than 2 years and the msfs crash has been proven several times not related to this mod. Please check the user manual, there are possible checks to help find out why.





------------------ Original ------------------
From: The-SKunkworx ***@***.***&gt;
Date: Wed,Sep 4,2024 8:44 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Crash to Desktop using 8.0.7,8.0.8, and 8.0.9 (Issue #735)





 
Hmmm, I never had the in game cache on though.  I was only using the cache within Map Enhancement but was still getting the CTD.  I wonder if just using 8.0.5 is the key?

**Comment by RFlint1** [comment]
Yeah, I'm sure you can find reports of people having problems even from 2 years ago. For me, it sometimes works. Most of the time, the app just randomly crashes, causes MSFS to crash, or causes my PC to crash. This is with an empty Community folder.
