### ISSUE TITLE
Always crashes

### ISSUE THREAD

**Issue by tassiemal** [derekhe/msfs2020-map-enhancement#738]
I downloaded the app and it all worked fine, added google pro 2 to it and still worked fine, then 2 days later it just stopped working, does the normal start up and i press install, it starts then the lot disappears, stops working, nothing, can't even get into the settings, just nothing, i have tied re-downloaded the app a number of times but same thing happens, can you help please.

**Comment by RFlint1** [comment]
Same problem here. New windows install, all dependencies installed, fresh sim with clean community folder, yet it does nothing but crash. Have run through all the troubleshooting steps multiple times, read the FAQ multiple times. The app just doesn't work.

**Comment by tassiemal** [comment]
Yes, definitely agree, was working fine, nothing and I just paid for google map 2, bugger

________________________________
