### ISSUE TITLE
[Feature] Notification when Load Errors occur

### ISSUE THREAD

**Issue by leftos** [derekhe/msfs2020-map-enhancement#741]
#### Motivation

Using the Google Map 1 (Pro) server, a couple of times over the last couple of months, the app has been unable to download any tiles, leading to a flood of Load Errors. However, there's no notification for that unless you're actively looking at the UI. 

#### Detailed design

Some sort of Windows notification, dialog, anything, to let us know there's load errors would be helpful. I'm using 8.0.10 with Hybrid map (Pro) as the primary and Google Map 1 (Pro) as the fallback, and apparently both failed during a flight into Hawaii today.

**Comment by derekhe** [comment]
Thanks for feedback, I will look into this feature.

**Comment by derekhe** [comment]
Now it will show how many errors (when >300)

**Comment by derekhe** [comment]
But there is no notification right now because the underlaying UI framework doesn't support it.
