### ISSUE TITLE
standalone feature to create cached maps

### ISSUE THREAD

**Issue by jesterelly** [derekhe/msfs2020-map-enhancement#742]
i still live in a region with poor internet service (just 3G/4G internet connection only, limited bandwith) and i am not able to create local cached maps with the MSF since i have no suitable internet connection at home. running MFS is possible but without any streaming. luckily there is a suitable internet bandwith at work where i could download map data but not run the MFS (due the fact that i just have limited access to my office workstation), so creating cached maps directly with MFS is not possible.

thats why i am just asking could you implement a standalone feature in your great tool to create local cached maps for the MFS, which can be copied / imported to the MFS folders then?

the feature would be a clear selling point for me. without this feature, your great tool is unfortunately useless for me

kind regards

**Comment by derekhe** [comment]
I thought about this feature before and seems it is minor case feature; I will wait until more people request for this.

**Comment by jesterelly** [comment]
ok, that sucks but it's understandable. considering the work hours it would take you to implement this feature, what would be the costs in $ to you? would you implement the feature if there wasn't the demand but your implementation costs were reimbursed?
