### ISSUE TITLE
Failed to create map cache file, but it's already there

### ISSUE THREAD

**Issue by leftos** [derekhe/msfs2020-map-enhancement#743]
**Describe the bug**

It appears that the app tries to create a new cache.db file every time it launches, independent of the existence of one already. So, if there's not enough free space for two of them of the same size to exist at the same time, it reports that I'm out of space. That doesn't seem right. Why is it trying to create a new one at all, when the one that I was using last time the application was running still exists?

**MSFS version:**
N/A

**Mod version:**
8.0.10

**Device ID**
G30HV4ADR6CGTXT3G6NJNX6GDYM2VP6J2SSMHDDXDG0FE353Q0G0

**Screenshots**
N/A

**Additional context**
N/A

**Comment by derekhe** [comment]
How about now? I find out a bug in cache handling and it should be good now.
