### ISSUE TITLE
possibly hinder communications between MSFS and other software

### ISSUE THREAD

**Issue by AndyCYXU** [derekhe/msfs2020-map-enhancement#744]
**Describe the bug**

hi, i have been using your mod since beginning and have a pro license as well, as of recent there has been a problem using your mod and some other program.

I use something called MultiCrewExperience which is a co-pilot for MSFS can move all dials and knobs etc in aircraft. Used it and it worked for very long time without issues with your MapsMod, now every time I use mapmod there seems to be an issue where MCE cannot communicate with my aircraft FENIX in this case and cannot switch many of the them, as if there is a communication problem between MCE and MSFS, but it only happens when I run your MapMod, since you know all the inside workings of your mod can you think of anything that it could be doing to hinder the communication between other programs and MSFS. 

There has been no recent updates to MCE to cause that so i ma leaning that it has something to do with MapMod
I also had problems with FCUIPC not communicating with MSFS when MapMod is being used. Tested it various times and every time when I run the MSFS with MapMod there is a problem when i run MSFS without the MApMod worked fine.

There has been and update to Fenix software recently so it might be that your MapMod is blocking some communication that Fenix has with MSFS and other software via MSFS.. but the one thing in common is always when I do not use MapMod then everything is fine and it is a bummer as I really like your mod and used it pretty much since day ONE :(

Thanks for taking time to look into it.

**MSFS version:**
 - Microsoft Store
 - MSFS2020 Version Newest

**Mod version:**
- 8.0.10 and tried older also 7.6.2 same issue

**Device ID**
- KE1MFP9X3T0YNCKX745KVT919Y79473FFZYW8WXZHQSV0ZX3WXRG
-

**Comment by derekhe** [comment]
My app will use the 443 port for https server hijacking.
And it will also use SimConnect to get plane location and altitude.

If you have many plugins and they may use up all SimConnect resources, the simconnect server can be configured to allow more clients.
Look into the SImConnect.xml in your msfs's local cache folder:
![image](https://github.com/user-attachments/assets/f097fd65-84dd-49ee-ad95-c79b3c3dfd3e)

Change the MaxClients to bigger value:
![image](https://github.com/user-attachments/assets/fd0bfb08-7926-4246-bd6c-ca7b7ddea9d2)

Hope it will solve this issue.

**Comment by derekhe** [comment]
@AndyCYXU is this helpful?

**Comment by AndyCYXU** [comment]
There was an update to the Fenix software after I wrote this message and now it seems they all work again just fine.. 
Your program MCE and Fenix all together no issues.
i am not sure what it was all about.. my simconnect clients where already set to 128.. it works now just fine naybe it was was some conflict with Fenix software that needs to run when I use the aircraft, also I did not mention but I had no problems with PMDG while Fenix was not working as earlier explained.

**Comment by robvalkyrie** [comment]
It messed up my MSFS imagery, Love it but now I dont know what to do

**Comment by derekhe** [comment]
Please try remove the lines in hosts file as described in the manual. After removing the lines it doesn’t relative to this mod any more. In the recent version when you uninstall the hosts file should be fixed automatically.





------------------ Original ------------------
From: robvalkyrie ***@***.***&gt;
Date: Fri,Oct 4,2024 10:54 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] possibly hinder communicationsbetween MSFS and other software (Issue #744)





 
It messed up my MSFS imagery, Love it but now I dont know what to do
