### ISSUE TITLE
Cancel the update installation

### ISSUE THREAD

**Issue by Vitold69** [derekhe/msfs2020-map-enhancement#745]
8.0.10

"Enable the option to cancel the update installation"

Where is his option?????

**Comment by derekhe** [comment]
When there is an update and it prompts to install the new install, there is a cancel button.
Generally speaking, I'd like to keep the version update to date.

**Comment by Vitold69** [comment]
When you should make an option - "Do not check for updates"

**Comment by derekhe** [comment]
No, I won't provide this feature because I'd like to keep the app up to date. Otherwise, I will face issues from different versions.

**Comment by derekhe** [comment]
No, I won't provide this feature because I'd like to keep the app up to date. Otherwise I will face issues from different versions.
