### ISSUE TITLE
Cannot save setting

### ISSUE THREAD

**Issue by ayrton74** [derekhe/msfs2020-map-enhancement#746]
From the last version, i cannot save setting (quality and folders)

**Comment by derekhe** [comment]
What's your device id?

**Comment by jef32** [comment]
Hi
Same for me. MSFS Map Enhancement don't launch MSFS and cannot save the settings on Steam version.
MSFS works properly when launching it directly.

**Comment by derekhe** [comment]
Please leave me your device id in the license page and I will investigate&nbsp;





------------------ Original ------------------
From: jef32 ***@***.***&gt;
Date: Mon,Sep 23,2024 10:11 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cannot save setting (Issue#746)





 
Hi
 Same for me. MSFS Map Enhancement don't launch MSFS and cannot save the settings on Steam version.
 MSFS works properly when launching it directly.

**Comment by jef32** [comment]
As I've said just above, my ID license showed in the application is :
8HP1M7KWPJ0RC3GPSHZ8Q2EDBREZX4YDFV4V66GW89Q8405TWTHG.
I've tried several methods: With the auto-update
With the uninstall the reinstall with the version found here.
It's the same, MSFS doesn't launch. My setting saying that I use a steam version is not kept and each time, MSFS2020-ME has return to "MS Store" but my personnal settings for the cache directory and the colours are always available from previous versions.
Perhaps we have to erase the .cfg file or the .ini somewhere on the computer to generate a new one but I don't find where it is hidden.

**Comment by ayrton74** [comment]
Xplane 12.
My ID
1JE9ZTWBWEK855JZZJ4W35DC6JGKQCZHF0SV10ZH2A39ZX36NPB0

**Comment by ayrton74** [comment]
I saw on discord another user has the same issue

**Comment by 5443322** [comment]
the same problem after update ! My ID MHRFJVZX53MT9CPGQBYRG9QK7REMN4SGFA0XF2B02J8QN21RJYH0

**Comment by derekhe** [comment]
I will investigate asap





------------------ Original ------------------
From: 5443322 ***@***.***&gt;
Date: Tue,Sep 24,2024 10:25 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cannot save setting (Issue#746)





 
the same problem after update ! My ID MHRFJVZX53MT9CPGQBYRG9QK7REMN4SGFA0XF2B02J8QN21RJYH0

**Comment by jerry28111** [comment]
Same issue after update, I set Enable high LOD, however, when I start the app next time, map settings turn to be unselected.

**Comment by derekhe** [comment]
Should be fixed in 8.0.13, please update.

**Comment by ayrton74** [comment]
And for xplane?

**Comment by derekhe** [comment]
yes





------------------ Original ------------------
From: ayrton74 ***@***.***&gt;
Date: Tue,Sep 24,2024 10:07 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Cannot save setting (Issue#746)





 
And for xplane?

**Comment by ayrton74** [comment]
It's ok now
Thank you very much
