### ISSUE TITLE
Offline maps only after 8.0.12 update

### ISSUE THREAD

**Issue by buj818** [derekhe/msfs2020-map-enhancement#747]
As title states, cannot import google, arcis, or bing latest maps after latest update.  All online settings are on in MSFS2020 Data page, all online functions work within game except the maps. Changed network from enhanced to normal, several times.  Rebooted.   It tells me tiles are loaded, but in game theres nothing but generic/offline buildings and terrain.  Ive uninstalled/reinstalled, did not fix the issue.  Is there still access to previous version so i can try to reduplicate?  If i run msfs2020 without running this mod, the stock photogrammetry returns and looks fine.  This is on Win11 MS store version of msfs2020. Device ID: 3GVN5D3KN5BEH1FCVABFESQB5M04FX6R00KNQ568ZETWEAWXJDF0

EDIT: 8.0.10 works flawless on my PC.  It tells me it will auto update next time program is ran.  I entered the game and everything was perfect.  Closed game, allowed it to do its thing, and it updated to 8.0.12, then right back to offline buildings.  I cant figure out why this is happening.  As of now, I am keeping 8.0.10 and cancelling the update on program start.  The only downside so far other than this issue is that the color wheel is no longer adjustable.  It worked just fine 2 days ago.  Can you please throw me a recommendation how to get that working again please?  Thank you for your time.  Brian

**Comment by Vitold69** [comment]
What I understand is when the Sim can't/stop getting online imaginery it crashes. My sim started CTD after 8.0.12. going back to 8.0.10 and let's see.

**Comment by buj818** [comment]
> What I understand is when the Sim can't/stop getting online imaginery it crashes. My sim started CTD after 8.0.12. going back to 8.0.10 and let's see.

Yes, going back to 8.0.10 is still working great for me.  The only downside is that you have to make sure you cancel the update every time it asks you after restarting the program.

**Comment by Vitold69** [comment]
What do you think about downgrade process? Do I need to uninstall the higher version first? I know I can downgrade versions simply by installing the lower one but is it correct procedure?

**Comment by derekhe** [comment]
Should be fixed in 8.0.13, please update.
