### ISSUE TITLE
[Feature] Manual Install

### ISSUE THREAD

**Issue by ItMeCorban** [derekhe/msfs2020-map-enhancement#750]
#### Motivation

I'm always frustrated when mods require arbitrary EXE's just to copy some files.

#### Detailed design

A zip file with the required files and a text file telling you where to put them

#### Alternatives

A 7z file with the required files and a test file telling you where to put them

#### More detail (optional)

exe installers are not OS agnostic

**Comment by derekhe** [comment]
I won't provide this until more people need this feature. In the installer it installs dependencies and does proper clean up when uninstalled.

**Comment by derekhe** [comment]
I won't provide this until more people need this feature. In the installer it installs dependencies and does proper clean up when uninstall.

**Comment by ItMeCorban** [comment]
Oh no not dependencies D: how could anyone ever figure out how those work
