### ISSUE TITLE
8.0.13.0 can't access  c:\windows\system32\drivers\etc\hosts anymore

### ISSUE THREAD

**Issue by ddezulier** [derekhe/msfs2020-map-enhancement#751]
8.0.13.0 can't access c:\windows\system32\drivers\etc\hosts

:-/

**Comment by derekhe** [comment]
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#85-hosts-file-issues

**Comment by ddezulier** [comment]
closed to fast : I am using Map Enhancement for a while, and the etc/hosts access problem just came with 8.013.0.
Map Enhancement is launched with admin privileges so it should not be a problem 
etc/hosts is a sensitive file and giving any users all control on etc/hosts is not the best way to solve the problem

what kind of access to etc/hosts and for what purpose ? 
Thank you

**Comment by derekhe** [comment]
It redirects MSFS's traffic to my mod so that I can return images for MSFS other than fetch it from MS.

**Comment by ddezulier** [comment]
Hello,ThanksI started Map Enhancement as admin which solved etc/hosts access.far better than allow etc/hosts access to anybody ... ;-) A glimpse from etc/hosts# Copyright (c) 1993-2009 Microsoft Corp.## This is a sample HOSTS file used by Microsoft TCP/IP for Windows.## This file contains the mappings of IP addresses to host names. Each# entry should be kept on an individual line. The IP address should# be placed in the first column followed by the corresponding host name.# The IP address and the host name should be separated by at least one# space.## Additionally, comments (such as these) may be inserted on individual# lines or following the machine name denoted by a '#' symbol.## For example:## 102.54.94.97 rhino.acme.com # source server# 38.25.63.10 x.acme.com # x client host# localhost name resolution is handled within DNS itself.# 127.0.0.1 localhost# ::1 localhost192.168.0.31 homen.home #FBW https MCDU for A32NX# ---- the part Map Enhancement dynamically adds and suppresses ---- 127.0.0.1 kh.ssl.ak.tiles.virtualearth.net127.0.0.1 t3.ssl.ak.tiles.virtualearth.net127.0.0.1 t2.ssl.ak.tiles.virtualearth.net127.0.0.1 t1.ssl.ak.tiles.virtualearth.net127.0.0.1 t0.ssl.ak.tiles.virtualearth.net127.0.0.1 khstorelive.azureedge.netRegardsDanielenvoyé : 26 septembre 2024 à 16:33de : hesicong ***@***.***>à : derekhe/msfs2020-map-enhancement ***@***.***>cc : ddezulier ***@***.***>, Author ***@***.***>objet : Re: [derekhe/msfs2020-map-enhancement] 8.0.13.0 can't access c:\windows\system32\drivers\etc\hosts anymore (Issue #751) It redirects MSFS's traffic to my mod so that I can return images for MSFS other than fetch it from MS.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ddezulier** [comment]
Hello, Ok, But do not forget to replace the advices "stop antivirus", or "change etc/hosts access rights" by "try to launch map enhancement as an admin". Cyber attacks are more difficult to launch if right security principles are given to customers and end users.;-)RegardsDaniel envoyé : 26 septembre 2024 à 16:33de : hesicong ***@***.***>à : derekhe/msfs2020-map-enhancement ***@***.***>cc : ddezulier ***@***.***>, Author ***@***.***>objet : Re: [derekhe/msfs2020-map-enhancement] 8.0.13.0 can't access c:\windows\system32\drivers\etc\hosts anymore (Issue #751) It redirects MSFS's traffic to my mod so that I can return images for MSFS other than fetch it from MS.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
