### ISSUE TITLE
No Photogrametry when MSFS2020 Map Enhancement Pro running, since few days (Update 8.0.12 and 8.0.13)

### ISSUE THREAD

**Issue by herpijay** [derekhe/msfs2020-map-enhancement#753]
**Since both updates I have no more photogrametry 3d for all cities in msfs, onnly appear autogen buildings and WU POIs, it is since few days coupled with the both updates

When the program is closed; everything is ok with the default map from msfs and photogrametry (see both situation from screenshoot).

![Zrzut ekranu 2024-09-24 220605](https://github.com/user-attachments/assets/69328cf5-f494-4103-af73-bf2ab17bd9a1)
Salzburg with MSFS2020 Map Enhancement

![Zrzut ekranu 2024-09-24 221216](https://github.com/user-attachments/assets/67ea057c-31c0-4864-bb54-ed6bcac25f77)
NY with MSFS2020 Map Enhancement

![Zrzut ekranu 2024-09-24 222445](https://github.com/user-attachments/assets/6a4506ee-57cb-477d-b569-317ae2af1984)
Salzburg, default MSFS bing without the MSFS2020 Map Enhancement

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - steam
 - MSFS2020 Version [1.37.19.0]

**Mod version:**
-  8.0.13

**Device ID**
- 715J4004YREF4A0Y608Q9ZV8HDP34H6X4RAXHQ0N95A8QDVKNQFG

**Comment by FedeVerd** [comment]
I have the same issue.

**Comment by jef32** [comment]
Same issue for me.

**Comment by derekhe** [comment]
Interseting, let me test. My MSFS crashed and I need to reinstall it.

**Comment by jef32** [comment]
Revert back to 8.10.0 working well with Photogrammetry, waiting for the fix 8.14.0

**Comment by herpijay** [comment]
Do you have 8.0.11 i installe?, it is possible to bloc the update,  it was
the last stabile version for use.

**Comment by jef32** [comment]
To block the update, you simply click "cancel" when it asks to install the update. You have to do it, each time you launch Msfs2020- Map Enhancement, but it's the only solution waiting the fix. With the 8.10.0, I've tried to fly above Bordeaux since it's the town where I was born and raised and all the good buildings and monuments are here with photogrammetry ON.

**Comment by derekhe** [comment]
Hello everyone, the issue has been resolved. Kindly update to the latest version. Apologies for the inconvenience.

**Comment by jef32** [comment]
Derekhe, you give freely to the MSFS community a fabulous software to enhance MSFS2020. No need to apologize for your recent mistakes. It's up to us to be grateful to you.
