### ISSUE TITLE
generate device ID

### ISSUE THREAD

**Issue by freeman7846** [derekhe/msfs2020-map-enhancement#754]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore 
![Desktop Screenshot 2024 09 28 - 16 16 57 34](https://github.com/user-attachments/assets/1b289739-edec-4274-a756-edc63e0619b2)
![Desktop Screenshot 2024 09 28 - 16 16 57 34](https://github.com/user-attachments/assets/619628fe-aef3-40ab-84f8-62a88d0a0661)

 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
This is due to the WMIC service is disabled, please try to fix this first:
https://learn.microsoft.com/en-us/windows/win32/wmisdk/starting-and-stopping-the-wmi-service

**Comment by freeman7846** [comment]
Je n'y arrive pas à exécuter

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
