### ISSUE TITLE
Color settings isn't working

### ISSUE THREAD

**Issue by jonhyleo** [derekhe/msfs2020-map-enhancement#756]
Please describe the bug in detail to help me understand the scenario:
Color settings won't affect the sim terrain. I tried to move the color adjustments slider and nothing happened. I have the FS rolling cache disabled and the app cache disabled as well.

**MSFS version:**
 - Steam
 - Latest MSFS2020 Version

**Mod version:**
- 8.0.14.0

**Additional context**
I'm using Lossless Scaling and AutoFPS, but the color settings worked in previous versions of FS Map Enhancement

**Comment by derekhe** [comment]
Where did you fly? Maybe it is photogrammetry data so any adjustment won't work for it.

**Comment by tadeuprimo** [comment]
Notice this problem too.. I usually fly over Brazil and I tried to disable cache in both, MSFS and MAP Enhancement to make sure that I wasn't seeing older images.
Neither contrast, nor brightness, nor colors have worked as before.

**Comment by tadeuprimo** [comment]
Even when flying for hours with cache disable, doing extreme settings in this panel, nothing change. 

![Untitled](https://github.com/user-attachments/assets/1012d86e-cdee-4b45-9961-1bdac2d2e8eb)

**Comment by derekhe** [comment]
I will have a look

**Comment by derekhe** [comment]
Ok, I know why you have this issue. In latest version I changed this feature to be pro version only, I will add some notification of this feature change.

**Comment by tadeuprimo** [comment]
Sad
