### ISSUE TITLE
Re connect after internet drop out

### ISSUE THREAD

**Issue by rob1183** [derekhe/msfs2020-map-enhancement#759]
A few times recently, my internet has dropped out for a few minutes. After this i've noticed that the Mod doesn't seem to refresh and add new data.

Is the a way of reconnecting the mod to an active internet after a drop out without a total restart.

**Comment by derekhe** [comment]
Please try switch to another map server. Or you can change the network settings from enhanced to normal&nbsp;





------------------ Original ------------------
From: rob1183 ***@***.***&gt;
Date: Sat,Oct 5,2024 5:06 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Re connect after internet drop out(Issue #759)





 
A few times recently, my internet has dropped out for a few minutes. After this i've noticed that the Mod doesn't seem to refresh and add new data.
 
Is the a way of reconnecting the mod to an active internet after a drop out without a total restart.

**Comment by rob1183** [comment]
I have tried this previously and it didn't seem to do anything, I'll give it another go next time it happens and see.
