### ISSUE TITLE
won't load after installing pro version

### ISSUE THREAD

**Issue by Woomaster5150** [derekhe/msfs2020-map-enhancement#761]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario
![Screenshot 2024-10-08 200649](https://github.com/user-attachments/assets/f7386843-6a9e-4670-abcd-df0e38dfcb8d)

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Make sure you setup and test the custom map before use it.





------------------ Original ------------------
From: Woomaster5150 ***@***.***&gt;
Date: Wed,Oct 9,2024 9:10 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] won't load after installing proversion (Issue #761)
