### ISSUE TITLE
Impossible to generate device ID

### ISSUE THREAD

**Issue by oraziodipietro** [derekhe/msfs2020-map-enhancement#762]
**Describe the bug**

At launch the following message appears:
It is impossible to generate device ID. Please ensure that your WMIC service has been opened. Applications are about to exit.

**MSFS version:**
 - msstore or steam
 - MSFS2020 Version [e.g. 22]

**Mod version:**
- Mod version

**Device ID**
- Device ID

**Screenshots**

![image](https://github.com/user-attachments/assets/633d2481-93cd-4d6d-bc8a-8263e6422c29)

**Additional context**

**Comment by derekhe** [comment]
Please try the following solutions: https://www.tweaking.com/fix-wmi-corrupted-in-windows/
