### ISSUE TITLE
[Feature] Bring back the in-app map view

### ISSUE THREAD

**Issue by BirdmanRS** [derekhe/msfs2020-map-enhancement#766]
#### Motivation

Versions 7.6.2 and prior had the ability to view the map from the server you had selected.  This was incredibly helpful in checking which server had the most recent view/data.  Even after v8 was released, I kept using 7.6.2 for this reason.  Now 7.6.2 won't run, stating it has been blacklisted.  Being forced to use v8, I'd love to see the map view function return.  Its very helpful for scenery design, knowing I'll be using the most recent map data in the sim.

#### Detailed design

Similar to versions prior to v8, a section in the app to view the map data from the selected server.

#### Alternatives

Without knowing the exact URLs the default map servers are using, I don't know of a way to have these views any other way.

#### More detail (optional)

Thanks!

**Comment by derekhe** [comment]
Thanks for the feedback. I am working on bringing this back soon. There are some coding need to do to make it consistent between MSFS and xplane.





------------------ Original ------------------
From: BirdmanRS ***@***.***&gt;
Date: Fri,Oct 18,2024 6:24 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] [Feature] Bring back the in-appmap view (Issue #766)





 
Motivation
 
Versions 7.6.2 and prior had the ability to view the map from the server you had selected.  This was incredibly helpful in checking which server had the most recent view/data.  Even after v8 was released, I kept using 7.6.2 for this reason.  Now 7.6.2 won't run, stating it has been blacklisted.  Being forced to use v8, I'd love to see the map view function return.  Its very helpful for scenery design, knowing I'll be using the most recent map data in the sim.
 
Detailed design
 
Similar to versions prior to v8, a section in the app to view the map data from the selected server.
 
Alternatives
 
Without knowing the exact URLs the default map servers are using, I don't know of a way to have these views any other way.
 
More detail (optional)
 
Thanks!

**Comment by BirdmanRS** [comment]
Looking forward to it... Thanks for the quick response!

**Comment by derekhe** [comment]
Done

**Comment by BirdmanRS** [comment]
Thanks! Will give it a try!
