### ISSUE TITLE
Bing maps updates

### ISSUE THREAD

**Issue by slavamirin** [derekhe/msfs2020-map-enhancement#769]
Hello! I am about Bing service maps updates frequency. For example the winter comes and what about winter or other seasons textures from Bing maps? How often Bing updates its images? I know that XP12 has a seasons, but if we use fototerraine from Bing, is it will changes seasonal or not?

**Comment by derekhe** [comment]
I don't know when Bing maps will get updated.
Yes, XP12 has seasons, but it won't change the satellite images.
