### ISSUE TITLE
Runway can not be loaded

### ISSUE THREAD

**Issue by h0wardch3ng** [derekhe/msfs2020-map-enhancement#77]
**Describe the bug**
All other satellite tiles images load normally, Runway can not be loaded.

**Screenshots**
![Snipaste_2022-03-22_17-27-40](https://user-images.githubusercontent.com/2175497/159449249-ee1c9560-3fa1-4986-bf4c-75725efee424.jpg)

**Comment by h0wardch3ng** [comment]
Runway is satellite image, not a in-game runway.

**Comment by derekhe** [comment]
I have no idea about this, please give me where you are flying? Longtitude and lattitude.

**Comment by h0wardch3ng** [comment]
ZSPD
But I tested on another computer is normal.
I do not know how to solve this problem.

**Comment by h0wardch3ng** [comment]
Solution in https://github.com/derekhe/msfs2020-map-enhancement/issues/87#issuecomment-1093297653
