### ISSUE TITLE
Impossible to Generate ID....

### ISSUE THREAD

**Issue by ypaul123** [derekhe/msfs2020-map-enhancement#770]
**Describe the bug**
When opening the software it says:
![image](https://github.com/user-attachments/assets/582bb3b1-3cae-40c3-bf3e-41071f2cfea2)

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 **steam**
 - MSFS2020 Version [e.g. 22]
 - **Latest**

**Mod version:**
- **MSFS.Map.Enhancement.Installer.8.0.19.0**

**Device ID**
- **Can't tell you that, that's the issue...**

**Screenshots**
![image](https://github.com/user-attachments/assets/96e7915d-d09a-4020-83aa-e329a600c784)

I followed this website's instructions: https://www.tweaking.com/fix-wmi-corrupted-in-windows/

also 

![image](https://github.com/user-attachments/assets/ccf153d8-eafc-47df-8c81-cdbd370775a2)
![image](https://github.com/user-attachments/assets/29bbbeb3-63d0-4336-9294-f7edc37f949f)

Please help.

**Comment by ypaul123** [comment]
OK I've fixed it.
Thanks!

**Comment by haliyahewa** [comment]
Yes, I bought it on the MSFS Map Enhancement, no matter how many times I tried  to find it the code in GitHub, where I bought it. Could you please help me.
haliyahewa@gmail.com or casa@aqazul.com Please.
