### ISSUE TITLE
Errors when using Mapbox

### ISSUE THREAD

**Issue by ypaul123** [derekhe/msfs2020-map-enhancement#771]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario
I'm getting load errors  when downloading tiles from **Mapbox**.

**MSFS version:**
**steam**
 - MSFS2020 Version [e.g. 22]
**Latest**
**Mod version:**
**8.0.19.0**

**Device ID**
PQ0VMR7K3V9PKNNAK6XSHF63KYA3EMAR8TDG417D2X2JMDXJ7540

**Comment by derekhe** [comment]
Please provide more details for me to help. Where are you flying? And please take screenshots.
