### ISSUE TITLE
Load Errors after fresh PC Restore

### ISSUE THREAD

**Issue by dutto98** [derekhe/msfs2020-map-enhancement#773]
Hey Guys, 

Been using Google Map Mod for last year, always only used Bing Latest Maps. Never ran into a problem with it until i did a fresh Re install of my PC last week. now using the Bing latest im getting Load Errors. 

Have tried switching network configs from normal to enhanced and back etc but to no Avail. 

Any other suggestions? 

Thank you

Jack

**Comment by Richdem** [comment]
I have also noticed that each flight I am getting tons of errors being reported when I go to close the application down. For me it started about 2 weeks ago.

**Comment by dutto98** [comment]
Strange, about the same time for me also!

Thank you for your reply.

**Comment by derekhe** [comment]
The application and the map service are good. I just checked, please have a try again.

**Comment by Richdem** [comment]
> The application and the map service are good. I just checked, please have a try again.

Is there anything that needs to be done in the settings? I did a quick test yesterday with Google Maps and had no errors but I prefer Bing Maps. Will try now

Thanks for the reply

**Comment by Richdem** [comment]
I am about 25 minutes into my current flight and the app is reporting over 70,000 load errors and is climbing rapidly

**Comment by derekhe** [comment]
I see, when it is loading over the ocean there are errors happen. There is no impact on the actual fly but I will optimize it in future.

**Comment by Richdem** [comment]
> I see, when it is loading over the ocean there are errors happen. There is no impact on the actual fly but I will optimize it in future.

Thank you Sir !

I did a fight from Toronto to Fort Lauderdale yesterday and did see some errors over land but not as many as I had seen before. Just thought I would provide some more feedback.

**Comment by dutto98** [comment]
Yeah for me it doesnt matter where i fly, over water or land. Been using google maps and apple maps and all load correctly, just bing maps for some reason

**Comment by Richdem** [comment]
> Yeah for me it doesnt matter where i fly, over water or land. Been using google maps and apple maps and all load correctly, just bing maps for some reason

Interestingly I did another flight in Europe yesterday with Google Maps and I got even more errors than I did with Bing Maps

**Comment by tencatao** [comment]
Same issue here.

 More load errors than load

 Independent of where I'm flying

**Comment by derekhe** [comment]
Please check the latest version and see if it is better.

**Comment by Richdem** [comment]
> Please check the latest version and see if it is better.

I did two flights yesterday in Europe using Bing Maps and there were no errors. 

Thank you for fixing this
