### ISSUE TITLE
Link to purchase pro licence wont work

### ISSUE THREAD

**Issue by dutto98** [derekhe/msfs2020-map-enhancement#775]
Hi, 

Just trying to purchase the pro licence again after mine expired, and the link - https://k.aiflygo.com/  wont open and says HTP error 502. Cant open the link in any device. Any way around this so i can purchase again??

**Comment by derekhe** [comment]
Please wait a while. The server has some issues. You can try after 6 hours.

**Comment by derekhe** [comment]
It is back to normal now.
