### ISSUE TITLE
Blocked by Antivirus after last update (20)

### ISSUE THREAD

**Issue by MajorAlvega1** [derekhe/msfs2020-map-enhancement#776]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

Detected: Trojan:Script/Wacatac.B!ml

file: C:\Program Files (x86)\MSFS Map Enhancement\MapEnhancement.dll

MSFS store

Mapbox pro

It's on quarentine, i can't open the app anymore

Microsoft default anti-virus

**Comment by supertrampy** [comment]
![file](https://github.com/user-attachments/assets/e4fcc515-829f-449b-a871-48f2203a984c)

**Comment by derekhe** [comment]
I checked with virtualtotal and it should be a false positive, please check it here: https://www.virustotal.com/gui/file/b6e0ad26548e728d85038b2cb7a9be35eaf1c74a9bcb3c418982d1f4ec1f91d5

And the installer: https://www.virustotal.com/gui/file/8084be1162fd4d7d4dd3fcfbfd7026e151c9c218b88feb998322ad26d452d674

Please also have a look: https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#86-virus-report-and-https-certificate-error
