### ISSUE TITLE
Color changes not working (I have Pro license)

### ISSUE THREAD

**Issue by buj818** [derekhe/msfs2020-map-enhancement#778]
**MSFS version 2020:**
 - msstore 
 - MSFS2020 Version latest

**Mod version: latest 8.0.20.0

I just purchased and activated Pro license yesterday.  I cannot change colors, saturation, brightness, etc.  The sliders are unlocked and move, but no changes happen no matter how extreme I go.  I have cleared, disabled all caches and restarted PC several times.  MSFS rolling cache is off.  This happens in both 2D and VR.  I have tried google pro maps 1 and 2.  

**Device ID**
- Device ID 3GVN5D3KN5BEH1FCVABFESQB5M04FX6R00KNQ568ZETWEAWXJDF0

**Comment by derekhe** [comment]
Hello, I tested today and it is working. I changed the color setting to very red and you can see the changes in the mapview.
![image](https://github.com/user-attachments/assets/a649c104-7203-4fb5-b00f-daa9c918d2b2)

![image](https://github.com/user-attachments/assets/25283d7e-26b0-46f2-b72a-ed3556c735ab)

I think you may fly over a photogrammetry covered area which covers the satellite images below. Please try another place and see if it works.

**Comment by buj818** [comment]
Thank you for the response.  I have tried New York, Central Pennsylvania, DC, Maryland, Puerto Rico, Dominican Republic, and western Cuba.  It still shows no color/image modifications no matter where I fly.  Following your example above using the map, the only color difference I can see when experimenting is a slightly darker blue, but it doesn't reflect the terrain in game.  Do you know of any other mods that may conflict with this?  I removed my entire community folder and did a couple "bare bones" flights, and still saw no difference.

**Comment by derekhe** [comment]
Hmm, do you see color changes in the map view? If the map view shows the modified images, then you should check if the in game rolling cache (should be OFF), and also the bing online map is ON in the game. 
![image](https://github.com/user-attachments/assets/1a45caf1-73c7-4406-875f-762c4d4b58c4)

![image](https://github.com/user-attachments/assets/98d6f1da-7a34-48ba-bf68-d0c4213aaba0)

**Comment by buj818** [comment]
Yes sir, rolling cache has been off, and bing data on.  I will disable OpenXR Toolkit this afternoon and see maybe if there is a conflict there.  I really don't think it will matter though because there is still no changes visible in 2D mode.  I will also try a reinstall and activation of your mod as well.  I will report back to you in a few hours.  Let me know if there is anything else you can think of.  Thanks.  Brian

**Comment by buj818** [comment]
When I started mod today, there was an update.  Downloaded, restarted, and it all works as it should now.  Flew in the desert and over some major cities, the difference is now there.  All seems to work now.
