### ISSUE TITLE
Stop working.

### ISSUE THREAD

**Issue by JoaquinBCVR** [derekhe/msfs2020-map-enhancement#781]
Sorry for this simple issue, but many time working, and now, reinstalling MSFS2020, a license of map enhacement just starting, map enhacement reinstalling, but, I dont know why now dont work. Many hours trying.

(Thanks for the app, is very useful).

How can I verify that all is correct? There is a "checklist" of config? In MSFS about map enhacement, I mean.

Thanks.

**Comment by JoaquinBCVR** [comment]
Sorry, I think works, only I had installed zinertek enhance airports, and in my home zone, near the airport, dissapear the map enhacement. maybe is this another prg.

Thanks.

**Comment by derekhe** [comment]
Your airport may have a satellite image layer which is above the satellite image layer.
