### ISSUE TITLE
Doesn't load data

### ISSUE THREAD

**Issue by Maisi089** [derekhe/msfs2020-map-enhancement#782]
When the game starts, no data is loaded on the map or only 1 field
Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore
 - MSFS2020 Version [e.g. 22]

**Mod version:**
8.0.21.0

**Device ID**
CA6RESY8YYFWF5RJ1Q6RKM4YG14WCPS9PDC1385HFKYCYYBQE0P0

**Screenshots**
![Screenshot (4)](https://github.com/user-attachments/assets/741e83f5-ab31-40dc-ae1f-c1bc4bcd3b3f)

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by Maisi089** [comment]
![Screenshot (5)](https://github.com/user-attachments/assets/35d3e9bd-2dc1-4cf1-811c-c30b742ed983)
Here you can see best that the data is no longer being loaded

**Comment by derekhe** [comment]
Please make sure everything setup is correct:
https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN#4-usage

**Comment by Maisi089** [comment]
Thanks, something was wrong
