### ISSUE TITLE
MSFS24 Version 8.0.22.0 - Apple Maps Not Working

### ISSUE THREAD

**Issue by AppleUK123** [derekhe/msfs2020-map-enhancement#783]
Hi,

I've followed your instructions regarding the cache for MSFS24. However, when using Apple Maps, the ground imagery appears identical to the default. I've compared images, and they look the same.

Could you please confirm if Apple Maps is functioning correctly in MSFS24?

Regards, AppleUK

**Comment by derekhe** [comment]
Is working. I think you may have rolling cache issue, please make sure it is deleted before the game starts. Then you can view the map in the map viewer in the mod. In some area, the satellite images are covered by photogrammetry data, you can try different places.

**Comment by AppleUK123** [comment]
Thank you. I just remembered that I had my MSFS cache set to a non-default location. So have set the correct path in Map Mod and will report back.

**Comment by AppleUK123** [comment]
@derekhe Could you post a comparison shot somewhere with the default maps and Apple Maps, please? I've tried again, but I still can't notice any difference

**Comment by derekhe** [comment]
Can you try other maps? If none of the maps works, then there is some setup issues, I think. Please remember start the mod BEFORE starting the game.

**Comment by AppleUK123** [comment]
Yes, I've tried other map. Always Start map mod before starting MSFS24. 
I've tried random locations and can't see a difference.

**Comment by AppleUK123** [comment]
![image](https://github.com/user-attachments/assets/a2d12623-a25e-41b6-b902-22d7ca3bcff0)

**Comment by derekhe** [comment]
Did you see the "load" images in the start page?

**Comment by derekhe** [comment]
Another thing you can try is to tune the colors, if you see nothing changed on the map, then there should be something wrong.
Please make a screenshot you have seen.

**Comment by AppleUK123** [comment]
Ah yes tuning the colors I can tell a difference. Strange, maybe the all the added ground stuff in 24 makes it more difficult to tell a difference.
Thanks for your help

**Comment by derekhe** [comment]
Yes, especially trees cover a lot of ground textures :)
