### ISSUE TITLE
This is more question less of an issue

### ISSUE THREAD

**Issue by c9jayyy** [derekhe/msfs2020-map-enhancement#784]
**Describe the bug**

So how do i tell if the mod is on. I have LOD on according to the application and it says stop but i cant see if its running anywhere. i wanna upgrade to pro but it said check free see if it works but idk where to even look

**MSFS version:**
 - msstore
 - MSFS2024Version

**Mod version:**
- On latest version

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please have a look how to setup it properly. https://github.com/derekhe/msfs2020-map-enhancement/wiki/Manual-EN
