### ISSUE TITLE
Google Map 1 (Pro) does not reflect maps.google.com?

### ISSUE THREAD

**Issue by fstlaneukraine** [derekhe/msfs2020-map-enhancement#785]
I am using Google Map 1 (Pro) as my map in the mod and had a question of why it doesn't look like the actual satellite view I see on maps.google.com?

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - MS Store
 - MSFS 2024

**Mod version:**
- 8.0.25.0

**Device ID**
- S35YCMVE1ME6YVH1PXSD5JNTWX7HP79FC8THE3Y64A8GDMEW1SN0

**Screenshots**

In Game:

![image](https://github.com/user-attachments/assets/982f8307-4a33-4cf0-8c7a-3ef15ddefc52)

Google Maps:

![image](https://github.com/user-attachments/assets/e4175eb7-9bda-4337-8067-c97fa0a526d1)

**Additional Details**

The map link for the view above is: https://www.google.com/maps/@28.0291453,-82.33406,972m/data=!3m1!1e3?entry=ttu&g_ep=EgoyMDI0MTExOS4yIKXMDSoASAFQAw%3D%3D

**Comment by derekhe** [comment]
If you enjoy the photogrammetry data, it is fine to turn it on because it provides more realistic buildings
