### ISSUE TITLE
 photogrammetry disabled

### ISSUE THREAD

**Issue by hpair917** [derekhe/msfs2020-map-enhancement#787]
**Describe the bug**

 Photogrammetry buildings are replaced by default autogens when the mod is on

**MSFS version:**
 - msstore
 - MSFS2020 latest ver

**Mod version:**
- latest (8.0.21.0)

**Device ID**
- 5CG19GMNPZFW7C27QSDW4KWSM9FN34DTZ5F5CCZKZQ93SKM40F80

**Comment by hpair917** [comment]
p.s. Seems that the satellite image of this mod covers the images providing photogrammetry models

**Comment by derekhe** [comment]
Please provide location and screenshot&nbsp;





------------------ Original ------------------
From: hpair917 ***@***.***&gt;
Date: Wed,Nov 27,2024 11:55 AM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement]  photogrammetry disabled(Issue #787)

**Comment by hpair917** [comment]
Manhattan
Mod on
![屏幕截图 2024-11-27 121728](https://github.com/user-attachments/assets/a0632447-999c-4007-8ec5-e23549375664)
Mod off
![屏幕截图 2024-11-27 122227](https://github.com/user-attachments/assets/f17747b8-7135-4fce-90eb-885a2ad5bbdb)

**Comment by derekhe** [comment]
I tested the photogrammetry is working, please have a look your photogrammetry toggle is on in the game.
![Microsoft Flight Simulator 2024 - 1 1 9 0 2024_11_28 20_21_02](https://github.com/user-attachments/assets/45f0de55-cc4b-42c6-a08c-96bb833c3976)
