### ISSUE TITLE
Issues with FS2024

### ISSUE THREAD

**Issue by plum130992** [derekhe/msfs2020-map-enhancement#788]
**Describe the bug**

Hello,
Thanks for this great addon

I did a test last night and I'm reporting two anomalies:
1) the FS2024 rolling cache file is not deleted despite a setting that seems correct. I deleted it manually.

2) I made a flight in the Alps, over Chatel and Morgins. The relief is abnormally flattened, the steep peaks appear like hills.

My contribution.
Thanks a lot.

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
 - msstore 
 - MSFS2024

**Mod version:**
- Mod version 8.0.26

**Device ID**
- Device ID

**Screenshots**

Please provide me screenshots for the mod and msfs2020 if possible

**Additional context**

**Comment by derekhe** [comment]
Please provide the device id in the license page.

**Comment by derekhe** [comment]
I can't see your screenshots

**Comment by plum130992** [comment]
> Please provide the device id in the license page.

JKXH5PVPQN1SQWAWKHMRRRW13NCGY0ZHZ9M2R8JC786TXXJ87RPG

**Comment by plum130992** [comment]
![settings](https://github.com/user-attachments/assets/31ea8cd9-c169-4dcb-943b-d2365f0254ef)
![Using MapEnh](https://github.com/user-attachments/assets/f08d8073-2b68-4e20-905a-4b942763902f)
![Without MapEnh](https://github.com/user-attachments/assets/e406db59-e559-408e-8915-78a36e246a26)
