### ISSUE TITLE
FS2020 not working anymore after 8,0.27.0 . Missing FS2020 rolling cache path????

### ISSUE THREAD

**Issue by zawadzkk** [derekhe/msfs2020-map-enhancement#790]
**Describe the bug**

Please describe the bug in detail to help me understand the scenario

**MSFS version:**

 - MSFS2020 Version [latest

FS2020 not working anymore after 8,0.27.0 . Missing FS202 rolling cache path????

**Comment by derekhe** [comment]
What do you mean? Please paste screenshot.

**Comment by gdwnet** [comment]
![image](https://github.com/user-attachments/assets/faf6d472-54a3-4264-8a6a-825c62a85a64)

**Comment by gdwnet** [comment]
Seems to be because "Delete MSFS 2024 rolling cache when start" was enabled. Disabled that and the error went away. I do not have MSFS 2024.
