### ISSUE TITLE
Works flawless in 2020, Not in 2024

### ISSUE THREAD

**Issue by buj818** [derekhe/msfs2020-map-enhancement#797]
**Describe the bug**
2020 works amazing, I had the Pro license for one month to test out, and was even better with 2020.  I cannot however get the mod to work with 2024.  No tiles update while flying, I cannot see anything changing in distance at all like I could with 2020.  Verified that my cache location is identical to mod target path, and have store and version set to 2024 correctly.  I also still manually delete rolling cache file before mod start.  I am starting mod before msfs2024.  The start screen says tiles are loading, as can be seen in the pictures, but they are not actually populating on screen.  MSFS cache file size set to 100G.  Tried all map options with same result.  Please let me know if you need more specific info on anything, Id love this to work for 2024 like it does on 2020 and get that Pro license again.  Id like to add that the pic with my finger pointing at a warehouse (MSFS2024) is actually supposed to be a football field as shown in the last picture (MSFS2020).

![20241203_171413 1](https://github.com/user-attachments/assets/8127d35f-afd0-4b12-9f31-54dda3419cbb)
![20241203_172241 1](https://github.com/user-attachments/assets/65408cf3-0d70-484f-852d-b71265497365)
![20241203_173140 1](https://github.com/user-attachments/assets/16fee203-c542-41b8-a657-519b07452a09)

Please describe the bug in detail to help me understand the scenario

**MSFS version:**
  MSFS2024

**Mod version:**
- Mod version 8.0.29.0

**Device ID**
   M8G25C7XXQ7TAJQYW433PKXVJT7XYQ8N0NW3Y1ECZPX0NYARKW80

**Comment by derekhe** [comment]
I think the area you point to has photogrammetry data or 3d mesh （newly introduced in 2024） covered so you can't see the tiles （although they are loading）.
You can try disable the photogrammetry data and see if you can see the tiles.

**Comment by buj818** [comment]
Yes sir, I have tried several times with both photogrammetry on and off.  It's not just this area as well, its also in NYC, Las Vegas, Dominican Republic, Dallas, and central Virginia (all my most common flight areas).  I just have yet to see any visible changes anywhere.  After speaking with several other users on FB, bouncing settings and sharing screenshots, they are seeing completely different scenery than me in the same areas.  My last resort not yet tried (that I know of) is a complete uninstall/reinstall.

**Comment by derekhe** [comment]
Please make sure you deleted the MSFS2024's rollingcache.

**Comment by buj818** [comment]
That rolling cache file that's selected in the first image here is manually deleted before every startup of the mod.

**Comment by derekhe** [comment]
Alright, if you're uncertain, you could adjust the color settings to a high red intensity and see if that helps. It's possible that the 3D meshes in MSFS2024 are causing issues. If you provide me with your location, I can attempt to troubleshoot when I'm available.

**Comment by buj818** [comment]
My pro license expired earlier this month, color changing is no longer an option.  Is there another setting maybe within MSFS 2024 itself I can try?

**Comment by derekhe** [comment]
You can try switch different maps to see if any changes. It should make changes when you move around.

**Comment by buj818** [comment]
The location of the included is takeoff from N79 (Northumberland County airport, Shamokin PA) Runway 26.  Turn left heading 200° for approx 3 miles.  Thank you for your time helping me getting this figured out.

**Comment by derekhe** [comment]
Would be great if you can provide the location on the google earth so that I can find it easily.

**Comment by buj818** [comment]
A picture of the map?  What all details would you like me to include on the map?

**Comment by derekhe** [comment]
the longitude and latitude of the location

**Comment by buj818** [comment]
40.783570,  -76.583694 are the coordinates of the specific area of my hometown in question.

**Comment by derekhe** [comment]
Here is the screenshots for you location:

Game's world view:
![image](https://github.com/user-attachments/assets/7afbab03-76a7-4dfb-81f3-9f21cff13359)

Google earth for the position you give
![image](https://github.com/user-attachments/assets/5b0fdb24-e3b5-4225-b98e-195d7596018a)

In the game:
![image](https://github.com/user-attachments/assets/8faf143e-a01d-453f-bce3-d5892e17731c)

**Comment by buj818** [comment]
Thank you!  That 100% verifies that the football field has been turned into a warehouse.  So I'm assuming is an Asobo issue that nothing can be done about, correct?

**Comment by derekhe** [comment]
Aha, you are talking about the building. I can't do anything for it, it is autogenerated by Asobo and had to turn on the developer mode to exclude that area. You can find some old tutorials for MSFS2020 about this.

**Comment by buj818** [comment]
Oh!  So there are ways that I can change that back myself?  Is the process the same for 2024 as in 2020?  I didn't know that was possible at all.

**Comment by buj818** [comment]
If you could, please just let me know what that actual process is called and I'll start looking into and learning up on that

**Comment by derekhe** [comment]
Msfs2020 devmode remove building&nbsp;





------------------ Original ------------------
From: buj818 ***@***.***&gt;
Date: Mon,Dec 9,2024 10:08 PM
To: derekhe ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] Works flawless in 2020, Not in2024 (Issue #797)





 
If you could, please just let me know what that actual process is called and I'll start looking into and learning up on that

**Comment by buj818** [comment]
Thank you.  I'm gonna purchase another pro license when I get home from work.  Once I can confirm that this mod is working with the color change, I'll dive into the devmode stuff.  I screen shorted everything in this thread that I need, feel free to close this out if you need to.  Thanks again for your time and help.

**Comment by buj818** [comment]
Update:  bought another Pro license yesterday, ran game, no color change.  Closed all programs, restarted PC, and all seems to be working as advertised now.
