### ISSUE TITLE
Looks like MSFS2020 Map Replacement v4.2.1 is not working at all with the newest Spain World Update?

### ISSUE THREAD

**Issue by 3DSpotters** [derekhe/msfs2020-map-enhancement#80]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**

**Comment by 3DSpotters** [comment]
Here is image_server.zip LOG..
[image_server.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/8341552/image_server.zip)
.

I tried all the possible options: both Google and Bing...
I still get only ONE image loaded on GUI...
![MSMR_nothing](https://user-images.githubusercontent.com/47834083/159920953-f4096d76-0ddd-48bc-84e8-8c31bf4beec1.jpg)

**Comment by 3DSpotters** [comment]
Also I still get CERTIFICATE WARNING and clicking "Yes" does not help...

**Comment by derekhe** [comment]
I have no idea. Will close this now.
