### ISSUE TITLE
[Feature] Add ability to start maps even when rolling cache deletion fails

### ISSUE THREAD

**Issue by tylertran349** [derekhe/msfs2020-map-enhancement#803]
#### Motivation

When I update the map enhancement tool to the latest version while FS2024 is running and then open it, it tells me that the game is running so the rolling cache can't be deleted, but I can't start the maps unless I disable the delete rolling cache when FS2024 starts option in settings. It is a bit annoying to do every time this happens.

#### Detailed design

Add the ability to start the maps even if the FS2024 rolling cache can't be deleted.

#### Alternatives

You can disable the delete rolling cache when FS2024 starts option in settings but this is a bit annoying to do every time this happens.

**Comment by derekhe** [comment]
Sure, will fix this soon.
