### ISSUE TITLE
China Map 2023 HD Pro not working

### ISSUE THREAD

**Issue by morganthomas757** [derekhe/msfs2020-map-enhancement#805]
**Describe the bug**

When attempting to start the mod, I am greeted with a message saying 'Access remote image server error'. This message only appears when trying to use the China HD Pro Layers. When trying to use Google Maps and other sources, the mod works as intended.

**MSFS version:**
 - Microsoft Store
 - MSFS2024

**Mod version:**
- 8.0.31.0

**Device ID**
- 7KY6GK801GY5DGPW9VEPJ1TBKHCRV9S68EXVM81C8D51M6RBPWK0

**Screenshots**

![image](https://github.com/user-attachments/assets/2cf09e06-8fc6-4b55-b466-83268f0e48ee)

**Comment by derekhe** [comment]
If you are not in china you may not access the image server

morganthomas757 ***@***.***>于2024年12月21日 周六22:08写道：

**Comment by morganthomas757** [comment]
Since when has this changed? It always worked for the past year or more. I live in the UK. To be honest, it is the main reason why I paid for the license as I fly in China on flight sim a lot.

**Comment by derekhe** [comment]
I don’t know and it depends on the policy from the map provider. Generally speaking the satellite services do not work for foreign countries IP. Maybe you can try use vpn?





------------------ Original ------------------
From: morganthomas757 ***@***.***&gt;
Date: Sun,Dec 22,2024 1:21 PM
To: derekhe/msfs2020-map-enhancement ***@***.***&gt;
Cc: hesicong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [derekhe/msfs2020-map-enhancement] China Map 2023 HD Pro notworking (Issue #805)
