### ISSUE TITLE
Won't connect to image server. never done this before

### ISSUE THREAD

**Issue by joseph740** [derekhe/msfs2020-map-enhancement#82]
It will connect to  the nginx server but not image. I can't really do anything until this is resolves. This is the first time its happened and nothing i have tried works
![image](https://user-images.githubusercontent.com/59077319/160300842-0a5d5df6-cc02-41df-9bf6-b0e00b48ed76.png)

**Comment by h0wardch3ng** [comment]
Try https://github.com/derekhe/msfs2020-map-enhancement/issues/72

**Comment by derekhe** [comment]
Could you please give me more logs metioned in "Trouble Shooting" Tab?
