### ISSUE TITLE
FR and RFC - Allow launching on boot and starting in/minimizing to the system tray

### ISSUE THREAD

**Issue by USA-RedDragon** [derekhe/msfs2020-map-enhancement#83]
Feature Request and Request for Comment - Allow launching on boot and starting in/minimizing to the system tray

Hello, I wanted to express my desire to submit a PR for allowing this application to be started on boot minimized to the system tray and get any feedback any users or @derekhe about this, and whether this is a change you would like to see or accept before getting started.

# Rationale
With the Auto Inject option available, the only requirement to use this tool is to remember to open it before launching the sim. Forgetting to launch this tool first can cause cache issues that can be annoying to clear and repopulate. In order to simplify this, I added a shortcut to this tool in my startup folder. Now, on all boots the UI appears and I have to manually minimize it each time. The icon stays visible in my application bar, and I find this to be a slight UX annoyance. 

# Implementation rough thoughts
I don't have any familiarity with this codebase or Electron, but I do have a few years of professional, production NodeJS experience. Two changes need to be implemented, as far as I can tell:

1. A system tray icon that can serve as a replacement for the taskbar icon on minimize. This can (should be?) a configurable option.

    > There is a tray API in Electron: https://www.electronjs.org/docs/latest/api/tray.

2. Starting up in the background via Electron

    > Based on https://github.com/electron/electron/issues/6893 it seems at least possible to accomplish this task. Unfortunately, it seems the package referenced in that issue (https://github.com/Teamwork/node-auto-launch) is very old, unmaintained, and probably not a good dependency to have. Presumably, appropriate functional equivalents exist. 

Optional 3. Give the user an easy option to add this tool to startup. This option can be tied to the task 1 option of minimizing to the toolbar, giving the appropriate behavior. 

I'd be glad to hear any thoughts by any interested parties on this change before I start working on it. I appreciate the work so far in allowing us to avoid Bing Maps.

**Comment by USA-RedDragon** [comment]
Edit: never mind. I could never enter the sim as I got CTD crashes every single load no matter what I tried. I asked Steam for a refund, and since I don't own the sim I won't be working on this FR.

**Comment by derekhe** [comment]
Since I changed all the development frameworks in the latest version, I will close this issue.
