### ISSUE TITLE
Port 443 Issue

### ISSUE THREAD

**Issue by AaronPiah** [derekhe/msfs2020-map-enhancement#85]
Port 443, is the bug
I followed the instructions on disabling programs that use this port, however the problem is that windows services uses this port and i don't like disabling windows services. i did close any other programs using the port, but these are things I particular like to keep running. can the program use a different port? also looking at the log in developer tools there were several warning about java not being enabled which doesn't make sense because i have the latest version of java installed for other software.
Thanks for any assistance ! 

**Desktop (please complete the following information):**
 - MSFS2020 steam
 - MSFS2020 Version latest

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8384935/error.log)
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8384956/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8384957/renderer.log)
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8384961/image_server.log)

**Comment by derekhe** [comment]
Hi, the 443 port must be used for this application because the msfs2020 gets a satellite image from a remote server, which is using the default 443 port. This mod hijacks this request into its own server to make it work, so only 443 port can be used.
Please find out why your 443 is occupied and close the related applications or services.
