### ISSUE TITLE
Airport collision map bug

### ISSUE THREAD

**Issue by KiwinoJohnWick** [derekhe/msfs2020-map-enhancement#87]
**Describe the bug**

collision map bug on runway 26 Arlanda airport

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [e.g. msstore/steam]
 - MSFS2020 Version [e.g. 22]

steam
msfs2020 1.24.5.0

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
![20220402123238_1](https://user-images.githubusercontent.com/102859335/161381274-ea0f7ef3-ded3-4421-ad38-ff51ce2079e3.jpg)
![20220402123255_1](https://user-images.githubusercontent.com/102859335/161381276-56e302ac-668e-42b4-900f-ae0616779590.jpg)
![20220402123525_1](https://user-images.githubusercontent.com/102859335/161381278-230c16ef-ccd6-47d6-9d91-6a663d334f5b.jpg)
![20220402123549_1](https://user-images.githubusercontent.com/102859335/161381279-d106f032-ddde-49bc-95c0-e48cf826e33b.jpg)
![20220402123556_1](https://user-images.githubusercontent.com/102859335/161381280-e2f392c5-17b8-4835-8708-b2c44dfd27dc.jpg)
![msfs2020mrv4 2 1](https://user-images.githubusercontent.com/102859335/161381394-4245fbe8-7ccc-4611-9ce4-c29177c1c500.PNG)

![Built](https://user-images.githubusercontent.com/102859335/161381281-3b4ea2b8-99a6-4559-8102-825a7b78d97d.PNG)
![OS](https://user-images.githubusercontent.com/102859335/161381340-09e18f01-94bc-4d29-8662-cba77c04185a.PNG)
[virtualearth-access.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8402427/virtualearth-access.log)

**Comment by derekhe** [comment]
I think this caused by MSFS's terrain data, please disable my mod and try the original one. If it still exists, it means MSFS's fault.

**Comment by h0wardch3ng** [comment]
The same as this issue https://github.com/derekhe/msfs2020-map-enhancement/issues/77

Delete all config files, And run game again.

Steam
C:\Users\%USERNAME%\AppData\Roaming\Microsoft Flight Simulator

Microsoft Store
C:\Users\%USERNAME%\AppData\Local\Packages\Microsoft.Microsoft Flight Simulator_{RandomId}
