### ISSUE TITLE
Nginx Sever Access Check Loading all the time, unable to connect

### ISSUE THREAD

**Issue by a543150176** [derekhe/msfs2020-map-enhancement#91]
1.Nginx Sever Access Check Loading all the time, unable to connect，It can be used before, but suddenly it can't，Checked the firewall and network connection, no problem

2.![QQ截图20220404103844](https://user-images.githubusercontent.com/102936211/161465037-09463732-4b50-4e11-bd0f-e037f25566c7.png)

3.MSFS2020版本msstore   

4.[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8406327/error.log)

**Comment by a543150176** [comment]
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8406340/image_server.log)
It's very normal

**Comment by derekhe** [comment]
Please try disable all your antivirus or add this program into whitelist.
Do a refresh installation of the program.

**Comment by a543150176** [comment]
I have reinstalled several versions and the problem is the same. My computer's firewall, network, are all turned off.

**Comment by a543150176** [comment]
> 请尝试禁用所有防病毒软件或将此程序添加到白名单中。执行程序的刷新安装。

I have reinstalled several versions and the problem is the same. My computer's firewall, network, are all turned off.

**Comment by derekhe** [comment]
@a543150176 is your problem solved? if not, is your system not in drive C?
