### ISSUE TITLE
Start server failed, error: Error: ENOENT: no such file or directory, open 'C:\windows\system32\drivers\etc\hosts'

### ISSUE THREAD

**Issue by priorat001** [derekhe/msfs2020-map-enhancement#92]
**Describe the bug**

**Screenshots**

**Desktop (please complete the following information):**
 - MSFS2020 version: [msstore]
 - MSFS2020 Version [e.g. 24.5.0]

**Log** 
Please provide the logs:
- Find out "Trouble Shooting" tab and attach the log files
- Attach logs from: (INSTALLATION PATH)\resources\extra\nginx\logs

**Additional context**
Start server failed, error: Error: ENOENT: no such file or directory, open 'C:\windows\system32\drivers\etc\hosts'. i have my windows 11 on anither dick A. i read trouble shooting but i cant find runner.py

**Comment by h0wardch3ng** [comment]
Go to C:\windows\system32\drivers\etc
New a file, name as hosts

**Comment by derekhe** [comment]
Please refer to https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ
