### ISSUE TITLE
Start server failed, error: Error: EPERM

### ISSUE THREAD

**Issue by israv87** [derekhe/msfs2020-map-enhancement#94]
**Describe the bug**
Start server failed, error: Error: EPERM: operation not permitted, open 'C:\windows\system32\drivers\etc\hosts'
**Screenshots**
![2022-04-07 19_32_00-msfs2020-map-enhancement](https://user-images.githubusercontent.com/27635055/162340543-8987aa3c-982b-41b2-9436-6b379b1bc661.png)

**Comment by h0wardch3ng** [comment]
Go to C:\windows\system32\drivers\etc\
New a file, name as hosts

**Comment by derekhe** [comment]
Please refer to https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ

**Comment by israv87** [comment]
Thank you very much for helping me, now I have a problem inside the game, the images that are loaded have this error, can you help me?
![2022-04-15 12_09_03-Microsoft Flight Simulator - 1 24 5 0](https://user-images.githubusercontent.com/27635055/163604044-a0335a2c-0124-4377-a1c9-7d82eba8c442.png)
![2022-04-15 12_09_23-Microsoft Flight Simulator - 1 24 5 0](https://user-images.githubusercontent.com/27635055/163604049-74958361-0b76-4993-a3b3-01ef40750b59.png)
![2022-04-15 12_25_22-Microsoft Flight Simulator - 1 24 5 0](https://user-images.githubusercontent.com/27635055/163604054-eb249952-42fa-4a33-8526-a394fdfe3992.png)
![2022-04-15 12_39_21-Microsoft Flight Simulator - 1 24 5 0](https://user-images.githubusercontent.com/27635055/163604056-ac35e919-3b11-42fb-b278-3d4275e64a1a.png)

**Comment by h0wardch3ng** [comment]
Please make sure your community folder is empty

1.Open the replacement software and turn off the cache function and wipe all cache
2.Enter the game
3.Close bing online service (inside the `Data`, all five items are closed)
4.Delete the game's scrolling update, and close this function
5.Turn on bing online landscape
6.Try to test again
