### ISSUE TITLE
[FR] Consider adding a license

### ISSUE THREAD

**Issue by USA-RedDragon** [derekhe/msfs2020-map-enhancement#98]
Please note, I am not a lawyer. This _is_ advice, but **not** of the legal variety.

Right now, this repo may have publicly available source code, but it is not open source. The reason being that the default copyright on a copyrightable work is "All rights reserved" because it is does not contain an explicit license. Adding an appropriate open-source license that meets the goals of your project ensures that your IP is protected by copyright exactly to the extent that you want and clarifies to contributors like me what we are and aren't allowed to do with your code.

**Comment by derekhe** [comment]
Yes, it is correct. I will add one.

**Comment by derekhe** [comment]
I added and will close this :)
